### ISSUE TITLE
Value must be one of {4, 5, 6, 7, 10, 12}.

### ISSUE THREAD

**Issue by SirPigari** [Rapptz/discord.py#10010]
### Summary

Value must be one of {4, 5, 6, 7, 10, 12}.

### Reproduction Steps

i dont know it just spawned

### Minimal Reproducible Code

```python
C:\Users\Admin\PycharmProjects\skittle-chan\.venv\Scripts\python.exe E:\skittle-chan\main.py 
[2024-11-11 18:41:13] [INFO    ] discord.client: logging in using static token
INFO:discord.client:logging in using static token
[2024-11-11 18:41:14] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 7d4f8514e2d8b6f6f5c6183ae127de58).
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: 7d4f8514e2d8b6f6f5c6183ae127de58).
Logged in as skittle-chan#6900
[2024-11-11 18:41:17] [system-0000000000000000000] (⚙️|SYSTEM): Channel with ID 1223385713014345841 not found. Checking if it's a DM channel...
[2024-11-11 18:41:17] [system-0000000000000000000] (⚙️|SYSTEM): Channel with ID 1223385713014345841 found as a DM channel.
[2024-11-11 18:41:18] [system-0000000000000000000] (⚙️|SYSTEM): Email received: sirpigari.mail@gmail.com
[2024-11-11 18:41:20] [system-0000000000000000000] (⚙️|SYSTEM): Verification code sent to email: sirpigari.mail@gmail.com
[2024-11-11 18:41:20] [ERROR   ] discord.ui.modal: Ignoring exception in modal <EmailModal timeout=None children=1>:
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\skittle-chan\.venv\Lib\site-packages\discord\ui\modal.py", line 189, in _scheduled_task
    await self.on_submit(interaction)
  File "E:\skittle-chan\main.py", line 694, in on_submit
    await sign_up_user(self.client, interaction, email)
  File "E:\skittle-chan\main.py", line 331, in sign_up_user
    await interaction.response.send_modal(VerificationModal(bot, user_id, email))
  File "C:\Users\Admin\PycharmProjects\skittle-chan\.venv\Lib\site-packages\discord\interactions.py", line 1041, in send_modal
    await adapter.create_interaction_response(
  File "C:\Users\Admin\PycharmProjects\skittle-chan\.venv\Lib\site-packages\discord\webhook\async_.py", line 223, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In type: Value must be one of {4, 5, 6, 7, 10, 12}.
ERROR:discord.ui.modal:Ignoring exception in modal <EmailModal timeout=None children=1>:
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\skittle-chan\.venv\Lib\site-packages\discord\ui\modal.py", line 189, in _scheduled_task
    await self.on_submit(interaction)
  File "E:\skittle-chan\main.py", line 694, in on_submit
    await sign_up_user(self.client, interaction, email)
  File "E:\skittle-chan\main.py", line 331, in sign_up_user
    await interaction.response.send_modal(VerificationModal(bot, user_id, email))
  File "C:\Users\Admin\PycharmProjects\skittle-chan\.venv\Lib\site-packages\discord\interactions.py", line 1041, in send_modal
    await adapter.create_interaction_response(
  File "C:\Users\Admin\PycharmProjects\skittle-chan\.venv\Lib\site-packages\discord\webhook\async_.py", line 223, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In type: Value must be one of {4, 5, 6, 7, 10, 12}.
```

### Expected Results

nothing

### Actual Results

C:\Users\Admin\PycharmProjects\skittle-chan\.venv\Scripts\python.exe E:\skittle-chan\main.py 
[2024-11-11 18:41:13] [INFO    ] discord.client: logging in using static token
INFO:discord.client:logging in using static token
[2024-11-11 18:41:14] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 7d4f8514e2d8b6f6f5c6183ae127de58).
INFO:discord.gateway:Shard ID None has connected to Gateway (Session ID: 7d4f8514e2d8b6f6f5c6183ae127de58).
Logged in as skittle-chan#6900
[2024-11-11 18:41:17] [system-0000000000000000000] (⚙️|SYSTEM): Channel with ID 1223385713014345841 not found. Checking if it's a DM channel...
[2024-11-11 18:41:17] [system-0000000000000000000] (⚙️|SYSTEM): Channel with ID 1223385713014345841 found as a DM channel.
[2024-11-11 18:41:18] [system-0000000000000000000] (⚙️|SYSTEM): Email received: sirpigari.mail@gmail.com
[2024-11-11 18:41:20] [system-0000000000000000000] (⚙️|SYSTEM): Verification code sent to email: sirpigari.mail@gmail.com
[2024-11-11 18:41:20] [ERROR   ] discord.ui.modal: Ignoring exception in modal <EmailModal timeout=None children=1>:
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\skittle-chan\.venv\Lib\site-packages\discord\ui\modal.py", line 189, in _scheduled_task
    await self.on_submit(interaction)
  File "E:\skittle-chan\main.py", line 694, in on_submit
    await sign_up_user(self.client, interaction, email)
  File "E:\skittle-chan\main.py", line 331, in sign_up_user
    await interaction.response.send_modal(VerificationModal(bot, user_id, email))
  File "C:\Users\Admin\PycharmProjects\skittle-chan\.venv\Lib\site-packages\discord\interactions.py", line 1041, in send_modal
    await adapter.create_interaction_response(
  File "C:\Users\Admin\PycharmProjects\skittle-chan\.venv\Lib\site-packages\discord\webhook\async_.py", line 223, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In type: Value must be one of {4, 5, 6, 7, 10, 12}.
ERROR:discord.ui.modal:Ignoring exception in modal <EmailModal timeout=None children=1>:
Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\skittle-chan\.venv\Lib\site-packages\discord\ui\modal.py", line 189, in _scheduled_task
    await self.on_submit(interaction)
  File "E:\skittle-chan\main.py", line 694, in on_submit
    await sign_up_user(self.client, interaction, email)
  File "E:\skittle-chan\main.py", line 331, in sign_up_user
    await interaction.response.send_modal(VerificationModal(bot, user_id, email))
  File "C:\Users\Admin\PycharmProjects\skittle-chan\.venv\Lib\site-packages\discord\interactions.py", line 1041, in send_modal
    await adapter.create_interaction_response(
  File "C:\Users\Admin\PycharmProjects\skittle-chan\.venv\Lib\site-packages\discord\webhook\async_.py", line 223, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In type: Value must be one of {4, 5, 6, 7, 10, 12}.

### Intents

intents = discord.Intents.default() intents.messages = True intents.guilds = True intents.members = True intents.message_content = True bot = commands.Bot(command_prefix="!", intents=intents) tree = bot.tree

### System Information

(.venv) PS E:\skittle-chan> python -m discord -v
- Python v3.12.6-final
- discord.py v2.4.0-final
- aiohttp v3.10.5
- system info: Windows 11 10.0.22621
(.venv) PS E:\skittle-chan> 

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by SirPigari** [comment]
> If you are sending a modal as a response of another modal, you cannot do that, modals can only be sent as a response of slash commands and components.

oh thank you but how can i do that other way?
i want to open another modal after sending one

**Comment by DA-344** [comment]
You can respond with a message containing a button, and when the user clicks it, the other modal pops up.
