### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by KinG2308** [Rapptz/discord.py#1020]
Command Prompt (Admin rights)
Windows 10 Pro (Build 16299.125, Ver. 1709)

```
C:\Users\Alex>python -m pip install -U discord.py
Collecting discord.py
  Using cached discord.py-0.16.12.tar.gz
Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py)
  Using cached aiohttp-1.0.5.tar.gz
Collecting websockets<4.0,>=3.1 (from discord.py)
  Using cached websockets-3.4-cp36-cp36m-win_amd64.whl
Requirement already up-to-date: chardet in c:\users\alex\appdata\local\programs\python\python36\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py)
Requirement already up-to-date: multidict>=2.0 in c:\users\alex\appdata\local\programs\python\python36\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py)
Requirement already up-to-date: async_timeout in c:\users\alex\appdata\local\programs\python\python36\lib\site-packages (from aiohttp<1.1.0,>=1.0.0->discord.py)
Installing collected packages: aiohttp, websockets, discord.py
  Found existing installation: aiohttp 2.3.8
    Uninstalling aiohttp-2.3.8:
      Successfully uninstalled aiohttp-2.3.8
  Running setup.py install for aiohttp ... error
  Rolling back uninstall of aiohttp
Exception:
Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 3: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Users\Alex\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 3: invalid continuation byte
```

**Comment by MysterialPy** [comment]
Please read through my comments here:
https://github.com/Rapptz/discord.py/issues/923

**Comment by KinG2308** [comment]
I can not install it on python-64, but it works on 32. This partially solves the problem.

**Comment by MysterialPy** [comment]
Correct. Hence my instructions clearly state use 32bit.

Also for future reference this is not a library specific issue, and is related to pip.
So if you would like to investigate it further, or try get more help, it would be best to look over their issue tracker:
https://github.com/pypa/pip/issues

**Comment by KinG2308** [comment]
I meant discord.py installing on python-32 without any troubles and extra actions. By the way, thanks for you instruction, discord.py on python-64 is working.
