### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by diceroll123** [Rapptz/discord.py#103]
I'm essentially doing exactly https://github.com/Rapptz/discord.py/blob/async/examples/background_task.py _with small modifications, it's for a "remind me" sort of thing._

Here's what I've got, if it's any help.

```
@asyncio.coroutine
def background_tasks():
  yield from client.wait_until_ready()
  while not client.is_closed:
    if client.is_logged_in: # this prevents a crash that occurs when the send_message is called before actually logged in. The example file I stated above possibly suffers from this error.
      reminders = db.get_reminders()
      for reminder in reminders:
        if float(reminder['unix_timestamp']) <= time.time():
          yield from client.send_message(bot.get_member_by_id(reminder['userid']), "Time's up! Your reminder is here: " + reminder['note'])
          db.delete_reminder(reminder) # because I don't care what you want to remind yourself of!

    yield from asyncio.sleep(10)
```

but I get this

```
Traceback (most recent call last):
  File "discordbot.py", line 305, in <module>
    loop.run_until_complete(client.close())
  File "C:\Python3\lib\asyncio\base_events.py", line 314, in run_until_complete
    self._check_closed()
  File "C:\Python3\lib\asyncio\base_events.py", line 284, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
exception calling callback for <Future at 0x1758510 state=finished returned list>
Traceback (most recent call last):
  File "C:\Python3\lib\concurrent\futures\_base.py", line 297, in _invoke_callbacks
    callback(self)
  File "C:\Python3\lib\asyncio\futures.py", line 439, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Python3\lib\asyncio\base_events.py", line 482, in call_soon_threadsafe
    handle = self._call_soon(callback, args)
  File "C:\Python3\lib\asyncio\base_events.py", line 456, in _call_soon
    self._check_closed()
  File "C:\Python3\lib\asyncio\base_events.py", line 284, in _check_closed
    raise RuntimeError('Event loop is closed')
```

---

I'm not sure what causes it, but I'm 100% sure it's not the sqlite database or those functions to access it.

**Comment by diceroll123** [comment]
Hrm...

My `pm2` log shows this.

```
Task exception was never retrieved
future: <Task finished coro=<background_tasks() done, defined at discordbot.py:280> exception=InvalidArgument('Destination must be Channel, PrivateChannel, User, or Object',)>
Traceback (most recent call last):
  File "C:\Python3\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "discordbot.py", line 289, in background_tasks
    yield from client.send_message(bot.get_member_by_id(reminder['userid']), "Time's up! Your reminder is here: " + reminder['note'])
  File "C:\Python3\lib\site-packages\discord\client.py", line 944, in send_message
    channel_id = yield from self._resolve_destination(destination)
  File "C:\Python3\lib\site-packages\discord\client.py", line 233, in _resolve_destination
    raise InvalidArgument('Destination must be Channel, PrivateChannel, User, or Object')
discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object
```

Which leads me to believe that my `get_member_by_id` function is the cause of the issue.

Here's my function:

```
class Bot: # yes there are other functions but they're unnecessary to show here
    def get_member_by_id(self, userid):
      for server in client.servers:
        for member in server.members:
          if member.id == userid:
            return member
```

BUT IT WORKS SOMETIMES!! discord.py needs an easier method to get users by ID. :sob:

I'll continue looking into this.

**Comment by khazhyk** [comment]
is get_member_by_id returning `None` ?

**Comment by Rapptz** [comment]
The way to get a member from ID is `Server.get_member(id)`. Or `discord.utils.get(bot.get_all_members(), id='id')`.

**Comment by diceroll123** [comment]
@khazhyk yep. Sometimes.

@Rapptz, changed things using your advice, see below _thanks for letting me know about get_member! unsure how I missed that..._ BUT, still getting an error for both of those. _It's returning `None`_

So I changed my get_member_by_id function to the following:
```
  def get_member_by_id(self, userid):
    for server in client.servers:
      return server.get_member(userid)
```

Works fine when I check, say, my own ID. I just did `print(bot.get_member_by_id(my_user_id))` in `on_ready`, and worked great. Returned my username as it should. _the bot and I are not using the same account, for future reference._

But through the background task, I get

```
Task exception was never retrieved
future: <Task finished coro=<background_tasks() done, defined at discordbot.py:295> exception=InvalidArgument('Destination must be Channel, PrivateChannel, User, or Object',)>
Traceback (most recent call last):
  File "C:\Python3\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "discordbot.py", line 306, in background_tasks
    yield from client.send_message(bot.get_member_by_id(reminder['userid']), "Time's up! Your reminder is here: " + reminder['note'])
  File "C:\Python3\lib\site-packages\discord\client.py", line 944, in send_message
    channel_id = yield from self._resolve_destination(destination)
  File "C:\Python3\lib\site-packages\discord\client.py", line 233, in _resolve_destination
    raise InvalidArgument('Destination must be Channel, PrivateChannel, User, or Object')
discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object
```

---

Is it possible that the bot needs access to user lists or something? Hmm... Maybe it returns `None` if they're offline? I'll try.

**Comment by diceroll123** [comment]
Nope, this thing has a mind of its own.

**Comment by Rapptz** [comment]
Make sure your library is up to date.

**Comment by diceroll123** [comment]
Yeah, still returns None sometimes. Very strange, but I have workarounds that stop the crashing (not to make it work, but, just to ignore that the member is None)...
