### ISSUE TITLE
 ffmpeg/avconv was not found in your PATH environment variable

### ISSUE THREAD

**Issue by AaronIlMentor** [Rapptz/discord.py#1072]
I keep getting the error " ffmpeg/avconv was not found in your PATH environment variable", when I try to use the create_ffmpeg_player or the create_ytdl_player functions. 

I've looked through the previous issues and googled around, and nothing has been able to solve my problem. 

I also am pretty sure that ffmpeg is installed correctly and a part of my system PATH because I can execute it from the command prompt. 

Any ideas?

**Comment by Modelmat** [comment]
If this is rewrite - http://discordpy.readthedocs.io/en/rewrite/migrating.html#voice-changes
If this is async, please post your full code and error traceback.

**Comment by Helehelehele** [comment]
Did you restart your command prompt after adding ffmpeg into your PATH?

**Comment by AaronIlMentor** [comment]
I think its async, but I'm kinda green so I'll just post the code and see what you lads think: 

```python
@bot.command(pass_context = True)
async def play(ctx, search_query : str):
    player = await vc.create_ytdl_player('https://www.youtube.com/watch?v=rUWaBDvyhqU')
    player.start()
    query_string = urllib.parse.urlencode({"search_query" : input()})
    html_content = urllib.request.urlopen("http://www.youtube.com/results?" + query_string)
    search_results = re.findall(r'href=\"\/watch\?v=(.{11})', html_content.read().decode())
    bot.say(search_results)
```
```
Traceback (most recent call last):
  File "C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Aaron-PC\OneDrive\Visual Studio\Homunculus\Homunculus\Homunculus.py", line 136, in airhorn
    player = await vc.create_ffmpeg_player("mlg-airhorn.mp3")
  File "C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\voice_client.py", line 434, in create_ffmpeg_player
    raise ClientException('ffmpeg/avconv was not found in your PATH environment variable') from e
discord.errors.ClientException: ffmpeg/avconv was not found in your PATH environment variable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientException: ffmpeg/avconv was not found in your PATH environment variable
```

Also tried getting some help on a discord bot developer server, we tried some stuff. I asked if I could screenshot the conversation to show you what else I've tried: https://imgur.com/a/5tFfP


> Did you restart your command prompt after adding ffmpeg into your PATH?

Also I did restart the command prompt after adding ffmpeg. I can open ffmpeg no problem with command prompt. Python just doesn't seem to want to open it for some reason from what I can tell.

**Comment by leovoel** [comment]
did you restart your computer? sometimes people need to do it on windows

**Comment by AaronIlMentor** [comment]
Yes, twice actually.

**Comment by Modelmat** [comment]
What is the result of echo %PATH%

**Comment by AaronIlMentor** [comment]
```
C:\ffmpeg\bin;C:\ffmpeg-20180211-4961ddf-win64-static\bin;C:\Program Files\Microsoft MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\;C:\Users\Aaron-PC\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\DLLs;C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\Lib;C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\Lib\site-packages;C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\;C:\Users\Aaron-PC\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\DLLs;C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\Lib;C:\Users\Aaron-PC\AppData\Local\Programs\Python\Python36-32\Lib\site-packages;
```

**Comment by Modelmat** [comment]
https://github.com/coursera-dl/edx-dl/issues/405

**Comment by Modelmat** [comment]
also could we please move to the discord.py supprot server https://discord.gg/r3sSKJJ

**Comment by AaronIlMentor** [comment]
So for future people who show up: 

The nice gentlemen helped me in their discord server.

I was debugging from visual studio, which caused some weird issues. 

If you try running the python script directly from the command prompt, then it works perfectly.

**Comment by pastorhudson** [comment]
You probably need avconv.
If it won't let you install using  `sudo apt-get install libav-tools` You can [download the .deb from here][1]:

`wget http://launchpadlibrarian.net/339874908/libav-tools_3.3.4-2_all.deb`

Then run `sudo apt install ./libav-tools_3.3.4.2_all.deb`

  [1]: https://launchpad.net/ubuntu/bionic/amd64/libav-tools/7:3.3.4-2

**Comment by wellingtonsilverio** [comment]
or install 'sudo apt-get install ffmpeg' in linux/debian
