### ISSUE TITLE
Color read-only wasn't working that way

### ISSUE THREAD

**Issue by MaximeDawn** [Rapptz/discord.py#1109]
Hi ! I dev bots for some months now, and i used to use embeds to display my Bots documentation.
I used to change the embed color usign this line :

`em = discord.Embed(description="Some description", colour=0x720000)`

This worked perfectly until this morning, where i get this message :

`discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Colour' object attribute 'value' is read-only`

(it's obviously the same if I replace colour by color)

Any idea ? 🤔

**Comment by Gorialis** [comment]
No repro here. Do you have an extended traceback, and what version are you running on?

**Comment by MaximeDawn** [comment]
```
Exception in command 'redportal search'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/stormy/Red-DiscordBot/cogs/redportal.py", line 84, in search
    embeds, data = await self._search_redportal(ctx, url)
  File "/home/stormy/Red-DiscordBot/cogs/redportal.py", line 53, in _search_redportal
    color=0xfd0000)
  File "lib/discord/embeds.py", line 98, in __init__
    self.colour = colour
  File "lib/discord/embeds.py", line 154, in colour
    self._colour = Colour(value=value)
  File "lib/discord/colour.py", line 56, in __init__
    self.value = value
AttributeError: 'Colour' object attribute 'value' is read-only

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 634, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "lib/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Colour' object attribute 'value' is read-only
```

There you go.

**Comment by Gorialis** [comment]
I can't seem to pin down what would cause this, I can't reproduce the issue but judging from the traceback nothing is different on your end internally.

Have you tried reinstalling discord.py? (`pip install -U discord.py`)

**Comment by MaximeDawn** [comment]
```
    @checks.admin_or_permissions(manage_server=True)
    @commands.command(pass_context=True, no_pm=True)
    async def testembed(self, ctx):
        em = discord.Embed(description="Some desc", colour=0x4286f4)
        em.set_author(name="Some author", url = '')
        em.add_field(name="A field title", value="A field value")
        em.set_footer(text="Some footer", icon_url='')
        await self.bot.say(embed = em)
```

Even this isn't working.... I'm trying to reinstall..

**Comment by Rapptz** [comment]
Can't reproduce this. Python's a dynamic language so there could have been some monkey patching fuckery that caused this.

**Comment by MaximeDawn** [comment]
@Gorialis Yeah ! Reinstalling Discord.py solved it ! Had a pretty hard to have an admin SSH connection, but solved it ! Ty man ♥

**Comment by TheRockettek** [comment]
Oh i thought it was colour=discord.Colour(0x4286f4) ._.
