### ISSUE TITLE
Discord.py Crashes on ConnectionResetError exception which gets thrown in asyncio

### ISSUE THREAD

**Issue by AraHaan** [Rapptz/discord.py#112]
```py
Logged in as DecoraterBot
Bot id=104976661711179776
Discord.py v0.10.0-alpha Async
-------------------------------
Traceback (most recent call last):
  File "E:\Python35\lib\asyncio\tasks.py", line 2
41, in _step
    result = coro.throw(exc)
  File "E:\Python35\lib\site-packages\websockets\
protocol.py", line 302, in run
    msg = yield from self.read_message()
  File "E:\Python35\lib\site-packages\websockets\
protocol.py", line 324, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "E:\Python35\lib\site-packages\websockets\
protocol.py", line 379, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "E:\Python35\lib\site-packages\websockets\
protocol.py", line 411, in read_frame
    self.reader.readexactly, is_masked, max_size=max_size)
  File "E:\Python35\lib\site-packages\websockets\
framing.py", line 77, in read_frame
    data = yield from reader(2)
  File "E:\Python35\lib\asyncio\streams.py", line
 509, in readexactly
    block = yield from self.read(n)
  File "E:\Python35\lib\asyncio\streams.py", line
 482, in read
    yield from self._wait_for_data('read')
  File "E:\Python35\lib\asyncio\streams.py", line
 423, in _wait_for_data
    yield from self._waiter
  File "E:\Python35\lib\asyncio\futures.py", line
 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "E:\Python35\lib\asyncio\tasks.py", line 2
90, in _wakeup
    future.result()
  File "E:\Python35\lib\asyncio\futures.py", line
 274, in result
    raise self._exception
  File "E:\Python35\lib\asyncio\selector_events.p
y", line 664, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly close
d by the remote host
Task was destroyed but it is pending!
task: <Task pending coro=<Client.keep_alive_handler() running at E:\Python35\lib\site-packages\discord\client.py:315> wait_for=<F
uture pending cb=[Task._wakeup()]>>
Press any key to continue . . .```
So yeah this ends up being a real issue in Discord.py and needs fixed.

**Comment by shrx** [comment]
Same issue as #101 ?

**Comment by Rapptz** [comment]
Your problem.

**Comment by flashrifle7** [comment]
yep also had this issue
