### ISSUE TITLE
 change_presence doesn't know about game argrument 

### ISSUE THREAD

**Issue by Haroon01** [Rapptz/discord.py#1125]
trying to make a playing game status

```
client = discord.Client()
@bot.event
async def on_ready():
    await bot.change_presence(discord.Game(name='my game', type=1))
    print("Logged in as")
    print("HaroonBot")
    print("------")
```
```


C:\WINDOWS\system32>python "C:\Users\Haroon\Documents\discordbot.py"
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Haroon\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 224, in _run_event
    yield from coro(*args, **kwargs)
  File "C:\Users\Haroon\Documents\discordbot.py", line 12, in on_ready
    await client.change_presence(game=discord.Game(name='my game', type=1))
TypeError: change_presence() got an unexpected keyword argument 'game'

```

**Comment by Rapptz** [comment]
If you're using the rewrite version of the library then you should be in the #news channel in the official server to be notified of breaking changes.

**Comment by TheSnoozer** [comment]
Pretty late but I bumped into this as well:
``game keyword argument in Client.change_presence was renamed to activity``

```python
activity = discord.Game(name="with the API")
await client.change_presence(status=discord.Status.idle, activity=activity)
```
