### ISSUE TITLE
Bot crashs after failed to reconnect

### ISSUE THREAD

**Issue by Zenrac** [Rapptz/discord.py#1127]
Hi,

I'm using the reconnect parameter (rewrite) to auto-reconnect my bot, but this time it didn't worked as exepted

```
Traceback (most recent call last):
  File "run.py", line 370, in main
    m.run()
  File "/home/zenrac/Rewrite/bot.py", line 478, in run
    super().run(token, reconnect=True)
  File "/home/zenrac/Rewrite/src/discord.py/discord/client.py", line 580, in run
    return task.result()
  File "/home/zenrac/Rewrite/src/discord.py/discord/client.py", line 488, in start
    yield from self.connect(reconnect=reconnect)
  File "/home/zenrac/Rewrite/src/discord.py/discord/client.py", line 408, in connect
    yield from self._connect()
  File "/home/zenrac/Rewrite/src/discord.py/discord/shard.py", line 286, in _connect
    f.result()
  File "/home/zenrac/Rewrite/src/discord.py/discord/shard.py", line 77, in poll
    yield from self.ws.poll_event()
  File "/home/zenrac/Rewrite/src/discord.py/discord/gateway.py", line 448, in poll_event
    msg = yield from self.recv()
  File "/usr/local/lib/python3.6/site-packages/websockets/protocol.py", line 323, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
  File "/usr/local/lib/python3.6/site-packages/websockets/exceptions.py", line 147, in __init__
    if 3000 <= code < 4000:
TypeError: '<=' not supported between instances of 'int' and 'NoneType'
```

Any idea ?

**Comment by Rapptz** [comment]
See also: https://github.com/aaugustin/websockets/issues/350

**Comment by crazygmr101** [comment]
Is the library still needing to be downgraded after https://github.com/aaugustin/websockets/commit/402059e4a46a764632eba8a669f5b012f173ee7b? https://github.com/aaugustin/websockets/issues/350#issuecomment-386092541 Seems to have been fixed.
