### ISSUE TITLE
Exception when reconnecting

### ISSUE THREAD

**Issue by LemonadeCellar** [Rapptz/discord.py#1144]
A script I use ([Panopticon](https://github.com/ihaveamac/panopticon) but rewritten for Rewrite and with a few more features) crashed while attempting to reconnect, I don't think any code in the script itself is relevant to this but I could explain what it does if necessary. Here's the traceback:

> Traceback (most recent call last):
  File ".\panopticon.py", line 754, in <module>
    client.run(TOKEN, bot=BOT_ACCOUNT, max_messages=MAX_MESSAGES)
  File "C:\Python36\lib\site-packages\discord\client.py", line 580, in run
    return task.result()
  File "C:\Python36\lib\site-packages\discord\client.py", line 488, in start
    yield from self.connect(reconnect=reconnect)
  File "C:\Python36\lib\site-packages\discord\client.py", line 408, in connect
    yield from self._connect()
  File "C:\Python36\lib\site-packages\discord\client.py", line 370, in _connect
    yield from self.ws.poll_event()
  File "C:\Python36\lib\site-packages\discord\gateway.py", line 448, in poll_event
    msg = yield from self.recv()
  File "C:\Python36\lib\site-packages\websockets\protocol.py", line 323, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
  File "C:\Python36\lib\site-packages\websockets\exceptions.py", line 147, in __init__
    if 3000 <= code < 4000:
TypeError: '<=' not supported between instances of 'int' and 'NoneType'

The only relevant messages in the log file (that was when it crashed):

> 2018-03-15 22:14:27,284:WARNING:discord.gateway: Shard ID None has stopped responding to the gateway. Closing and restarting.
2018-03-15 22:14:37,287:INFO:discord.client: Cleaning up event loop.
2018-03-15 22:14:37,288:INFO:discord.client: Cleaning up after 6 tasks

The only other time an error like this happened was when I tried manually calling logout() or close() from the script, never while it was just running as usual, so I don't know if I can replicate it.
This was on commit 31cc4c3, so latest version before the Spotify color fix.

**Comment by Vexs** [comment]
See #1127

**Comment by Gorialis** [comment]
This issue duplicates #1127. It is a websockets bug and we cannot do anything about it as of the current moment. I'd recommend installing an older version, but this isn't guaranteed to fix the problem.
