### ISSUE TITLE
Can't change the game status for my bot

### ISSUE THREAD

**Issue by TheUnbAnmAn** [Rapptz/discord.py#1156]
I've searched far and wide, but I can't find any code that works. Here is the current one (that doesn't work) that I have for this:

``` 
import discord
import asyncio

client = discord.Client()


@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')
    await client.change_presence(game=discord.Game(name='Do >help'))
```

**Comment by Vexs** [comment]
I'm assuming you're using the rewrite branch? If so, this is why you need to be in the discord and keep up with the news, as breaking changes are announced there. There was a breaking change regarding how presences work, they're now activities. 

From the new post:
```- Member.game has been renamed to Member.activity
- Member.activity objects are now up to 4 distinct types instead of always being Game.
    - More on this later.
- game keyword argument in Client.change_presence was renamed to activity.
- game keyword argument in Client.__init__ was renamed to activity
- Game no longer accepts type as a keyword argument.
    - If you want to set the type, you must use the new Activity type.
    - If you want to set the Streaming status you can just use the new Streaming type instead.

Now for the new features:

- Spotify class to have a nice read-only interface of how the Spotify integration works
- Activity class to check rich presence information. At the moment this is kind of bare-bones, but more features will come if asked for.
- Splitting Game into Activity/Game/Streaming/Spotify allows for nice memory optimisations when dealing with Rich Presence information.
- Add a new keyword argument (case_insensitive) to Bot/Group and the appropriate decorators to support case-insensitive commands more easily.
    - This is a popular request so there's an opt-in for it. The default is still False.
- Add ability to change the activity set on logging in/IDENTIFY at runtime via Client.activity property.
- Allow handling of unicode quotes for the quoted word parser thanks to @b-hodges```

**Comment by TheUnbAnmAn** [comment]
So I would do something like this?
```
await client.change_presence(activity=discord.Activity(name='Do >help'))
```
*I tried that and it did not work, so I believe I am doing something wrong. Is it something to do with the "name" argument?

**Comment by Rapptz** [comment]
Please provide more information instead of "doesn't work". That phrase can mean a million different things and is not actionable.

**Comment by TheUnbAnmAn** [comment]
```
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\jam12\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "F:\CrackerBot.py", line 11, in on_ready
    await client.change_presence(activity=discord.Game(name="a game"))
TypeError: change_presence() got an unexpected keyword argument 'activity'
```

**Comment by Rapptz** [comment]
Then you're not using the library version that @Vexs assumed you were using.

Give the original error that is applicable to the original issue.

**Comment by TheUnbAnmAn** [comment]
I tried the original again, and it worked. I'm not entirely sure why it was giving me syntax errors before. Thanks for the suggestions, though.

**Comment by ndisalvio** [comment]
Just in case anyone form 2019 has the same issue you just need to make sure activity is capitalized.
