### ISSUE TITLE
Asyncio error

### ISSUE THREAD

**Issue by JennyDiscord** [Rapptz/discord.py#1166]
C:\Users\helga\Documents>python pop.py
Traceback (most recent call last):
  File "pop.py", line 2, in <module>
    import discord
  File "C:\Users\helga\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\helga\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\helga\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\helga\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax

**Comment by Gorialis** [comment]
You are on an old version of discord.py that doesn't have the 3.7 compatibility fixes. This is actually irrelevant though, as due to similar issues in its dependencies, **discord.py does not work on 3.7 natively.**.
Download and use 3.6 instead for now.

**Comment by JennyDiscord** [comment]
Okay! I hope this works

**Comment by JennyDiscord** [comment]
It worked!!!
