### ISSUE TITLE
Using on_command_error() makes every command error out

### ISSUE THREAD

**Issue by Nuk3lar** [Rapptz/discord.py#1171]
When i try use the following code in my bot
```py
@client.event
async def on_command_error(ctx, error):
     #Gets the message object
    logging.error(error) #logs the error
    await client.send_message(discord.Object(id=428284312526389250), u'\u274C'+' There was a error!')
```
and my test command is like this
```py
@client.command(pass_context=True)
@commands.has_role("Rank 7 [Leader]")
async def test(ctx): 				#Nukelar's testing command
    logging.info('cmd test ran by: '+ctx.message.author)
    await client.say("Test "+ctx.message.author.mention)
```
[Full Code](https://raw.githubusercontent.com/Nuk3lar/ScopedBot/master/bot.py)

And when i run the command ~~test, it errors out like this
```
C:\Users\user\Documents\GitHub\ScopedBot>"C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python36_64/python.exe" c:/Users/user/Documents/GitHub/ScopedBot/bot.py
SCOPED v0.3.2 STARTED
Ignoring exception in command test
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\discord\ext\commands\core.py", line 367, in invoke
    yield from self.prepare(ctx)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\discord\ext\commands\core.py", line 344, in prepare
    self._verify_checks(ctx)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\discord\ext\commands\core.py", line 339, in _verify_checks
    raise CheckFailure('The check functions for command {0.qualified_name} failed.'.format(self))
discord.ext.commands.errors.CheckFailure: The check functions for command test failed.```

**Comment by Rapptz** [comment]
That CheckFailure is because you don't have a role named "Rank 7 [Leader]", it has nothing to do with the `on_command_error` event which just tells you the `CheckFailure` happened.

**Comment by Nuk3lar** [comment]
Ah, stupid me. Realized that i was using my 2nd discord account, that had not got that role. Thanks anyway!
