### ISSUE TITLE
Issues with pruning, dont understand how to use the function.

### ISSUE THREAD

**Issue by LaserPenis123** [Rapptz/discord.py#1185]
So I run a quite simple script, just to test out the function:
for server in client.servers:
    print(client.estimate_pruned_members(server, 1))

I receive the server and can output the name with server.name etc. But when running the script I get the error:
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
yield from getattr(self, event)(*args, **kwargs)
File "prune.py", line 21, in on_ready
print(client.estimate_pruned_members(server.id, 7))
TypeError: estimate_pruned_members() takes 2 positional arguments but 3 were given

I cant find any examples on this and I don't understand why it does this at all, tried calling the function with server.name but get the same issue. It states that I give it 3 arguments, but that is not my intention at all, why is it doing this? If I call the function with "(server, days=1)" it returns a generator object:
<generator object Client.estimate_pruned_members at 0xb6f3a59c>
The documentation says it should return an int, but I guess there is an int inside the generator? However I cannot open the generator, if I try to loop through it and print each item like this:
for a in client.estimate_pruned_members(server, days=7):
    print(a)
I get this error:
<Future pending>
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "prune.py", line 23, in on_ready
    for b in a:
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 2488, in estimate_pruned_members
    data = yield from self.http.estimate_pruned_members(server.id, days)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 137, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 202, in _request
    yield from resp.start(conn, read_until_eof)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client_reqrep.py", line 640, in start
    message = yield from httpstream.read()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/streams.py", line 641, in read
    result = yield from super().read()
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/streams.py", line 476, in read
    yield from self._waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 362, in __iter__
    assert self.done(), "yield from wasn't used with future"
AssertionError: yield from wasn't used with future
Future exception was never retrieved
future: <Future finished exception=ServerDisconnectedError()>
aiohttp.errors.ServerDisconnectedError

Does anybody know what I'm doing wrong?

**Comment by PapyrusThePlant** [comment]
[From the documentation](http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.estimate_pruned_members), your first error is caused there is only one positional argument in the function's signature. `days` is a keyword argument, which you sort of guessed by doing `client.estimate_pruned_members(server, days=7)`.

Then from that same page you should notice that this function is a coroutine, that's why it returns a generator, it needs to be awaited.

Correct usage is then `num = await client.estimate_pruned_members(server, days=7)`.

In the future, as this is not an issue with the library, those questions are better asked in the [official discord.py server](https://discord.gg/r3sSKJJ) ;)

**Comment by LaserPenis123** [comment]
Thanks man, awesome! Sorry I'm not too good of a programmer, these scripts are a bit ahead of my experience. I didn't know about the discord channel, but I'll keep my questions there. Thanks a lot!
