### ISSUE TITLE
TypeError: unorderable types on exception

### ISSUE THREAD

**Issue by JellyWX** [Rapptz/discord.py#1199]
```------------
Traceback (most recent call last):
  File "main.py", line 462, in <module>
    client.run(token)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 580, in run
    return task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 488, in start
    yield from self.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 408, in connect
    yield from self._connect()
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 370, in _connect
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 448, in poll_event
    msg = yield from self.recv()
  File "/usr/local/lib/python3.5/dist-packages/websockets/protocol.py", line 323, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
  File "/usr/local/lib/python3.5/dist-packages/websockets/exceptions.py", line 147, in __init__
    if 3000 <= code < 4000:
TypeError: unorderable types: int() <= NoneType()
Task was destroyed but it is pending!
task: <Task pending coro=<BotClient.cleanup() running at main.py:242> wait_for=<Future pending cb=[Task._wakeup()]>>```

Error occurs infrequently but always forces the bot offline. This may have been patched in a later release. I'm on rewrite channel since it was changed from `game` to `activity`

**Comment by Rapptz** [comment]
Dupe https://github.com/Rapptz/discord.py/issues/1127

**Comment by JellyWX** [comment]
Apologies, got carried away
