### ISSUE TITLE
Using wait=True in webhook.execute raises AttributeError

### ISSUE THREAD

**Issue by nguuuquaaa** [Rapptz/discord.py#1242]
Title.

Here's the code (using eval command) and traceback in case.
```py
webhook = (await ctx.channel.webhooks())[0]
msg = await webhook.execute("test", wait=True)
```
```
Traceback (most recent call last):
  File "/home/nguuuquaaa/bot/Belphegor/belphegor/admin.py", line 131, in _eval
    await func()
  File "<string>", line 3, in func
  File "/usr/local/lib/python3.6/dist-packages/discord/webhook.py", line 197, in handle_execution_response
    return Message(data=data, state=self, channel=self.webhook.channel)
  File "/usr/local/lib/python3.6/dist-packages/discord/message.py", line 213, in __init__
    self._update(channel, data)
  File "/usr/local/lib/python3.6/dist-packages/discord/message.py", line 278, in _update
    getattr(self, '_handle_%s' % handler)(data[handler])
  File "/usr/local/lib/python3.6/dist-packages/discord/message.py", line 291, in _handle_author
    self.author = self._state.store_user(author)
AttributeError: 'AsyncWebhookAdapter' object has no attribute 'store_user'
```

**Comment by xSke** [comment]
This can be fixed on the user end by monkey-patching the webhook's adapter. Like this:

    hook._adapter.store_user = hook._adapter._store_user

The issue arises from the "store_user" mock being named incorrectly in WebhookAdapter. The implementation has an underscore, whereas the method being called doesn't.
