### ISSUE TITLE
discord.errors.LoginFailure: Improper credentials have been passed.

### ISSUE THREAD

**Issue by 0xCoto** [Rapptz/discord.py#1247]
So I've been trying to run the Quick Example with python3.5: https://github.com/Rapptz/discord.py#quick-example

However, I keep getting this...

```
Python 3.5.3 (default, Apr 22 2017, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import discord
>>> import asyncio
>>> 
>>> client = discord.Client()
>>> 
>>> @client.event
... async def on_ready():
...     print('Logged in as')
...     print(client.user.name)
...     print(client.user.id)
...     print('------')
... 
>>> @client.event
... async def on_message(message):
...     if message.content.startswith('!test'):
...         counter = 0
...         tmp = await client.send_message(message.channel, 'Calculating messages...')
...         async for log in client.logs_from(message.channel, limit=100):
...             if log.author == message.author:
...                 counter += 1
...         await client.edit_message(tmp, 'You have {} messages.'.format(counter))
...     elif message.content.startswith('!sleep'):
...         await asyncio.sleep(5)
...         await client.send_message(message.channel, 'Done sleeping')
... 
>>> client.run('my_email@gmail.com', 'my_password')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 243, in email_login
    data = yield from self.request(Route('POST', '/auth/login'), json=payload)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 490, in start
    yield from self.login(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 416, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 367, in _login_2
    yield from self.http.email_login(email, password)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 246, in email_login
    raise LoginFailure('Improper credentials have been passed.') from e
discord.errors.LoginFailure: Improper credentials have been passed.
>>> 
```

I've triple-checked and my credentials are correct. What is wrong?

**Comment by ccubed** [comment]
1) That's not what quick example says

2) You can't login using your email and password. You need a bot token.

**Comment by Modelmat** [comment]
A couple of things:
- This is not the place for discord.py help, [this](https://discord.gg/r3sSKJJ) is
- You can't sign in with your email and password
- To get your token, use [this](http://discordpy.readthedocs.io/en/rewrite/discord.html#discord-intro)

**Comment by 0xCoto** [comment]
@ccubed 

1. What does it say?

2. I've tried using a token as well - same issue. For some reason however, it seems to work fine on my Mac using client.run('email, 'password'), but not on my ubuntu VPS...

@Modelmat 

Tried with a token, didn't work.

**Comment by Modelmat** [comment]
**Please move to the discord.py server where we can help you more**
How long is your token? I'm guessing you have used to client secret.

**Comment by katmai1** [comment]
This fail was caused by my new IP address, the Discord rejects my connection with the bot but I if try connecting with Discord client I can see the real error.
The discord sends an email for allow my new IP address.
Now works perfectly with email and password

**Comment by jwshields** [comment]
Selfbots are disallowed by the Discord ToS
https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-
