### ISSUE TITLE
Unretrieved Exception in Task - How to handle this?

### ISSUE THREAD

**Issue by cyclostationary** [Rapptz/discord.py#1268]
First, let me be clear I understand that this message can be ignored - but in my case this is quite annoying as I have a text based interface running that gets screwed up when the exception dumps the traceback text. 

First the actual traceback:

```Task exception was never retrieved
future: <Task finished coro=<WebSocketCommonProtocol.run() done, defined at /home/mike/.local/lib/python3.5/site-packages/websockets/protocol.py:428> exception=ConnectionResetError(104, 'Connection reset by peer')>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/mike/.local/lib/python3.5/site-packages/websockets/protocol.py", line 434, in run
    msg = yield from self.read_message()
  File "/home/mike/.local/lib/python3.5/site-packages/websockets/protocol.py", line 456, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/home/mike/.local/lib/python3.5/site-packages/websockets/protocol.py", line 511, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/home/mike/.local/lib/python3.5/site-packages/websockets/protocol.py", line 546, in read_frame
    self.reader.readexactly, is_masked, max_size=max_size)
  File "/home/mike/.local/lib/python3.5/site-packages/websockets/framing.py", line 86, in read_frame
    data = yield from reader(2)
  File "/usr/lib/python3.5/asyncio/streams.py", line 670, in readexactly
    block = yield from self.read(n)
  File "/usr/lib/python3.5/asyncio/streams.py", line 627, in read
    yield from self._wait_for_data('read')
  File "/usr/lib/python3.5/asyncio/streams.py", line 457, in _wait_for_data
    yield from self._waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 662, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
```

So this occurs whenever my wifi adapter craps out, which can be pretty frequent - it's also of note that this still occurs with the re-write branch which has re-connect logic built in, so even though it reconnects fine its still dumping this error which doesn't feel right to me.

It appears to not be occurring with on_error so overloading that won't work.

Is there anyway to catch this exception and avoid it dumping to console? My only idea is to use something like all_tasks on the client's event loop and retrieve exceptions for all the tasks. Any other way around this?

**Comment by cyclostationary** [comment]
Finally found a fix for this, basically setup your own exception handler for the event loop

`
def my_handler(loop,context):
    print("Caught this annoying unretrieved exception")
client.loop.set_exception_handler(my_handler)
`
