### ISSUE TITLE
Can't run commands cause ctx isnt defined anymore?

### ISSUE THREAD

**Issue by SIX10** [Rapptz/discord.py#1304]
I am getting this when running my invite command:
`Ignoring exception in command invite
Traceback (most recent call last):
  File "C:\Users\James\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "partly.py", line 25, in invite
    await ctx.send(embed=msg)
NameError: name 'ctx' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\James\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\James\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\James\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'ctx' is not defined`

My invite code is
`@bot.command()
async def invite():
    msg = discord.Embed(title="Invite",
                        description="You can invite me to your server with https://discordapp.com/oauth2/authorize?client_id=447940688508878868&scope=bot&permissions=0",
                        color=discord.Color.red())
    await ctx.send(embed=msg)`

I am running Python 3.6 on windows.

**Comment by SIX10** [comment]
Closed as the discord server helped me :D

**Comment by gurke12** [comment]
What was the solution? I think I have the same problem

**Comment by AnInternetTroll** [comment]
async def invite(**ctx**):
