### ISSUE TITLE
Discord Bot Python (Bot Command Send_File)

### ISSUE THREAD

**Issue by DevilishScarlet** [Rapptz/discord.py#1306]
Hey, I'm having some trouble with a randomizer I'm trying to create, but the sending image file isn't working. Here is what I have:

@bot.command(pass_context=True)
async def firstroll(ctx):
    embed = discord.Embed(title="Servant Card", description="Current Card:", color=0x808080)
    await bot.send_file(ctx.message.channel, 'Saber1.png')
    await bot.say(embed=embed)

If anyone played the Pokecord, it's a similar concept. I want to make it randomize between images that I have saved on my laptop. But I get this error:

Ignoring exception in command firstroll
Traceback (most recent call last):
  File "C:\Users\thejo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\thejo\Desktop\FateDiscord\Fate.py", line 28, in firstroll
    await bot.send_file(ctx.message.channel, 'Saber1.png')
  File "C:\Users\thejo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 1226, in send_file
    with open(fp, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'Saber1.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\thejo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\thejo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\thejo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: [Errno 2] No such file or directory: 'Saber1.png'

**Comment by Harmon758** [comment]
Is the image file in your current working directory, i.e. the directory you're running the script from?

Also, for future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by DevilishScarlet** [comment]
First, my apologies, I just recently signed to this and skipped that part. I'll do a full reading soon.

And no. They are on a folder separated on my Desktop.
I have Python and am using Visual Studio Coding.

Should I move the pictures to the folder of Python or Visual Coding?

**Comment by Harmon758** [comment]
You can either move the file to your working directory or specify the relative or full path to the file.

**Comment by DevilishScarlet** [comment]
However, when I specify the directory, for example, from my Desktop it gives me the current error:
E0001:(unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<string>, line 28)

The code being like this:
await bot.send_file(ctx.message.channel, 'C:\Users\thejo\Desktop\Class Cards\Saber1.png')

**Comment by Harmon758** [comment]
You have to escape your backslashes: `\\`.
