### ISSUE TITLE
Error importing aiohttp with newer version of rewrite

### ISSUE THREAD

**Issue by mdiller** [Rapptz/discord.py#1308]
I updated my rewrite version of discord.py today and when I started my bot, i hit an exception when discord.py tried to import aiohttp.

Trace:
```
Traceback (most recent call last):
  File "mybotbot.py", line 1, in <module>
    import discord
  File "/usr/local/lib/python3.6/dist-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 30, in <module>
    from .guild import Guild
  File "/usr/local/lib/python3.6/dist-packages/discord/guild.py", line 39, in <module>
    from .channel import *
  File "/usr/local/lib/python3.6/dist-packages/discord/channel.py", line 31, in <module>
    from .webhook import Webhook
  File "/usr/local/lib/python3.6/dist-packages/discord/webhook.py", line 27, in <module>
    import aiohttp
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/connector.py", line 17, in <module>
    from .client_proto import ResponseHandler
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_proto.py", line 6, in <module>
    from .http import HttpResponseParser, StreamWriter
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/http.py", line 8, in <module>
    from .http_parser import (HttpParser, HttpRequestParser, HttpResponseParser,
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/http_parser.py", line 15, in <module>
    from .http_writer import HttpVersion, HttpVersion10
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/http_writer.py", line 304, in <module>
    class URL(yarl.URL):
  File "/usr/local/lib/python3.6/dist-packages/yarl/__init__.py", line 232, in __init_subclass__
    "is forbidden".format(cls))
TypeError: Inheritance a class <class 'aiohttp.http_writer.URL'> from URL is forbidden
```

pip showed that my aiohttp version was `2.2.5`, so I tried downgrading to `2.0.0`, and now it seems to be working just fine.

Is anyone else able to reproduce this?

**Comment by Harmon758** [comment]
This is a duplicate of #1280

**Comment by mdiller** [comment]
Whoops, didn't check before posting. My bad.

**Comment by mdiller** [comment]
Closing because duplicate
