### ISSUE TITLE
Exception in keep_alive_handler: Cannot write to a WebSocket in the CLOSING state

### ISSUE THREAD

**Issue by BigSako** [Rapptz/discord.py#131]
Using latest git version (0.10.0 alpha, 050c668eaceb063e2c22404aa0e97abf2abd5934):
Stack trace:

```
task: <Task pending coro=<_run_event() running at /somewhere/discord_app/py34/lib/python3.4/site-packages/discord/client.py:267> wait_for=<Future pending cb=[Task._wakeup()]>>

Task exception was never retrieved
future: <Task finished coro=<keep_alive_handler() done, defined at /somewhere/discord_app/py34/lib/python3.4/site-packages/discord/client.py:287> exception=InvalidState('Cannot write to a WebSocket in the CLOSING state',)>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 238, in _step
    result = next(coro)
  File "/somewhere/discord_app/py34/lib/python3.4/site-packages/discord/client.py", line 298, in keep_alive_handler
    yield from self._send_ws(utils.to_json(payload))
  File "/somewhere/discord_app/py34/lib/python3.4/site-packages/discord/client.py", line 161, in _send_ws
    yield from self.ws.send(data)
  File "/somewhere/discord_app/py34/lib/python3.4/site-packages/websockets/protocol.py", line 261, in send
    yield from self.write_frame(opcode, data)
  File "/somewhere/discord_app/py34/lib/python3.4/site-packages/websockets/protocol.py", line 421, in write_frame
    "in the {} state".format(self.state_name))
```

**Comment by Rapptz** [comment]
You're blocking the library for too long (more than `heartbeat_interval` seconds) so the websocket closes and tries to write a keep alive packet and it fails.

Try to not block.
