### ISSUE TITLE
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'generator' object has no attribute 'server'

### ISSUE THREAD

**Issue by EpicShardGamingYT** [Rapptz/discord.py#1310]
Seems like the get_inv is broken or just me beeing dumb again -_-
`@client.command(pass_context=True)
async def partner(link: str):
	dirObj = client.get_invite(link)
	await client.say(dirObj.server.name)`
Error is title xD

**Comment by EpicShardGamingYT** [comment]
UPDATE: 
my code now (still not working):
@client.command(pass_context=True)
async def partner(link:str):
	dirObj = await client.get_invite(link) 
	await client.say(dirObj.server.name)
Error:
Ignoring exception in command partner
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "E:\Development\DiscordBots\Coder\Main.py", line 112, in partner
    dirObj = await client.get_invite(link)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\discord\client.py", line 2662, in get_invite
    invite_id = self._resolve_invite(url)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\discord\client.py", line 259, in _resolve_invite
    m = re.match(rx, invite)
  File "C:\Program Files (x86)\Python36-32\lib\re.py", line 172, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: expected string or bytes-like object

**Comment by Harmon758** [comment]
You have `pass_context` set to `True`, so it's being passed to `partner` as `link`, which is why `get_invite` is raising an error telling you it expected a `string` instead of a `Context` object.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
