### ISSUE TITLE
Can't install Discord.py 1.0

### ISSUE THREAD

**Issue by MonkeyBot2020** [Rapptz/discord.py#1328]
I ran `python3 -m pip install -U discord.py` but it only installed discord.py 0.16. How do I install the new discord.py 1.0? I uninstalled it using pip uninstall discord.py and re-ran the pip install discord.py, only to get version 0.16 again instead of the new 1.0 version.

I'm using python 3.6, anaconda3 on a mac.

What do I do?

**Comment by NCPlayz** [comment]
Run the following: 
`pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]` 
To install without voice just take out `[voice]`.

**Comment by ItWasAllIntended** [comment]
The documentation is written with the future in mind, they will be correct when rewrite becomes the version on pip. For now, use this pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]

**Comment by EvieePy** [comment]
pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]

**Comment by MonkeyBot2020** [comment]
I did that, now I can't even `import discord`! I get the following error:

`>>> import discord
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Kumar/anaconda3/lib/python3.6/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo
  File "/Users/Kumar/anaconda3/lib/python3.6/site-packages/discord/client.py", line 30, in <module>
    from .guild import Guild
  File "/Users/Kumar/anaconda3/lib/python3.6/site-packages/discord/guild.py", line 39, in <module>
    from .channel import *
  File "/Users/Kumar/anaconda3/lib/python3.6/site-packages/discord/channel.py", line 31, in <module>
    from .webhook import Webhook
  File "/Users/Kumar/anaconda3/lib/python3.6/site-packages/discord/webhook.py", line 27, in <module>
    import aiohttp
  File "/Users/Kumar/anaconda3/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/Users/Kumar/anaconda3/lib/python3.6/site-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/Users/Kumar/anaconda3/lib/python3.6/site-packages/aiohttp/connector.py", line 17, in <module>
    from .client_proto import ResponseHandler
  File "/Users/Kumar/anaconda3/lib/python3.6/site-packages/aiohttp/client_proto.py", line 6, in <module>
    from .http import HttpResponseParser, StreamWriter
  File "/Users/Kumar/anaconda3/lib/python3.6/site-packages/aiohttp/http.py", line 8, in <module>
    from .http_parser import (HttpParser, HttpRequestParser, HttpResponseParser,
  File "/Users/Kumar/anaconda3/lib/python3.6/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .http_writer import HttpVersion, HttpVersion10
  File "/Users/Kumar/anaconda3/lib/python3.6/site-packages/aiohttp/http_writer.py", line 304, in <module>
    class URL(yarl.URL):
  File "/Users/Kumar/anaconda3/lib/python3.6/site-packages/yarl/__init__.py", line 232, in __init_subclass__
    "is forbidden".format(cls))
TypeError: Inheritance a class <class 'aiohttp.http_writer.URL'> from URL is forbidden
`

**Comment by ItWasAllIntended** [comment]
Do **pip install -U "yarl>1.2"**

**Comment by MonkeyBot2020** [comment]
I did that, now I can't even `import discord`! I get the following error:

`>>> import discord
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/blah/anaconda3/lib/python3.6/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo
  File "/Users/blah/anaconda3/lib/python3.6/site-packages/discord/client.py", line 30, in <module>
    from .guild import Guild
  File "/Users/blah/anaconda3/lib/python3.6/site-packages/discord/guild.py", line 39, in <module>
    from .channel import *
  File "/Users/blah/anaconda3/lib/python3.6/site-packages/discord/channel.py", line 31, in <module>
    from .webhook import Webhook
  File "/Users/blah/anaconda3/lib/python3.6/site-packages/discord/webhook.py", line 27, in <module>
    import aiohttp
  File "/Users/blah/anaconda3/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/Users/blah/anaconda3/lib/python3.6/site-packages/aiohttp/client.py", line 15, in <module>
    from . import connector as connector_mod
  File "/Users/blah/anaconda3/lib/python3.6/site-packages/aiohttp/connector.py", line 17, in <module>
    from .client_proto import ResponseHandler
  File "/Users/blah/anaconda3/lib/python3.6/site-packages/aiohttp/client_proto.py", line 6, in <module>
    from .http import HttpResponseParser, StreamWriter
  File "/Users/blah/anaconda3/lib/python3.6/site-packages/aiohttp/http.py", line 8, in <module>
    from .http_parser import (HttpParser, HttpRequestParser, HttpResponseParser,
  File "/Users/blah/anaconda3/lib/python3.6/site-packages/aiohttp/http_parser.py", line 15, in <module>
    from .http_writer import HttpVersion, HttpVersion10
  File "/Users/blah/anaconda3/lib/python3.6/site-packages/aiohttp/http_writer.py", line 304, in <module>
    class URL(yarl.URL):
  File "/Users/blah/anaconda3/lib/python3.6/site-packages/yarl/__init__.py", line 232, in __init_subclass__
    "is forbidden".format(cls))
TypeError: Inheritance a class <class 'aiohttp.http_writer.URL'> from URL is forbidden
`

**Comment by ItWasAllIntended** [comment]
I editied it

**Comment by MonkeyBot2020** [comment]
Yup, I did `pip install -U "yarl>1.2"` and then `pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]`

Still no luck with importing discord

**Comment by ItWasAllIntended** [comment]
yarl<1.2

**Comment by MonkeyBot2020** [comment]
it works - thank you!
