### ISSUE TITLE
[SOLVED] [SORRY] Crash when a user creates a category

### ISSUE THREAD

**Issue by mataxor** [Rapptz/discord.py#1333]
Windows 10 64-bit
discord.py version 1.0.0a
Python version 3.6.3

Cause:
A user creating a category

Error:
```
Traceback (most recent call last):
    File "C:\...\myBot.py", line 37, in <module>
        bot.run(<token redacted>)
    File "C:\...\discord\client.py", line 567, in run
        return task.result()
    File "C:\...\discord\client.py", line 487, in _silence_gathered
        fut.result()
    File "C:\...\discord\client.py", line 475, in start
        yield from self.connect(reconnect=reconnect)
    File "C:\...\discord\client.py", line 407, in connect
        yield from self._connect()
    File "C:\...\discord\client.py", line 369, in _connect
        yield from self.ws.poll_event()
    File "C:\...\discord\gateway.py", line 438, in poll_event
        yield from self.received_message(msg)
    File "C:\...\discord\gateway.py", line 391, in received_message
        func(data)
    File "C:\...\discord\state.py", line 499, in parse_channel_create
        channel = factory(guild=guild, state=self, data=data)
TypeError: 'NoneType' object is not callable
```

**Comment by Harmon758** [comment]
This was fixed in https://github.com/Rapptz/discord.py/commit/1367877d36872ae98e8375d6a9b76ab7dc1c991e when category channels came out on Canary.
Support was later added for category channels in https://github.com/Rapptz/discord.py/commit/53b48904358866e62c6afec1a548424f12c7e1d1 the next week.

Since `channel = factory(guild=guild, state=self, data=data)` has not been on line 499 of state.py since before these commits, you are almost certainly running a version of the rewrite branch that hasn't been updated since at least September of last year.

Please make sure you're up to date with the latest versions when submitting issues, especially for the rewrite branch. In the future, you should also include the full version number when reporting issues on the rewrite branch, e.g. something like 1.0.0a1467+g6b75179.

**Comment by Harmon758** [comment]
Please close the issue instead of just changing the title.
