### ISSUE TITLE
server.main_channel returns None?

### ISSUE THREAD

**Issue by scottbeebiwan** [Rapptz/discord.py#1339]
I'm using this code as the on_ready in my Discord bot.
@client.event
```
async def on_ready():
        print('Logged in as '+client.user.name)
        await client.change_presence(game=discord.Game(name=prefix+'help'))
        print('Sending welcome messages...')
        for s in client.servers:
          print([s.name, s.default_channel])
          await client.send_message(s.default_channel,joinmsg)
```
When I run it, I expect it to send `joinmsg` to every server it's on.
Instead,
```
Sending welcome messages...
['crappy internet club', None]
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/home/scottbeebiwan/Desktop/scottbeebibot/scottbeebibot.py", line 33, in on_ready
    await client.send_message(s.default_channel,joinmsg)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 1145, in send_message
    channel_id, guild_id = yield from self._resolve_destination(destination)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 289, in _resolve_destination
    raise InvalidArgument(fmt.format(destination))
discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object. Received NoneType
```

**Comment by Vexs** [comment]
Default channels have been removed from Discord as of some time ago. You'll have to find some other way to specify a channel. Take a look at the `get_channel` method.

**Comment by Cristy86** [comment]
for more help, join the support server.

https://discord.gg/r3sSKJJ
