### ISSUE TITLE
NameError: name 'create_task' is not defined

### ISSUE THREAD

**Issue by tagptroll1** [Rapptz/discord.py#1342]
```Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 60, in wrapped
    ret = await coro(*args, **kwargs)
  File "E:\Python\Bot Projects\demetori2\cogs\officer.py", line 133, in clear_all
    async with ctx.channel.typing():
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\context_managers.py", line 64, in __aenter__
    return self.__enter__()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\context_managers.py", line 54, in __enter__
    self.task = create_task(self.do_typing(), loop=self.loop)
NameError: name 'create_task' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 876, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 913, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 503, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 69, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'create_task' is not defined```

From my code : 
```    @clear.command(name="all")
    @commands.has_role("Officer")
    async def clear_all(self, ctx):
        """Deletes all messages in a channel (up to 1000)"""
        async with ctx.channel.typing():
            async for message in ctx.channel.history(limit=1000):
                await message.delete()
        await ctx.send("Done!", delete_after=5)```

Edit: full traceback

**Comment by Rapptz** [comment]
Should be fixed.
