### ISSUE TITLE
'NoneType' object has no attribute 'change_presence'

### ISSUE THREAD

**Issue by alwayslivid** [Rapptz/discord.py#1347]
I initially didn't realize that the "game" attribute was renamed to "activity", but even after changing it, I still came across the same issue.

```
import discord
from discord.ext import commands

activity = discord.Game(name=random.choice(str(config.statuses)))
client = discord.Client()
bot = commands.Bot(command_prefix=str(config.prefix), description=config.description)

@bot.event
async def on_ready():
  await client.change_presence(status=discord.Status.idle, activity=activity)

bot.run(config.token)
```

Here's the entire error:
```
Traceback (most recent call last):
  File "C:\Users\AlwaysLivid\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 220, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\AlwaysLivid\Desktop\Discord Mailbot\main.py", line 32, in on_ready
    await client.change_presence(status=discord.Status.idle, activity=activity)
  File "C:\Users\AlwaysLivid\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 839, in change_presence
    await self.ws.change_presence(activity=activity, status=status, afk=afk)
AttributeError: 'NoneType' object has no attribute 'change_presence'
```

**Comment by alwayslivid** [comment]
EDIT: A person on the Discord pointed out that this happened because I used both discord.ext.commands and discord at the same time. My apologies!

**Comment by Cristy86** [comment]
If you have `bot = commands.Bot(. . .)` don't use `client = discord.Client()`

Please join the support server for more problems.
https://discord.gg/r3sSKJJ
