### ISSUE TITLE
Failing to install PyNaCl while building

### ISSUE THREAD

**Issue by MemesOnAStick** [Rapptz/discord.py#1359]
Hi, I'm trying to add voice support for my bot, but as I try to install, I get this rather large error

> Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4ldnooqj/PyNaCl/setup.py", line 259, in <module>
        "Programming Language :: Python :: 3.5",
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-4ldnooqj/PyNaCl/setup.py", line 186, in run
        cwd=build_temp,
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/tmp/pip-install-4ldnooqj/PyNaCl/src/libsodium/configure', '--disable-shared', '--enable-static', '--disable-debug', '--disable-dependency-tracking', '--with-pic', '--prefix', '/tmp/pip-install-4ldnooqj/PyNaCl/build/temp.linux-x86_64-3.5']' returned non-zero exit status 1
    

> Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-4ldnooqj/PyNaCl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-d_68ivka/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-4ldnooqj/PyNaCl/

How should I fix this problem? I am on uBuntu 16.04.4, with Python 3.5.2

Thanks for the help!

**Comment by ButterCheezii** [comment]
Do you have `libsodium` installed?

```
sudo apt-get install libsodium
```

**Comment by Gorialis** [comment]
This stack seems kind of weird, but my best guess is you're missing `libffi-dev` (which is a dependency as mentioned in the [README](https://github.com/Rapptz/discord.py#installing).

On Debian/Ubuntu you should try:
```sh
sudo apt-get update && sudo apt-get install build-essential python3-dev libffi-dev
```
On Arch Linux (or derivatives/sibling distros that use `pacman`):
```sh
sudo pacman -Sy base-devel python libffi
```
On Alpine Linux:
```sh
sudo apk update && sudo apk add alpine-sdk python3-dev libffi-dev
```

**Comment by MemesOnAStick** [comment]
Thank you so much! @Gorialis @ButterCheezii
