### ISSUE TITLE
TypeError: create_connection() got an unexpected keyword argument 'compression'

### ISSUE THREAD

**Issue by KiraIsJustice** [Rapptz/discord.py#1363]
I just installed the rewrite version of discord.py and a friend of mine helped me rewriting my bot, but when i try to lauch it I have this large error message comming up : 
`Traceback (most recent call last):
File "D:\Users\DESKTOP-V715THM\Downloads\Bot trop coul\bot-roulette.py", line 162, in <module>
    bot.run("token")
  File "D:\Users\DESKTOP-V715THM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord.py-1.0.0a0-py3.6.egg\discord\client.py", line 568, in run
    return task.result()
  File "D:\Users\DESKTOP-V715THM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord.py-1.0.0a0-py3.6.egg\discord\client.py", line 488, in _silence_gathered
    fut.result()
  File "D:\Users\DESKTOP-V715THM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord.py-1.0.0a0-py3.6.egg\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "D:\Users\DESKTOP-V715THM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord.py-1.0.0a0-py3.6.egg\discord\client.py", line 398, in connect
    await self._connect()
  File "D:\Users\DESKTOP-V715THM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord.py-1.0.0a0-py3.6.egg\discord\client.py", line 358, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "D:\Users\DESKTOP-V715THM\AppData\Local\Programs\Python\Python36-32\lib\asyncio\tasks.py", line 358, in wait_for
    return fut.result()
  File "D:\Users\DESKTOP-V715THM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord.py-1.0.0a0-py3.6.egg\discord\gateway.py", line 199, in from_client
    ws = await websockets.connect(gateway, loop=client.loop, klass=cls, compression=None)
  File "D:\Users\DESKTOP-V715THM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\py35\client.py", line 19, in __await__
    return (yield from self.client)
  File "D:\Users\DESKTOP-V715THM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\websockets\client.py", line 210, in connect
    factory, wsuri.host, wsuri.port, **kwds)
TypeError: create_connection() got an unexpected keyword argument 'compression'`
I'm learning python so I'm not very familiar with it

**Comment by Harmon758** [comment]
First off, you're going to want to change your token now.
It seems like you're using an outdated version of websockets (likely 3.4). The library now requires websockets>=5.0.

**Comment by KiraIsJustice** [comment]
Yeah I just realised I'm dumb and i forgot to hide it
I'll google how to upgrade and tell if something changes

**Comment by Rapptz** [comment]
Your dependencies are out of date.

**Comment by KiraIsJustice** [comment]
Ok first I have a new token, and i updated my version of websockets, it fixed the issue, thank you a lot
