### ISSUE TITLE
KeyError: '460561093450924043' DISCORD.PY

### ISSUE THREAD

**Issue by zomatree** [Rapptz/discord.py#1373]
error
`
Ignoring exception in command bal
Traceback (most recent call last):
  File "C:\Users\angel\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "c:\Users\angel\Desktop\PYTHON_STUFF\Casino-Bot\bot.py", line 50, in bal
    await bot.say("you have {}".format(money[ctx.message.id]))
KeyError: '460561093450924043'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\angel\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\angel\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\angel\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: '460561093450924043'
`

code: https://pastebin.com/LVGeX6Bu

can anyone pls help me why im getting this

**Comment by khazhyk** [comment]
You are attempting to access a key which is not in your dictionary. (Your program will *only* try to access the key if it does not exist in the dictionary). This doesn't look like an issue with the library. If you are just learning python, you may want to join some python learning chats or run through some tutorials (I'm sorry I don't have good links :( )

For future questions regarding using discord.py, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.

**Comment by komq79Korea** [comment]
저도 그래요
