### ISSUE TITLE
help me..

### ISSUE THREAD

**Issue by Heedue** [Rapptz/discord.py#1387]
Traceback (most recent call last):
  File "D:\Documents\작업물\bot.py", line 1, in <module>
    import discord.ext
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax

-----------------------------------
--why is this?

**Comment by Harmon758** [comment]
This is a duplicate of #1249.

**Comment by Heedue** [comment]
Thanks for your help, I was able to solve it!
