### ISSUE TITLE
[Python 3.7] cannot 'yield from' a coroutine object in a non-coroutine generator 

### ISSUE THREAD

**Issue by romangraef** [Rapptz/discord.py#1390]
Code:
```py
bot = Bot(command_prefix=when_mentioned_or('!'))

load_all_modules(bot)

if __name__ == '__main__':
    bot.run(token)
```
`load_all_modules` simply includes a bunch of cogs, which only contain three commands + an on_ready and an on_event listener.

Using Python3.7 (using `python3.7 -m venv`) i get the following stacktrace 
```
Traceback (most recent call last):
  File "/home/romangraef/PycharmProjects/evalbot/main.py", line 11, in <module>
    bot.run(token)
  File "/home/romangraef/PycharmProjects/evalbot/venv/lib64/python3.7/site-packages/discord/client.py", line 568, in run
    return task.result()
  File "/home/romangraef/PycharmProjects/evalbot/venv/lib64/python3.7/site-packages/discord/client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "/home/romangraef/PycharmProjects/evalbot/venv/lib64/python3.7/site-packages/discord/client.py", line 398, in connect
    await self._connect()
  File "/home/romangraef/PycharmProjects/evalbot/venv/lib64/python3.7/site-packages/discord/client.py", line 358, in _connect
    self.ws = await asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "/usr/lib64/python3.7/asyncio/tasks.py", line 412, in wait_for
    return fut.result()
  File "/home/romangraef/PycharmProjects/evalbot/venv/lib64/python3.7/site-packages/discord/gateway.py", line 199, in from_client
    ws = await websockets.connect(gateway, loop=client.loop, klass=cls, compression=None)
  File "/home/romangraef/PycharmProjects/evalbot/venv/lib64/python3.7/site-packages/websockets/client.py", line 397, in __await__
    transport, protocol = yield from self._creating_connection
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f97a63be0f0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f97a627b8d0>, 3189.251525591)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f97a63be128>
sys:1: RuntimeWarning: coroutine 'BaseEventLoop.create_connection' was never awaited
```
Using Python3.6 (again: `python3.6 -m venv`) the bot runs just fine. Used 3.7 features: dataclasses
```bash
$ python3.7 --version
Python 3.7.0rc1
$ pip freeze
aiohttp==3.3.2
async-timeout==3.0.0
attrs==18.1.0
chardet==3.0.4
discord.py==1.0.0a1481+g983be10
idna==2.7
idna-ssl==1.0.1
multidict==4.3.1
websockets==5.0.1
yarl==1.2.6
```

**Comment by ItWasAllIntended** [comment]
This error is due to the Pypi version of Websockets not yet supporting 3.7. If you wish to use 3.7, install the websockets from the ws repo. Just note you may encounter more issues in 3.7 as it hasn't been out for too long, though, as far as we're aware, it is alright to use
