### ISSUE TITLE
AttributeError on GUILD_MEMBER_REMOVE

### ISSUE THREAD

**Issue by Hornwitser** [Rapptz/discord.py#14]
When you leave a server, a GUILD_DELETE message is sent on the WebSocket deleting the server.  But afterwards a GUILD_MEMBER_REMOVE may appear referencing yourself, and the just deleted guild. Causing the following traceback:

    Traceback (most recent call last):
      File "bot.py", line 66, in <module>
        bot.run()
      File "/home/julian/prog/record/discord/client.py", line 472, in run
        self.ws.run()
      File "/usr/lib/python3.5/site-packages/ws4py/websocket.py", line 427, in run
        if not self.once():
      File "/usr/lib/python3.5/site-packages/ws4py/websocket.py", line 305, in once
        if not self.process(b):
      File "/usr/lib/python3.5/site-packages/ws4py/websocket.py", line 377, in process
        self.received_message(s.message)
      File "/home/julian/prog/record/discord/client.py", line 122, in received_message
        self.dispatch('socket_update', event, data)
      File "/home/julian/prog/record/discord/client.py", line 459, in dispatch
        getattr(self, handle_method, _null_event)(*args, **kwargs)
      File "/home/julian/prog/record/discord/client.py", line 467, in handle_socket_update
        getattr(self.connection, method)(data)
      File "/home/julian/prog/record/discord/client.py", line 285, in handle_guild_member_remove
        member = utils.find(lambda m: m.id == user_id, server.members)
    AttributeError: 'NoneType' object has no attribute 'members'

See also the [WebSocket context](http://hornwitser.no/discord/query?query=SELECT+*+FROM+message+WHERE+id+%3C+7000+ORDER+BY+id+DESC+LIMIT+20).

**Comment by Rapptz** [comment]
Should be fixed in 4ec052a35cd4ee812504ff9d1fd7240d546995ec.
