### ISSUE TITLE
await bot.say broken?

### ISSUE THREAD

**Issue by wntjq6902** [Rapptz/discord.py#1414]
```python
@bot.group(pass_context=True)
async def skip(ctx):
        global skip_vote
        global should_skip
        if ctx.invoked_subcommand is None:
                if skip_vote is 3:
                        await bot.say("Enough people voted to skip, skip, skipping...")
                        skip_vote = 0
                        should_skip = True
                else:
                        skip_vote = skip_vote + 1
                        if ctx.message.author.nick is None:
                                await bot.say("{} Wants to skip current song! {}/4 people requird.", format(ctx.message.author.name, str(skip_vote)))
                        else:
                                await bot.say("{} Wants to skip current song! {}/4 people requird.", format(ctx.message.author.nick, str(skip_vote)))

@skip.command(pass_context=True)
async def force(ctx):
        global skip_vote
        global should_skip
        highest_role = selfuser.roles[0]
        for i in selfuser.roles:
                if i > highest_role:
                        highest_role = i

        bot_role = highest_role

        highest_role = ctx.message.author.roles[0]
        for i in ctx.message.author.roles:
                if i > highest_role:
                        highest_role = i

        if highest_role < i:
                await bot.say("You don't have permission to force a song skip! voting normally...")
                if skip_vote is 3:
                        await bot.say("Enough people voted to skip, skip, skipping...")
                        skip_vote = 0
                        should_skip = True
                else:
                        skip_vote = skip_vote + 1
                        if ctx.message.author.nick is None:
                                await bot.say("{} Wants to skip current song! {}/4 people requird.", format(ctx.message.author.name, str(skip_vote)))
                        else:
                                await bot.say("{} Wants to skip current song! {}/4 people requird.", format(ctx.message.author.nick, str(skip_vote)))
        else:
                if ctx.message.author.nick is None:
                        await bot.say("Admin {} is skipping this song!", format(ctx.message.author.name))
                else:
                        await bot.say("Admin {} is skipping this song!", format(ctx.message.author.nick))
                skip_vote = 0
                should_skip = true
```

```python
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "E:\custom_discord_bgm_bot\bot.py", line 149, in skip
    await bot.say("{} Wants to skip current song! {}/4 people requird.", format(ctx.message.author.name, str(skip_vote)))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\discord\ext\commands\bot.py", line 350, in say
    coro = self.send_message(destination, *args, **kwargs)
TypeError: send_message() takes from 2 to 3 positional arguments but 4 were given
```

i know my code is horrible, but it should work.. or am i doing something stupid?

**Comment by mrc0mmand** [comment]
You have the `str.format()` wrong:

```python
await bot.say("This is a {} string".format("formatted"))
```

**Comment by wntjq6902** [comment]
well, i feel stupid now. problem solved. closing
