### ISSUE TITLE
Classic Error plus some I didn't find in Issues

### ISSUE THREAD

**Issue by G3bE** [Rapptz/discord.py#1461]
Well, I downloaded the current version from GitHub and ran this command in the folder:
`python3 -m pip install -U .[voice]`
I tried to run this code:
```
import discord
import asyncio

client = discord.Client()

TOKEN = "Don't even think about it!"
PREFIX = ":"

@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')

@client.event
async def on_message(message):
    if message.content.startswith(PREFIX + 'test'):
        counter = 0
        await client.send_message(message.channel, 'Wow, I am amazing!')
    elif message.content.startswith(PREFIX + 'sleep'):
        await asyncio.sleep(5)
        await client.send_message(message.channel, 'Done sleeping!')

client.run(TOKEN)
```
and this errors were shown:
```
Traceback (most recent call last):
  File "/Users/nikolas/Documents/CaptianOverkill/CaptainOverkill.py", line 1, in <module>
    import discord
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/discord/voice_client.py", line 43, in <module>
    import websockets
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/__init__.py", line 3, in <module>
    from .client import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/client.py", line 12, in <module>
    from .protocol import CONNECTING, OPEN, WebSocketCommonProtocol
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/protocol.py", line 17, in <module>
    from .compatibility import asyncio_ensure_future
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/websockets/compatibility.py", line 9
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                        ^
SyntaxError: invalid syntax
```
If there is already a issue that solved this, just post it - it would be really helpful!

PS: I got python version 3.7 and YES I tried installing the old version from pip while using python 3.6.0

**Comment by ItWasAllIntended** [comment]
That error is because the async branch is not compatible with 3.7. Double check you're installing and running dpy on 3.6.6. Though you'll be fine here for the moment, questions like these are better suited to the discord.py server[discord.py server](https://discord.gg/r3sSKJJ) in future

**Comment by Harmon758** [comment]
Duplicate of #1401

**Comment by Harmon758** [comment]
Duplicate of #423

**Comment by G3bE** [comment]
Worked, thank you! <3
