### ISSUE TITLE
change_status with unavailable guilds breaks

### ISSUE THREAD

**Issue by khazhyk** [Rapptz/discord.py#151]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/asyncio/tasks.py", line 236, in _step
    result = coro.send(value)
  File "main.py", line 96, in status_stats
    yield from bot.change_status(game=discord.Game(name=msg))
  File "/home/sam/.local/lib/python3.4/site-packages/discord/client.py", line 1532, in change_status
    server.me.game = game
AttributeError: 'NoneType' object has no attribute 'game'
```

**Comment by Maxie01** [comment]
What's the code you are using?

**Comment by khazhyk** [comment]
This is caused by unavailable guilds in the ready message when using a large or bot account since a recent update

**Comment by ayancey** [comment]
I just can't get `change_status` to work at all.

**Comment by Rapptz** [comment]
This was fixed already.
