### ISSUE TITLE
Audio player error at end of song [rewrite]

### ISSUE THREAD

**Issue by maikka39** [Rapptz/discord.py#1536]
When using the following code:
```python
vc.play(discord.FFmpegPCMAudio("temp.mp3"))
```
I get the following error at the end of the audio file:
```bash
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/maik/.local/lib/python3.6/site-packages/discord/player.py", line 299, in run
    self.source.cleanup()
  File "/home/maik/.local/lib/python3.6/site-packages/discord/player.py", line 180, in cleanup
    proc.kill()
  File "/usr/lib/python3.6/subprocess.py", line 1590, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python3.6/subprocess.py", line 1580, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
```

This happens with other sound files to.

**Comment by maikka39** [comment]
Anyone else who has this issue?
