### ISSUE TITLE
This happens everytime the client joins a server for me.

### ISSUE THREAD

**Issue by AraHaan** [Rapptz/discord.py#155]
Traceback (most recent call last):
      File "E:\Users\Elsword\Desktop\DecoraterBot\Async\\DecoraterBot.py", line 38,
     in <module>
        await DecoraterBotCore.Login.on_login(client)
      File "E:\Users\Elsword\Desktop\DecoraterBot\Async\DecoraterBotCore\Login.py",
    line 35, in login_info
        client.run(discord_user_email, discord_user_password)
      File "E:\Python35\lib\site-packages\discord\client.py", line 608, in run
        self.loop.run_until_complete(self.start(email, password))
      File "E:\Python35\lib\asyncio\base_events.py", line 337, in run_until_complete

        return future.result()
      File "E:\Python35\lib\asyncio\futures.py", line 274, in result
        raise self._exception
      File "E:\Python35\lib\asyncio\tasks.py", line 239, in _step
        result = coro.send(None)
      File "E:\Python35\lib\site-packages\discord\client.py", line 578, in start
        yield from self.connect()
      File "E:\Python35\lib\site-packages\discord\client.py", line 547, in connect
        yield from self.received_message(msg)
      File "E:\Python35\lib\site-packages\discord\client.py", line 381, in received_message
        result = func(data)
      File "E:\Python35\lib\site-packages\discord\state.py", line 284, in parse_guild_member_update
        member = server.get_member(user_id)
    AttributeError: 'NoneType' object has no attribute 'get_member'
    Unclosed client session
    client_session: <aiohttp.client.ClientSession object at 0x03075CB0>
    Unclosed client session
    client_session: <aiohttp.client.ClientSession object at 0x005D7270>
    Task was destroyed but it is pending!
    task: <Task pending coro=<WebSocketCommonProtocol.run() running at E:\Python35\lib\site-packages\websockets\protocol.py:302> wait_for=<Future pending cb=[Task._wakeup()]>>
    Task was destroyed but it is pending!
    task: <Task pending coro=<Client.keep_alive_handler() running at E:\Python35\lib\site-packages\discord\client.py:300> wait_for=<Future pending cb=[Task._wakeup()]>>
    Press any key to continue . . .
This is something that seems like a issue in state.py itself.

**Comment by AraHaan** [comment]
:ok: so it seems like this fixes it
    def parse_guild_member_update(self, data):
        server = self._get_server(data.get('guild_id'))
        user_id = data['user']['id']
        if server is not None:
            member = server.get_member(user_id)
           if member is not None:
                user = data['user']
                old_member = copy.copy(member)
                member.name = user['username']
                member.discriminator = user['discriminator']
                member.avatar = user['avatar']
                member.roles = [server.default_role]
                # update the roles
                for role in server.roles:
                    if role.id in data['roles']:
                        member.roles.append(role)

                self.dispatch('member_update', old_member, member)
