### ISSUE TITLE
Unknown Error in files i didnt know they were there

### ISSUE THREAD

**Issue by H3X3DTech** [Rapptz/discord.py#1554]
this is my code:
`import discord
from discord.ext import commands
from discord.ext.commands import Bot
import asyncio

bot = commands.Bot(command_prefix='-')

print('Logging in...')

@bot.event
async def on_ready():
    print ("Logged In!")

@bot.command(pass_context=True)
async def ping(ctx):
    await bot.say('Pong!')
    print('User has ran the ping command')

@bot.command(pass_context=True)
async def logout(ctx):
    await logout()

@bot.command(pass_context=True)
async def emoji(ctx):
    await get_all_emojis()

bot.run(ive blurred out the token ecksdee)`

and the error i got was
`C:\Users\harry>C:\Users\harry\OneDrive\Desktop\Pepsi-Bot\index.py
Traceback (most recent call last):
  File "C:\Users\harry\OneDrive\Desktop\Pepsi-Bot\index.py", line 1, in <module>
    import discord
  File "C:\Users\harry\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\harry\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\harry\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\harry\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax`

**Comment by Harmon758** [comment]
Duplicate of #1249 and #1401

**Comment by H3X3DTech** [comment]
@Harmon758 ok thx
