### ISSUE TITLE
Issue adding roles

### ISSUE THREAD

**Issue by H3X3DTech** [Rapptz/discord.py#1555]
I have issues adding roles to users:

the command is
`@bot.command(pass_context=True)
async def verify(ctx, Member):
    await add_roles(Member, Verified)
    await bot.say('Member has been given the Verified Role.')`

and the error im getting is
`Traceback (most recent call last):
  File "C:\Users\harry\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\harry\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\harry\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'add_roles' is not defined`

**Comment by H3X3DTech** [comment]
also, im not using rewrite because im used to the old one

**Comment by ItWasAllIntended** [comment]
This is because add_roles is an attribute of discord.Client and commands.Bot. GitHub issue are for issues with the library. Questions like this are better suited to the [D.py server](https://discord.gg/r3sSKJJ)

**Comment by H3X3DTech** [comment]
ok
