### ISSUE TITLE
Python3 pip error by installing discord.py

### ISSUE THREAD

**Issue by NaturalHacker** [Rapptz/discord.py#1569]
python3 -m pip install -U discord.py

```
Downloading/unpacking discord.py
  Downloading discord.py-0.16.12.tar.gz (414kB): 414kB downloaded
  Running setup.py (path:/tmp/pip-build-y43uyxtf/discord.py/setup.py) egg_info f                                                                                        or package discord.py
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-y43uyxtf/discord.py/setup.py", line 50, in <module>
        'Topic :: Utilities',
      File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.4/dist-packages/setuptools/dist.py", line 409, in __init__
        self._finalize_requires()
      File "/usr/local/lib/python3.4/dist-packages/setuptools/dist.py", line 428, in _finalize_requires
        self._convert_extras_requirements()
      File "/usr/local/lib/python3.4/dist-packages/setuptools/dist.py", line 443, in _convert_extras_requirements
        suffix = self._suffix_for(r)
      File "/usr/local/lib/python3.4/dist-packages/setuptools/dist.py", line 452, in _suffix_for
        return ':' + str(req.marker) if req.marker else ''
    AttributeError: 'Requirement' object has no attribute 'marker'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-y43uyxtf/discord.py/setup.py", line 50, in <module>

    'Topic :: Utilities',

  File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 131, in setup

    return distutils.core.setup(**attrs)

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/local/lib/python3.4/dist-packages/setuptools/dist.py", line 409, in __init__

    self._finalize_requires()

  File "/usr/local/lib/python3.4/dist-packages/setuptools/dist.py", line 428, in _finalize_requires

    self._convert_extras_requirements()

  File "/usr/local/lib/python3.4/dist-packages/setuptools/dist.py", line 443, in _convert_extras_requirements

    suffix = self._suffix_for(r)

  File "/usr/local/lib/python3.4/dist-packages/setuptools/dist.py", line 452, in _suffix_for

    return ':' + str(req.marker) if req.marker else ''

AttributeError: 'Requirement' object has no attribute 'marker'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-y43uyxtf/discord.py
Storing debug log for failure in /root/.pip/pip.log

```

**Comment by nathanctech** [comment]
What version of pip do you have? Update it with `python -m pip install --upgrade pip` then try again. Appears to be a bug with older pip versions.
