### ISSUE TITLE
Api Oauth login

### ISSUE THREAD

**Issue by Berttholio** [Rapptz/discord.py#158]
Utilizing a bot account does not allow for the bot to connect, is there a workaround?

```
Traceback (most recent call last):
  File "test.py", line 113, in <module>
    client.run('REDACTED', 'REDACTED')
  File "/usr/local/lib/python3.4/dist-packages/discord/client.py", line 590, in run
    self.loop.run_until_complete(self.start(email, password))
  File "/usr/lib/python3.4/asyncio/base_events.py", line 276, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 277, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 235, in _step
    result = coro.send(value)
  File "/usr/local/lib/python3.4/dist-packages/discord/client.py", line 561, in start
    yield from self.login(email, password)
  File "/usr/local/lib/python3.4/dist-packages/discord/client.py", line 469, in login
    raise LoginFailure('Improper credentials have been passed.')
discord.errors.LoginFailure: Improper credentials have been passed.
```

**Comment by shrx** [comment]
+1

**Comment by khazhyk** [comment]
You do not login with oauthid/client secret - you just use the token. https://github.com/Rapptz/discord.py/pull/140 has a possible implementation

**Comment by Rapptz** [comment]
Done.

Use `client.login('token')` or `client.run('token')` to do so.

**Comment by cheetahfm** [comment]
```
from discord.ext.commands import Bot

my_bot = Bot(command_prefix="!")

bot_token = 'client_secret_from_bot_page'

if __name__ == '__main__':
    my_bot.run(bot_token)
```

gives "discord.errors.LoginFailure: Improper token has been passed."

Hasn't it been resolved?

**Comment by Phxntxm** [comment]
Client secret is not the same thing as a token

https://discord.is-serious.business/6fd481.mp4
