### ISSUE TITLE
Cannot subscript an existing Union. Use Union[u, t] instead.

### ISSUE THREAD

**Issue by Poccket** [Rapptz/discord.py#1591]
I'm getting this error when importing discord.py, couldn't find anything after searching google for half an hour
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from discord.ext import commands
  File "/home/poccket/.local/lib/python3.5/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/home/poccket/.local/lib/python3.5/site-packages/discord/client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "/home/poccket/.local/lib/python3.5/site-packages/discord/voice_client.py", line 65, in <module>
    from .gateway import *
  File "/home/poccket/.local/lib/python3.5/site-packages/discord/gateway.py", line 31, in <module>
    import aiohttp
  File "/home/poccket/.local/lib/python3.5/site-packages/aiohttp/__init__.py", line 5, in <module>
    from . import hdrs  # noqa
  File "/home/poccket/.local/lib/python3.5/site-packages/aiohttp/hdrs.py", line 6, in <module>
    from multidict import istr
  File "/home/poccket/.local/lib/python3.5/site-packages/multidict/__init__.py", line 18, in <module>
    from ._abc import MultiMapping, MutableMultiMapping
  File "/home/poccket/.local/lib/python3.5/site-packages/multidict/_abc.py", line 37, in <module>
    class MutableMultiMapping(MultiMapping[_T], MutableMapping[str, _T]):
  File "/home/poccket/.local/lib/python3.5/site-packages/multidict/_abc.py", line 44, in MutableMultiMapping
    def extend(self, *args: _Arg[_T], **kwargs: _T) -> None:
  File "/usr/lib/python3.5/typing.py", line 546, in __getitem__
    "Cannot subscript an existing Union. Use Union[u, t] instead.")
TypeError: Cannot subscript an existing Union. Use Union[u, t] instead.
```

**Comment by ItWasAllIntended** [comment]
Though it is possible this is a library issue, a little more info is needed to help you fix it. A GitHub issue isn't the aptest place for a conversation so please join the [D.py](https://discord.gg/r3sSKJJ) server and we'll get you sorted.

**Comment by ItWasAllIntended** [comment]
For anyone with this issue, it is due to one of D.py's dependencies breaking support with anything lower than the Python version 3.5.2. The issue isn't with us so the only fix is using a Python version greater than 3.5.2 but lower than 3.7 as the async version does not support this.

**Comment by Harmon758** [comment]
> For anyone with this issue, it is due to one of D.py's dependencies breaking support with anything lower than the Python version 3.5.2.

To be clear, current versions of aiohttp, a requirement for discord.py, require Python >= 3.5.3.
The current locked version of aiohttp supports Python >= 3.4.2, but a recent update to multidict, a requirement for aiohttp that is not version locked, only supports Python >= 3.5.3.
See https://github.com/aio-libs/multidict/issues/286.

Your options are to either update to Python >= 3.5.3, downgrade to multidict >= 2.0, < 4.4.1 (e.g. 4.4.0), or wait to see if a future update to multidict maintains support for older Python versions < 3.5.3.

**Comment by Harmon758** [comment]
This should now be fixed with multidict 4.4.2.
