### ISSUE TITLE
ImportError: cannot import name 'Type'

### ISSUE THREAD

**Issue by Budgo** [Rapptz/discord.py#1597]
Log:
Traceback (most recent call last):
  File "C:/Users/Name/AppData/Local/Programs/Python/Python35-32/Discord.py", line 1, in <module>
    import discord.py
  File "C:\Users\Name\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\Name\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "C:\Users\Name\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\voice_client.py", line 65, in <module>
    from .gateway import *
  File "C:\Users\Name\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\gateway.py", line 31, in <module>
    import aiohttp
  File "C:\Users\Name\AppData\Local\Programs\Python\Python35-32\lib\site-packages\aiohttp\__init__.py", line 10, in <module>
    from .protocol import *  # noqa
  File "C:\Users\Name\AppData\Local\Programs\Python\Python35-32\lib\site-packages\aiohttp\protocol.py", line 18, in <module>
    from .helpers import reify
  File "C:\Users\Name\AppData\Local\Programs\Python\Python35-32\lib\site-packages\aiohttp\helpers.py", line 16, in <module>
    from async_timeout import timeout
  File "C:\Users\Name\AppData\Local\Programs\Python\Python35-32\lib\site-packages\async_timeout\__init__.py", line 5, in <module>
    from typing import Optional, Type
**ImportError: cannot import name 'Type'**

**Comment by Budgo** [comment]
How would you downgrade async_timeout?

**Comment by Harmon758** [comment]
You could just pip install a specific version of it after installing discord.py.

**Comment by Budgo** [comment]
Microsoft Windows [Version 10.0.17134.285]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Me>pip install asyncio 2.0.1
Collecting asyncio
  Downloading https://files.pythonhosted.org/packages/22/74/07679c5b9f98a7cb0fc147b1ef1cc1853bc07a4eb9cb5731e24732c5f773/asyncio-3.4.3-py3-none-any.whl (101kB)
    100% |################################| 102kB 25kB/s
Collecting 2.0.1
  Could not find a version that satisfies the requirement 2.0.1 (from versions: )
No matching distribution found for 2.0.1
You are using pip version 7.1.2, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\Me>

**Comment by Harmon758** [comment]
[async_timeout](https://github.com/aio-libs/async-timeout), not [asyncio](https://docs.python.org/3/library/asyncio.html)

**Comment by Budgo** [comment]
Microsoft Windows [Version 10.0.17134.285]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\Me>pip install async_timeout 2.0.1
Requirement already satisfied (use --upgrade to upgrade): async-timeout in c:\users\me\appdata\local\programs\python\python35-32\lib\site-packages
Collecting 2.0.1
  Could not find a version that satisfies the requirement 2.0.1 (from versions: )
No matching distribution found for 2.0.1
You are using pip version 7.1.2, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by Budgo** [comment]
Sorry to keep bothering you with my incompetence.

**Comment by Harmon758** [comment]
You're trying to install a library called "2.0.1" instead of async_timeout==2.0.1.

For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Budgo** [comment]
Thanks so much! It finally worked. Any way I can repay you?

**Comment by Harmon758** [comment]
No problem and no need. Happy to help.
