### ISSUE TITLE
Unable to run in another thread on Linux

### ISSUE THREAD

**Issue by thebluefish** [Rapptz/discord.py#1598]
I am attempting to write a discord.py bot from the `rewrite` branch in Python 3.7. Since it runs off a blocking asyncio loop, I wrapped it in a class that creates a new thread, runs the loop in this thread, and provides helpers for interacting with it from other threads.

```
class DiscordWrapper:
    event_loop = asyncio.new_event_loop()
    bot = commands.Bot('>', loop=event_loop)

    def __init__(self):
        # Events
        self.on_ready = self.bot.event(self.on_ready)
        self.on_error = self.bot.event(self.on_error)
        self.on_guild_join = self.bot.event(self.on_guild_join)

        # Commands
        self.cmd_purge = self.bot.command(self.cmd_purge)

        t = Thread(target=self.bot.run, args=(TOKEN,))
        t.start()
```
Which works great on Windows! However I have recently switched to an Ubuntu 18.04 environment, and the same thing within that produces:

```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/asyncio/unix_events.py", line 92, in add_signal_handler
    signal.set_wakeup_fd(self._csock.fileno())
ValueError: set_wakeup_fd only works in main thread

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/mazoku/discord_connector.py", line 51, in init
    self.bot.run(TOKEN)
  File "/root/.pyenv/versions/venv/lib/python3.7/site-packages/discord/client.py", line 552, in run
    loop.add_signal_handler(signal.SIGINT, self._do_cleanup)
  File "/root/.pyenv/versions/3.7-dev/lib/python3.7/asyncio/unix_events.py", line 94, in add_signal_handler
    raise RuntimeError(str(exc))
RuntimeError: set_wakeup_fd only works in main thread
```

It seems that signal handlers can only run on the main thread in Linux. However, I am unsure how I can run this loop without blocking the main thread. In my project, there are other operations that can only run on the main thread.

**Comment by thebluefish** [comment]
Oh! Thank you for pointing that out. It sounds like I'll be better off working with `start` instead of `run`. Thanks!
