### ISSUE TITLE
Issue with discord.ext.commands import Bot

### ISSUE THREAD

**Issue by Y4hL** [Rapptz/discord.py#1605]
With this code there are multiple issues:

```
from discord.ext.commands import Bot
import random
bot_prefix = "-"
TOKEN = "NDkyMzczODAxNTQwMTI0NzAy.Doeayw.VmIw5fE9Z7VakG7ggxcT_w5D0HY"

client = Bot(command_prefix=bot_prefix)

@client.command()
async def eight_ball():
    possible_responses = {
        'Meaby',
        'Yes',
        'NO',
    }
    await client.say(random.choice(possible_responses))

client.run(TOKEN)
```

The issues are as followed:

```
Ignoring exception in command eight_ball
Traceback (most recent call last):
  File "C:\Users\Rasmus\Python\venv\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:/Users/Rasmus/Python/botnoggi2.py", line 15, in eight_ball
    await client.say(random.choice(possible_responses))
  File "C:\Users\Rasmus\AppData\Local\Programs\Python\Python36\lib\random.py", line 261, in choice
    return seq[i]
TypeError: 'set' object does not support indexing

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Rasmus\Python\venv\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\Rasmus\Python\venv\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Rasmus\Python\venv\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'set' object does not support indexing
```

**Comment by Rapptz** [comment]
1. You are leaking your token, this is like a password so consider regenerating it.
2. `random.choice` takes a `list`, you passed it a `set`. This is not a problem with the library.
