### ISSUE TITLE
Question (Important)

### ISSUE THREAD

**Issue by archiebaer** [Rapptz/discord.py#1611]
D:\patrickthepigeon>py -3.6 live.py 483321494261465100
```
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Archie\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "live.py", line 52, in on_ready
    guild = self.get_guild(self.guild_id)
  File "C:\Users\Archie\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Archiver'>' object has no attribute 'get_guild'
```

I'm using some python discord bot.

**Comment by Harmon758** [comment]
From what I can tell, it seems like you're using the async branch to run code that uses the rewrite branch.
You'd have to share the relevant code for further help.
However, this isn't an issue with the library, and as such, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
