### ISSUE TITLE
'ctx' missing parameter when I clearly have one.

### ISSUE THREAD

**Issue by ImJustTatan** [Rapptz/discord.py#1618]
Recently I started my bot and hosted it on Heroku, and so far it hasn't given many problems, but this one is just annoying now. For some reason, cogs don't work (they used to work well). Whatever processes the commands seems to be searching for a `'ctx'` parameter (which I very clearly have in the code). This is the error I get in the log when I use any command in a cog:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Tatan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 483, in _parse_arguments
    next(iterator)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tatan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 225, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Tatan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 936, in on_message
    await self.process_commands(message)
  File "C:\Users\Tatan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 933, in process_commands
    await self.invoke(ctx)
  File "C:\Users\Tatan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 898, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Tatan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 607, in invoke
    await self.prepare(ctx)
  File "C:\Users\Tatan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 572, in prepare
    await self._parse_arguments(ctx)
  File "C:\Users\Tatan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 486, in _parse_arguments
    raise discord.ClientException(fmt.format(self))
discord.errors.ClientException: Callback for greet command is missing "ctx" parameter.
```
The entire source code for my bot can be found [here](https://github.com/ImJustTatan/new-natat), and the commands that don't work are only cogs. I tested with commands in the bot.py file and they work fine. The above error was returned from using `!greet` (cogs.useless):
```python3
@commands.command(description='A simple command for testing the bot.', aliases=['hello', 'salute', 'test'])
async def greet(ctx):
	"""Greets you. Mainly used for testing."""
	await ctx.send(random.choice(["boyyoass", "heyo", "what do you want"]))
```
But it returns the same for every command. I've looked at my code for hours and I honestly don't know what I'm doing wrong. Maybe it's a bug in discord.py itself? I need help fixing this, it's really getting on my nerves.

**Comment by Vexs** [comment]
As a cog is a class, and all the commands are functions within that class- the first argument must be `self`. 
See: [this cogs example](https://gist.github.com/EvieePy/d78c061a4798ae81be9825468fe146be) and the documentation on [classes](https://docs.python.org/3/tutorial/classes.html)

As a note, the issues section is more for actual issues with the lib, and not issues with your code. Please direct similar questions to our support server [https://discord.gg/r3sSKJJ](here).

**Comment by ImJustTatan** [comment]
Thanks, @Vexs! Makes sense, I completely forgot about that. The bot is now working perfectly.

Also, sorry for posting this here, I just tried a lot of things to fix my issue and I thought maybe it had to do with the lib itself, but I was clearly wrong.
