### ISSUE TITLE
When loading a cog that errors, it will sometimes get stuck in this state

### ISSUE THREAD

**Issue by Phxntxm** [Rapptz/discord.py#1658]
```
# Commands used
    async def load(self, ctx, *, module: str):
        """Loads a module"""

        # Do this because I'm too lazy to type cogs.module
        module = module.lower()
        if not module.startswith("cogs"):
            module = "cogs.{}".format(module)

        # This try catch will catch errors such as syntax errors in the module we are loading
        try:
            self.bot.load_extension(module)
            await ctx.send("I have just loaded the {} module".format(module))
        except Exception as error:
            fmt = 'An error occurred while processing this request: ```py\n{}: {}\n```'
            await ctx.send(fmt.format(type(error).__name__, error))

    async def reload(self, ctx, *, module: str):
        """Reloads a module"""

        # Do this because I'm too lazy to type cogs.module
        module = module.lower()
        if not module.startswith("cogs"):
            module = "cogs.{}".format(module)
        self.bot.unload_extension(module)

        # This try block will catch errors such as syntax errors in the module we are loading
        try:
            self.bot.load_extension(module)
            await ctx.send("I have just reloaded the {} module".format(module))
        except Exception as error:
            fmt = 'An error occurred while processing this request: ```py\n{}: {}\n```'
            await ctx.send(fmt.format(type(error).__name__, error))
```
Test cog
```
class Test:
        def __init__(self, bot):
                print(self._test)

def setup(bot):
        bot.add_cog(Test(bot))
```
Steps:
Create "test.py" in cogs folder with the test content above
Run command "load test" (Error: AttributeError: 'Test' object has no attribute '_test')
Remove test file
Run command "reload test" (Error: AttributeError: 'Test' object has no attribute '_test')

```
Traceback (most recent call last):
  File "/home/bonfire/cogs/owner.py", line 325, in reload
    self.bot.load_extension(module)
  File "/home/bonfire/Bonfire-env/src/discord.py/discord/ext/commands/bot.py", line 700, in load_extension
    lib.setup(self)
  File "/home/bonfire/cogs/test.py", line 6, in setup
    bot.add_cog(Test(bot))
  File "/home/bonfire/cogs/test.py", line 3, in init
    print(self._test)
AttributeError: 'Test' object has no attribute '_test'
```

This happens with any change that happens to the file, if you don't remove it and instead fix the error for example, it will still not load and report the original error....removing the file is just the best way to show that that this is happening. 

Unloading happens without an issue, when something is unloaded you can't retrieve it through `get_cog` yet somehow when trying to load after, it continues to read it as if the file is the same as when it errored.

**Comment by Phxntxm** [comment]
A pull request that addresses this: https://github.com/Rapptz/discord.py/pull/1659

**Comment by tilda** [comment]
I can confirm this, I've had this happen multiple times in the past

**Comment by Rapptz** [comment]
Should be fixed in https://github.com/Rapptz/discord.py/commit/caf3d17d4aa3ce45435bb96ea6d99317bfef8618

**Comment by Snek123** [comment]
H
