### ISSUE TITLE
Opus not loaded

### ISSUE THREAD

**Issue by KironDevCoder** [Rapptz/discord.py#1660]
I have an discord bot which works fine on my computer but when I try to run it on Heroku since my computer sometimes has internet problems I get an error discord.opus.OpusNotLoaded.
My source code is on `https://github.com/KironDevCoder/ASMR-discord-bot` and the complete error is:
`2018-10-11T17:31:23.822484+00:00 app[worker.1]: Ignoring exception in on_ready
2018-10-11T17:31:23.823999+00:00 app[worker.1]: Traceback (most recent call last):
2018-10-11T17:31:23.824060+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
2018-10-11T17:31:23.824061+00:00 app[worker.1]:     yield from getattr(self, event)(*args, **kwargs)
2018-10-11T17:31:23.824099+00:00 app[worker.1]:   File "bot.py", line 27, in on_ready
2018-10-11T17:31:23.824101+00:00 app[worker.1]:     vc = await bot.join_voice_channel(get_asmr_channel())
2018-10-11T17:31:23.824103+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 3209, in join_voice_channel
2018-10-11T17:31:23.824104+00:00 app[worker.1]:     voice = VoiceClient(**kwargs)
2018-10-11T17:31:23.824109+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/voice_client.py", line 230, in __init__
2018-10-11T17:31:23.824110+00:00 app[worker.1]:     self.encoder = opus.Encoder(48000, 2)
2018-10-11T17:31:23.824142+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/opus.py", line 197, in __init__
2018-10-11T17:31:23.824143+00:00 app[worker.1]:     raise OpusNotLoaded()
2018-10-11T17:31:23.824197+00:00 app[worker.1]: discord.opus.OpusNotLoaded` I tried loading:

- libopus-0.x86.dll

- libopus-0.x64.dll

- libopus-0.dll

- libopus.so.0

- libopus.0.dylib

But none of them worked :/

**Comment by CapnS** [comment]
This is just a problem with Heroku itself. I would recommend using a different hosting service instead of Heroku. Heroku is not meant for bots, and as such discord bots will not run well on it.
