### ISSUE TITLE
Having trouble with permission check

### ISSUE THREAD

**Issue by Steffbeard** [Rapptz/discord.py#1666]
Getting this error whenever I try to test my `checks` in the `utils` folder using a debug command (.pd).

```
Ignoring exception in command pd:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/core.py", line 482, in invoke
    yield from self.prepare(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/core.py", line 438, in prepare
    yield from self._verify_checks(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/core.py", line 389, in _verify_checks
    raise CheckFailure('The check functions for command {0.qualified_name} failed.'.format(self))
discord.ext.commands.errors.CheckFailure: The check functions for command pd failed.
```

Here is my command to test the permission check:

```py
@bot.command()
@checks.is_owner()
async def pd(ctx):
    """Check to see if perms is working"""
    if not checks.is_owner_check(ctx):
        return await ctx.send('This aint it chief!')
    await ctx.send('This is it chief!')
```

and here is the code from the utils folder,

```py
def is_owner_check(ctx):
    return ctx.author.id == 499019897754484737 or ctx.author.id == 489211942603456512
def is_owner():
    return commands.check(is_owner_check)
def is_admin_check(ctx):
    role = discord.utils.get(ctx.bot.get_guild(489211942603456512).roles, name='Staff')
    user = discord.utils.get(ctx.bot.get_guild(489211942603456512).members, id=ctx.author.id)
    return role in user.roles or is_owner_check(ctx)
def is_admin():
    return commands.check(is_admin_check)
```

**Comment by Rapptz** [comment]
1. To do code blocks in the future, please use \`\`\`py syntax (and terminate it with \`\`\`).
2. The `checks.is_owner()` code already does the check so it makes no sense to do `checks.is_owner_check` inside the body since the checks are called before the callback is called.
3. Are you sure the IDs are correct? There is nothing wrong in this code.
4. For more information on checks, you should check the [documentation](https://discordpy.readthedocs.io/en/rewrite/ext/commands/commands.html#checks).
5. Likewise, for error handling, there are [docs](https://discordpy.readthedocs.io/en/rewrite/ext/commands/commands.html#error-handling) on this too.

For more help, consider joining the [official server](https://discord.gg/r3sSKJJ).
