### ISSUE TITLE
Youtube said: That video does not exist.

### ISSUE THREAD

**Issue by jzburda** [Rapptz/discord.py#170]
My Bot's been working fine with music playing, until recently when it decided to start saying this when I try to request something from Youtube:

> [youtube] px613u_dwze: Downloading webpage
[youtube] px613u_dwze: Downloading video info webpage
ERROR: px613u_dwze: YouTube said: This video does not exist.
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\jzbur\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 671, in extract_info
    ie_result = ie.extract(url)
  File "C:\Users\jzbur\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\common.py", line 341, in extract
    return self._real_extract(url)
  File "C:\Users\jzbur\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\extractor\youtube.py", line 1305, in _real_extract
    expected=True, video_id=video_id)
youtube_dl.utils.ExtractorError: px613u_dwze: YouTube said: This video does not exist.

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "C:\Users\jzbur\AppData\Local\Programs\Python\Python35\lib\site-packages\discord.py-0.10.0a0-py3.5.egg\discord\client.py", line 283, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\jzbur\AppData\Local\Programs\Python\Python35\LuneBotSerav2.py", line 60, in on_message
    player = await voice.create_ytdl_player( Args[1] )
  File "C:\Users\jzbur\AppData\Local\Programs\Python\Python35\lib\site-packages\discord.py-0.10.0a0-py3.5.egg\discord\voice_client.py", line 516, in create_ytdl_player
    info = yield from self.loop.run_in_executor(None, func)
  File "C:\Users\jzbur\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\jzbur\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Users\jzbur\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\jzbur\AppData\Local\Programs\Python\Python35\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\jzbur\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 686, in extract_info
    self.report_error(compat_str(e), e.format_traceback())
  File "C:\Users\jzbur\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 545, in report_error
    self.trouble(error_message, tb)
  File "C:\Users\jzbur\AppData\Local\Programs\Python\Python35\lib\site-packages\youtube_dl\YoutubeDL.py", line 515, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: px613u_dwze: YouTube said: This video does not exist.

How do I fix this?

**Comment by Rapptz** [comment]
This isn't my issue. This is ytdl's issue. Ask them.
