### ISSUE TITLE
SSL Certificate verify Failed - Linux-based OS

### ISSUE THREAD

**Issue by Zinal001** [Rapptz/discord.py#1704]
## Long story short

I'm trying to make the bot work on a **Synology DiskStation DS412+** NAS (Linux-based OS) using SSH, but I'm getting an SSL Certificate verify Failed error. Is there a way to disable SSL on the Discord bot? _(Not optional, but if it works...)_

I found that a couple of other people also had the same problem, but the general fix `Install Certificates.command` isn't going to work on Linux.

## Expected behaviour

The bot runs as it should.

## Actual behaviour

I get the following error:

```
Traceback (most recent call last):
  File "/opt/lib/python3.6/site-packages/aiohttp/connector.py", line 601, in _create_direct_connection
    local_addr=self._local_addr)
  File "/base_events.py", line 803, in create_connection
  File "/base_events.py", line 829, in _create_connection_transport
  File "/sslproto.py", line 503, in data_received
  File "/sslproto.py", line 201, in feed_ssldata
  File "/ssl.py", line 683, in do_handshake
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c:748)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/lib/python3.6/site-packages/aiohttp/connector.py", line 304, in connect
    yield from self._create_connection(req)
  File "/opt/lib/python3.6/site-packages/aiohttp/connector.py", line 578, in _create_connection
    transport, proto = yield from self._create_direct_connection(req)
  File "/opt/lib/python3.6/site-packages/aiohttp/connector.py", line 624, in _create_direct_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Can not connect to discordapp.com:443 [[SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c:748)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "RconTest.py", line 29, in <module>
    client.run('<<REDACTED>>')
  File "/opt/lib/python3.6/site-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/base_events.py", line 467, in run_until_complete
  File "/opt/lib/python3.6/site-packages/discord/client.py", line 490, in start
    yield from self.login(*args, **kwargs)
  File "/opt/lib/python3.6/site-packages/discord/client.py", line 416, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/opt/lib/python3.6/site-packages/discord/client.py", line 346, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "/opt/lib/python3.6/site-packages/discord/http.py", line 258, in static_login
    data = yield from self.request(Route('GET', '/users/@me'))
  File "/opt/lib/python3.6/site-packages/discord/http.py", line 137, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/opt/lib/python3.6/site-packages/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/opt/lib/python3.6/site-packages/aiohttp/client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "/opt/lib/python3.6/site-packages/aiohttp/connector.py", line 314, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [[SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c:748)]]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x8d661fc>
```

## Steps to reproduce

1. Install python3 and pip.
2. Download discord.py.
3. Try running the example [here](https://github.com/Rapptz/discord.py#quick-example).

## Your environment

**OS**: Linux DiskStation 3.10.105 #23824 SMP Fri Oct 12 18:30:00 CST 2018 x86_64 GNU/Linux synology_cedarview_412+

**Comment by gogurtenjoyer** [comment]
This is not an issue with discord.py, and should be solved by installing SSL root certificates in the appropriate method for your operating system.

**Comment by Vexs** [comment]
To further; not only should you super not disable SSL, but Discord won't talk to you without it.

**Comment by bmintz** [comment]
Discord may talk to you if you accept all invalid certificates, but this is also something you should not do, especially on coffee shop wifi.
