### ISSUE TITLE
No module named 'idna_ssl'

### ISSUE THREAD

**Issue by owengaming001** [Rapptz/discord.py#1723]
<h1>I Am Trying To Get A Discord Bot Setup On My Raspberry Pi 3 Using Python 3.5.3</h1>
<p>I Installed Everything But The Dependencies Aren't Working,<br>I Got Websockets And AIOHTTP Working,<br>But No Matter What I Try It Always Says</p>

> Traceback (most recent call last):
  File "/home/pi/Desktop/Python/Bots/DiscordBot.py", line 1, in <module>
    import discord
  File "/usr/lib/python3.5/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/usr/lib/python3.5/discord/client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "/usr/lib/python3.5/discord/voice_client.py", line 65, in <module>
    from .gateway import *
  File "/usr/lib/python3.5/discord/gateway.py", line 31, in <module>
    import aiohttp
  File "/usr/lib/python3.5/aiohttp/__init__.py", line 6, in <module>
    from .client import *  # noqa
  File "/usr/lib/python3.5/aiohttp/client.py", line 19, in <module>
    from . import client_exceptions, client_reqrep
  File "/usr/lib/python3.5/aiohttp/client_reqrep.py", line 18, in <module>
    from . import hdrs, helpers, http, multipart, payload
  File "/usr/lib/python3.5/aiohttp/helpers.py", line 44, in <module>
    import idna_ssl
ImportError: No module named 'idna_ssl'

<h2>My Code Is:</h2>

<p>import discord<br>
client = discord.Client()<br>
@client.event<br>
async def on_message(message):<br>
    # we do not want the bot to reply to itself<br>
    if message.author == client.user:<br>
        return<br>
    print(message.content)<br>
    if message.content.startswith('!hello'):<br>
        msg = 'Hello {0.author.mention}'.format(message)<br>
        await client.send_message(message.channel, msg)<br>
@client.event<br>
async def on_ready():<br>
    print('Logged in as')<br>
    print(client.user.name)<br>
    print(client.user.id)<br>
    print('------')<br>
client.run('TOKEN')</p>
<h3>And Yes, I Remembered To Enter My Token, <br>I Replaced It So Nobody Can Use My Bot,
<br>I Am Trying To Get This Code Working Before I Modify It</h3>

**Comment by Phxntxm** [comment]
Try updating pip, then reinstalling aiohttp, it request idna_ssl but you do not have it installed...pip should automatically install this when installing discord.py, as it requires aiohttp, which then requires idna_ssl.

**Comment by owengaming001** [comment]
<h3>When I Try Installing Discord With The New Version It Says:</h3>

> pi@raspberrypi:~ $ pip install discord.py
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

That Is Not A Good Sign

**Comment by Harmon758** [comment]
idna_ssl was added as a requirement for aiohttp on Python < 3.7 in v2.3.10.
You're using the async branch, which has the aiohttp requirement version locked to >=1.0.0,<1.1.0.
I'd recommend downgrading to aiohttp v1.0.5. If you want to use a more up to date version of aiohttp, you should try the rewrite branch. Otherwise, you'd have to install the idna_ssl requirement.
As for your error with pip, see https://github.com/pypa/pip/issues/5599.

**Comment by owengaming001** [comment]
Can Someone Just Tell Me Where I Can Obtain The Source Code For Inda_ssl So I Can Inject It Into My Python Folder

**Comment by Harmon758** [comment]
https://github.com/aio-libs/idna-ssl
However, I'd highly recommend you install it properly through aiohttp, as this is probably how you've reached the situation of having a missing dependency in the first place.

**Comment by owengaming001** [comment]
But I Installed Discord Through The Command, So It Should Have Installed All The Dependencies, But It Didn't

**Comment by owengaming001** [comment]
Is There A Way To Install All Dependencies

**Comment by Harmon758** [comment]
Like I said, you're using the async branch of this library, which requires aiohttp >=1.0.0,<1.1.0, but you have >2.3.10 installed. A proper installation should have included aiohttp v1.0.5. I'd recommend you fix your pip installation before proceeding.

**Comment by owengaming001** [comment]
Ill Fix Pip Later, But For Now I Installed inda-ssl Manually And Then It Said No Module Named Keyboard Extensions So I Installed That The Same Way And Now It Works, Thanks For Helping Me
