### ISSUE TITLE
Can't run red bot

### ISSUE THREAD

**Issue by ItsRealSnow** [Rapptz/discord.py#1724]
> Traceback (most recent call last):
  File "red.py", line 12, in <module>
    from discord.ext import commands
  File "/usr/local/lib/python3.7/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/usr/local/lib/python3.7/site-packages/discord/client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "/usr/local/lib/python3.7/site-packages/discord/voice_client.py", line 43, in <module>
    import websockets
  File "/usr/local/lib/python3.7/site-packages/websockets/__init__.py", line 3, in <module>
    from .client import *
  File "/usr/local/lib/python3.7/site-packages/websockets/client.py", line 12, in <module>
    from .protocol import CONNECTING, OPEN, WebSocketCommonProtocol
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 17, in <module>
    from .compatibility import asyncio_ensure_future
  File "/usr/local/lib/python3.7/site-packages/websockets/compatibility.py", line 9
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                        ^
SyntaxError: invalid syntax
Red has been terminated. Exit code: 1
Press enter to continue.

i get this whenever i try to run the bot

**Comment by BeatButton** [comment]
For troubleshooting, please join the discord server. The issue tracker is for library bugs.
 https://discord.gg/r3sSKJJ
The problem is that the async branch doesn't support Python 3.7. You'll have to downgrade to 3.6.

**Comment by Phxntxm** [comment]
Also....this git repo isn't for redbot, typically redbot issues go to https://github.com/Cog-Creators/Red-DiscordBot
If you would read the instructions that are provided with Red....it says do not use anything above 3.5
https://twentysix26.github.io/Red-Docs/red_install_windows/

**Comment by ItsRealSnow** [comment]
OOOOPS WRONG PLACE SORRY
