### ISSUE TITLE
Problem while Installing

### ISSUE THREAD

**Issue by da39a3ee5e6b** [Rapptz/discord.py#1727]
I've not clue how I can fix this, someone can help me ?

` Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/http.py", line 258, in st              atic_login
    data = yield from self.request(Route('GET', '/users/@me'))
  File "/usr/local/lib/python3.6/site-packages/discord/http.py", line 200, in re              quest
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "del.py", line 28, in <module>
    c.run(token, bot=False)
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 518, in               run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 467, in run_until              _complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 489, in               start
    yield from self.login(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 416, in               login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 346, in               _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "/usr/local/lib/python3.6/site-packages/discord/http.py", line 262, in st              atic_login
    raise LoginFailure('Improper token has been passed.') from e
discord.errors.LoginFailure: Improper token has been passed.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f6a7b615eb8>
root@name:/home/discord-scripts/del# discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized
-bash: syntax error near unexpected token `('
[1]+  Exit 1                  python3 del.py
`

**Comment by XuaTheGrate** [comment]
You are using the wrong token to launch your bot. Double check your token is in the correct format and you aren't using the Client Secret.

**Comment by da39a3ee5e6b** [comment]
I'm using it as standard client not as developper, like it's my client ID and what's the Client Secret ?

**Comment by XuaTheGrate** [comment]
Does your token look mostly similar to this? 
```
MjM4NDk0Nz.LARGEpEe.c3Nzky.CunGFQ.wUILz7z6HoJzVeq6pyHPmVgQgV4
```
If not, you are using the wrong token.
If it is, you most likely regenerated your token or aren't passing it correctly.

**Comment by da39a3ee5e6b** [comment]
nop, isn't.

But like why should I create a bot application ? so that mean I've to go through a bot instead typing .del on my own acc? and How I can generate this token ?

**Comment by Vexs** [comment]
If you want to use a user account, you must pass `bot=False` in `client.run`. However, its worth mentioning that this is [against the tos and can get you banned.](https://support.discordapp.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-).

Further, the last line in your traceback is... odd, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends for further support. 
GitHub issues for this repository should be used to report issues with this library.

**Comment by da39a3ee5e6b** [comment]
I actually didn't know this. Thanks for claryifing this.
