### ISSUE TITLE
discord.ext.commands.errors.MissingRequiredArgument: message is a required argument that is missing.

### ISSUE THREAD

**Issue by HypersDevelopment** [Rapptz/discord.py#1731]
Every one of my commands in my bot keeps raising this error. Here's the ping command code and the error...

```python
@client.command()
async def ping(ctx):
    start = time.perf_counter()
    msg = await ctx.send("Timing...")
    end = time.perf_counter()
    duration = (end - start) * 1000
    embed = Embed(
        title=f"{client.user.name}'s Ping",
        description=f"Ping, pong, ping, pong...",
        color=0xeee657)
    embed.add_field(
        name="Web-socket Ping",
        value=f"{round((client.latency*1000),2)}ms")
    embed.add_field(
        name="Message Ping",
        value=f"{round(duration, 2)}ms")
    await msg.edit(content=None, embed=embed)
```
```
Ignoring exception in command ping
Traceback (most recent call last):
  File "/home/sha-pc/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 848, in process_commands
    yield from command.invoke(ctx)
  File "/home/sha-pc/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 362, in invoke
    yield from self.prepare(ctx)
  File "/home/sha-pc/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 340, in prepare
    yield from self._parse_arguments(ctx)
  File "/home/sha-pc/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 299, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "/home/sha-pc/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 207, in transform
    raise MissingRequiredArgument('{0.name} is a required argument that is missing.'.format(param))
discord.ext.commands.errors.MissingRequiredArgument: ctx is a required argument that is missing.
```
What confuzes me is why this works on my windows 7 PC, but not this linux debian...

**Comment by HypersDevelopment** [comment]
Wait what? I used the rewrite branch instalation... I'll use `pip uninstall discord` and retry...

**Comment by HypersDevelopment** [comment]
Now it's breaking...
```
sha-pc@debian:~$ python3.6 -m pip install -U git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
Collecting discord.py[voice] from git+https://github.com/Rapptz/discord.py@rewrite#egg=discord.py[voice]
  Cloning https://github.com/Rapptz/discord.py (to rewrite) to /tmp/pip-build-m5lq60sa/discord.py
  Error [Errno 2] No such file or directory: 'git': 'git' while executing command git clone -q https://github.com/Rapptz/discord.py /tmp/pip-build-m5lq60sa/discord.py
Cannot find command 'git'
```

**Comment by RainbowLegend** [comment]
You need to install Git and/or add it to PATH.

**Comment by HypersDevelopment** [comment]
I'm on debian linux. I don't think there's a PATH on debian linux.

**Comment by Hornwitser** [comment]
A cursory look into the [shell manual](https://www.gnu.org/software/bash/manual/bash.html#Bourne-Shell-Variables) or the numerous ways variables can shown, for examble by executing `echo $PATH` or just `export` in a shell will tell you otherwise.

If you don't already have git installed, `sudo apt-get install git` will probably install it.

**Comment by Dr-Insanity** [comment]
> I'm on debian linux. I don't think there's a PATH on debian linux.

your "home" folder is your path.
