### ISSUE TITLE
NameError: name 'voice' is not defined

### ISSUE THREAD

**Issue by Oklomsy** [Rapptz/discord.py#1788]
2018-12-18T16:57:44.807402+00:00 app[worker.1]: NameError: name 'player' is not defined
2018-12-18T16:57:44.807461+00:00 app[worker.1]: 
2018-12-18T16:57:44.807464+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2018-12-18T16:57:44.807466+00:00 app[worker.1]: 
2018-12-18T16:57:44.807569+00:00 app[worker.1]: Traceback (most recent call last):
2018-12-18T16:57:44.807636+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
2018-12-18T16:57:44.807638+00:00 app[worker.1]:     yield from getattr(self, event)(*args, **kwargs)
2018-12-18T16:57:44.807674+00:00 app[worker.1]:   File "baldibot.py", line 122, in on_message
2018-12-18T16:57:44.807676+00:00 app[worker.1]:     player = await voice.create_ytdl_player(str1)
2018-12-18T16:57:44.807723+00:00 app[worker.1]: NameError: name 'voice' is not defined

can someone help me?

**Comment by Phxntxm** [comment]
Typically, git issues are for issues with the codebase of discord.py, not learning how to use the library or python itself. I would recommend joining [the discord server](https://discord.gg/r3sSKJJ) for questions such as these. 

In regards to the question itself, the error is quite clear....`voice` is not defined in your code. Without seeing what your code is, it's hard to really give more information than that. So to repeat I'd again recommend joining the discord server and asking there.
