### ISSUE TITLE
Bot randomly exits with OSError

### ISSUE THREAD

**Issue by KunalsDatabase** [Rapptz/discord.py#1819]
The bot randomly closes multiple times a day with the following error: 

```
Traceback (most recent call last):
  File "test.py", line 561, in <module>
    bot.run(TOKEN)
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 567, in run
    self._do_cleanup()
  File "C:\Users\user\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 510, in _do_cleanup
    loop.run_forever()
  File "C:\python\lib\asyncio\base_events.py", line 422, in run_forever
    self._run_once()
  File "C:\python\lib\asyncio\base_events.py", line 1398, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\python\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\python\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket

```

**Comment by Harmon758** [comment]
I've encountered this once when issues with Discord's voice servers put a bot into a bad state as it tried to join a voice channel and play audio.
Attempting to disconnect from the voice channel caused this error to occur, seemingly due to:
https://github.com/Rapptz/discord.py/blob/7f4c57dd5ad20b7fa10aea485f674a4bc24b9547/discord/voice_client.py#L268 and the bot froze up.
However, I was unable to reproduce this during normal operation.

Can you share any relevant voice code (specifically where you disconnect from the voice channel) to reproduce this?
