### ISSUE TITLE
Rewrite: Error on commands.Bot.start()

### ISSUE THREAD

**Issue by MrSpinne** [Rapptz/discord.py#1834]
Every time I start my bot, this error is thrown. Please help.:

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 994, in emit
    stream.write(msg)
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f389' in position 3362: character maps to <undefined>
Call stack:
  File "D:/---/Workspace/Clicky/clicky.py", line 369, in <module>
    loop.run_until_complete(setup())
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 1426, in _run_once
    handle._run()
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "D:/---/Workspace/Clicky/clicky.py", line 363, in setup
    await clicky.start("---")
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 480, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 402, in connect
    await self._connect()
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 367, in _connect
    await self.ws.poll_event()
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\gateway.py", line 449, in poll_event
    await self.received_message(msg)
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\gateway.py", line 332, in received_message
    log.debug('For Shard ID %s: WebSocket Event: %s', self.shard_id, msg)
Message: 'For Shard ID %s: WebSocket Event: %s'
Arguments: (None, {'t': 'GUILD_CREATE', ---})
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\logging\__init__.py", line 994, in emit
    stream.write(msg)
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f451' in position 436: character maps to <undefined>
Call stack:
  File "D:/---/Workspace/Clicky/clicky.py", line 369, in <module>
    loop.run_until_complete(setup())
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 421, in run_forever
    self._run_once()
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\asyncio\base_events.py", line 1426, in _run_once
    handle._run()
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\asyncio\events.py", line 127, in _run
    self._callback(*self._args)
  File "D:/---/Workspace/Clicky/clicky.py", line 363, in setup
    await clicky.start("NTMzMjQ4NjI0Nzk3MTU1MzI5.Dxtu9Q.Q_vZ9C5ip2E_76sZ_z3AW_0csvY")
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 480, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 402, in connect
    await self._connect()
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 367, in _connect
    await self.ws.poll_event()
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\gateway.py", line 449, in poll_event
    await self.received_message(msg)
  File "C:\Users\---\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\gateway.py", line 332, in received_message
    log.debug('For Shard ID %s: WebSocket Event: %s', self.shard_id, msg)
Message: 'For Shard ID %s: WebSocket Event: %s'
Arguments: (None, {'t': 'GUILD_CREATE', ---}

**Comment by Harmon758** [comment]
First of all, you've leaked your token, so you're going to want to reset it now.
As the errors says, this is a failure to encode a character during logging.
This should be easily resolved by using UTF-8 instead of CP-1252.

For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README recommends.
For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by MrSpinne** [comment]
Ok thanks, that worked.
