### ISSUE TITLE
Import Failure on Python 3.7.2 32-bit Windows

### ISSUE THREAD

**Issue by sinistervengeance** [Rapptz/discord.py#1892]
I understand that this issue is not the first one to be reported but I would like to add emphasis to it regardless. When attempting to import the discord module I receive this error; 
"Traceback (most recent call last):
  File "c:/Users/*/PythonScript/Main.py", line 10, in <module>
    import discord
  File "C:\Users\*\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\*\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\*\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\*\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax"

This sadly makes my python program currently unusable until this is fixed or I find a suitable working replacement.

**Comment by Harmon758** [comment]
Duplicate of #1249 and #1401
