### ISSUE TITLE
wait=True has a new error

### ISSUE THREAD

**Issue by XuaTheGrate** [Rapptz/discord.py#1898]
Similar to #1242, I get this error when constructing a new webhook like so: (via jishaku)
```python
wh = discord.Webhook.from_url(url, adapter=discord.AsyncWebhookAdapter(_bot.session))
await wh.send("test", wait=True)
```
Which now raises the following:
```python
Traceback (most recent call last):
  File "/home/xua/adventure/venv/lib/python3.6/site-packages/jishaku/cog.py", line 314, in jsk_python
    async for result in AsyncCodeExecutor(argument.content, scope, arg_dict=arg_dict):
  File "/home/xua/adventure/venv/lib/python3.6/site-packages/jishaku/repl/compilation.py", line 160, in traverse
    yield await func(*async_executor.args)
  File "<repl>", line 2, in _repl_coroutine
  File "/home/xua/adventure/venv/lib/python3.6/site-packages/discord/webhook.py", line 200, in handle_execution_response
    return Message(data=data, state=self.webhook._state, channel=self.webhook.channel)
  File "/home/xua/adventure/venv/lib/python3.6/site-packages/discord/message.py", line 216, in __init__
    self._update(channel, data)
  File "/home/xua/adventure/venv/lib/python3.6/site-packages/discord/message.py", line 281, in _update
    getattr(self, '_handle_%s' % handler)(data[handler])
  File "/home/xua/adventure/venv/lib/python3.6/site-packages/discord/message.py", line 294, in _handle_author
    self.author = self._state.store_user(author)
AttributeError: 'NoneType' object has no attribute 'store_user'
```
I know I am on the latest version (according to pkg_resources, `discord.py 1.0.0a1659+g700dbb5`)
This doesn't seem to error when fetching the webhook via `channel.webhooks`
According to @crrapi, this commit broke it, and reverting it had fixed the problem 33dc3411acb56ddaf86cb16242016ba4918c0d23

**Comment by CapnS** [comment]
This happens with from_url() because when using that method, state isn't passed to the Webhook, so it defaults to None. 
```
m = re.search(r'discordapp.com/api/webhooks/(?P<id>[0-9]{17,21})/(?P<token>[A-Za-z0-9\.\-\_]{60,68})', url)
if m is None:
    raise InvalidArgument('Invalid webhook URL given.')
return cls(m.groupdict(), adapter=adapter)```
