### ISSUE TITLE
Passing a list of roles to client.remove_roles() throws an error

### ISSUE THREAD

**Issue by AdautoP** [Rapptz/discord.py#1909]
Ignoring exception in command level
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/Users/adautopinheiro/Desktop/discord-cuck-bot/main.py", line 65, in level
    await client.remove_roles(ctx.message.author, rolesToRemove)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/client.py", line 2946, in remove_roles
    new_roles.remove(role.id)
AttributeError: 'list' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'list' object has no attribute 'id'

**Comment by calebj** [comment]
As stated in the [documentation](https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.remove_roles), `Client.remove_roles` takes an *argument* list, which means you pass each role as a separate argument. Fortunately, Python lets you [unpack](https://docs.python.org/3/tutorial/controlflow.html#unpacking-argument-lists) the list into arguments with the `*`-operator like so:
```py
await client.remove_roles(ctx.message.author, *rolesToRemove)
```

**Comment by AdautoP** [comment]
Hmm, my bad. i thought the documentation said it was a list. but ty!
