### ISSUE TITLE
Errors out on basic bot script. 

### ISSUE THREAD

**Issue by SquirrelKiev** [Rapptz/discord.py#1928]
No idea whats wrong. :/
```
import discord
from discord.ext import commands

TOKEN = 'Token goes here github. '

client = commands.Bot(command_prefix = '£')

@client.event
async def on_ready():
    print('Bot is ready. ')

client.run(TOKEN)
```
Error:
```
Traceback (most recent call last):
  File "pathtopythonfile\example_bot.py", line 1, in <module>
    import discord
  File "C:\Users\laidb\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "C:\Users\laidb\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\client.py", line 38, in <module>
    from .state import ConnectionState
  File "C:\Users\laidb\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\state.py", line 36, in <module>
    from . import utils, compat
  File "C:\Users\laidb\AppData\Local\Programs\Python\Python37\lib\site-packages\discord\compat.py", line 32
    create_task = asyncio.async
                              ^
SyntaxError: invalid syntax
```

**Comment by Gorialis** [comment]
You have leaked your token. You'll need to reset it on your developer page.

The exception here is because the async branch is not compatible with Python 3.7. You need to either install Python 3.4-3.6 or change to using the rewrite branch (supporting Python 3.5+), which you can learn how to do from the [discord.py support server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api).

**Comment by laggycomputer** [comment]
Before continuing, kindly change your bot token immediately at discordapp.com/developers. You just gave it out (and therefore bot access) to anyone with internet access.

**Comment by SquirrelKiev** [comment]
ah. thanks dude.

**Comment by SquirrelKiev** [comment]
its been reset.

**Comment by Harmon758** [comment]
Duplicate of #1249 and #1401
