### ISSUE TITLE
VoiceClient reconnect lasting when connected voice channel deleted

### ISSUE THREAD

**Issue by cod-sushi** [Rapptz/discord.py#1954]
When voice channel deleted, voice client keep tring to reconnect.
`disconnect(force=True)` did not work.

It occurs when these conditions are met.
- User removed voice channel that the bot connected in web browser UI.
- When voice channel deleted, connected user is the bot only.
If Other user was in the channel, `disconnect(force=True)` worked.

```
03/05 07:57:58 [WARNING ] discord.voice_client( 252) : Could not connect to voice... Retrying...
03/05 07:57:58 [ERROR   ] discord.voice_client( 244) : Disconnected from voice... Reconnecting in 0.79s.
Traceback (most recent call last):
  File "/path/to/project/venv/lib/python3.6/site-packages/discord/gateway.py", line 730, in poll_event
    msg = await asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/path/to/project/venv/lib/python3.6/site-packages/websockets/protocol.py", line 350, in recv
    yield from self.ensure_open()
  File "/path/to/project/venv/lib/python3.6/site-packages/websockets/protocol.py", line 501, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4014 (private use), reason = Disconnected.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/project/venv/lib/python3.6/site-packages/discord/voice_client.py", line 232, in poll_voice_ws
    await self.ws.poll_event()
  File "/path/to/project/venv/lib/python3.6/site-packages/discord/gateway.py", line 733, in poll_event
    raise ConnectionClosed(exc, shard_id=None) from exc
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4014 (private use), reason = Disconnected.
03/05 07:58:03 [WARNING ] discord.voice_client( 252) : Could not connect to voice... Retrying...
03/05 07:58:03 [ERROR   ] discord.voice_client( 244) : Disconnected from voice... Reconnecting in 222.28s.
Traceback (most recent call last):
  File "/path/to/project/venv/lib/python3.6/site-packages/discord/gateway.py", line 730, in poll_event
    msg = await asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/path/to/project/venv/lib/python3.6/site-packages/websockets/protocol.py", line 350, in recv
    yield from self.ensure_open()
  File "/path/to/project/venv/lib/python3.6/site-packages/websockets/protocol.py", line 501, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4014 (private use), reason = Disconnected.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/path/to/project/venv/lib/python3.6/site-packages/discord/voice_client.py", line 232, in poll_voice_ws
    await self.ws.poll_event()
  File "/path/to/project/venv/lib/python3.6/site-packages/discord/gateway.py", line 733, in poll_event
    raise ConnectionClosed(exc, shard_id=None) from exc
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4014 (private use), reason = Disconnected.
```

**Comment by Rapptz** [comment]
Could you try the following commit? https://github.com/Rapptz/discord.py/commit/78459f3ed02b309922683e7181cdad070eb215c9

I'm not sure if it fixes the reconnect loop but it's worth a shot.

**Comment by cod-sushi** [comment]
Commit 78459f3 worked. Reconnect loop has been cleared up.

Following exception appears randomly whether other user is in the channel or isn't. 
```
03/06 19:09:32 [ERROR   ] asyncio        (1260) : Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f93b01673c8>
transport: <_SelectorSocketTransport closing fd=13 read=idle write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/sslproto.py", line 638, in _process_write_backlog
    ssldata, offset = self._sslpipe.feed_appdata(data, offset)
AttributeError: 'NoneType' object has no attribute 'feed_appdata'
```

**Comment by Rapptz** [comment]
That seems to be an asyncio bug, which is unrelated to this. A search shows that it's fixed in 3.6.5 or higher and it's safe to be ignored otherwise.

At least this issue seems fixed though. :+1:

**Comment by cod-sushi** [comment]
Thanks. I'll update my python.
Thank you for the quick response!

**Comment by Harmon758** [comment]
For posterity, the relevant asyncio bug: https://bugs.python.org/issue33037
