### ISSUE TITLE
Attachment.save() throws HTTPException when used on non-image attachment file with default parameters.

### ISSUE THREAD

**Issue by xSke** [Rapptz/discord.py#1973]
### Summary

[This commit](https://github.com/Rapptz/discord.py/commit/aceec2009a7c819d2236884fa9ccc5ce58a92bea) changes the default behaviour of `Attachment.save()` to use the given proxy URL from the message object to fetch the attachment file. This URL is invalid for non-image attachments, and will result in a 415 being returned from the proxy server.

The proper default behaviour would either be to use the non-proxy URL to fetch the file if the file isn't an image, or to try the proxy URL first and fall back to the non-proxy URL in case of a 415 being returned.

A workaround for this is of course to set `use_cached=False`, but it feels wrong to have the default behavior explode on edge cases rather than Do The Right Thing :tm:.

### Reproduction Steps

`message.attachments[0].save("whatever")` on a message containing a non-image attachment.

### Expected Results

I expect the file to save properly.

### Actual Results

This error gets thrown:

```
Traceback (most recent call last):
  File "/home/astrid/Projects/PluralKit/venv/lib/python3.6/site-packages/discord/client.py", line 227, in _run_event
    await coro(*args, **kwargs)
  File "/home/astrid/Projects/PluralKit/src/pluralkit/bot/__init__.py", line 84, in on_message
    did_run_command = await commands.command_dispatch(client, message, conn)
  File "/home/astrid/Projects/PluralKit/src/pluralkit/bot/commands/__init__.py", line 237, in command_dispatch
    await run_command(ctx, command_root)
  File "/home/astrid/Projects/PluralKit/src/pluralkit/bot/commands/__init__.py", line 214, in run_command
    await func(ctx)
  File "/home/astrid/Projects/PluralKit/src/pluralkit/bot/commands/__init__.py", line 195, in command_root
    await import_commands.import_root(ctx)
  File "/home/astrid/Projects/PluralKit/src/pluralkit/bot/commands/import_commands.py", line 13, in import_root
    await import_tupperbox(ctx)
  File "/home/astrid/Projects/PluralKit/src/pluralkit/bot/commands/import_commands.py", line 33, in import_tupperbox
    await message.attachments[0].save(s)
  File "/home/astrid/Projects/PluralKit/venv/lib/python3.6/site-packages/discord/message.py", line 114, in save
    data = await self._http.get_attachment(url)
  File "/home/astrid/Projects/PluralKit/venv/lib/python3.6/site-packages/discord/http.py", line 228, in get_attachment
    raise HTTPException(resp, 'failed to get attachment')
discord.errors.HTTPException: Unsupported Media Type (status code: 415): failed to get attachment
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] have removed my token from display, if visible.

### System Information

- discord.py version: https://github.com/Rapptz/discord.py/commit/aceec2009a7c819d2236884fa9ccc5ce58a92bea
- Python version: 3.6
- Operating system: Arch Linux

**Comment by Rapptz** [comment]
Thanks for the report.

I do remember there being a particular reason why I chose the url rather than the proxy one but this seemed to have been lost with time so I forgot it.
