### ISSUE TITLE
Can not connect to discordapp.com:443 [Name or service not known]

### ISSUE THREAD

**Issue by shrx** [Rapptz/discord.py#199]
I get this error on bot start:
```
Traceback (most recent call last):
  File "bin/discordBotClass.py", line 736, in <module>
    loop.run_until_complete(bot.login(email, password))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 373, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/home/shrx/.local/lib/python3.5/site-packages/discord/client.py", line 479, in login
    resp = yield from self.session.post(endpoints.LOGIN, data=data, headers=self.headers)
  File "/home/shrx/.local/lib/python3.5/site-packages/aiohttp/client.py", line 528, in __iter__
    resp = yield from self._coro
  File "/home/shrx/.local/lib/python3.5/site-packages/aiohttp/client.py", line 183, in _request
    conn = yield from self._connector.connect(req)
  File "/home/shrx/.local/lib/python3.5/site-packages/aiohttp/connector.py", line 320, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno -2] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [Name or service not known]]
```

**Comment by khazhyk** [comment]
That is a DNS error which is generally an issue you need to resolve in your server's configuration. Does this error always happen?

**Comment by shrx** [comment]
It just happened yesterday without me changing anything.

**Comment by khazhyk** [comment]
Does this error always happen?

**Comment by shrx** [comment]
Since yesterday, yes.

**Comment by khazhyk** [comment]
Can you do an nslookup/etc on discordapp.com? That particular error is something wrong with your server/setup/netowrk, and not an issue with the library.

**Comment by shrx** [comment]
It appears my DNS servers got borked by themselves somehow, I fixed them and it works fine now.

**Comment by FatRagdoll** [comment]
Do you remember exactly how you fixed this problem. I'm getting the same error when starting the bot.

**Comment by shrx** [comment]
This depends on your OS - check where you have the DNS server IPs and verify they are working.
