### ISSUE TITLE
Latest commit now gives me this issue...

### ISSUE THREAD

**Issue by AraHaan** [Rapptz/discord.py#202]
Traceback (most recent call last):
      File "E:\Users\Elsword\Desktop\DecoraterBot\Async\DecoraterBot.py", line 78, in <module>
        DecoraterBotCore.BotCore._login_helper(client)
      File "E:\Users\Elsword\Desktop\DecoraterBot\Async\DecoraterBotCore\Core.py", line 94, in _login_helper
        Login.login_info(client)
      File "E:\Users\Elsword\Desktop\DecoraterBot\Async\DecoraterBotCore\Login.py", line 44, in login_info
        client.run(bot_token)
      File "E:\Users\Elsword\Desktop\DecoraterBot\Async\Dependencies\discord\client.py", line 455, in run
        self.loop.run_until_complete(self.start(token))
      File "asyncio\base_events.py", line 337, in run_until_complete
      File "asyncio\futures.py", line 274, in result
      File "asyncio\tasks.py", line 239, in _step
      File "E:\Users\Elsword\Desktop\DecoraterBot\Async\Dependencies\discord\client.py", line 423, in start
        yield from self.connect()
      File "E:\Users\Elsword\Desktop\DecoraterBot\Async\Dependencies\discord\client.py", line 369, in connect
        yield from self.ws.poll_event()
    AttributeError: 'NoneType' object has no attribute 'poll_event'
    Task was destroyed but it is pending!
    task: <Task pending coro=<WebSocketCommonProtocol.run() running at E:\Users\Elsword\Desktop\DecoraterBot\Async\Dependencies\websockets\protocol.py:411> wait_for=<Future pending cb=[Task._wakeup()]>>
    Unclosed client session
    client_session: <aiohttp.client.ClientSession object at 0x0397B090>
    Press any key to continue . . .

**Comment by EJH2** [comment]
I gave you help for the other one... the link isn't a universal fix for this and I am not a Discord.py guru who fixes one problem and then fixes them all. Sorry if I disappointed you.

**Comment by AraHaan** [comment]
Well something has to be settign them to None unless it is because of the ``__init__`` having a initial value for it being None. Or it could be due to Danny not returning something for it.

**Comment by AraHaan** [comment]
Looks like I am getting closer it is because Danny is not returning something I tested it by adding ``return ws`` to ``from_client`` in ``gateway.py``
