### ISSUE TITLE
Using Python 3.7 causes a lot of errors to appear when using the logging library

### ISSUE THREAD

**Issue by TheSilvus** [Rapptz/discord.py#2036]
### Summary

The libary attempts to log things using `logging` during shutdown. If one is logging to a file this causes a crash because `open`, used by `logging` to write to the file, is not available anymore.

### Reproduction Steps

I've tested this program with Python 3.7.2. Running it causes a cascade of errors.

```
import os
import logging
import discord


logging.basicConfig(filename="logger.log", level=logging.DEBUG)

client = discord.Client()

@client.event
async def on_ready():
    await client.close()

client.run("TOKEN")
```

### Expected Results

The program crashes on shutdown.

### Actual Results

```
Exception ignored in: <function ClientSession.__del__ at 0x7f7ba038dd90>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/aiohttp/client.py", line 216, in __del__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1640, in call_exception_handler
  File "/usr/lib/python3.7/logging/__init__.py", line 1412, in error
  File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1131, in emit
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
NameError: name 'open' is not defined
Exception ignored in: <function BaseConnector.__del__ at 0x7f7ba062e840>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/aiohttp/connector.py", line 227, in __del__
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1640, in call_exception_handler
  File "/usr/lib/python3.7/logging/__init__.py", line 1412, in error
  File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1131, in emit
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1640, in call_exception_handler
  File "/usr/lib/python3.7/logging/__init__.py", line 1412, in error
  File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1131, in emit
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
NameError: name 'open' is not defined
Exception ignored in: <coroutine object DiscordWebSocket.close_connection at 0x7f7b9f901b48>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/discord/gateway.py", line 539, in close_connection
  File "/usr/lib/python3.7/site-packages/websockets/protocol.py", line 852, in close_connection
  File "/usr/lib/python3.7/logging/__init__.py", line 1371, in debug
  File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1131, in emit
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1640, in call_exception_handler
  File "/usr/lib/python3.7/logging/__init__.py", line 1412, in error
  File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1131, in emit
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
NameError: name 'open' is not defined
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### System Information

- discord.py version: Directly pulled from `rewrite` branch earlier today (Following line in `requirements.txt`: `git+https://github.com/Rapptz/discord.py@rewrite`)
- Python version: 3.7.2
- Operating system: Linux Arch

**Comment by TheSilvus** [comment]
I actually did not have the newest discord.py version installed. The error changes, but still appears.

```
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1640, in call_exception_handler
  File "/usr/lib/python3.7/logging/__init__.py", line 1412, in error
  File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1131, in emit
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
NameError: name 'open' is not defined
Exception ignored in: <coroutine object DiscordWebSocket.close_connection at 0x7f6b6df75e48>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/discord/gateway.py", line 539, in close_connection
  File "/usr/lib/python3.7/site-packages/websockets/protocol.py", line 852, in close_connection
  File "/usr/lib/python3.7/logging/__init__.py", line 1371, in debug
  File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1131, in emit
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
NameError: name 'open' is not defined
Exception ignored in: <bound method BaseEventLoop.call_exception_handler of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1640, in call_exception_handler
  File "/usr/lib/python3.7/logging/__init__.py", line 1412, in error
  File "/usr/lib/python3.7/logging/__init__.py", line 1519, in _log
  File "/usr/lib/python3.7/logging/__init__.py", line 1529, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
  File "/usr/lib/python3.7/logging/__init__.py", line 905, in handle
  File "/usr/lib/python3.7/logging/__init__.py", line 1131, in emit
  File "/usr/lib/python3.7/logging/__init__.py", line 1121, in _open
NameError: name 'open' is not defined
```

**Comment by NCPlayz** [comment]
Just tested this on Python 3.7.3 (Microsoft Windows [Version 10.0.17763.402]) on rewrite (4ec7213). No repro. My program closes safely with no errors.

```
2019-03-31 12:45:20,112:INFO:discord.gateway: Websocket closed with 1000 (), cannot reconnect.
2019-03-31 12:45:20,112:DEBUG:discord.client: Dispatching event disconnect
2019-03-31 12:45:20,113:INFO:discord.client: Cleaning up event loop.
2019-03-31 12:45:20,113:INFO:discord.client: Cleaning up after 5 tasks
```

**Comment by Harmon758** [comment]
I'm also unable to reproduce this with the given code on Python 3.7.2 on Microsoft Windows 7 (64-bit) [Version 6.1.7601] using https://github.com/Rapptz/discord.py/commit/4ec72135063f0f200f3b7250504eee8bd83c2f02.
What is the exact version of discord.py you're using?
Is this the exact code you used to produce the errors?
https://bugs.python.org/issue26789 is possibly related, but this seems like an issue that is neither specific to discord.py nor Python 3.7

**Comment by TheSilvus** [comment]
Huh, that's weird. I've been able to reproduce the issue inside a docker container, although I may be doing something else wrong. I've created a Gist with the files I used: https://gist.github.com/TheSilvus/dc414f76fafca8c04c069458d26c4b9b .

**Comment by Rapptz** [comment]
Ultimately this problem is not mine or one with the library.

1) No code is run during finalization on my end, there is no `log` calls during any `__del__`.
2) If there were any calls during finalization then it'd be on the third party modules and not on this library, in which case you can take it up with them.

So there's nothing to be done here.

**Comment by yousefissa** [comment]
Is anyone still having this issue? Getting it when I'm running my bots with docker, but don't know if it's purely coincidental.
