### ISSUE TITLE
Unable to start the bot

### ISSUE THREAD

**Issue by Meirewes** [Rapptz/discord.py#2087]
Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Users\Bernardo Meireles\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 255, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Bernardo Meireles\Downloads\Spotify-Inviter-master\Spotify-Inviter-master\bot.py", line 174, in on_ready
    await client.change_presence(game=discord.Game(name=data['BotStatus']))
TypeError: change_presence() got an unexpected keyword argument 'game'

**Comment by tjubutsi** [comment]
This has been changed since the last major update, please refer to the documentation for the correct syntax: https://discordpy.readthedocs.io/en/rewrite/api.html

**Comment by Harmon758** [comment]
For posterity: https://discordpy.readthedocs.io/en/latest/api.html#discord.Client.change_presence
