### ISSUE TITLE
Internal state doesn't handle being kicked from voice, resulting in infinite reconnections upon connecting back to the channel

### ISSUE THREAD

**Issue by slice** [Rapptz/discord.py#2130]
### Summary

The library doesn't handle being kicked from voice very well. The only indication sent by Discord that you have been kicked is a self-referencial `VOICE_STATE_UPDATE` with `"channel_id": null` sent through the main WS. Nothing appears to be sent from the voice WS.

<details>
  <summary><b>Running the command to kick itself</b></summary>
<pre><code>[2019-04-30 20:24:34] [DEBUG] discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 9, 'op': 0, 'd': {'type': 0, 'tts': False, 'timestamp': '...', 'pinned': False, 'nonce': '...', 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': [], 'nick': None, 'mute': False, 'joined_at': '...', 'deaf': False}, 'id': '...', 'embeds': [], 'edited_timestamp': None, 'content': 'd_jsk py await _guild.me.move_to(None)', 'channel_id': '...', 'author': {'username': 'slice', 'id': '...', 'discriminator': '0001', 'avatar': '...'}, 'attachments': [], 'guild_id': '...'}}
[2019-04-30 20:24:34] [DEBUG] discord.client: Dispatching event socket_response
[2019-04-30 20:24:34] [DEBUG] discord.client: Dispatching event message
[2019-04-30 20:24:34] [DEBUG] discord.client: Dispatching event command
[2019-04-30 20:24:34] [DEBUG] discord.http: PATCH https://discordapp.com/api/v7/guilds/.../members/... with {"channel_id":null} has returned 204
[2019-04-30 20:24:34] [DEBUG] discord.http: PATCH https://discordapp.com/api/v7/guilds/.../members/... has received</code></pre>
</details>

<details>
<summary><b>Websocket data received upon being kicked</b></summary>
<pre><code>[2019-04-30 20:24:34] [DEBUG] websockets.protocol: client < Frame(fin=True, opcode=2, data=b'...', rsv1=False, rsv2=False, rsv3=False)
[2019-04-30 20:24:34] [DEBUG] discord.client: Dispatching event socket_raw_receive
[2019-04-30 20:24:34] [DEBUG] discord.gateway: For Shard ID None: WebSocket Event: {'t': 'VOICE_STATE_UPDATE', 's': 10, 'op': 0, 'd': {'member': {'user': {'username': '...', 'id': '...', 'discriminator': '...', 'bot': True, 'avatar': '...'}, 'roles': ['...'], 'nick': None, 'mute': False, 'joined_at': '...', 'deaf': False}, 'user_id': '...', 'suppress': False, 'session_id': '...', 'self_video': False, 'self_mute': False, 'self_deaf': False, 'mute': False, 'guild_id': '...', 'deaf': False, 'channel_id': None}}
[2019-04-30 20:24:34] [DEBUG] discord.client: Dispatching event socket_response
[2019-04-30 20:24:34] [DEBUG] discord.client: Dispatching event voice_state_update
[2019-04-30 20:24:35] [DEBUG] websockets.protocol: client < Frame(fin=True, opcode=2, data=b'...', rsv1=False, rsv2=False, rsv3=False)</code></pre>
</details>

Upon being kicked, the voice WS remains alive, and pings are sent as normal. It appears that the lib doesn't update its internal state; it doesn't seem to notice that it was kicked. Upon having the bot connect again once kicked, the bot immediately gets closed with `4000`:

<details>
  <summary><b>Upon reconnecting after being kicked</b></summary>
<pre><code>[2019-04-30 20:24:38] [DEBUG] websockets.protocol: client - state = CLOSING
[2019-04-30 20:24:38] [DEBUG] websockets.protocol: client > Frame(fin=True, opcode=8, data=b'\x0f\xa0', rsv1=False, rsv2=False, rsv3=False)
[2019-04-30 20:24:39] [DEBUG] websockets.protocol: client - event = eof_received()
[2019-04-30 20:24:39] [DEBUG] websockets.protocol: client < Frame(fin=True, opcode=8, data=b'\x0f\xa0', rsv1=False, rsv2=False, rsv3=False)
[2019-04-30 20:24:39] [DEBUG] websockets.protocol: client - event = connection_lost(None)
[2019-04-30 20:24:39] [DEBUG] websockets.protocol: client - state = CLOSED
[2019-04-30 20:24:39] [DEBUG] websockets.protocol: client x code = 4000, reason = [empty]
[2019-04-30 20:24:39] [ERROR] discord.voice_client: Disconnected from voice... Reconnecting in 1.54s.
Traceback (most recent call last):
  File "/Users/slice/Code/lib/discord.py/discord/gateway.py", line 735, in poll_event
    msg = await asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 350, in recv
    yield from self.ensure_open()
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 512, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4000 (private use), no reason

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/slice/Code/lib/discord.py/discord/voice_client.py", line 242, in poll_voice_ws
    await self.ws.poll_event()
  File "/Users/slice/Code/lib/discord.py/discord/gateway.py", line 738, in poll_event
    raise ConnectionClosed(exc, shard_id=None) from exc
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4000 (private use), no reason
[2019-04-30 20:24:39] [DEBUG] websockets.protocol: client x closing TCP connection
</code></pre>
</details>

From here on out it gets stuck in a loop of being closed with `4000` and reconnecting every 30s or so. 

### Reproduction Steps

- Make the bot connect to voice channel A
- Make the bot kick itself (`await _guild.me.move_to(None)`)
- Make the bot connect to voice channel A again

### Expected Results

- The bot closes the voice WS upon being kicked (?)
- The bot doesn't get stuck in a loop after reconnecting to the voice channel 

### Actual Results

- The bot keeps the voice WS open after being kicked
- Attempting to reconnect to the voice channel results in an infinite loop of code `4000` closes and reconnects

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- discord.py version: 1.1.0a1919+g91e00d8
- Python version: Python 3.7.3
- Operating system: macOS 10.14

**Comment by Rapptz** [comment]
I couldn't quite reproduce this as given but after talking to Jake about it and noticing that the websocket becomes a zombie (i.e. never terminating with any close code) it turned out that Discord doesn't terminate the websocket and this will be fixed upstream soon-ish, hopefully.

**Comment by AutumnClove** [comment]
Is discord addressing this too? I'm hoping it fixes an on going issue I can't do anything about, without doing extra stuff I don't wanna do for performance reasons.

**Comment by Rapptz** [comment]
I believe this has been fixed on Discord's end now.
