### ISSUE TITLE
AttributeError: 'Bot' object has no attribute 'logs_from'

### ISSUE THREAD

**Issue by Abirul** [Rapptz/discord.py#2180]
``` 
import discord
from discord.ext import commands
from discord.ext.commands import Bot

TOKEN = "token"

client = commands.Bot(command_prefix = "-")

@client.event
async def on_ready():
    print("Bot is ready.")

@client.command(pass_context=True)
async def clear(ctx,amount=100):
    channel = ctx.message.channel
    messages = []
    async for message in client.logs_from(channel,limit=int(amount)):
        messages.append(message)
    await client.delete_messages(messages)
    await ctx.send("Messages deleted.")

client.run(TOKEN)
```

``` 
Bot is ready.
Ignoring exception in command clear:
Traceback (most recent call last):
  File "C:\Users\abrar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "F:\Abirul\Bot\Python Bot\bot.py", line 17, in clear
    async for message in client.logs_from(channel,limit=init(amount)):
AttributeError: 'Bot' object has no attribute 'logs_from'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\abrar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\bot.py", line 859, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\abrar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 725, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\abrar\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Bot' object has no attribute 'logs_from'
```

**Comment by jsnells1** [comment]
I believe logs_from has been changed in 1.0.

You can now call `channel.history(limit=amount)`

Correct me if I'm wrong, trying to get into helping this library since it's been very helpful to me :)

**Comment by Harmon758** [comment]
You're attempting to use syntax from v0.16.x of the library, which is no longer supported.
See https://discordpy.readthedocs.io/en/latest/migrating.html.

For further help, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.
