### ISSUE TITLE
Handle unavailable servers in READY event

### ISSUE THREAD

**Issue by Hornwitser** [Rapptz/discord.py#22]
When a guild is unavailable, it will contain

    {
        "unavailable": true,
        "id": "41771983423143937"
    }

in the guilds array in the READY event.  This is not handled properly, and a KeyError is raised.

    Traceback (most recent call last):
      File "bot.py", line 345, in <module>
        bot.run()
      File "/home/julian/prog/record/logger/discord/client.py", line 530, in run
        self.ws.run()
      File "/usr/lib/python3.5/site-packages/ws4py/websocket.py", line 427, in run
        if not self.once():
      File "/usr/lib/python3.5/site-packages/ws4py/websocket.py", line 305, in once
        if not self.process(b):
      File "/usr/lib/python3.5/site-packages/ws4py/websocket.py", line 377, in process
        self.received_message(s.message)
      File "/home/julian/prog/record/logger/discord/client.py", line 130, in received_message
        self.dispatch('socket_update', event, data)
      File "/home/julian/prog/record/logger/discord/client.py", line 507, in dispatch
        getattr(self, handle_method, _null_event)(*args, **kwargs)
      File "/home/julian/prog/record/logger/discord/client.py", line 515, in handle_socket_update
        getattr(self.connection, method)(data)
      File "/home/julian/prog/record/logger/discord/client.py", line 202, in handle_ready
        self._add_server(guild)
      File "/home/julian/prog/record/logger/discord/client.py", line 161, in _add_server
        guild['roles'] = [Role(**role) for role in guild['roles']]
    KeyError: 'roles'

[Relevant WebSocket message](http://hornwitser.no/discord/query?query=SELECT+*+FROM+message+WHERE+id+%3D+231098) (Warning: big).

**Comment by Rapptz** [comment]
I tried to support it here: https://github.com/Rapptz/discord.py/commit/5efddaf35def4559e8f2124bc4fc6bf8acb8b158

However due to not having any unavailable guilds it was hard to test.
