### ISSUE TITLE
AttributeError: module 'discord' has no attribute 'Server'

### ISSUE THREAD

**Issue by CryptoLover705** [Rapptz/discord.py#2221]
Hey I am trying to set up a tipbot, I get this message and an error at the bottom please help 

```
root@TipBot:~/sct-tip-bot# python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    from utils import output, parsing, checks, mysql_module, g
  File "/root/sct-tip-bot/utils/checks.py", line 1, in <module>
    from utils import parsing, mysql_module
  File "/root/sct-tip-bot/utils/mysql_module.py", line 11, in <module>
    class Mysql:
  File "/root/sct-tip-bot/utils/mysql_module.py", line 24, in Mysql
    class __Mysql:
  File "/root/sct-tip-bot/utils/mysql_module.py", line 98, in __Mysql
    def check_server(self, server: discord.Server):
AttributeError: module 'discord' has no attribute 'Server'
```

**Comment by ShineyDev** [comment]
i gave you an answer to this error on the issue you necrobumped, it's `discord.Guild` now

**Comment by CryptoLover705** [comment]
Oh ok thank you, If i get any other problems can I send you a message?

**Comment by ShineyDev** [comment]
you can join the discord.py guild (https://discord.gg/r3sSKJJ) and get help there
