### ISSUE TITLE
Ten seconds delay on cleanup due to WS TCP timeout.

### ISSUE THREAD

**Issue by PendragonLore** [Rapptz/discord.py#2236]
### Summary

The WebSocket waits for TCP closing when cleaning up until it times out, delaying the closure of the bot by about 10 seconds.

### Reproduction Steps

This issue can be reproduced easily with any bot that uses ``Bot.run(...)`` to start.

Once the bot is running and ready try to press ctrl+c or send SIGINT to kill it.

### Expected Results

The bot cleans up and shuts down relatively quickly.

### Actual Results

The bot waits for 10 seconds, then it shuts down.

The logs from ``websockets`` and ``discord`` show this:
```2019-06-20 18:11:34 | INFO     | client:run:594 - Cleaning up tasks.
2019-06-20 18:11:34 | INFO     | client:_cancel_tasks:73 - Cleaning up after 4 tasks.
2019-06-20 18:11:44 | DEBUG    | protocol:close_connection:827 - client ! timed out waiting for TCP close
2019-06-20 18:11:44 | DEBUG    | protocol:close_connection:852 - client x closing TCP connection
2019-06-20 18:11:44 | DEBUG    | protocol:eof_received:998 - client - event = eof_received()
2019-06-20 18:11:44 | DEBUG    | protocol:connection_lost:1007 - client - event = connection_lost(None)
2019-06-20 18:11:44 | DEBUG    | protocol:connection_lost:1009 - client - state = CLOSED
2019-06-20 18:11:44 | DEBUG    | protocol:connection_lost:1013 - client x code = 1006, reason = [empty]
2019-06-20 18:11:44 | INFO     | client:_cancel_tasks:78 - All tasks finished cancelling.
2019-06-20 18:11:44 | INFO     | client:_cleanup_loop:96 - Closing the event loop.
```
If ctrl+c is pressed again before it times out a ``RuntimeError`` will be raised before completely dying.
```python
Traceback (most recent call last):
  File "bot.py", line 19, in <module>
    bot.run(token)
  File "/Users/<user>/Desktop/Bot/venv/lib/python3.7/site-packages/discord/client.py", line 595, in run
    _cleanup_loop(loop)
  File "/Users/<user>/Desktop/Bot/venv/lib/python3.7/site-packages/discord/client.py", line 92, in _cleanup_loop
    _cancel_tasks(loop)
  File "/Users/<user>/Desktop/Bot/venv/lib/python3.7/site-packages/discord/client.py", line 77, in _cancel_tasks
    loop.run_until_complete(asyncio.gather(*tasks, loop=loop, return_exceptions=True))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 582, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.2-final
- discord.py v1.2.2-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Darwin 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64

**Comment by Rapptz** [comment]
Not my problem.
