### ISSUE TITLE
Failure to properly propagate client exceptions: Task exception was never retrieved 

### ISSUE THREAD

**Issue by 0x5c** [Rapptz/discord.py#2237]
### Summary

Client exceptions are never propagated out of `.run()`.  
Cause is seemingly a failure to take the steps to ensure propagation, as [the `asyncio` documentation](https://docs.python.org/3/library/asyncio-dev.html#detect-never-retrieved-exceptions) suggests.

### Reproduction Steps

1. Use the latest discord.py version (freshly installed).
2. Use python 3.7.3 (Versions 3.6.?, 3.7.1, and 3.8.? were shown in [the discord thread][1] to exhibit the same issue).
3. This code:
```py
import discord

try:
    discord.Client().run("borked token")
except:
    print("Caught!")
```

### Expected Results

Exception is propagated to user code, where it can be caught.

### Actual Results

Exception is lost in library code, and it is [seemingly] not propagated through the *loop(?)*.
```none
(botenv) root@GLaDOS:/mnt/c/dev/bots/asyncdemo# python -V; pip -V
Python 3.7.3
pip 19.1.1 from /mnt/c/dev/bots/asyncdemo/botenv/lib/python3.7/site-packages/pip (python 3.7)
(botenv) root@GLaDOS:/mnt/c/dev/bots/asyncdemo# cat main.py
#!/usr/bin/env python3

import discord

try:
    discord.Client().run("borked token")
except:
    print("Caught!")
(botenv) root@GLaDOS:/mnt/c/dev/bots/asyncdemo# ./main.py
Task exception was never retrieved
future: <Task finished coro=<Client.run.<locals>.runner() done, defined at /mnt/c/dev/bots/asyncdemo/botenv/lib/python3.7/site-packages/discord/client.py:577> exception=LoginFailure('Improper token has been passed.')>
Traceback (most recent call last):
  File "/mnt/c/dev/bots/asyncdemo/botenv/lib/python3.7/site-packages/discord/http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/mnt/c/dev/bots/asyncdemo/botenv/lib/python3.7/site-packages/discord/http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 UNAUTHORIZED (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/dev/bots/asyncdemo/botenv/lib/python3.7/site-packages/discord/client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "/mnt/c/dev/bots/asyncdemo/botenv/lib/python3.7/site-packages/discord/client.py", line 542, in start
    await self.login(*args, bot=bot)
  File "/mnt/c/dev/bots/asyncdemo/botenv/lib/python3.7/site-packages/discord/client.py", line 400, in login
    await self.http.static_login(token, bot=bot)
  File "/mnt/c/dev/bots/asyncdemo/botenv/lib/python3.7/site-packages/discord/http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
```

### Checklist

- [x] I have searched the open issues for duplicates.
  --> Malformed and poorly-researched issue #1420 shows up.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible. **N/A**

### System Information

- Python v3.7.3-final
- discord.py v1.2.2-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.4.0-17763-Microsoft #253-Microsoft Mon Dec 31 17:49:00 PST 2018

[1]: https://discordapp.com/channels/336642139381301249/381965515721146390/591364345640779796 "The discussion thread on the server"

**Comment by 0x5c** [comment]
Some change between 1.0.0 and 1.0.1 seem to be the cause of the issue.

**Comment by 0x5c** [comment]
Culprit: dcdcf1ad
