### ISSUE TITLE
Cant install: error in code

### ISSUE THREAD

**Issue by PaxPlay** [Rapptz/discord.py#226]
`Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-12EKQ3/aiohttp/`

**Comment by ccubed** [comment]
We need more information from the traceback but my bet is that you're trying to use the lib on python version <3.4.2. You need at least 3.4.2.

**Comment by PaxPlay** [comment]
I'm using python3.5-dev.

**Comment by PaxPlay** [comment]
I don't know how, but now it worked.
I started it multiple times and now everything works fine.

**Comment by ZerataX** [comment]
I'm having the exact same Problem

```
sudo pip3 install git+https://github.com/Rapptz/discord.py@async
Collecting git+https://github.com/Rapptz/discord.py@async
  Cloning https://github.com/Rapptz/discord.py (to async) to /tmp/pip-n588ql0i-build
Collecting aiohttp<0.22.0,>=0.21.0 (from discord.py==0.10.0a0)
  Using cached aiohttp-0.21.6.tar.gz
Collecting websockets==3.1 (from discord.py==0.10.0a0)
  Using cached websockets-3.1.tar.gz
Collecting PyNaCl==1.0.1 (from discord.py==0.10.0a0)
  Using cached PyNaCl-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:2:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/lib64/python3.4/distutils/unixccompiler.py", line 126, in _compile
        extra_postargs)
      File "/usr/lib64/python3.4/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib64/python3.4/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib64/python3.4/distutils/spawn.py", line 162, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib64/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib64/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 160, in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/usr/lib/python3.4/site-packages/setuptools/command/bdist_egg.py", line 146, in call_command
        self.run_command(cmdname)
      File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.4/site-packages/setuptools/command/install_lib.py", line 10, in run
        self.build()
      File "/usr/lib64/python3.4/distutils/command/install_lib.py", line 107, in build
        self.run_command('build_ext')
      File "/usr/lib64/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib64/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.4/site-packages/setuptools/command/build_ext.py", line 49, in run
        _build_ext.run(self)
      File "/usr/lib64/python3.4/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/usr/lib64/python3.4/distutils/command/build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "/usr/lib/python3.4/site-packages/setuptools/command/build_ext.py", line 174, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/lib64/python3.4/distutils/command/build_ext.py", line 503, in build_extension
        depends=ext.depends)
      File "/usr/lib64/python3.4/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/lib64/python3.4/distutils/unixccompiler.py", line 128, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 239, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 269, in run
        return func()
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 238, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-xd0_i3lk/cffi-1.6.0/setup.py", line 192, in <module>
        # Check the build library
      File "/usr/lib64/python3.4/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1065, in run_setup
        run_setup(setup_script, args)
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 242, in run_setup
        raise
      File "/usr/lib64/python3.4/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib64/python3.4/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 141, in resume
        compat.reraise(type, exc, self._tb)
      File "/usr/lib/python3.4/site-packages/setuptools/compat.py", line 69, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 239, in run_setup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 269, in run
        return func()
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 238, in runner
        _execfile(setup_script, ns)
      File "/usr/lib/python3.4/site-packages/setuptools/sandbox.py", line 46, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-xd0_i3lk/cffi-1.6.0/setup.py", line 192, in <module>
        # Check the build library
      File "/usr/lib64/python3.4/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8ighy0kk/PyNaCl/setup.py", line 259, in <module>
        "Programming Language :: Python :: 3.5",
      File "/usr/lib64/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.4/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3.4/site-packages/setuptools/dist.py", line 312, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 846, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1091, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1103, in obtain
        return installer(requirement)
      File "/usr/lib/python3.4/site-packages/setuptools/dist.py", line 379, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 638, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 668, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 851, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1079, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/lib/python3.4/site-packages/setuptools/command/easy_install.py", line 1067, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8ighy0kk/PyNaCl/
```
```
$ pip3 --version
pip 8.1.2 from /usr/lib/python3.4/site-packages (python 3.4)
$ python3 --version
Python 3.4.3
```

**Comment by khazhyk** [comment]
You need to install python-dev or your platform's equivilent @ZerataX

**Comment by ZerataX** [comment]
@khazhyk, thank you so much!
For me it's part of the EPEL Repository, it has a python34-devel package.

**Comment by ZerataX** [comment]
Hmm now executing a small script, that works on my arch machine i get this:
```
 async def on_ready():
        ^
SyntaxError: invalid syntax
```
Do I need to execute this differently than just _python3 file.py_ ?

**Comment by khazhyk** [comment]
In order to use `async def` you need to be using python 3.5.1+. I'd recommend reading over the documentation for discord.py, as this is mentioned in there.

**Comment by ZerataX** [comment]
Oh I've really overread this all, I'm very sorry, thank you for answering.
