### ISSUE TITLE
selfbot dies

### ISSUE THREAD

**Issue by LittleEndu** [Rapptz/discord.py#2302]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/message.py", line 403, in _handle_member
    if author.joined_at is None:
AttributeError: 'User' object has no attribute 'joined_at'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 58, in <module>
    Selfbot().run(config.TOKEN, bot=False)
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 598, in run
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 457, in connect
    await self._connect()
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 421, in _connect
    await self.ws.poll_event()
  File "/usr/local/lib/python3.6/site-packages/discord/gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "/usr/local/lib/python3.6/site-packages/discord/gateway.py", line 423, in received_message
    func(data)
  File "/usr/local/lib/python3.6/site-packages/discord/state.py", line 399, in parse_message_update
    message._update(data)
  File "/usr/local/lib/python3.6/site-packages/discord/message.py", line 348, in _update
    handler(self, value)
  File "/usr/local/lib/python3.6/site-packages/discord/message.py", line 406, in _handle_member
    self.author = Member._from_message(message=self, data=member)
  File "/usr/local/lib/python3.6/site-packages/discord/member.py", line 197, in _from_message
    return cls(data=data, guild=message.guild, state=message._state)
  File "/usr/local/lib/python3.6/site-packages/discord/member.py", line 162, in __init__
    self._user = state.store_user(data['user'])
  File "/usr/local/lib/python3.6/site-packages/discord/state.py", line 170, in store_user
    user_id = int(data['id'])
KeyError: 'id'
```

**Comment by LittleEndu** [comment]
I think the only requirement is to be in ready state and this error can randomly happen

**Comment by LittleEndu** [comment]
apparently it's already fixed but not pushed to pypi

**Comment by Gorialis** [comment]
Duplicate of #2287, #2265
