### ISSUE TITLE
Cant run bot (pycharm)

### ISSUE THREAD

**Issue by DyciaDev** [Rapptz/discord.py#2321]
Hi!

im new and watch some vid of programming, when i want to run my first bot, its says:

> C:\Users\Chiura\PycharmProjects\UniqueBot\venv\Scripts\python.exe C:/Users/Chiura/PycharmProjects/UniqueBot/main.py
> Traceback (most recent call last):
>   File "C:\Users\Chiura\PycharmProjects\UniqueBot\venv\lib\site-packages\discord\http.py", line 258, in static_login
>     data = await self.request(Route('GET', '/users/@me'))
>   File "C:\Users\Chiura\PycharmProjects\UniqueBot\venv\lib\site-packages\discord\http.py", line 222, in request
>     raise HTTPException(r, data)
> discord.errors.HTTPException: 401 UNAUTHORIZED (error code: 0): 401: Unauthorized
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:/Users/Chiura/PycharmProjects/UniqueBot/main.py", line 19, in <module>
>     client.run('TVEwpux1tuCXCxs-3MN1ty-wNHzUeUgP')
>   File "C:\Users\Chiura\PycharmProjects\UniqueBot\venv\lib\site-packages\discord\client.py", line 598, in run
>     return future.result()
>   File "C:\Users\Chiura\PycharmProjects\UniqueBot\venv\lib\site-packages\discord\client.py", line 579, in runner
>     await self.start(*args, **kwargs)
>   File "C:\Users\Chiura\PycharmProjects\UniqueBot\venv\lib\site-packages\discord\client.py", line 542, in start
>     await self.login(*args, bot=bot)
>   File "C:\Users\Chiura\PycharmProjects\UniqueBot\venv\lib\site-packages\discord\client.py", line 400, in login
>     await self.http.static_login(token, bot=bot)
>   File "C:\Users\Chiura\PycharmProjects\UniqueBot\venv\lib\site-packages\discord\http.py", line 262, in static_login
>     raise LoginFailure('Improper token has been passed.') from exc
> discord.errors.LoginFailure: Improper token has been passed.
> 
> Process finished with exit code 1
> 

Someone can help me? (Im new!)

**Comment by TheRockettek** [comment]
The token is invalid

**Comment by DyciaDev** [comment]
Thank i found out now works but thanks!
