### ISSUE TITLE
Unable to create a client with multithreading

### ISSUE THREAD

**Issue by ion2014** [Rapptz/discord.py#2341]
### Summary
THe client will fail to start when running using client.start() 

### Reproduction Steps
```
import asyncio
import threading
from discord.client import Client


def thr(cl, token):
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(cl.start(token))
    loop.close()


def main():
    cl = Client()
    token = "XXXXXXXXXI"
    threads = [threading.Thread(target=thr, args=(cl, token))]
    [t.start() for t in threads]
    [t.join() for t in threads]
    print("bye")


if __name__ == "__main__":
    main()
```

### Expected Results
 The bot get online and ready

### Actual Results

Errors raised:
```

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/abc/miniconda3/envs/py37/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/abc/miniconda3/envs/py37/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/abc/PycharmProjects/tgd_bot/main.py", line 39, in thr
    loop.run_until_complete(cl.start(token))
  File "/Users/abc/miniconda3/envs/py37/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/abc/miniconda3/envs/py37/lib/python3.7/site-packages/discord/client.py", line 542, in start
    await self.login(*args, bot=bot)
  File "/Users/abc/miniconda3/envs/py37/lib/python3.7/site-packages/discord/client.py", line 400, in login
    await self.http.static_login(token, bot=bot)
  File "/Users/abc/miniconda3/envs/py37/lib/python3.7/site-packages/discord/http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/Users/abc/miniconda3/envs/py37/lib/python3.7/site-packages/discord/http.py", line 158, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/Users/abc/miniconda3/envs/py37/lib/python3.7/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/Users/abc/miniconda3/envs/py37/lib/python3.7/site-packages/aiohttp/client.py", line 417, in _request
    with timer:
  File "/Users/abc/miniconda3/envs/py37/lib/python3.7/site-packages/aiohttp/helpers.py", line 568, in __enter__
    raise RuntimeError('Timeout context manager should be used '
RuntimeError: Timeout context manager should be used inside a task

Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10637e1d0>
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.3-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Darwin 19.0.0 Darwin Kernel Version 19.0.0: Fri Aug  9 21:59:46 PDT 2019; root:xnu-6153.0.139.161.2~2/RELEASE_X86_64

**Comment by TheRockettek** [comment]
I believe this problem is due to the client being made in a different event loop

**Comment by Vexs** [comment]
As a primary note, you likely do not need to use threading, as asyncio is more than capable of doing concurrent bots and whatever other processes you're doing. **I highly stress that odds are, you don't need to be doing threads at all.**

Aside from that, you need to define your client object inside the thread, as the client object is attached to a differing event loop.

**Comment by ion2014** [comment]
> As a primary note, you likely do not need to use threading, as asyncio is more than capable of doing concurrent bots and whatever other processes you're doing. **I highly stress that odds are, you don't need to be using threads at all.**
> 
> Aside from that, you need to define your client object inside the thread, as the client object is attached to a differing event loop.

Sorry i'm new to async in python so im not quite familiar with the detailed implementation.
After researching i found that i should've passed a custom event loop to assign to the client.
```
self.loop = asyncio.new_event_loop()
self.client = Client(loop=self.loop)
```
Thanks for your help!
