### ISSUE TITLE
[Commands] Converters defined in custom extensions fail unless defined in specific submodule.

### ISSUE THREAD

**Issue by bijij** [Rapptz/discord.py#2369]
### Summary

Classes defined in custom `discord.ext` modules with converters will fail unless placed in a sub-module with a name ending in `converter`.

As the commands extension assumes the class to be a regular discord.py class and attempts to invoke a commands extension specific converter rather than the classes own.

The issue is caused by [line 347 of discord/ext/commands/core.py](../blob/master/discord/ext/commands/core.py#L347).

Unsure as to what approach would be best for fixing this issue.

### Reproduction Steps

See this example code:

> `discord.ext.foo.__init__`
```py
from discord.ext import commands
from .converter import Baz

class Bar(commands.Converter):

    @classmethod
    async def convert(cls, ctx, argument):
        return 1

```

> `discord.ext.foo.converter`
```py
from discord.ext import commands

class Baz(commands.Converter):

    @classmethod
    async def convert(cls, ctx, argument):
        return 2
```

> `bot.py`
```py
from discord.ext import commands, foo

bot = commands.Bot(command_prefix='t.')

@bot.command()
async def test_1(ctx, arg: foo.Bar):
    await ctx.send(arg)

@bot.command()
async def test_2(ctx, arg: foo.Baz):
    await ctx.send(arg)

bot.run('TOKEN')
```

### Expected Results

invoking commands `test_1` and `test_2` with any argument should work.

### Actual Results

Only invoking command `test_2` is successful, 
Here's a sample traceback

```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\discord\client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\discord\ext\commands\bot.py", line 901, in on_message
    await self.process_commands(message)
  File "C:\Program Files\Python37\lib\site-packages\discord\ext\commands\bot.py", line 898, in process_commands
    await self.invoke(ctx)
  File "C:\Program Files\Python37\lib\site-packages\discord\ext\commands\bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Program Files\Python37\lib\site-packages\discord\ext\commands\core.py", line 721, in invoke
    await self.prepare(ctx)
  File "C:\Program Files\Python37\lib\site-packages\discord\ext\commands\core.py", line 685, in prepare
    await self._parse_arguments(ctx)
  File "C:\Program Files\Python37\lib\site-packages\discord\ext\commands\core.py", line 599, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "C:\Program Files\Python37\lib\site-packages\discord\ext\commands\core.py", line 455, in transform
    return await self.do_conversion(ctx, converter, argument, param)
  File "C:\Program Files\Python37\lib\site-packages\discord\ext\commands\core.py", line 408, in do_conversion
    return await self._actual_conversion(ctx, converter, argument, param)
  File "C:\Program Files\Python37\lib\site-packages\discord\ext\commands\core.py", line 348, in _actual_conversion
    converter = getattr(converters, converter.__name__ + 'Converter')
AttributeError: module 'discord.ext.commands.converter' has no attribute 'BarConverter'
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.7.3-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 10 10.0.18999

**Comment by romangraef** [comment]
A quick fix would be to replace https://github.com/Rapptz/discord.py/blob/c6539bbc615e22a59455179b8526dc6ae264c2a4/discord/ext/commands/core.py#L348 with 
```py
converter = getattr(converters, converter.__name__ + 'Converter', converter)
```
I will probably hand this in as a PR later, but I don't know if it's top priority since this probably won't happen a lot.
