### ISSUE TITLE
i can't make my own bot

### ISSUE THREAD

**Issue by Scorpions95** [Rapptz/discord.py#2379]
Hi there 
here is my 3 files 

[3 bots.zip](https://github.com/Rapptz/discord.py/files/3744952/3.bots.zip)
tryed to make 3 times bot, one from this 3 file i made bot,but it's offline
how can i make it online?

**Comment by ShineyDev** [comment]
github issues should be used to point out issues with the library. try our [discord server](https://discord.gg/r3sSKJJ) for help with this.

**Comment by Scorpions95** [comment]
when i run one of them i see this
```
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
====== RESTART: C:\Users\User\Desktop\Stuff\discord bot\ресурси\rockbot.py =====
Traceback (most recent call last):
  File "D:\porgrams\Python\lib\site-packages\discord\http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "D:\porgrams\Python\lib\site-packages\discord\http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 UNAUTHORIZED (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Desktop\Stuff\discord bot\ресурси\rockbot.py", line 10, in <module>
    client.run('w36Ok2xPAOb-cEyqC54YHqdlB9J76ohI')
  File "D:\porgrams\Python\lib\site-packages\discord\client.py", line 598, in run
    return future.result()
  File "D:\porgrams\Python\lib\site-packages\discord\client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "D:\porgrams\Python\lib\site-packages\discord\client.py", line 542, in start
    await self.login(*args, bot=bot)
  File "D:\porgrams\Python\lib\site-packages\discord\client.py", line 400, in login
    await self.http.static_login(token, bot=bot)
  File "D:\porgrams\Python\lib\site-packages\discord\http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
>>> 
how can i fix it?
```

**Comment by TheRockettek** [comment]
github issues should be used to point out issues with the library. try our [discord server](https://discord.gg/r3sSKJJ) help with this.

ᵗʰᵉ ᵗᵒᵏᵉⁿ ᶦˢ ᶦⁿᵛᵃˡᶦᵈ

**Comment by CapnS** [comment]
**Oh no! You just leaked your bot token!**

You accidentally gave out your code and forgot to remove the token! What does that do?
Well, it leads to letting users access your bot acccount/controlling it.
Don't worry, you can reset your token anytime!

You only have to go on **https://discordapp.com/developers/aplications/** and generate a new token under the bot tab.

Make sure next time you don't leak your bot token.
Always keep in mind that you have to remove the bot token before taking a screenshot or sending your code to get help.
