### ISSUE TITLE
Timeout context manager should be used in task when calling await channel.send(msg)

### ISSUE THREAD

**Issue by GodschildGaming** [Rapptz/discord.py#2389]
So far I am in a major experiment mode with discord.py, so far it has been a perfect solution from switching from hangups bot for hangouts to discord. Now as a side project I have started working on code for a countdown timer for events and stuff. I do this in a new thread that has async enabled to run with the bot. The time code works perfectly but whenever I try to use await to send, fetch_message or edit I get and error. I spent hours searching for solutions to come up empty handed so now I personally ask for help. 
**Code that is throwing error**
```python
            try:
                cid = TimeTracker[list(TimeTracker)[i]].chanid
                mid = TimeTracker[list(TimeTracker)[i]].Chatid
                mes = await cid.fetch_message(int(mid)) #timeout here
                #await cid.send("I am in pain") #timeout 3 as debug proof of await not working
                print(a-b)
                await mes.edit(content = str(a-b)) #timeout here as well
            except Exception as e:
                print("something messed up! " + str(e))
```
now I will share the rest of my code
**All code in file**
<details>
<summary>Spoiler: 238 lines</summary>

```python
import discord
import sys
import asyncio
from discord.ext import commands
import json, random
from threading import Thread
import time
import re
import datetime
from AiTime import atime
import datetime
from datetime import timedelta
import string
config = ""
TimeTracker = {}

def cal(time):
    a = datetime.datetime.strptime(time, '%Y-%m-%dT%H:%M:%S.%fZ') - timedelta(hours=5, minutes=0)
    aa = a.time()
    b = datetime.datetime.now().replace(microsecond=0)
    bb = b.time()
    return a-b

def con(time):
    a = datetime.datetime.strptime(time, '%Y-%m-%dT%H:%M:%S.%fZ') - timedelta(hours=5, minutes=0)
    return a
def current():
    return datetime.datetime.now().replace(microsecond=0)

def start_loop(loop):
    asyncio.set_event_loop(loop)
    loop.run_forever()
new_loop = asyncio.new_event_loop()
t = Thread(target=start_loop, args=(new_loop,))
t.start()

def aTimer(loop):
    asyncio.set_event_loop(loop)
    loop.run_forever()
timer = asyncio.new_event_loop()
t = Thread(target=aTimer, args=(timer,))
t.start()

result = ""
cmds = ["ping", 'help']
#ai.user.id
with open(f'config.json') as json_file:
    config = json.load(json_file)
    json_file.close()
token = config["distoken"]
autoreplies = config["autoreplies"]
ai = commands.Bot(command_prefix = '!')

async def countdown():
    while True:
        dellist = []
        for i in range(len(list(TimeTracker))):
            try:
                tar = datetime.datetime.strptime(TimeTracker[list(TimeTracker)[i]].time, '%Y-%m-%dT%H:%M:%S.%fZ') - timedelta(hours=5, minutes=0)
                current = datetime.datetime.now().replace(microsecond=0)
                if tar<current:
                    dellist.append(list(TimeTracker)[i])
            except:
                pass
        for i in dellist:
            del TimeTracker[i]
        print(len(list(TimeTracker)))
        #if len(list(TimeTracker)) == 0:
            #break
        for i in range(len(list(TimeTracker))):
            print(TimeTracker[list(TimeTracker)[0]].time)
            print(TimeTracker[list(TimeTracker)[0]].Chatid)
            try:
                ac = TimeTracker[list(TimeTracker)[i]].time
                a = datetime.datetime.strptime(ac, '%Y-%m-%dT%H:%M:%S.%fZ') - timedelta(hours=5, minutes=0)
                aa = a.time()
                b = datetime.datetime.now().replace(microsecond=0)
                bb = b.time()
            except:
                print("something broke")
            print(str(TimeTracker[list(TimeTracker)[0]].Chatid))
            #mes = await fetch_message(int(TimeTracker[list(TimeTracker)[i]].Chatid))
            cid = TimeTracker[list(TimeTracker)[i]].chanid
            mid = TimeTracker[list(TimeTracker)[i]].Chatid
            print(str(cid))
            try:
                cid = TimeTracker[list(TimeTracker)[i]].chanid
                mid = TimeTracker[list(TimeTracker)[i]].Chatid
                mes = await cid.fetch_message(int(mid))
                #await cid.send("I am in pain")
                print(a-b)
                await mes.edit(content = str(a-b))
            except Exception as e:
                print("something messed up! " + str(e))
        print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
        time.sleep(1)

async def statloop():
    while True:
        try:
            if config["DiscordStatus"]["enabled"] == True:
                if len(config["DiscordStatus"]["status"]) >= 2:
                    for x in range(len(config["DiscordStatus"]["status"])):
                        ac = config["DiscordStatus"]["status"][x][0]
                        sname = config["DiscordStatus"]["status"][x][1]
                        if "watching" == ac.lower():
                            await ai.change_presence(activity=discord.Activity(type=discord.ActivityType.watching, name=sname))
                        elif ac.lower() == "playing":
                            await ai.change_presence(activity=discord.Activity(type=discord.ActivityType.playing, name=sname))
                        elif ac.lower() == "streaming":
                            await ai.change_presence(activity=discord.Activity(type=discord.ActivityType.streaming, name=sname))
                        elif ac.lower() == "listening":
                            await ai.change_presence(activity=discord.Activity(type=discord.ActivityType.listening, name=sname))
                        elif ac.lower() == "unknown":
                            await ai.change_presence(activity=discord.Activity(type=discord.ActivityType.unknown, name=sname))
                        time.sleep(config["DiscordStatus"]["delay"])
                elif len(config["DiscordStatus"]["status"]) == 1:
                    ac = config["DiscordStatus"]["status"][0][0]
                    sname = config["DiscordStatus"]["status"][0][1]
                    if "watching" == ac.lower():
                        await ai.change_presence(activity=discord.Activity(type=discord.ActivityType.watching, name=sname))
                    elif ac.lower() == "playing":
                        await ai.change_presence(activity=discord.Activity(type=discord.ActivityType.playing, name=sname))
                    elif ac.lower() == "streaming":
                        await ai.change_presence(activity=discord.Activity(type=discord.ActivityType.streaming, name=sname))
                    elif ac.lower() == "listening":
                        await ai.change_presence(activity=discord.Activity(type=discord.ActivityType.listening, name=sname))
                    elif ac.lower() == "unknown":
                        await ai.change_presence(activity=discord.Activity(type=discord.ActivityType.unknown, name=sname))
                else:
                    print("[WARNING] No status detected in config, skipping and disabling status feature for this bot")
                    break
        except:
            print("[ERROR] DiscordStatus not detected in config, skipping and disabling status feature for this bot")
            break

async def commandcenter(cid, bot, *args):
    #print(f'{bot} starting here')
    #print(f'{args} args here')
    result = ""
    if len(args) >= 1:
        if args[0].lower() == "ping":
            result = f'Pong! {(round(ai.latency * 1000))}ms delay'
        elif args[0].lower() == "help":
            result = f'```User commands:\n{", ".join(cmds)}\nAdmin commands:\n\nbot info```'
        elif args[0].lower() == "reload":
            await ai.get_channel(cid).send(f'**reloading config**')
            with open(f'C:\\Hangout Ai\\{sys.argv[1]}\\config.json') as json_file:
                config = json.load(json_file)
                json_file.close()
            result = "**Done**"
        else:
            result = "Error command not found please use **/bot help** for a list of commands"
    await ai.get_channel(cid).send(result)
    return

async def command_handle(message, cs):
    print(message.content)
    cmds = message.content.split()
    await commandcenter(cs, *cmds)
    return result
    
def trimmsg(msg, message):
    tm = msg
    tm = tm.replace("<b>", "**")
    tm = tm.replace("</b>", "**")
    tm = tm.replace("{event.user.full_name}", message.author.name)
    tm = tm.replace("{event.user.first_name}", message.author.name)
    return tm

@ai.event
async def on_ready():
    print('Bot has connected to discord')
    asyncio.run_coroutine_threadsafe(statloop(), new_loop)
    asyncio.run_coroutine_threadsafe(countdown(), timer)
    #t1 = Thread(target = await statloop)
    #t1.setDaemon(True)
    #t1.start()
    #asyncio.ensure_future(statloop())
    #await statloop()
    

    
@ai.event
async def on_message(message):
    msg = message.content.lower()
    try:
        print(f'{message.created_at}> {message.author.name}: {message.content} - {message.channel.name} << {message.channel.guild.name}')
    except:
        print(f'{message.created_at}> {message.author.name}: {message.content} - Direct Message')
    if message.author.id != ai.user.id:
        if msg[:1] == "/":
            if "/bot" in msg or f"/{ai.user.name}".lower() in msg:
                await command_handle(message, message.channel.id)
                return
        for i in range(len(autoreplies)):
            if isinstance(autoreplies[i][0], str):
                if autoreplies[i][0].lower() in msg:
                    if isinstance(autoreplies[i][1], str):
                        tm = str(autoreplies[i][1])
                        await message.channel.send(trimmsg(tm, message))
                        break
                    else:
                        tm = str(random.choice(autoreplies[i][1]))
                        await message.channel.send(trimmsg(tm, message))
                        break
            else:
                for kw in range(len(autoreplies[i][0])):
                    if autoreplies[i][0][kw].lower() in msg:
                        if isinstance(autoreplies[i][1], str):
                            tm = str(autoreplies[i][1])
                            await message.channel.send(trimmsg(tm, message))
                            break
                        else:
                            tm = str(random.choice(autoreplies[i][1]))
                            await message.channel.send(trimmsg(tm, message))
                            break
    else:
        if "```<t>" in msg:
            result = re.search('```<t>(.*)</t>```', msg)
            letters = string.ascii_lowercase
            rname = ''.join(random.choice(letters) for i in range(20))
            TimeTracker[rname] = atime(message.id, message.channel, result.group(1), message.content)
            
@ai.command()
async def bot(ctx, *args):
    print("Command ran")
    response = ""
    cmds = ["ping", 'help']
    if len(args) >= 1:
        if args[0].lower() == "ping":
            response = f'Pong! {(round(ai.latency * 1000))}ms delay'
        if args[0].lower() == "help":
            response = f'***User commands:\n{", ".join(cmds)}\nAdmin commands:\n\nbot info***'
        await ctx.send(response)
    return
    
ai.run(token)
```
</details>

**atime is a class that just holds the info I put into it in the same order, chatid is message.id and chanid is channel, trying to avoid confusion**
**without try/exception results in thread-3 to hang forever, trying to raise RunTimeError() also causes it to hang forever. However raise RuntimeError("Something bad happened") from e produced this**
<details>
<summary>Traceback from raise RuntimeError("Something bad happened") from e </summary>

```
C:\Users\GodschildGaming\Desktop\Discord Bots\Cephalon Sabe>sabe
Bot has connected to discord
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-10-22 15:23:45.692000> dis: test01 - Direct Message
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-10-22 15:23:45.823000> Cephalon Sabe: ```<t>2019-10-22T22:50:00.000Z</t>``` - Direct Message
1
2019-10-22t22:50:00.000z
636223176879243265
636223176879243265
Direct Message with dis#1234
[ERROR] DiscordStatus not detected in config, skipping and disabling status feature for this bot
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\site-packages\discord\gateway.py", line 99, in run
    f = asyncio.run_coroutine_threadsafe(coro, loop=self.ws.loop)
  File "C:\Python\lib\asyncio\tasks.py", line 716, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "C:\Python\lib\asyncio\base_events.py", line 620, in call_soon_threadsafe
    self._check_closed()
  File "C:\Python\lib\asyncio\base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

C:\Python\lib\threading.py:949: RuntimeWarning: coroutine 'DiscordWebSocket.send_as_json' was never awaited
  del exc_type, exc_value, 
```

</details>

**Comment by Phxntxm** [comment]
Please provide the traceback; not just the string representation of the error as you're printing right now, the traceback (easiest way would be to just remove the try/except and let it error)

**Comment by GodschildGaming** [comment]
@Phxntxm it doesn't display traceback once it hits the code it just hangs forever
**with try/except**
```
C:\Users\GodschildGaming\Desktop\Discord Bots\Cephalon Sabe>sabe
Bot has connected to discord
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-10-22 15:04:06.448000> dis: test01 - Direct Message
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-10-22 15:04:06.674000> Cephalon Sabe: ```<t>2019-10-22T22:50:00.000Z</t>``` - Direct Message
2019-10-22 15:04:06.681000> Cephalon Sabe: ```<t>2019-10-22T07:50:00.000Z</t>``` - Direct Message
1
2019-10-22t22:50:00.000z
636218231170007070
636218231170007070
Direct Message with dis#1234
something messed up! Timeout context manager should be used inside a task
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1
2019-10-22t22:50:00.000z
636218231170007070
636218231170007070
Direct Message with dis#1234
something messed up! Timeout context manager should be used inside a task
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
**without try/exception**
```
C:\Users\GodschildGaming\Desktop\Discord Bots\Cephalon Sabe>sabe
Bot has connected to discord
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-10-22 15:09:16.233000> dis: test01 - Direct Message
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-10-22 15:09:16.427000> Cephalon Sabe: ```<t>2019-10-22T22:50:00.000Z</t>``` - Direct Message
1
2019-10-22t22:50:00.000z
636219530368122880
636219530368122880
Direct Message with dis#1234



```
>

**Comment by TheRockettek** [comment]
Can you provide a proper traceback instead of just the except Exception as e

**Comment by GodschildGaming** [comment]
I got some traceback from using `raise RuntimeError("Something bad happened") from e` it returned the following. otherwise no idea how to get proper traceback when it freezes

```
C:\Users\GodschildGaming\Desktop\Discord Bots\Cephalon Sabe>sabe
Bot has connected to discord
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-10-22 15:23:45.692000> dis: test01 - Direct Message
0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-10-22 15:23:45.823000> Cephalon Sabe: ```<t>2019-10-22T22:50:00.000Z</t>``` - Direct Message
1
2019-10-22t22:50:00.000z
636223176879243265
636223176879243265
Direct Message with dis#1234
[ERROR] DiscordStatus not detected in config, skipping and disabling status feature for this bot
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\site-packages\discord\gateway.py", line 99, in run
    f = asyncio.run_coroutine_threadsafe(coro, loop=self.ws.loop)
  File "C:\Python\lib\asyncio\tasks.py", line 716, in run_coroutine_threadsafe
    loop.call_soon_threadsafe(callback)
  File "C:\Python\lib\asyncio\base_events.py", line 620, in call_soon_threadsafe
    self._check_closed()
  File "C:\Python\lib\asyncio\base_events.py", line 357, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

C:\Python\lib\threading.py:949: RuntimeWarning: coroutine 'DiscordWebSocket.send_as_json' was never awaited
  del exc_type, exc_value, exc_tb
```

**Comment by Harmon758** [comment]
This is because you're attempting to use discord.py methods in new different event loops, rather than the existing event loop that those methods use.
You should also look into [using a background task](https://discordpy.readthedocs.io/en/latest/faq.html#how-do-i-run-something-in-the-background) and/or [the tasks extension](https://discordpy.readthedocs.io/en/latest/ext/tasks/index.html) instead: 

This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.
