### ISSUE TITLE
Websocket connection is closed: code = 1006

### ISSUE THREAD

**Issue by FightMan01** [Rapptz/discord.py#2404]
### Summary

My bot disconnects from the voice channel and gives me this error.

### Reproduction Steps

I just listening to music and suddenly my bot disconnected. I saw this error in the terminal:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/voice_client.py", line 250, in poll_voice_ws
    await self.ws.poll_event()
  File "/usr/local/lib/python3.6/site-packages/discord/gateway.py", line 816, in poll_event
    raise ConnectionClosed(exc, shard_id=None) from exc
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```

My bot is running on a linux vps (Ubuntu 19.10).
It happens very often.

The code:
```py
guild = ctx.guild
channel = ctx.message.author.voice.channel
await channel.connect()
vc = ctx.voice_client
source = await YTDLSource.from_url(f"ytsearch: {url}", loop=self.client.loop, stream=True)
zene = vc.play(source, after=lambda e: print('Player error: %s' % e) if e else self.check_queue(guild.id))
```
PS: YTDLSource class is from the `basic_voice.py`.

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

discord.py 1.2.4
Python 3.6.8
Ubuntu 19.10 (same on MacOS 10.15)

**Comment by FightMan01** [comment]
I saved a bit more traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/voice_client.py", line 250, in poll_voice_ws
    await self.ws.poll_event()
  File "/usr/local/lib/python3.6/site-packages/discord/gateway.py", line 816, in poll_event
    raise ConnectionClosed(exc, shard_id=None) from exc
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
'587261822344626196'
[30/Oct/2019 18:17:21] INFO - Disconnecting from voice normally, close code 4014.
[30/Oct/2019 18:17:21] INFO - The voice handshake is being terminated for Channel ID 601750115010609178 (Guild ID 587261822344626196)
[30/Oct/2019 18:17:21] INFO - The voice client has been removed for Channel ID 601750115010609178 (Guild ID 587261822344626196)
[30/Oct/2019 18:17:21] INFO - Preparing to terminate ffmpeg process 9121.
[30/Oct/2019 18:17:21] INFO - ffmpeg process 9121 has not terminated. Waiting to terminate...
[30/Oct/2019 18:17:21] INFO - ffmpeg process 9121 should have terminated with a return code of -9.
```

**Comment by Harmon758** [comment]
`Connection reset by peer` simply means that Discord terminated the connection.
Again, this isn't an issue with the library, and it should automatically attempt to reconnect as it says.
If you're sure it's not an Internet connection issue, I'd recommend double checking that you're not blocking for too long.
