### ISSUE TITLE
Error whenever i run my code of static_login

### ISSUE THREAD

**Issue by OishikGuha** [Rapptz/discord.py#2407]
### The error 

```
C:\Users\OishikG\PycharmProjects\Hello_World!>python onoto.py
Traceback (most recent call last):
  File "C:\Users\OishikG\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\http.py", line 258, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\OishikG\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 UNAUTHORIZED (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "onoto.py", line 25, in <module>
    client.run(TOKEN)
  File "C:\Users\OishikG\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 598, in run
    return future.result()
  File "C:\Users\OishikG\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\OishikG\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 542, in start
    await self.login(*args, bot=bot)
  File "C:\Users\OishikG\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\client.py", line 400, in login
    await self.http.static_login(token, bot=bot)
  File "C:\Users\OishikG\AppData\Local\Programs\Python\Python37-32\lib\site-packages\discord\http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
```

### The code I used

```
#  Work with Python 3.6
import discord

TOKEN = ''

client = discord.Client()

@client.event
async def on_message(message):
    # we do not want the bot to reply to itself
    if message.author == client.user:
        return

    if message.content.startswith('!hello'):
        msg = 'Hello {0.author.mention}'.format(message)
        await client.send_message(message.channel, msg)

@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')

client.run(TOKEN)

```
### Expected Results

I wanted my Discord bot to function but whenever i Run my code on Pycharm it always gives an error

### Actual Results

I ran my code and theres an error now

### Checklist

- [x ] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [x ] I have removed my token from display, if visible.

**Comment by Harmon758** [comment]
As the error says, you're passing an improper token.

For future help like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.
