### ISSUE TITLE
Bot can't get guild object

### ISSUE THREAD

**Issue by vikingiwan** [Rapptz/discord.py#2421]
So I have this:
```Python
@bot.event
async def on_member_join(member):
    print(member.name + " has joined the guild...assigning rank...")
    _role = bot.get_guild(vtacGuild).get_role(rank_rec)
    await bot.add_roles(member, _role)
    print("Role added to " + member.name)
```

But I get this traceback:
```
Viking has joined the guild...assigning rank...
Ignoring exception in on_member_join
Traceback (most recent call last):
  File "D:\Dev\Python\Enviornments\katV2\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "Main.py", line 213, in on_member_join
    _role = bot.get_guild(vtacGuild).get_role(rank_rec)
  File "D:\Dev\Python\Enviornments\katV2\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute 'get_guild'
```

**Comment by Harmon758** [comment]
You're using an old outdated version, v0.16.x, of discord.py that is no longer supported.
For help migrating, see https://discordpy.readthedocs.io/en/latest/migrating.html.
For future help like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links.
