### ISSUE TITLE
Crash on handling reactions

### ISSUE THREAD

**Issue by Samohtemmitt** [Rapptz/discord.py#2425]
### Summary

Since this afternoon, I have noticed my bot sessions crashing with the below traceback.  As far as I can tell, this is an issue with the handling of people adding custom reactions to messages, although considering the number of servers / channels the bot can see, I can't pin down exactly what triggers it (although I have a suspicion that my specific issue is triggered by Groovy reacting to user messages)

### Reproduction Steps

Nothing special - the bot listens on the following message events:
on_message
on_message_edit
on_member_join
on_member_remove
on_member_ban
on_member_unban
on_member_update
on_user_update
on_voice_state_update

### Expected Results

Nothing - I don't use reactions for anything on my bot.

### Actual Results

Traceback (most recent call last):
  File ".\bot.py", line 309, in <module>
    client.run(TOKEN)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 598, in run
    return future.result()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 579, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 543, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 457, in connect
    await self._connect()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 421, in _connect
    await self.ws.poll_event()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\gateway.py", line 469, in poll_event
    await self.received_message(msg)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\gateway.py", line 423, in received_message
    func(data)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\state.py", line 407, in parse_message_reaction_add
    emoji = PartialEmoji.with_state(self, animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

Tested on my computer:
- Python v3.6.8-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Windows 10 10.0.17763

and my Linux server:
- Python v3.6.8-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 201

I currently have a workaround in place to restart the bot every time it crashes, but this is not ideal.

**Comment by Rapptz** [comment]
Pinned issue: https://github.com/Rapptz/discord.py/issues/2422

**Comment by Harmon758** [comment]
Duplicate of the referenced issue, #2422.
This should now be fixed with v1.2.5.
In the future, please make sure you're using the latest development version when reporting issues.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
