### ISSUE TITLE
unable to add more than 1 message reaction

### ISSUE THREAD

**Issue by modernNeo** [Rapptz/discord.py#2474]
### Summary

the module seems to have an issue with adding more than 1 message reaction to a message.

### Reproduction Steps

```
toReactUnicode = [u"\U000023EA", u"\U000023E9", u"\U00002705"]
msg = await ctx.send(content=None, embed=embedObj)
await msg.add_reaction(toReactUnicode[0])
logger.info("[Paginate paginateEmbed()] first reaction added")
await msg.add_reaction(toReactUnicode[1])
logger.info("[Paginate paginateEmbed()] second reaction added")
await msg.add_reaction(toReactUnicode[2])
logger.info("[Paginate paginateEmbed()] third reaction added")

```

### Expected Results

What I expected was for the message to be sent to the channel and have the rewind, fast-forward and check emoji reaction added to it.

### Actual Results

on discord, the embed message does show up, along with the first specified reaction but then the second and third do not get added. Meanwhile, the bot prints out the following to the log instead

```
2019-12-10 00:36:10 = INFO - [Paginate paginateEmbed()] first reaction added
2019-12-10 00:36:10 = WARNING - Traceback (most recent call last):

2019-12-10 00:36:10 = WARNING -   File "./main.py", line 130, in <module>

2019-12-10 00:36:10 = WARNING -     
2019-12-10 00:36:10 = WARNING - bot.run(config.get_config_value("wall_e", "TOKEN"))
2019-12-10 00:36:10 = WARNING -   File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 598, in run

2019-12-10 00:36:10 = WARNING -     
2019-12-10 00:36:10 = WARNING - return future.result()
2019-12-10 00:36:10 = WARNING -   File "/usr/local/lib/python3.5/asyncio/futures.py", line 294, in result

2019-12-10 00:36:10 = WARNING -     
2019-12-10 00:36:10 = WARNING - raise self._exception
2019-12-10 00:36:10 = WARNING -   File "/usr/local/lib/python3.5/asyncio/tasks.py", line 240, in _step

2019-12-10 00:36:10 = WARNING -     
2019-12-10 00:36:10 = WARNING - result = coro.send(None)
2019-12-10 00:36:10 = WARNING -   File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 579, in runner

2019-12-10 00:36:10 = WARNING -     
2019-12-10 00:36:10 = WARNING - await self.start(*args, **kwargs)
2019-12-10 00:36:10 = WARNING -   File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 543, in start

2019-12-10 00:36:10 = WARNING -     
2019-12-10 00:36:10 = WARNING - await self.connect(reconnect=reconnect)
2019-12-10 00:36:10 = WARNING -   File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 457, in connect

2019-12-10 00:36:10 = WARNING -     
2019-12-10 00:36:10 = WARNING - await self._connect()
2019-12-10 00:36:10 = WARNING -   File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 421, in _connect

2019-12-10 00:36:10 = WARNING -     
2019-12-10 00:36:10 = WARNING - await self.ws.poll_event()
2019-12-10 00:36:10 = WARNING -   File "/usr/local/lib/python3.5/site-packages/discord/gateway.py", line 469, in poll_event

2019-12-10 00:36:10 = WARNING -     
2019-12-10 00:36:10 = WARNING - await self.received_message(msg)
2019-12-10 00:36:10 = WARNING -   File "/usr/local/lib/python3.5/site-packages/discord/gateway.py", line 423, in received_message

2019-12-10 00:36:10 = WARNING -     
2019-12-10 00:36:10 = WARNING - func(data)
2019-12-10 00:36:10 = WARNING -   File "/usr/local/lib/python3.5/site-packages/discord/state.py", line 407, in parse_message_reaction_add

2019-12-10 00:36:10 = WARNING -     
2019-12-10 00:36:10 = WARNING - emoji = PartialEmoji.with_state(self, animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
2019-12-10 00:36:10 = WARNING - KeyError
2019-12-10 00:36:10 = WARNING - : 
2019-12-10 00:36:10 = WARNING - 'animated'
2019-12-10 00:36:10 = WARNING - sys:1: RuntimeWarning: coroutine '__del__' was never awaited

2019-12-10 00:36:10 = WARNING - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd2534f8e80>
2019-12-10 00:36:10 = WARNING - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd252d3d978>
```

### Checklist

- [ X] I have searched the open issues for duplicates.
- [ X] I have shown the entire traceback, if possible.
- [ X] I have removed my token from display, if visible.

### System Information

```
/usr/src/app # python -m discord -v
- Python v3.5.5-final
- discord.py v1.2.3-final
- aiohttp v3.5.4
- websockets v6.0
- system info: Linux 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019
```

**Comment by modernNeo** [comment]
it seems when i searched the open issue for duplicates. I should have searched for the string "keyerror" and "animated" rather than what I did search for. apologizes for the duplicate.
