### ISSUE TITLE
Getting "ConnectionResetError: [Errno 104] Connection reset by peer" error.

### ISSUE THREAD

**Issue by FightMan01** [Rapptz/discord.py#2596]
### Summary

Hi. When my bot is trying t connect to the voice channel or the bot is in a voice channel it often disconnect/not connects and displays the issue. I have contacted the discord support and they said I should report this issue here. (screenshot attached)
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/29693718/76621065-d97d7400-652e-11ea-84b8-ed7fc47c0864.png">

### Reproduction Steps

I don't know how to reproduce this, I'm just getting this when my bot tries to join a voice channel or the bot is in a voice channel.

### Expected Results

The bot joins and stays in a voice channel and plays the radio/music.

### Actual Results

This traceback a bit old, but I'm getting the some nowadays as well.
```
2020-03-10 18:36:05,566:INFO:discord.voice_client: Connecting to voice...
2020-03-10 18:36:05,567:INFO:discord.voice_client: Starting voice handshake...
2020-03-10 18:37:05,573:INFO:discord.voice_client: The voice handshake is being terminated for Channel ID 682937050445643838 (Guild ID 671089108084588544)
2020-03-10 18:37:05,574:INFO:discord.voice_client: The voice client has been removed for Channel ID 682937050445643838 (Guild ID 671089108084588544)
2020-03-10 18:37:05,574:WARNING:discord.voice_client: Could not connect to voice... Retrying...
2020-03-10 18:37:05,579:ERROR:discord.voice_client: Disconnected from voice... Reconnecting in 637.99s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/usr/local/lib/python3.8/dist-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 740, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.8/asyncio/streams.py", line 534, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 836, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/gateway.py", line 746, in poll_event
    msg = await asyncio.wait_for(self.recv(), timeout=30.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/voice_client.py", line 243, in poll_voice_ws
    await self.ws.poll_event()
  File "/usr/local/lib/python3.8/dist-packages/discord/gateway.py", line 749, in poll_event
    raise ConnectionClosed(exc, shard_id=None) from exc
discord.errors.ConnectionClosed: code = 1006 (connection closed abnormally [internal]), no reason
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.0-final
- discord.py v1.3.2-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020

**Comment by FightMan01** [comment]
Now, my bot suddenly stopped with this traceback:
```
2020-03-13 16:44:43,466:ERROR:discord.ext.tasks: Internal background task failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websockets/protocol.py", line 838, in transfer_data
    await asyncio.shield(self._put_message_waiter)
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:
```

**Comment by FightMan01** [comment]
I upload a log here, it contains a lot of errors.
[dcerrors.log](https://github.com/Rapptz/discord.py/files/4330426/dcerrors.log)

**Comment by applebee1558** [comment]
This looks like you’re having internet issues. Consider getting a more stable internet connection?

**Comment by Vexs** [comment]
By all accounts error 104 is caused not by an internet problem but by exceeding ratelimits frequently. It's rather difficult to pin down the exact cause however, but I'd enable debug logging and look for indications you're exceeding the global ratelimit. 

Additionally, from your logs I see little to no sign of an internet problem.

**Comment by Daggy1234** [comment]
I am having the same issue 
https://sentry.io/share/issue/700e505d9d05439fa9518981146770db/

**Comment by Pirulax** [comment]
From my own experience it seems like it's guaranteed to happen in case 2 messages containing files are sent concurrently.
Eg.:
```py
await asyncio.wait(tuple(
    channel.send(file="file.png")
))
```
The above example might seem quite stupid, but it can also happen, if, for example there's a command that uploads files, and it just so happens that it's invoked in the exact same time (thus there'll be 2 concurrent file uploads).

This seems like some cloudflare thing tbh.
