### ISSUE TITLE
Discord.py has RuntimeError when I run my bot

### ISSUE THREAD

**Issue by hwahyang1** [Rapptz/discord.py#2612]
### Summary

I entered my bot code and ran it, and RuntimeError happened.

### Reproduction Steps

```python
# -*- coding:utf-8 -*- 

import discord, asyncio

token = "token"
client = discord.Client()

@client.event
async def on_ready():
  await client.change_presence(status=discord.Status.online, activity=discord.Game("반갑습니다 :D"))
  print("I'm Ready!")
  print(client.user.name)
  print(client.user.id)
  
@client.event
async def on_message(message):
  if message.author.bot:
    return None
  
  if message.content == "!명령어":
    await message.channel.send("응답")
    await message.author.send("응답")
    
client.run(token) # Error has happened here
```

### Expected Results

I expected the bot to be turned online.

### Actual Results

```
Traceback (most recent call last):
  File "C:\Users\msw95\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\msw95\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\msw95\.vscode\extensions\ms-python.python-2020.3.69010\pythonFiles\lib\python\debugpy\wheels\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\msw95\.vscode\extensions\ms-python.python-2020.3.69010\pythonFiles\lib\python\debugpy\wheels\debugpy/..\debugpy\server\cli.py", line 427, in main
    run()
  File "c:\Users\msw95\.vscode\extensions\ms-python.python-2020.3.69010\pythonFiles\lib\python\debugpy\wheels\debugpy/..\debugpy\server\cli.py", line 264, in run_file
    runpy.run_path(options.target, run_name="__main__")
  File "C:\Users\msw95\anaconda3\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\msw95\anaconda3\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\msw95\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\msw95\Rene.py", line 24, in <module>
    client.run(token)
  File "C:\Users\msw95\anaconda3\lib\site-packages\discord\client.py", line 640, in run       
    return future.result()
  File "C:\Users\msw95\anaconda3\lib\site-packages\discord\client.py", line 621, in runner    
    await self.start(*args, **kwargs)
  File "C:\Users\msw95\anaconda3\lib\site-packages\discord\client.py", line 584, in start     
    await self.login(*args, bot=bot)
  File "C:\Users\msw95\anaconda3\lib\site-packages\discord\client.py", line 442, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\msw95\anaconda3\lib\site-packages\discord\http.py", line 261, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\msw95\anaconda3\lib\site-packages\discord\http.py", line 165, in request     
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Users\msw95\anaconda3\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Users\msw95\anaconda3\lib\site-packages\aiohttp\client.py", line 483, in _request
    timeout=real_timeout
  File "C:\Users\msw95\anaconda3\lib\site-packages\aiohttp\connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\msw95\anaconda3\lib\site-packages\aiohttp\connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "C:\Users\msw95\anaconda3\lib\site-packages\aiohttp\connector.py", line 953, in _create_direct_connection
    sslcontext = self._get_ssl_context(req)
  File "C:\Users\msw95\anaconda3\lib\site-packages\aiohttp\connector.py", line 901, in _get_ssl_context
    raise RuntimeError('SSL is not supported.')
RuntimeError: SSL is not supported.
```

### Checklist

- [ O ] I have searched the open issues for duplicates.
- [ O ] I have shown the entire traceback, if possible.
- [ O ] I have removed my token from display, if visible.

### System Information

Windows 10
Python 3.7.6
Discord.py 1.3.2

**Comment by gogurtenjoyer** [comment]
This SSL issue is common with the Anaconda distribution of python - install the standard python from python.org and then install discord.py to this python - that should work fine.
