### ISSUE TITLE
bug report: the botping does not work

### ISSUE THREAD

**Issue by thegame4craft** [Rapptz/discord.py#2628]
The Bot ping function doesn't work 

my code (not the main):

```
from discord.ext import commands
import discord

bot = commands.Bot(command_prefix='!')


@commands.command()
async def ping(ctx):
    bping = bot.latency * 1000
    n_ping = round(bping)
    await ctx.send(bping)
```

my Error:

```
Ignoring exception in command ping:
nan
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\***\PycharmProjects\new-bot\cmds\nütz\cmd_ping.py", line 11, in ping
    n_ping = round(bping)
ValueError: cannot convert float NaN to integer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: cannot convert float NaN to integer


```

**Comment by IAmTomahawkx** [comment]
This is not an issue with discord.py.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api)

**Comment by Rapptz** [comment]
This is an error with your code.

`round` doesn't allow `NaN` which is a possible value of `Bot.latency` (as documented).
