### ISSUE TITLE
ValueError on GUILD_MEMBER_REMOVE

### ISSUE THREAD

**Issue by Hornwitser** [Rapptz/discord.py#29]
It's possible to receive a GUILD_MEMBER_REMOVE for a member that has not been present in the guilds.members array in the READY event and for which no GUILD_MEMBER_ADD has been received for.  Resulting in `ValueError` being raised with the following traceback.

    Traceback (most recent call last):
      File "bot.py", line 345, in <module>
        bot.run()
      File "/home/julian/prog/record/logger/discord/client.py", line 560, in run
        self.ws.run()
      File "/usr/lib/python3.5/site-packages/ws4py/websocket.py", line 427, in run
        if not self.once():
      File "/usr/lib/python3.5/site-packages/ws4py/websocket.py", line 305, in once
        if not self.process(b):
      File "/usr/lib/python3.5/site-packages/ws4py/websocket.py", line 377, in process
        self.received_message(s.message)
      File "/home/julian/prog/record/logger/discord/client.py", line 133, in received_message
        self.dispatch('socket_update', event, data)
      File "/home/julian/prog/record/logger/discord/client.py", line 537, in dispatch
        getattr(self, handle_method, _null_event)(*args, **kwargs)
      File "/home/julian/prog/record/logger/discord/client.py", line 545, in handle_socket_update
        getattr(self.connection, method)(data)
      File "/home/julian/prog/record/logger/discord/client.py", line 311, in handle_guild_member_remove
        server.members.remove(member)
    ValueError: list.remove(x): x not in list

This was encountered on commit 5efddaf of the develop branch.

[WebSocket context](http://hornwitser.no/discord/query?query=SELECT+*+FROM+message+WHERE+raw+LIKE+%27%2597778769732849664%25%27+AND+id+%3C+503679+ORDER+BY+id+DESC+LIMIT+20)

**Comment by Rapptz** [comment]
Should be fixed in 60dfd044395e7cf65a1d44c795eb43258cde83bf
