### ISSUE TITLE
create_ffmpeg_player stream randomly disconnects with "OSError Network Unreachable", does not pass this error to onerror, simply stops playing.

### ISSUE THREAD

**Issue by Insidious611** [Rapptz/discord.py#291]
I'm trying to write a bot to connect an icecast stream to a discord voice channel, and while it has mostly gone okay, occasionally the voice connection from the bot seems to disconnect with a random "OSError Network Unreachable". I have a command in my bot where I can interactively stop and then start the create_ffmpeg_player stream, and this fixes it, but since I can't find a way to "catch" this OSError exception (it doesn't trigger the on_error handler) I can't automatically deal with this situation.

```
The traceback is below:
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/dmorrison/.local/lib/python3.5/site-packages/discord/voice_client.py", line 150, in run
    super().run()
  File "/home/dmorrison/.local/lib/python3.5/site-packages/discord/voice_client.py", line 108, in run
    self.player(data)
  File "/home/dmorrison/.local/lib/python3.5/site-packages/discord/voice_client.py", line 655, in play_audio
    sent = self.socket.sendto(packet, (self.endpoint_ip, self.voice_port))
OSError: [Errno 101] Network is unreachable
```

**Comment by someunknownperson** [comment]
look in #292.

**Comment by Rapptz** [comment]
Chances are I won't pass this over to the `on_error` handler. Instead I'll probably catch it and discard it, i.e. a dropped packet. I'll keep this open as a reminder.
