### ISSUE TITLE
"Unclosed client session" error

### ISSUE THREAD

**Issue by AMVPh34r** [Rapptz/discord.py#329]
I searched around a bit and saw some similar issues but the most definitive answer seemed to be "there's an error in your bot's code." However I'm getting this error even trying to run the example programs provided in the repository (edit: looking at it now it seems to be due to the TypeError in gateway.py). Here's the traceback:
```
Traceback (most recent call last):
  File "./sample.py", line 67, in <module>
    bot.run(TOKEN)
  File "/home/alex/.local/lib/python3.5/site-packages/discord/client.py", line 487, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/alex/.local/lib/python3.5/site-packages/discord/client.py", line 459, in start
    yield from self.connect()
  File "/home/alex/.local/lib/python3.5/site-packages/discord/client.py", line 412, in connect
    self.ws = yield from DiscordWebSocket.from_client(self)
  File "/home/alex/.local/lib/python3.5/site-packages/discord/gateway.py", line 174, in from_client
    ws = yield from websockets.connect(gateway, loop=client.loop, klass=cls)
  File "/home/alex/.local/lib/python3.5/site-packages/websockets/py35/client.py", line 19, in __await__
    return (yield from self.client)
  File "/home/alex/.local/lib/python3.5/site-packages/websockets/client.py", line 160, in connect
    factory, wsuri.host, wsuri.port, **kwds)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 713, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 725, in _create_connection_transport
    protocol = protocol_factory()
  File "/home/alex/.local/lib/python3.5/site-packages/websockets/client.py", line 156, in <lambda>
    loop=loop, legacy_recv=legacy_recv,
  File "/home/alex/.local/lib/python3.5/site-packages/discord/gateway.py", line 158, in __init__
    super().__init__(*args, max_size=None, **kwargs)
TypeError: __init__() got multiple values for keyword argument 'max_size'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd109f74f98>
```
I'm not entirely sure what causes the "__init__() got multiple values for keyword argument 'max_size'" error but that seems to be breaking things.
I can provide any other needed info but to answer the general questions: I'm running python 3.5, have all the listed requirements installed, and copy-pasted the "basic_bot" example verbatim, only adding in my token as a constant and passing that to `bot.run()` instead.

**Comment by SunDwarf** [comment]
Update your lib.

**Comment by Kiseii** [comment]
^

**Comment by AMVPh34r** [comment]
I just installed everything fresh so it should all be up to date

**Comment by adongy** [comment]
Are you running master or latest pip version ?

**Comment by AMVPh34r** [comment]
Installed via pip, so I'm assuming that's up to date with master. My pip version is 8.1.1 and while I get notification that 8.1.2 is the latest, it doesn't seem to want to update. I don't imagine that's a big enough version difference to cause this problem but I could be wrong?

**Comment by SunDwarf** [comment]
Ah, yes, this fix isn't in the PyPI release yet.

Try `pip install -U websockets==3.1`.

**Comment by AMVPh34r** [comment]
`Requirement already up-to-date: websockets==3.1 in /home/alex/.local/lib/python3.5/site-packages`
Seems to be fine there as well, hmm

**Comment by adongy** [comment]
By master I meant master for discord.py, not pip itself

**Comment by SunDwarf** [comment]
In this case, you'll need to install directly from master until the fix is uploaded to PyPI.

`pip install -U git+https://github.com/Rapptz/discord.py.git`

**Comment by AMVPh34r** [comment]
@adongy Sorry, that's what I meant (discord.py is up to date with pypi which I assumed matched master, pip is almost up to date), could have worded it better I suppose.

@SunDwarf Great, thanks! Seems to be working fine now!

**Comment by Tobsta** [comment]
Hey, I'm having this error too. No changes to my code are fixing it. Is the latest version of discord.py supposed to fix this? (my installation is the latest version available on pip) I can't use @SunDwarf 's command because I don't have git. Is there any other way to fix this problem?
