### ISSUE TITLE
Lib seems to fail parsing members if a guild is actually unavailable

### ISSUE THREAD

**Issue by SunDwarf** [Rapptz/discord.py#336]
If a server is unavailable due to an outage or something similar, the bot will fail to load due to an AttributeError on the server object.

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "discord/state.py", line 179, in _delay_ready
    chunks.extend(self.chunks_needed(server))
  File "discord/state.py", line 162, in chunks_needed
    for chunk in range(math.ceil(server._member_count / 1000)):
AttributeError: _member_count
```

**Comment by Rapptz** [comment]
As a reminder to myself, this only happens for user bots. There is a fix in which you don't assume member_count is there in general for the unavailable packet.

**Comment by Rapptz** [comment]
This *should* be fixed in https://github.com/Rapptz/discord.py/commit/a0f4ad36eb0e4c82162c1ee571543c13b9a74bfd. I haven't seen an unavailable guild to test. Feel free to re-open if it isn't.

**Comment by ItsiAdam** [comment]
This doesn't seem to be fixed, I joined BetterDiscord which is offline 24/7 and got a similar error.

```Task exception was never retrieved
future: <Task finished coro=<ConnectionState._delay_ready() done, defined at C:\Users\Adam\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\state.py:166> exception=AttributeError('_member_count',)>
Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\state.py", line 180, in _delay_ready
    chunks.extend(self.chunks_needed(server))
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\state.py", line 163, in chunks_needed
    for chunk in range(math.ceil(server._member_count / 1000)):
AttributeError: _member_count
```

**Comment by Rapptz** [comment]
@ItsiAdam Missing version info.

As far as I'm aware this bug has been fixed for a long time.
