### ISSUE TITLE
Client.run with email + password fails ungracefully when account is using two factor authentication

### ISSUE THREAD

**Issue by e00E** [Rapptz/discord.py#364]
If I disable two factor authentication on my account the run function works just fine with my supplied email and password.
If enable it however I get an ugly exception:

```
python bot.py
Traceback (most recent call last):
  File "bot.py", line 43, in <module>
    client.run('email', password')
  File "C:\Users\username\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 485, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "C:\Users\username\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 337, in run_until_com
plete
    return future.result()
  File "C:\Users\username\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\username\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\username\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 456, in star
t
    yield from self.login(*args, **kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 382, in logi
n
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "C:\Users\username\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 340, in _log
in_2
    self._update_cache(email, password)
  File "C:\Users\username\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 191, in _upd
ate_cache
    f.write(self.http.token)
TypeError: write() argument must be str, not None
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001A8E1A66BA8>
```
It would be perfect if discord.py supported two factor authentication or at least failed gracefully.

**Comment by Rapptz** [comment]
I was specifically asked not to support the 2fa endpoints.

On that note, use the `bot.run('token', bot=False)` approach instead of using email + password combo.

**Comment by ccubed** [comment]
It does support 2fa. What it doesn't do is support logins using an email and password.

**Comment by e00E** [comment]
@Rapptz Could you elaborate who asked you and with what reasons? I am interested,
@ccubed Are you sure? The documentation http://discordpy.readthedocs.io/en/latest/api.html#discord.Client.login makes it look like email + password should work.

**Comment by Ayyko** [comment]
https://github.com/hammerandchisel/discord-api-docs/issues/69#issuecomment-223886862

**Comment by e00E** [comment]
Thanks for that link Ayyko, it also explains how to get the token for your real two factor enabled account and with that and bot=False it worked.

After all I feel like it would still be nice to update the documentation and error message to reflect that two factor login is intentionally not supported @Rapptz.

**Comment by NNTin** [comment]
Thanks, e00E. I had the same problem.  
I know v1.0.0.0 is not out but when it is released please put it in the documentation and/or update error message.
