### ISSUE TITLE
Attribute errors

### ISSUE THREAD

**Issue by GildaGriffon** [Rapptz/discord.py#369]
Traceback (most recent call last):
  File "discord.py", line 1, in <module>
    import discord
  File "C:\Users\User\Desktop\discord bot\discord.py", line 3, in <module>
    client = discord.Client()
AttributeError: module 'discord' has no attribute 'Client'

**Comment by Helehelehele** [comment]
Change your file name from `discord.py` to something else.

**Comment by GildaGriffon** [comment]
Im a fucking idiot
