### ISSUE TITLE
discord.errors.LoginFailure: Improper credentials have been passed.

### ISSUE THREAD

**Issue by ButterCheezii** [Rapptz/discord.py#373]
This exact file and configuration works on my local laptop, but upon attempting to run it on my server I get this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 180, in email_login
    data = yield from self.post(self.LOGIN, json=payload, bucket=_func_())
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "core.py", line 113, in <module>
    bot.run('email', 'password', bot = False)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 485, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 456, in start
    yield from self.login(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 382, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 333, in _login_2
    yield from self.http.email_login(email, password)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 183, in email_login
    raise LoginFailure('Improper credentials have been passed.') from e
discord.errors.LoginFailure: Improper credentials have been passed.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xMEMORYADDRES>
```

Can you please help me figure out what is causing the problem and how to fix it?

**Comment by fennekid** [comment]
Use a token login by typing `localStorage.token` into the console (ctrl+shift+i)
Using a email and password requires a verification email when signing on from a new IP address, but using a token ignores this. Its also why it worked on one device and not another.
