### ISSUE TITLE
logs_from broken (Argument should be str)

### ISSUE THREAD

**Issue by Tsumiki-Chan** [Rapptz/discord.py#386]
The way logs_from should be working doesn't work anymore.

```
Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/server.py", line 265, in start
    yield from self.handle_request(message, payload)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web.py", line 96, in handle_request
    resp = yield from handler(request)
  File "/home/tsumiki/NekoChanv2/modules/Webserver.py", line 79, in s_messages
    async for message in self.bot.logs_from(channel, limit=20):
  File "/usr/local/lib/python3.5/dist-packages/discord/iterators.py", line 173, in __anext__
    msg = yield from self.iterate()
  File "/usr/local/lib/python3.5/dist-packages/discord/iterators.py", line 115, in iterate
    yield from self.fill_messages()
  File "/usr/local/lib/python3.5/dist-packages/discord/iterators.py", line 123, in fill_messages
    data = yield from self._retrieve_messages(retrieve)
  File "/usr/local/lib/python3.5/dist-packages/discord/iterators.py", line 141, in _retrieve_messages_before_strategy
    data = yield from self.client._logs_from(self.channel, retrieve, before=self.before)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 105, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 548, in __iter__
    resp = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 198, in _request
    proxy=proxy, proxy_auth=proxy_auth, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client_reqrep.py", line 79, in __init__
    url2 = url.with_query(params)
  File "/usr/local/lib/python3.5/dist-packages/yarl/__init__.py", line 607, in with_query
    for k, v in query.items())
  File "/usr/local/lib/python3.5/dist-packages/yarl/__init__.py", line 607, in <genexpr>
    for k, v in query.items())
  File "yarl/_quoting.pyx", line 46, in yarl._quoting._quote (yarl/_quoting.c:1384)
TypeError: Argument should be str
```

Line causing the error on my side:
`async for message in self.bot.logs_from(channel, limit=20):`

**Comment by SunDwarf** [comment]
Known issue, see #384.

To work around it, just downgrade your aiohttp to 1.0.5 ala `pip install -U aiohttp==1.0.5`.

**Comment by Tsumiki-Chan** [comment]
Well, I can't atm as that will break other libs (in the current state)

See: https://github.com/Rapptz/discord.py/pull/384

**Comment by SunDwarf** [comment]
???

**Comment by Tsumiki-Chan** [comment]
Whoops, sorry, that should have went to aiohttp.

**Comment by Tsumiki-Chan** [comment]
Closing this as yarl==07.0 seems to have fixed it ¯\_(ツ)_/¯
