### ISSUE TITLE
Unable to send to Discord BAD REQUEST 400

### ISSUE THREAD

**Issue by nEo-1664** [Rapptz/discord.py#389]
I can browse to the discordapp website fine, and login via app or browser without a problem on the same workstation, but running discord.py trying to post an RSS feed summary to a channel I get the following:

DEBUG:discord.http:POST https://discordapp.com/api/v6/channels/status/messages with {"content":"Server Titan (Online) Players 26 (2%) Updated 08 Nov 2016 21:45 (UTC)\n","nonce":1858434292372827337} has returned 400
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<actually_send_message() done, defined at feed2discord.py:306> exception=HTTPException('BAD REQUEST (status code: 400)',) created at feed2discord.py:302>
source_traceback: Object created at (most recent call last):
  File "feed2discord.py", line 698, in <module>
    loop.run_until_complete(client.connect())
  File "C:\Program Files\Python35\lib\asyncio\base_events.py", line 375, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python35\lib\asyncio\base_events.py", line 345, in run_forever
    self._run_once()
  File "C:\Program Files\Python35\lib\asyncio\base_events.py", line 1304, in _run_once
    handle._run()
  File "C:\Program Files\Python35\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 307, in _wakeup
    self._step()
  File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "feed2discord.py", line 593, in background_check_feed
    message)
  File "C:\Program Files\Python35\lib\asyncio\coroutines.py", line 206, in coro
    res = func(*args, **kw)
  File "feed2discord.py", line 302, in send_message_wrapper
    actually_send_message(channel,message,delay,FEED,feed))
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "feed2discord.py", line 317, in actually_send_message
    yield from client.send_message(channel['object'],message)
  File "C:\Program Files\Python35\lib\site-packages\discord\client.py", line 1096, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts)
  File "C:\Program Files\Python35\lib\site-packages\discord\http.py", line 137, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)

**Comment by SunDwarf** [comment]
You're attempting to send a message to a channel with the id `status`...

Is `channel['object']` a channel you've created?

**Comment by Pandentia** [comment]
Also, make sure you're not trying to send something that's over 2000 characters. Discord doesn't seem to like that.

**Comment by 12dabbott** [comment]
This may or may not help, but I did have this same issue before and it was because I was forgot to send my json generator to my function that extracted the text from it, and instead sent it to discord chat

**Comment by Maverun** [comment]
what is  `channel['object]` and `message`?

also i think this is wrong place to ask to be honestly.

**Comment by Socialery** [comment]
hi chat

**Comment by SunDwarf** [comment]
Please don't shitpost on the issues @Socialery.

**Comment by Socialery** [comment]
please don't call out other users via issues @SunDwarf

**Comment by nEo-1664** [comment]
@SunDwarf the channel I'm trying to send it to is called "status", and it has been given allowed access to post into that channel. "channel['object']" is I'm assuming calling the channels to post into. It's not my script, it is feed2discord.py.

@Pandentia definitely not over 2000 chars.

**Comment by Rapptz** [comment]
You can't just pass a channel name and expect it to work. It needs to be a channel object or any of the things [documented that it accepts](http://discordpy.rtfd.io/en/latest/api.html#discord.Client.send_message). 

Check the [FAQ](http://discordpy.readthedocs.io/en/latest/faq.html) if you need help in actually getting a channel object from a name.
