### ISSUE TITLE
Opus problem

### ISSUE THREAD

**Issue by jbdo99** [Rapptz/discord.py#400]
Hello !
There is my problem : Opus doesn't want load !
This is the error : 
`Traceback (most recent call last):
  File "discordab.py", line 38, in <module>
    discord.opus.load_opus(OPUS_LIBS)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/discord/opus.py", line 124, in load_opus
    _lib = libopus_loader(name)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/discord/opus.py", line 60, in libopus_loader
    lib = ctypes.cdll.LoadLibrary(name)
  File "/opt/python/3.5.2/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/opt/python/3.5.2/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: Can't convert 'list' object to str implicitly
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2d229a1ba8>`
I test my code locally and by Travis.
This is the Github's link to my Bot : https://github.com/jbdo99/DiscordArmyBot

Thank's !

Jbdo99

**Comment by itslukej** [comment]
`discord.opus.load_opus()` accepts a str, not a list.

**Comment by GetRektByMe** [comment]
Remove `OPUS_LIBS` from `discord.opus.load_opus`. It'll find it for you, also get rid of the list since I assume that's it's only use

**Comment by jbdo99** [comment]
Ohh, I have an other problem ...

`Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "discordab.py", line 81, in on_message
    voice = yield from client.join_voice_channel(message.author.voice.voice_channel)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/discord/client.py", line 3115, in join_voice_channel
    voice = VoiceClient(**kwargs)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/discord/voice_client.py", line 226, in __init__
    self.encoder = opus.Encoder(48000, 2)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/discord/opus.py", line 190, in __init__
    raise OpusNotLoaded()
discord.opus.OpusNotLoaded`

Thank's 
Jbdo99

**Comment by GetRektByMe** [comment]
in .run of your bot do this
```py
if not discord.opus.is_loaded():
    discord.opus.load_opus()
```

**Comment by jbdo99** [comment]
In my code, I have already this : 
`def load_opus_lib():
    if opus.is_loaded():
        return True

    for opus_lib in opus_libs:
        try:
            opus.load_opus(opus_lib)
            return
        except OSError:
            pass`

Ok , I add that and I test

Jbdo99

**Comment by GetRektByMe** [comment]
By the way your token is shown in your repo, this should be kept secret. I'd regenerate it if I was you

**Comment by jbdo99** [comment]
Yes but do you have a solution to test my code with Travis and dont show the code  ?

Thank's
Jbdo99

**Comment by jbdo99** [comment]
Hey, and other problem !
`Traceback (most recent call last):
  File "discordab.py", line 52, in <module>
    discord.opus.load_opus()`

Jbdo99

**Comment by itslukej** [comment]
discord.gg/discord-api

**Comment by Oklomsy** [comment]
aaa

**Comment by Jacksxnn** [comment]
> in .run of your bot do this
> 
> ```python
> if not discord.opus.is_loaded():
>     discord.opus.load_opus()
> ```

so it would be
```python
client.run(if not discord.opus.is_loaded():
     discord.opus.load_opus()
```
but then where would your token go?
