### ISSUE TITLE
Player error: 'NoneType' object has no attribute 'read'

### ISSUE THREAD

**Issue by FightMan01** [Rapptz/discord.py#4003]
### Summary

I have a list with one YTDLSource object.
I've got an error when I'm trying to play it.
I asked it on the official discord server, and they said I should report it here.

### Reproduction Steps

Do this: `loop[str(ctx.guild.id)] = [ctx.voice_client.source]`
Then try to play it:
```py
player = loop[str(ctx.guild.id)][0]
music = ctx.voice_client.play(player)
```
Also, I'm added some print to it:
```py
print(f"Player: {player}")
print(f"voice: {ctx.voice_client}")
```

Print returns:
```
Player: <music.YTDLSource object at 0x11805b2e0>
voice: <discord.voice_client.VoiceClient object at 0x117f45850>
```

### Expected Results

It will play the music.

### Actual Results

It is showing me this traceback:
```
[15/Apr/2020 08:47:37] ERROR - Exception in voice thread Thread-5
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/player.py", line 598, in run
    self._do_run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/player.py", line 585, in _do_run
    data = self.source.read()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/player.py", line 538, in read
    ret = self.original.read()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/player.py", line 223, in read
    ret = self._stdout.read(OpusEncoder.FRAME_SIZE)
AttributeError: 'NoneType' object has no attribute 'read'
Exception in voice thread Thread-5
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/player.py", line 598, in run
    self._do_run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/player.py", line 585, in _do_run
    data = self.source.read()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/player.py", line 538, in read
    ret = self.original.read()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/player.py", line 223, in read
    ret = self._stdout.read(OpusEncoder.FRAME_SIZE)
AttributeError: 'NoneType' object has no attribute 'read'
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information
- Python v3.8.2-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v6.0
- system info: Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64

**Comment by FightMan01** [comment]
I discovered something. 
I ran this code immediately after a music stops. I see that the ffmpeg process terminates but it doesn't start an another process. 
Unfortunately I don't really know if this section is before or after the process start.
And it is still a problem in 1.4 alpha as well.

**Comment by guac420** [comment]
I get the same error when trying to loop a song using the music bot in this link:

https://gist.github.com/vbe0201/ade9b80f2d3b64643d854938d40a0a2d

I play a song and then loop it. When the song ends and should start again the error is thrown. 
The audio player in the bot is lines 233 - 259.

I'm sorry if this is repetitive information.

**Comment by Tsumiki-Chan** [comment]
Long story short:
Said error occurs when using the same `FFmpegPCMAudio` Object twice.

**Comment by alvinzzzzz** [comment]
@FightMan01 I have the exact same error did you find out how to solve it?

**Comment by imayhaveborkedit** [comment]
> 
> 
> Long story short:
> Said error occurs when using the same `FFmpegPCMAudio` Object twice.

Correct.  AudioSource objects cannot be reused.  You need to create a new one.

**Comment by alvinzzzzz** [comment]
@imayhaveborkedit Do you mind to explain how to creat4e a new audiocource object I am new to ffmpeg libary
