### ISSUE TITLE
AttributeError: _member_count

### ISSUE THREAD

**Issue by Cleanish** [Rapptz/discord.py#4008]
### Summary
Basically when particular user tokens try run the bot it throws out this Traceback (most recent call last) error
### Reproduction Steps
To reproduce this, you just need to find one of the usertokens that throws the Traceback, i obviously can't provide one for specific reasons but it's not all user tokens.
### Expected Results
The expected result is for the bot to load and function as it is suppose to, (Selfbot).
### Actual Results
What actually happened is that it returned a Traceback error when trying to i assume connect.

`Traceback (most recent call last):
  File "c:/Users/Caleb/Desktop/Sanitary Source/Maincopy.py", line 2253, in <module>
    Init()
  File "c:/Users/Caleb/Desktop/Sanitary Source/Maincopy.py", line 145, in Init
    Sanitary.run(token, bot=False, reconnect=True)
  File "C:\Users\Caleb\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 640, in run
    return future.result()
  File "C:\Users\Caleb\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\Caleb\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 585, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Caleb\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 499, in connect
    await self._connect()
  File "C:\Users\Caleb\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 463, in _connect
    await self.ws.poll_event()
  File "C:\Users\Caleb\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\gateway.py", line 471, in poll_event
    await self.received_message(msg)
  File "C:\Users\Caleb\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\gateway.py", line 425, in received_message
    func(data)
  File "C:\Users\Caleb\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\state.py", line 394, in parse_ready
    guild = self._add_guild_from_data(guild_data)
  File "C:\Users\Caleb\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\state.py", line 274, in _add_guild_from_data
    guild = Guild(data=guild, state=self)
  File "C:\Users\Caleb\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\guild.py", line 177, in __init__
    self._from_data(data)
  File "C:\Users\Caleb\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\guild.py", line 298, in _from_data
    self._large = None if member_count is None else self._member_count >= 250
AttributeError: _member_count`

### Checklist

- [x ] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [x ] I have removed my token from display, if visible.

### System Information
- Python v3.8.2-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.18362

**Comment by IAmTomahawkx** [comment]
Selfbotting is against TOS, and unsupported. If the library no longer works while selfbotting, oh well.

**Comment by Cleanish** [comment]
It isn't strictly Selfbots, Regular bots are also having this error!
