### ISSUE TITLE
client.run() AttributeError: module 'idna' has no attribute 'decode'

### ISSUE THREAD

**Issue by VidsSkids** [Rapptz/discord.py#4012]
### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by zomatree** [comment]
can you send the full traceback, your code along with your discord.py version, thanks

**Comment by VidsSkids** [comment]
When write my python code with all of my librairiy updated,
import discord
import asyncio

client = discord.Client()

@client.event
async def on_ready (self) :
    print('Logged on as {0}!'.format(self.user))

@client.event
async def on_message (self, message) :
    print('Message from {0.author}: {0.content}'.format(message))

client.run (******)
I have this error message : Traceback (most recent call last):
  File "D:\BOT\SELF-ENDERBOT\bot.py", line 12, in <module>
    client.run ("Njk5OTA2MDg3NzM4MTQ2OTA2.XpbMXA.y9Azd0yMyRXDOGUHjdKdvRPK3aE")
  File "D:\Program installé par nous\Python\lib\site-packages\discord\client.py", line 640, in run
    return future.result()
  File "D:\Program installé par nous\Python\lib\site-packages\discord\client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "D:\Program installé par nous\Python\lib\site-packages\discord\client.py", line 584, in start
    await self.login(*args, bot=bot)
  File "D:\Program installé par nous\Python\lib\site-packages\discord\client.py", line 442, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "D:\Program installé par nous\Python\lib\site-packages\discord\http.py", line 261, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "D:\Program installé par nous\Python\lib\site-packages\discord\http.py", line 165, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "D:\Program installé par nous\Python\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "D:\Program installé par nous\Python\lib\site-packages\aiohttp\client.py", line 464, in _request
    req = self._request_class(
  File "D:\Program installé par nous\Python\lib\site-packages\aiohttp\client_reqrep.py", line 285, in __init__
    self.update_host(url)
  File "D:\Program installé par nous\Python\lib\site-packages\aiohttp\client_reqrep.py", line 338, in update_host
    if not url.host:
    val = self.wrapped(inst)
  File "D:\Program installé par nous\Python\lib\site-packages\yarl\__init__.py", line 454, in host
    return idna.decode(raw.encode("ascii"))
AttributeError: module 'idna' has no attribute 'decode'
PS C:\Users\vicma> d:\BOT\SELF-ENDERBOT\bot.py
Traceback (most recent call last):
  File "D:\BOT\SELF-ENDERBOT\bot.py", line 14, in <module>
    client.run ("Njk5OTA2MDg3NzM4MTQ2OTA2.XpbMXA.y9Azd0yMyRXDOGUHjdKdvRPK3aE")
  File "D:\Program installé par nous\Python\lib\site-packages\discord\client.py", line 640, in run
    return future.result()
  File "D:\Program installé par nous\Python\lib\site-packages\discord\client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "D:\Program installé par nous\Python\lib\site-packages\discord\client.py", line 584, in start
    await self.login(*args, bot=bot)
  File "D:\Program installé par nous\Python\lib\site-packages\discord\client.py", line 442, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "D:\Program installé par nous\Python\lib\site-packages\discord\http.py", line 261, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "D:\Program installé par nous\Python\lib\site-packages\discord\http.py", line 165, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "D:\Program installé par nous\Python\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "D:\Program installé par nous\Python\lib\site-packages\aiohttp\client.py", line 464, in _request
    req = self._request_class(
  File "D:\Program installé par nous\Python\lib\site-packages\aiohttp\client_reqrep.py", line 285, in __init__
    self.update_host(url)
  File "D:\Program installé par nous\Python\lib\site-packages\aiohttp\client_reqrep.py", line 338, in update_host
    if not url.host:
  File "D:\Program installé par nous\Python\lib\site-packages\yarl\__init__.py", line 46, in __get__
    val = self.wrapped(inst)
  File "D:\Program installé par nous\Python\lib\site-packages\yarl\__init__.py", line 454, in host
    return idna.decode(raw.encode("ascii"))
AttributeError: module 'idna' has no attribute 'decode'
Help me plz and thanks in advance

**Comment by Soheab** [comment]
Regen your token.

**Comment by VidsSkids** [comment]
I already try it and nothing change same issue
