### ISSUE TITLE
Module crashes on deleted emoji when retrieving message

### ISSUE THREAD

**Issue by MvonK** [Rapptz/discord.py#4020]
### Summary
I am writing a bot, that will simply download all messages in a channel. Issue came, when I used `async for message in target_channel.history(limit=None, oldest_first=True):` and this loop came to a message, that had a deleted emoji as reaction. That emoji once existed, people reacted with it, but the it got deleted and the client crashes on it.

### Reproduction Steps

Send a few messages, create custom emoji, react with this emoji on a message.  Delete the emoji in settings, then call `channel.history().flatten()` and the module will crash.

### Expected Results
Not to crash

### Actual Results

`Ignoring exception in command gather:
Traceback (most recent call last):
  File "D:\Program Files (x86)\python\lib\site-packages\discord\state.py", line 891, in get_reaction_emoji
    return self._emojis[emoji_id]
KeyError: 701392904329101342

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\python\lib\site-packages\discord\ext\commands\core.py", line 63, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\personal\notimportnant\programovanie\Teenbot\Teenbot.py", line 36, in messages_gather
    async for message in target_channel.history(limit=None, oldest_first=True):
  File "D:\Program Files (x86)\python\lib\site-packages\discord\iterators.py", line 86, in __anext__
    msg = await self.next()
  File "D:\Program Files (x86)\python\lib\site-packages\discord\iterators.py", line 262, in next
    await self.fill_messages()
  File "D:\Program Files (x86)\python\lib\site-packages\discord\iterators.py", line 319, in fill_messages
    await self.messages.put(self.state.create_message(channel=channel, data=element))
  File "D:\Program Files (x86)\python\lib\site-packages\discord\state.py", line 918, in create_message
    return Message(state=self, channel=channel, data=data)
  File "D:\Program Files (x86)\python\lib\site-packages\discord\message.py", line 223, in __init__
    self.reactions = [Reaction(message=self, data=d) for d in data.get('reactions', [])]
  File "D:\Program Files (x86)\python\lib\site-packages\discord\message.py", line 223, in <listcomp>
    self.reactions = [Reaction(message=self, data=d) for d in data.get('reactions', [])]
  File "D:\Program Files (x86)\python\lib\site-packages\discord\reaction.py", line 70, in __init__
    self.emoji = emoji or message._state.get_reaction_emoji(data['emoji'])
  File "D:\Program Files (x86)\python\lib\site-packages\discord\state.py", line 893, in get_reaction_emoji
    return PartialEmoji(animated=data['animated'], id=emoji_id, name=data['name'])
KeyError: 'animated'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files (x86)\python\lib\site-packages\discord\ext\commands\bot.py", line 860, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Program Files (x86)\python\lib\site-packages\discord\ext\commands\core.py", line 698, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Program Files (x86)\python\lib\site-packages\discord\ext\commands\core.py", line 72, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'animated'`

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

python -m discord -v
discord.py v1.0.1 for Python 3.8.1

**Comment by Soheab** [comment]
This is fixed in discord.py 1.2.5 and above, latest is 1.3.3. See all changes (none breaking) and fixes in the changelog since 1.0.1 [here](https://discordpy.readthedocs.io/en/latest/whats_new.html)

**Comment by MvonK** [comment]
Oh I am sorry, I tried to update the package via `pip install discord` but it didn't update for some reason so I thought I have the latest version. I have manually deleted and installed module again, and it works with the newest version. Thanks

**Comment by Soheab** [comment]
> Oh I am sorry, I tried to update the package via `pip install discord` but it didn't update for some reason so I thought I have the latest version. I have manually deleted and installed module again, and it works with the newest version. Thanks

it's discord.py and you should use the --upgrade thing.

**Comment by tailoric** [comment]
Another note the `discord` package is a mirror package that only goes to 1.0.1
And it even says on the pypi website

> It is recommended to install discord.py instead.

https://pypi.org/project/discord/
