### ISSUE TITLE
WebSocket connection is closed: code = 4004 (private use), reason = Authentication failed.

### ISSUE THREAD

**Issue by eljequercin** [Rapptz/discord.py#4027]
### Summary

Hello I have make a bot and seems to works good but after a time working it suddenly stops with this error:

Traceback (most recent call last):
  File "/home/diego_cuenca_prieto/.local/lib/python3.5/site-packages/discord/gateway.py", line 470, in poll_event
    msg = await self.recv()
  File "/home/diego_cuenca_prieto/.local/lib/python3.5/site-packages/websockets/protocol.py", line 350, in recv
    yield from self.ensure_open()
  File "/home/diego_cuenca_prieto/.local/lib/python3.5/site-packages/websockets/protocol.py", line 512, in ensure_o
pen
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4004 (private use), reason = Authent
ication failed.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "BOT.py", line 229, in <module>
    client.run(TOKEN)
  File "/home/diego_cuenca_prieto/.local/lib/python3.5/site-packages/discord/client.py", line 640, in run
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/diego_cuenca_prieto/.local/lib/python3.5/site-packages/discord/client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "/home/diego_cuenca_prieto/.local/lib/python3.5/site-packages/discord/client.py", line 585, in start
    await self.connect(reconnect=reconnect)
  File "/home/diego_cuenca_prieto/.local/lib/python3.5/site-packages/discord/client.py", line 499, in connect
    await self._connect()
  File "/home/diego_cuenca_prieto/.local/lib/python3.5/site-packages/discord/client.py", line 463, in _connect
    await self.ws.poll_event()
  File "/home/diego_cuenca_prieto/.local/lib/python3.5/site-packages/discord/gateway.py", line 478, in poll_event
    raise ConnectionClosed(exc, shard_id=self.shard_id) from exc
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4004 (private use), reason = Authentication
 failed.

And when I reload it:

  File "BOT.py", line 229, in <module>
    client.run(TOKEN)
  File "/home/diego_cuenca_prieto/.local/lib/python3.5/site-packages/discord/client.py", line 640, in run
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/diego_cuenca_prieto/.local/lib/python3.5/site-packages/discord/client.py", line 621, in runner
    await self.start(*args, **kwargs)
  File "/home/diego_cuenca_prieto/.local/lib/python3.5/site-packages/discord/client.py", line 584, in start
    await self.login(*args, bot=bot)
  File "/home/diego_cuenca_prieto/.local/lib/python3.5/site-packages/discord/client.py", line 442, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "/home/diego_cuenca_prieto/.local/lib/python3.5/site-packages/discord/http.py", line 265, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.

It is hosted in a google cloud server

**Comment by Rapptz** [comment]
The token you're logging in with is invalid.
