### ISSUE TITLE
Bot isnt starting

### ISSUE THREAD

**Issue by mrxbox98** [Rapptz/discord.py#4031]
### Summary

When i start the bot (i alaready put the token and other stuff) i get animated error

### Reproduction Steps

run bot
### Expected Results

works

### Actual Results

doesnt work

Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 568, in run
    return task.result()
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\ASUS\AppData\Roaming\Python\Python36\site-packages\discord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'

### Checklist

- [x ] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [x ] I have removed my token from display, if visible.

### System Information

discord.py v1.0.0a for Python 3.6.5

**Comment by zomatree** [comment]
#2422

**Comment by mrxbox98** [comment]
@zomatree There is no emoji

**Comment by zomatree** [comment]
You are using an outdated version, update. plus this only happens when a reaction is added (pretty likely as your user-botting - you shouldn't)

**Comment by mrxbox98** [comment]
wut is user botting

**Comment by mrxbox98** [comment]
also found it this is the wrong discord bot
