### ISSUE TITLE
Executing a webhook with attachments fails if the per-channel ratelimit has been exhausted

### ISSUE THREAD

**Issue by RocketRace** [Rapptz/discord.py#4037]
### Summary

Refer to #2272 and potentially also #4026.

When sending messages using a webhook, after the 30 messages / 60 seconds per-channel rate limit has been exhausted, trying to execute the webhook again triggers a 429 HTTP response. _Internally,_ after waiting for the `retry_after` to elapse, trying to re-send the request triggers a `aiohttp.client_exceptions.ClientOSError: [Errno 54] Connection reset by peer` (Likely analogous to `[Errno 104] Connection reset by peer`), _if_ the message contains any attachments.

Note that this only applies for non-empty attachments (at least 1 byte in length).

### Reproduction Steps

Minimal reproduction steps:
```py
for i in range(30):
   await webhook.send(f"Message #{i}")
file = discord.File("foo")
await webhook.send(f"Message #30", file=file)
```

### Expected Results

The first 30 messages are sent as expected. The message with attachments is successfully sent after waiting for the per-channel rate limit to be refreshed.

### Actual Results

The first 30 messages are sent successfully. The bot then encounters a 429 sending the last messafe, and waits until the cooldown elapses. It tries to re-send the message, which results in the following traceback:

Traceback:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/client.py", line 317, in _run_event
    await coro(*args, **kwargs)
  File "bugtest.py", line 16, in on_ready
    await webhook.send(f"Message #30", file=file)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/webhook.py", line 231, in handle_execution_response
    data = await response
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/webhook.py", line 112, in _wrap_coroutine_and_cleanup
    return await coro
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/webhook.py", line 196, in request
    async with self.session.request(verb, url, headers=headers, data=data) as r:
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 54] Connection reset by peer
```

Here is a dump of the logs for the minimal reproduction code in DEBUG level. This specific bot has only access to one guild, channel and user to minimize noise in the logs.

https://hastebin.com/lowilegoja.php

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### System Information

- Python v3.8.2-final
- discord.py v1.4.0-alpha
    - discord.py pkg_resources: v1.4.0a2308+ge473f3c
- aiohttp v3.6.2
- websockets v8.1
- system info: Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64

**Comment by RocketRace** [comment]
Note that the following snippet that manually waits until the bucket is refreshed does _not_ trigger this error:

```py
import asyncio
import discord
import logging
from datetime import datetime, timedelta
from json import load

from discord.ext import tasks

client = discord.Client()
cfg = load(open("cfg.json"))
logging.basicConfig(filename="log.txt", level=logging.DEBUG)

@client.event
async def on_ready():
    webhook = await client.fetch_webhook(cfg["webhook"])
    wait_until = datetime.now() + timedelta(minutes=1)
    for i in range(30):
        await webhook.send(f"Message #{i}")
    try:
        time_remaining = (wait_until - datetime.now()).total_seconds()
        await asyncio.sleep(time_remaining)
        file = discord.File("foo")
        await webhook.send(f"Message #30", file=file)
    finally:
        await client.logout()

client.run(cfg["token"])
```
<img width="681" alt="image" src="https://user-images.githubusercontent.com/35444188/80444121-d35f1d80-894b-11ea-9628-f7b18df866b1.png">

So it is the act of receiving a 429 and re-trying after a timeout that triggers the error.

**Comment by RocketRace** [comment]
As of 425bb80, webhooks are logged. The issue still persists, with the following logs:

https://mystb.in/ReggaeRegressionLists.sql

The ratelimits are handled as expected. Afterwards, the entire client session crashes, producing no logs but the following traceback:

```py
File "/Users/-/Code/Python/bugtest/.venv/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "test.py", line 17, in on_ready
    await webhook.send(f"Message 30", file=file)
  File "/Users/-/Code/Python/bugtest/.venv/lib/python3.8/site-packages/discord/webhook.py", line 251, in handle_execution_response
    data = await response
  File "/Users/-/Code/Python/bugtest/.venv/lib/python3.8/site-packages/discord/webhook.py", line 117, in _wrap_coroutine_and_cleanup
    return await coro
  File "/Users/-/Code/Python/bugtest/.venv/lib/python3.8/site-packages/discord/webhook.py", line 206, in request
    async with self.session.request(verb, url, headers=headers, data=data) as r:
  File "/Users/-/Code/Python/bugtest/.venv/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/Users/-/Code/Python/bugtest/.venv/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/Users/-/Code/Python/bugtest/.venv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/Users/-/Code/Python/bugtest/.venv/lib/python3.8/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 54] Connection reset by peer
```

**Comment by Rapptz** [comment]
I tried this in the newest commit in master and could no longer reproduce. Please let me know if you can reproduce this issue.

**Comment by RocketRace** [comment]
Resolved in master. The 429 is handled gracefully.
