### ISSUE TITLE
KeyError: 'animated' but discord.py is 1.2.5

### ISSUE THREAD

**Issue by xhBIROhx** [Rapptz/discord.py#4081]
### Summary

i still have the KeyError 'animated' error but i updated everything (i think)

### Reproduction Steps

my versions:
wheel: newest
setuptools: newest
pip: newest
discord.py: 1.2.5 (tryied newest)
i ran:
python -m pip install --upgrade pip setuptools wheel
and after:
pip install discord.py==1.2.5
have git the newest ()
python 1.6.0 added to PATH

and after I installed all the things and everything, I also redid the config and just simply started the "run.bat" an error!

### Expected Results

that the bot starts... maybe I'm having the same issue for days (2 days)

### Actual Results

                      .__   ________.           __
          ______ ____ |  |_/ ____\_ |__   _____/  |_
         /  ___// __ \|  |\   __\ | __ \ /  _ \   __\
         \___ \\  ___/|  |_|  |   | \_\ (  <_> )  |
        /____  >\___  >____/__|   |___  /\____/|__|
             \/     \/                \/
                        ___.
                        \_ |__ ___.__.
                         | __ <   |  |
                         | \_\ \___  |
                         |___  / ____|
                             \/\/
                           ____________  ________  ________
_____  ______ ______  __ _/_   \_____  \ \_____  \ \_____  \
\__  \ \____ \\____ \|  |  \   |/  ____/   _(__  <  /  ____/
 / __ \|  |_> >  |_> >  |  /   /       \  /       \/       \
(____  /   __/|   __/|____/|___\_______ \/______  /\_______ \
     \/|__|   |__|                     \/       \/         \/

Requirements satisfied.
Starting the bot (this may take a minute or two)...
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 568, in run
    return task.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 568, in run
    return task.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 568, in run
    return task.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 568, in run
    return task.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 568, in run
    return task.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 568, in run
    return task.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 568, in run
    return task.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 568, in run
    return task.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 568, in run
    return task.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 568, in run
    return task.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 568, in run
    return task.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'
Traceback (most recent call last):
  File "appuselfbot.py", line 926, in <module>
    bot.run(token, bot=False)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 568, in run
    return task.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 488, in _silence_gathered
    fut.result()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 476, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 398, in connect
    await self._connect()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\client.py", line 361, in _connect
    await self.ws.poll_event()
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 444, in poll_event
    await self.received_message(msg)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\gateway.py", line 398, in received_message
    func(data)
  File "C:\Users\xhBIROhx\AppData\Roaming\Python\Python36\site-packages\discord\state.py", line 386, in parse_message_reaction_add
    emoji = PartialEmoji(animated=emoji_data['animated'], id=emoji_id, name=emoji_data['name'])
KeyError: 'animated'

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.6.0-final
- discord.py v1.2.5-final
- aiohttp v3.3.2
- websockets v6.0
- system info: Windows 10 10.0.17763

pls answer don't just say "DUPLICATE" and close this because I have tried the post (https://github.com/Rapptz/discord.py/issues/2422) and it just not happening.. maybe i am doing something wrong.

**Comment by Rapptz** [comment]
In order to update the library you need to do so within the interpreter you use. That is, if you're invoking python with `py -3 mybot.py` then you use `py -3 -m pip install -U discord.py` to update. Make sure that your interpreter's library is up to date. Based on the issue body you're running either on multiple interpreters or multiple library versions.

This issue was already fixed. Opening another issue that is a duplicate is not the proper way to do this. If you need help consider joining the official guild instead at https://discord.gg/dpy

Note however that self-bots are generally discouraged and are provided as-is with no guarantee of working.
