### ISSUE TITLE
"extension does not have a setup function" when extension has setup function

### ISSUE THREAD

**Issue by ButterCheezii** [Rapptz/discord.py#412]
My bot keeps raising this error:
```
[modules.watcher   ] 12/09/16 03:04:26:642 AM Module modules.debug was modified
[lib.cogs          ] 12/09/16 03:04:26:643 AM Unloading module modules.debug
[lib.cogs          ] 12/09/16 03:04:26:644 AM Loading module modules.debug
[lib.cogs          ] 12/09/16 03:04:26:645 AM Module modules.debug failed to load on try 1, trying again
[lib.cogs          ] 12/09/16 03:04:26:646 AM Module modules.debug failed to load on try 2, trying again
[lib.cogs          ] 12/09/16 03:04:26:646 AM Module modules.debug failed to load on try 3, trying again
[lib.cogs          ] 12/09/16 03:04:26:647 AM Module modules.debug failed to load on try 4, trying again
[lib.cogs          ] 12/09/16 03:04:26:647 AM Module modules.debug failed to load on try 5, trying again
[lib.cogs          ] 12/09/16 03:04:26:648 AM Module modules.debug failed to load on try 6, trying again
[lib.cogs          ] 12/09/16 03:04:26:649 AM Module modules.debug failed to load on try 7, trying again
[lib.cogs          ] 12/09/16 03:04:26:650 AM Module modules.debug failed to load on try 8, trying again
[lib.cogs          ] 12/09/16 03:04:26:650 AM Module modules.debug failed to load on try 9, trying again
[lib.cogs          ] 12/09/16 03:04:26:651 AM Module modules.debug failed to load on try 10, trying again
[lib.cogs          ] 12/09/16 03:04:26:651 AM Module modules.debug failed to load on try 11, trying again
[lib.cogs          ] 12/09/16 03:04:26:652 AM Module modules.debug failed to load on try 12, trying again
[lib.cogs          ] 12/09/16 03:04:26:652 AM Module modules.debug failed to load on try 13, trying again
[lib.cogs          ] 12/09/16 03:04:26:653 AM Module modules.debug failed to load on try 14, trying again
[lib.cogs          ] 12/09/16 03:04:26:653 AM Module modules.debug failed to load on try 15, trying again
[lib.cogs          ] 12/09/16 03:04:26:654 AM Module modules.debug failed to load on try 16, trying again
[lib.cogs          ] 12/09/16 03:04:26:655 AM Module modules.debug failed to load on try 17, trying again
[lib.cogs          ] 12/09/16 03:04:26:655 AM Module modules.debug failed to load on try 18, trying again
[lib.cogs          ] 12/09/16 03:04:26:656 AM Module modules.debug failed to load on try 19, trying again
[lib.cogs          ] 12/09/16 03:04:26:657 AM Module modules.debug failed to load on try 20
Exception in thread Thread-1:
Traceback (most recent call last):
  File "lib/cogs.py", line 11, in load_extension
    bot.load_extension(name)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 722, in load_extension
    raise discord.ClientException('extension does not have a setup function')
discord.errors.ClientException: extension does not have a setup function
```
When quite obviously this is a setup function:
```py
def setup(bot):
    bot.add_cog(Extension(bot))
```
This only seems to happen when the extension is automatically reloaded. Manual reload via my command `reload_mod` works every time.

**Comment by GetRektByMe** [comment]
Hastebin the entire file pls

**Comment by Phxntxm** [comment]
You say it doesn't work when it's automatically reloaded, but does in your command. Also show the difference between your automatic reloading and the manual reloading

**Comment by ButterCheezii** [comment]
Automatic reloading is triggered by filesystem events. Manual reloading is triggered via a command.

**Comment by Phxntxm** [comment]
That's nice. Please show the difference between your automatic reloading and the manual reloading

**Comment by ButterCheezii** [comment]
They both use the same functions. `bot.unload_extension` and then `bot.load_extension`. However automatic reloading happens immediately after the file is updated, while user-triggered reloading happens through a command.

**Comment by ccubed** [comment]
If it only happens when your file system monitoring version is the one calling the reload, then your file system monitoring code is at fault. Most likely, you don't understand how your particular brand of monitoring works and are probably attempting to reload the cog before the OS has committed the changes.

**Comment by ButterCheezii** [comment]
> attempting to reload the cog before the OS has committed the changes.

Thanks. Adding a `time.sleep` fixed the problem.
