### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by Dmunch04** [Rapptz/discord.py#4122]
### Summary
I get this error:
```
Traceback (most recent call last):
  File "/home/munchii/Documents/GitHub/ZenBot/ZenBot/__main__.py", line 4, in <module>
    instance: ZenBot = ZenBot()
  File "/home/munchii/Documents/GitHub/ZenBot/ZenBot/bot.py", line 26, in __init__
    command_prefix="!"
  File "/home/munchii/.local/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 109, in __init__
    self.description = inspect.cleandoc(description) if description else ''
AttributeError: can't set attribute
```
When trying to create my bot like so:
```python
class MyBot(commands.Bot):
    def __init__(self):
        super().__init__(
            command_prefix="!"
        )
```

### System Information
```
- Python v3.7.5-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 5.3.0-7642-generic #34~1584408018~19.10~21df4b1-Ubuntu SMP Tue Mar 17 13:38:51 UTC
```

**Comment by Gobot1234** [comment]
I can't reproduce this.

```py
>>> from discord.ext import commands
>>> class MyBot(commands.Bot):
...    def __init__(self):
...        super().__init__(
...            command_prefix="!"
...        )
>>> bot = MyBot()
```
I think you've removed the part which errors. The full code would be useful.

**Comment by Dmunch04** [comment]
Hmm. It seems like it might be a Pycharm related issue, as if I do
```python
from discord.ext import commands
class MyBot(commands.Bot):
    def __init__(self):
        super().__init__(command_prefix="!")

bot = MyBot()
```
in `__main__.py` it works. Not sure why it doesn't work when importing the class from another file

**Comment by Dmunch04** [comment]
Yes it was indeed a Pycharm error. Still not sure what the exact reason was, but switching to an environment fixed it. Closing now since error is non-existent

**Comment by Dmunch04** [comment]
Seems like I'm still experiencing this. I have no idea what the cause is

**Comment by Dmunch04** [comment]
Here's the bot class if it's to any help
```python
class ZenBot(commands.Bot):
    def __init__(self):
        super().__init__(
            command_prefix=get_prefix,
            description=self.description,
            activity=discord.Game(name=self.status.format('')),  # TODO: Display server prefix
            case_insensitive=True,
            max_messages=10_000
        )

        self.logger = LogManager()

    def startup(self):
        self.logger.debug(f'Bot started at: {str(datetime.now())}')

        self.logger.debug('Removing command: help..')
        self.remove_command('help')

        self.logger.debug('Loading events file..')
        self.load_extension('events')

        self.logger.debug('Running bot..')
        self.run(self.config.get('token'))
        self.logger.success('Bot is running!')

    @property
    def config(self) -> Dict[str, Any]:
        with open('./config.json', 'r') as config:
            return json.load(config)

    @property
    def description(self) -> str:
        return self.config.get('description', '')

    @property
    def status(self) -> str:
        return self.config.get('status', '')
```

**Comment by zomatree** [comment]
The libaray uses `Bot.description` already and you overwrite it with a property without a setter

**Comment by Dmunch04** [comment]
Yeah. I also just came to the conclusion after slowly adding all methods back in. Thank you. Didn't think about that before for some reason haha. Closing
