### ISSUE TITLE
'Message' object has no attribute 'attatchments' when using reaction.message

### ISSUE THREAD

**Issue by coletonodonnell** [Rapptz/discord.py#4145]
### Summary

For the life of me, I can't get reaction.message.attatchments to work at all, and I don't know why.

### Reproduction Steps

Here is the code, it is for a starboard I am writing:
```
@client.event
    async def on_reaction_add(reaction, user):
        if str(reaction.emoji) == "⭐":
            if reaction.count >= 1:
                embed = discord.Embed(title = str(reaction.message.author.display_name), colour = 0xd4af37)
                embed.set_thumbnail(url=str(reaction.message.author.avatar_url))
                embed.add_field(name="Content:", value=str(reaction.message.content), inline=False)
                #embed.set_image(url=str(message.attatchments.url))
                embed.add_field(name="Stars:", value=f"{reaction.count}  :star:")
                embed.add_field(name="Jump:", value=f"[Click here!]({reaction.message.jump_url})")
                embed.set_footer(text=f"{reaction.message.id}")
                await client.get_channel(715225209438863423).send(embed=embed)
                print(f"{reaction.message.attatchments[0].url}")
```
### Expected Results

For it to print out the URL of the reaction message attachment (1st one) 

### Actual Results

It throws the error:
```
Ignoring exception in on_reaction_add
Traceback (most recent call last):
  File "/home/admin/.local/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "/home/admin/Tools/DiscordBot/main.py", line 89, in on_reaction_add
    print(f"{reaction.message.attatchments[0].url}")
AttributeError: 'Message' object has no attribute 'attatchments'
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### System Information

```
- Python v3.8.3-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 5.6.14-arch1-1 #1 SMP PREEMPT Wed, 20 May 2020 20:43:19 +0000
```

**Comment by zomatree** [comment]
its `attachments` not `attatchments`

**Comment by coletonodonnell** [comment]
ah i can't spell that is cool
