### ISSUE TITLE
RuntimeWarning: coroutine 'Client.start' was never awaited   pass RuntimeWarning: Enable tracemalloc to get the object allocation traceback

### ISSUE THREAD

**Issue by 12944qwerty** [Rapptz/discord.py#4190]
### Summary

I keep getting an error saying that Client.start wasn't awaited. Then a RuntimeWarning. However, I can't find what could be making this happen.

### Expected Results

No error to be thrown, and the bot to connect properly.

### Actual Results

```py
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "Ratchet/main.py", line 23, in on_ready
    self.load_extension(cog)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 653, in load_extension
    self._load_from_module_spec(spec, name)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 599, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'Miscellaneous' raised an error: RuntimeError: Cannot close a running event loop
/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py:319: RuntimeWarning: coroutine 'Client.start' was never awaited
  pass
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

### System Information

Running `python -m discord -v` gave:
```
- Python v3.8.3-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 5.4.0-1009-gcp #9-Ubuntu SMP Fri Apr 10 19:12:03 UTC 2020
```
I'm using repl.it

**Comment by Gobot1234** [comment]
Can you show us your code?

**Comment by 12944qwerty** [comment]
Ok. Warning, my main.py is still long.

```py
import discord as d
from discord_webhook import DiscordWebhook
import sys, traceback
from discord.ext.commands import Bot
from discord.ext.commands import bot_has_permissions
from discord.ext.commands import has_permissions
from discord.ext import commands as c
import os
from random import randint
import sqlite3 as sql
import asyncio
from keep_alive import keep_alive

conn = sql.connect('Ratchet.db')
crsr = conn.cursor()

class MyClient(Bot):
	def __init__(self,*args,**kwargs):
		super().__init__(*args,**kwargs)
		
	async def on_ready(self):
		for cog in cogs:
			self.load_extension(cog)
		"""try:
			crsr.execute('DROP TABLE guilds;')
			conn.commit
		except sql.OperationalError:
			pass
		try:
			crsr.execute('DROP TABLE users;')
			conn.commit
		except sql.OperationalError:
			pass
		crsr.execute('CREATE TABLE guilds ( \
			guild_id UNSIGNED BIG integer NOT NULL, \
			prefix string \
		);')
		conn.commit
		for guild in self.guilds:
			crsr.execute('INSERT INTO guilds (guild_id, prefix) VALUES (?, ?)', (guild.id, '\\'))
			conn.commit
		crsr.execute('UPDATE guilds SET prefix=? WHERE guild_id=?',('&',550722337050198036))
		crsr.execute('CREATE TABLE users ( \
			guild_id UNSIGNED BIG INT, \
			user_id UNSIGNED BIG INT, \
			xp INT \
		);')
		conn.commit()"""
		print('Logged in as')
		print('{0.user}'.format(self))
		print('Serving', end=' ')
		print('{} server(s)'.format(len(self.guilds)))

		while not self.is_closed():
			await self.change_presence(activity=d.Activity(type=d.ActivityType.watching, name='\\help'))
			await asyncio.sleep(5)
			await self.change_presence(activity=d.Activity(type=d.ActivityType.watching, name=f'{len(self.guilds)} servers'))
			await asyncio.sleep(5)
		
	async def on_message(self,message):
		if not message.author.bot:
			try:
				crsr.execute('SELECT xp FROM users WHERE guild_id=? AND user_id=?', (message.guild.id, message.author.id))
				idk = crsr.fetchone()
				#await message.channel.send(idk)
				if idk is None: #user not ranked
					crsr.execute('INSERT INTO users (guild_id, user_id, xp) VALUES (?, ?, ?)', (message.guild.id, message.author.id, 1))
				else:
					crsr.execute('UPDATE users SET xp=? WHERE guild_id=? AND user_id=?', ((idk[0] or 0) + 1, message.guild.id, message.author.id))
				conn.commit()
			except AttributeError:
				pass
		await self.process_commands(message)		

def get_prefix(bot,msg):
	try:
		crsr.execute('SELECT prefix FROM guilds WHERE guild_id=?',(msg.guild.id,))
		idk = crsr.fetchone()
		if idk is None or idk[0] is None:
			return '\\'
		return (idk[0], '\\')
		crsr.commit()
	except AttributeError:
		return ['&','\\']

client = MyClient(command_prefix=get_prefix)

client.crsr = crsr
client.conn = conn

cogs = ['Bot','Moderation','Miscellaneous','Games','errorhandler','owner']

with open('Ratchet/login.txt') as f:
    token = f.readline().strip()

keep_alive()

try:
	client.loop.run_until_complete(client.start(token))
except KeyboardInterrupt:
	conn.close()
	client.loop.run_until_complete(client.logout())
finally:
	client.loop.close()
	conn.close()
```

**Comment by Harmon758** [comment]
> ```py
> discord.ext.commands.errors.ExtensionFailed: Extension 'Miscellaneous' raised an error: RuntimeError: Cannot close a running event loop
> ```
The relevant code is likely in your Miscellaneous cog.

**Comment by plun1331** [comment]
![image](https://user-images.githubusercontent.com/49261529/107065775-031c3b00-6792-11eb-8a3b-f0de6206beb9.png)

Just a guess, but maybe you didn't await it.

**Comment by Th3-young-wolf** [comment]
Getting the same for a telegran bot
If it ain't awaited how to await it??

**Comment by DHRUV-777** [comment]
Use : await client.start
