### ISSUE TITLE
Timeout Error when running for longer periods of time (not consistent)

### ISSUE THREAD

**Issue by Macintosh-Fan** [Rapptz/discord.py#4196]
I get this weird error message while I run discord.py for a long time (does not always happen consistently)
```
Error in data transfer
Traceback (most recent call last):
  File "/Users/user_account_1/Desktop/Code/PyCharm CE/Advanced/venv/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/Users/user_account_1/Desktop/Code/PyCharm CE/Advanced/venv/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/Users/user_account_1/Desktop/Code/PyCharm CE/Advanced/venv/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/Users/user_account_1/Desktop/Code/PyCharm CE/Advanced/venv/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/Users/user_account_1/Desktop/Code/PyCharm CE/Advanced/venv/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/selector_events.py", line 846, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out
```

Thanks.

**Comment by Rapptz** [comment]
This is a logging statement from the websocket library when an internet error occurs during data transfer. The library then proceeds to close the connection with a 1011 close code and terminate it. Since I see no signs of this propagating or causing any harm I'll close this issue.

**Comment by Macintosh-Fan** [comment]
Thanks, @Rapptz.
