### ISSUE TITLE
"RuntimeError: Event loop is closed"

### ISSUE THREAD

**Issue by flitee** [Rapptz/discord.py#4203]
Recently when I tried to run the bot, it didn't respond or go online. 

Here's the main file code, which I believe is where the problem arose from:
`import discord
import os
from discord.ext import commands

prefix = 'alexa, '
bot = commands.Bot(command_prefix=prefix)

bot.remove_command('help')
for filename in os.listdir('./cogs'):
    if filename.endswith('.py'):
        bot.load_extension(f'cogs.{filename[:-3]}')

bot.run(token)`

Here is the console error:

`Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001856AE053A0>
Traceback (most recent call last):
  File "C:\Users\44794\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\44794\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\44794\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\44794\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed`

If any more info is required or forgotten, lmk

**Comment by Rapptz** [comment]
This isn't an issue with the library but with the ProactorEventLoop on asyncio. Next time please use the template rather than deleting it -- it's there for a reason.

For this specific instance of the error you're free to ignore it -- the text even says so.
