### ISSUE TITLE
Silent crash (exception in background task)

### ISSUE THREAD

**Issue by Budovi** [Rapptz/discord.py#421]
My bot has "silently crashed" today, i.e. the exception was not propagated to my code to be handled (according to the trace, not even library code). Even worse, the bot has become unresponsive to commands, and thus I was unable to restart it using a command.

The following trace was repeated on the output several (4) times:
```python
Task exception was never retrieved
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at /usr/local/lib/python3.5/dist-packages/discord/voice_client.py:265> exception=ConnectionClosed('WebSocket connection is closed: code = 4015, reason = Voice server crashed..',)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 614, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/websockets/protocol.py", line 298, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 4015, reason = Voice server crashed..

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/voice_client.py", line 272, in poll_voice_ws
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 617, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 4015, reason = Voice server crashed..
```

**The bot was still using a discord.py version 0.15.1 when this happened.** If this was fixed in the meantime, I'm sorry, I cannot trigger this error reliably to test with a new library version.

In any case, all exceptions should be retrieved and if not handled (e.g. retry inside a library) they should be passed to `on_error` event handler so that no silent crashes occurs. Bots can only recover from errors programmatically (not a big deal) if such exceptions can be detected.

**Comment by Rapptz** [comment]
The voice reconnection logic has become a lot better in the rewrite version of the library (see [here](http://discordpy.readthedocs.io/en/rewrite/migrating.html#voice-changes)).
