### ISSUE TITLE
Error on sending through webhook adapter partial webhook.

### ISSUE THREAD

**Issue by hyper-blade** [Rapptz/discord.py#4216]
### Reproduction Steps

Inside of class:

`webhook = discord.Webhook.from_url(config['GENERAL']['Webhook URL'], adapter=discord.WebhookAdapter())`

Sending webhook:

`
embed = discord.Embed(title=product_name, url=product_url, description=f'**Sizes Loaded:**\n\n{sizes}')
embed.set_thumbnail(url='attachment://image.jpg')
self.webhook.send(embed=embed, file=discord.File('image.jpg'))`

### Expected Results

Webhook expected to send as normally.

### Actual Results

Webhook errors with error: `TypeError: request() got an unexpected keyword argument 'files'`

`Traceback (most recent call last):
  File "C:\Users\shado\Desktop\Programming\sneaker\asos monitor\asos_monitor.py", line 85, in <module>
    in_stock = monitor.detect_stock(product_id='12370920', product_url='https://www.asos.com/converse/converse-chuck-taylor-all-star-hi-black-trainers/prd/12370920?colourwayid=16383878&SearchQuery=&cid=4172')
  File "C:\Users\shado\Desktop\Programming\sneaker\asos monitor\asos_monitor.py", line 43, in detect_stock
    self.get_info(product_url)
  File "C:\Users\shado\Desktop\Programming\sneaker\asos monitor\asos_monitor.py", line 65, in get_info
    self.send_embed(product_name, product_url, sizes)
  File "C:\Users\shado\Desktop\Programming\sneaker\asos monitor\asos_monitor.py", line 81, in send_embed
    self.webhook.send(embed=embed, file=discord.File('image.jpg'))
  File "C:\Users\shado\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\webhook.py", line 778, in send
    return self._adapter.execute_webhook(wait=wait, file=file, files=files, payload=payload)
  File "C:\Users\shado\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\webhook.py", line 148, in execute_webhook
    maybe_coro = self.request('POST', url, multipart=multipart, payload=data, files=files_to_pass)
TypeError: request() got an unexpected keyword argument 'files'`

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.3-final
- discord.py v1.3.1-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.17763

**Comment by hyper-blade** [comment]
I should've used the RequestsWebhookAdapter, not WebhookAdapter.
