### ISSUE TITLE
[rewrite] TextChannel doesn't have `is_private`, Messageable.typing doesn't have `__exit__` or `__aexit__`

### ISSUE THREAD

**Issue by mikevb1** [Rapptz/discord.py#437]
```py
Traceback (most recent call last):
  File ".../env/lib/python3.5/site-packages/discord/ext/commands/core.py", line 47, in wrapped
    ret = yield from coro(*args, **kwargs)
  File ".../env/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 88, in _default_help_command
    pages = bot.formatter.format_help_for(ctx, bot)
  File ".../env/lib/python3.5/site-packages/discord/ext/commands/formatter.py", line 291, in format_help_for
    return self.format()
  File ".../env/lib/python3.5/site-packages/discord/ext/commands/formatter.py", line 336, in format
    data = sorted(self.filter_command_list(), key=category)
  File ".../env/lib/python3.5/site-packages/discord/ext/commands/formatter.py", line 255, in predicate
    return cmd.can_run(self.context) and self.context.bot.can_run(self.context)
  File ".../env/lib/python3.5/site-packages/discord/ext/commands/core.py", line 430, in can_run
    return all(predicate(context) for predicate in predicates)
  File ".../env/lib/python3.5/site-packages/discord/ext/commands/core.py", line 430, in <genexpr>
    return all(predicate(context) for predicate in predicates)
  File ".../env/lib/python3.5/site-packages/discord/ext/commands/core.py", line 871, in predicate
    me = ch.guild.me if not ch.is_private else ctx.bot.user
AttributeError: 'TextChannel' object has no attribute 'is_private'
```
When calling the default help command.

Also when using (`async`) `with ctx.typing()` in a command, I get an AttributeError about it not having `__exit__` or `__aexit__`, respectively.

**Comment by Rapptz** [comment]
Fixed.
