### ISSUE TITLE
context.mesage.author is a User object when channel is not private

### ISSUE THREAD

**Issue by mrjohnyhats** [Rapptz/discord.py#438]
`Ignoring exception in command join_vchan
Traceback (most recent call last):
  File "C:\Users\jonbu\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "bot.py", line 67, in join_vchan
    if type(ctx.message.author).__name__ is "User" and ctx.message.author.voice_channel is None:
AttributeError: 'User' object has no attribute 'voice_channel'`
The above exception was the direct cause of the following exception:
`Traceback (most recent call last):
  File "C:\Users\jonbu\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 848, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\jonbu\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 369, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\jonbu\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'User' object has no attribute 'voice_channel'`

`ctx.message.channel.is_private` is false, so according to the message.py file, author should be a Member object.

**Comment by Rapptz** [comment]
This happens if you get the message before `on_ready` is called.

**Comment by mrjohnyhats** [comment]
just logged `on_ready`, and the issue still persists after it's called. I think this has something to do with `guild_sync` not being called, but not sure.
