### ISSUE TITLE
Gateway.py `received_message` fails to do error checking

### ISSUE THREAD

**Issue by jneubrand** [Rapptz/discord.py#443]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 387, in poll_event
    yield from self.received_message(msg)
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 284, in received_message
    msg = json.loads(msg)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 33, in <module>
    bot.run(config.credentials)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 491, in start
    yield from self.connect()
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 448, in connect
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 388, in poll_event
    except websockets.exceptions.ConnectionClosed as e:
AttributeError: module 'websockets.exceptions' has no attribute 'ConnectionClosed'
```
This issue has occurred multiple times for me on a remote VM.

Fix should be as simple as adding `if msg` before [`gateway.py#387`](https://github.com/Rapptz/discord.py/blob/master/discord/gateway.py#L387) and perhaps the equivalent for the voice socket handler.

**Comment by Rapptz** [comment]
Update your websockets lib. It's out of date.

**Comment by jneubrand** [comment]
Thanks, can't believe I missed that 😅
