### ISSUE TITLE
aiohttp.errors.ClientRequestError: Can not write request body for https://discordapp.com/api/v6/channels/CENSORED/messages

### ISSUE THREAD

**Issue by ButterCheezii** [Rapptz/discord.py#453]
I keep getting this error when sending a file object:

```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/ubuntu/L-B0T/modules/image.py", line 21, in hey
    await self.bot.upload(temp, filename = 'hey.png')
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/client.py", line 1234, in send_file
    filename=filename, content=content, tts=tts)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/http.py", line 105, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/client.py", line 202, in _request
    yield from resp.start(conn, read_until_eof)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 640, in start
    message = yield from httpstream.read()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 641, in read
    result = yield from super().read()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 476, in read
    yield from self._waiter
  File "/usr/lib/python3.6/asyncio/tasks.py", line 304, in _wakeup
    future.result()
aiohttp.errors.ClientRequestError: Can not write request body for https://discordapp.com/api/v6/channels/CENSORED/messages

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 848, in process_commands
    yield from command.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 369, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ClientRequestError: Can not write request body for https://discordapp.com/api/v6/chs
```

The error appears on the `bot.upload` call here:

```py
from discord.ext import commands
import PIL, PIL.Image, requests, io, tempfile

class Extension:
    def __init__(self, bot):
        self.bot = bot
        type(self).__name__ = 'Imageing'

    @commands.command(pass_context = True)
    async def hey(self, ctx):
        image = PIL.Image.open('images/hey.png')

        temp = tempfile.TemporaryFile()
        image.save(temp, 'png')

        await self.bot.upload(temp, filename = 'hey.png')

def setup(bot):
    bot.add_cog(Extension(bot))
```

I am using the latest `pillow` library, Python 3.6.0, and the latest discord.py [not rewrite].

`hey.png` is a generic png image. I've stripped the code down to only what is causing the error.

**Comment by Rapptz** [comment]
TemporaryFile is not a file-like object.

**Comment by Rapptz** [comment]
Going into a bit more depth of this issue, `TemporaryFile` is not strictly equivalent to types `io.open` returns. This causes aiohttp to not accept it. Use `io.BytesIO` instead.

**Comment by ButterCheezii** [comment]
Thanks.
