### ISSUE TITLE
Discord music bot error

### ISSUE THREAD

**Issue by Dustdefender** [Rapptz/discord.py#454]
Ok, so i set up a bot yesterday and it was working fine but now when i try to  play music it has this error:
also it only does this to some videos i'm currently test videos. 

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "C:\Users\Zane\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 1005, in _decrypt_signature
    video_id, player_url, s
  File "C:\Users\Zane\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 932, in _extract_signature_function
    cache_res = res(test_string)
  File "C:\Users\Zane\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\extractor\youtube.py", line 984, in <lambda>
    return lambda s: initial_function([s])
  File "C:\Users\Zane\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "C:\Users\Zane\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "C:\Users\Zane\AppData\Local\Programs\Python\Python35-32\lib\site-packages\youtube_dl\jsinterp.py", line 174, in interpret_expression
    return obj[member](argvals)
KeyError: 'qC'
 (caused by KeyError(

any known fixes?

**Comment by Eternity71529** [comment]
update youtube_dl
there's a patch update released for this

**Comment by Rapptz** [comment]
This is not youtube_dl support.
