### ISSUE TITLE
join_voice_channel call failed

### ISSUE THREAD

**Issue by Petitsurume** [Rapptz/discord.py#479]
hi.
i'm creating a musicbot with this library.
I called `client.join_voice_channel(channel)`, then i got this error:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "main.py", line 23, in on_message
    voiceclient = await client.join_voice_channel(channel)
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 3195, in join_voice_channel
    yield from voice.connect()
  File "/usr/local/lib/python3.6/site-packages/discord/voice_client.py", line 247, in connect
    self.endpoint = self.endpoint.replace(':80', '')
AttributeError: 'NoneType' object has no attribute 'replace'
```
Is this error occured with my codes or this library?
thanks.

**Comment by jhonnold** [comment]
Any more code you're willing to share? I use join_voice_channel, never with any issues.

**Comment by Petitsurume** [comment]
sorry, because I was running the same two scripts 😱
But I think that this error message is inappropriate.
For now, Issue will close.
