### ISSUE TITLE
Client occasionally gets stuck/crashes on websocket reconnect

### ISSUE THREAD

**Issue by Isonami** [Rapptz/discord.py#48]
Thread with discord client stops working with this in logs:
```
[23/Nov/2015 02:20:19] DEBUG [discord.client:77] (Thread-5  ) Keeping websocket alive with timestamp 1448238019
[23/Nov/2015 02:20:19] DEBUG [discord.client:509] (Thread-5  ) Dispatching event socket_raw_send
[23/Nov/2015 02:20:33] DEBUG [ws4py:360] (Bot       ) Closing message received (1000) ''
[23/Nov/2015 02:20:33] INFO [discord.client:95] (Bot       ) Closed with 1006 ("Going away") at 1448238033
[23/Nov/2015 02:20:33] DEBUG [discord.client:509] (Bot       ) Dispatching event socket_closed
[23/Nov/2015 02:20:33] DEBUG [discord.client:509] (Bot       ) Dispatching event socket_closed
[23/Nov/2015 02:20:33] INFO [requests.packages.urllib3.connectionpool:756] (Bot       ) Starting new HTTPS connection (1): discordapp.com
[23/Nov/2015 02:20:33] DEBUG [requests.packages.urllib3.connectionpool:387] (Bot       ) "GET /api/gateway HTTP/1.1" 200 43
[23/Nov/2015 02:20:33] INFO [discord.client:428] (Bot       ) websocket gateway found
```

Might be an error around `self.ws.connect()` but there are no handlers at this point or in my thread code.

It is extremely rare, I have updated my code to log exceptions from client thread so next time hopefully I'll see why it happens.

**Comment by The-Penultimate-Defenestrator** [comment]
Is this the same error:
```
Traceback (most recent call last):
  File "/home/luke/Desktop/discord/discord_main.py", line 16, in <module>
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/discord/client.py", line 542, in run
    self.ws.run()
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 427, in run
    if not self.once():
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 305, in once
    if not self.process(b):
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 362, in process
    self.close(s.closing.code, s.closing.reason)
  File "/usr/local/lib/python2.7/dist-packages/ws4py/client/__init__.py", line 198, in close
    self._write(self.stream.close(code=code, reason=reason).single(mask=True))
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 243, in _write
    self.sock.sendall(b)
  File "/usr/lib/python2.7/ssl.py", line 721, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python2.7/ssl.py", line 687, in send
    v = self._sslobj.write(data)
error: [Errno 14] Bad address
```

**Comment by anon276** [comment]
I think I have the same problem: https://github.com/Rapptz/discord.py/issues/86

**Comment by diceroll123** [comment]
Anyone have some sort of reconnect method that doesn't suck?

Running `client.run()` in a `while True:` with a try/catch to `pass` the error is probably the worst idea possible.

_this kills the CPU_

**Comment by Monbrey** [comment]
diceroll123, I was trying to do something similar by launching it in a thread and monitoring thread.isAlive(). No better really.

Why not implement a sleep of 30 or 60 seconds in your while loop? The client.run() operation is threaded anyway, so you shouldn't be blocking interaction.

**Comment by The-Penultimate-Defenestrator** [comment]
I always start my script using `pm2`. Handles it automatically.

**Comment by diceroll123** [comment]
@The-Penultimate-Defenestrator Just started using pm2 _had to install node but that wasn't a big deal_, awesome! :smile: Thanks. This proves useful for various other scripts of mine. :)

**Comment by The-Penultimate-Defenestrator** [comment]
Glad I could help :)

**Comment by Rapptz** [comment]
ws4py is no longer used so I'm not sure how this issue applies anymore. Make a new one if something comes up in the async branch.
