### ISSUE TITLE
PyNaCl Compile Error on Raspberry pi 3 

### ISSUE THREAD

**Issue by kingcraftingnl** [Rapptz/discord.py#493]
`i@raspberrypi:~/MusicBot $ python3 -m pip install -U https://github.com/Rapptz/discord.py/arc                          hive/master.zip#egg=discord.py[voice]
Collecting discord.py[voice] from https://github.com/Rapptz/discord.py/archive/master.zip#egg=                          discord.py[voice]
  Downloading https://github.com/Rapptz/discord.py/archive/master.zip
     / 491kB 184kB/s
Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py[voice])
  Using cached aiohttp-1.0.5.tar.gz
Collecting websockets<4.0,>=3.1 (from discord.py[voice])
  Using cached websockets-3.2-py33.py34.py35-none-any.whl
Collecting PyNaCl==1.0.1 (from discord.py[voice])
  Using cached PyNaCl-1.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    Package libffi was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libffi.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libffi' found
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
     #include <ffi.h>
                     ^
    compilation terminated.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/distutils/unixccompiler.py", line 116, in _compile
        extra_postargs)
      File "/usr/local/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/local/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/local/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 160,                           in run
        cmd = self.call_command('install_lib', warn_dir=0)
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 146,                           in call_command
        self.run_command(cmdname)
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 10                          , in run
        self.build()
      File "/usr/local/lib/python3.5/distutils/command/install_lib.py", line 107, in build
        self.run_command('build_ext')
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 49,                           in run
        _build_ext.run(self)
      File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 338, in run
        self.build_extensions()
      File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 447, in build_exten                          sions
        self._build_extensions_serial()
      File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 472, in _build_exte                          nsions_serial
        self.build_extension(ext)
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 174,                           in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/local/lib/python3.5/distutils/command/build_ext.py", line 532, in build_exten                          sion
        depends=ext.depends)
      File "/usr/local/lib/python3.5/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/usr/local/lib/python3.5/distutils/unixccompiler.py", line 118, in _compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 152, in save_m                          odules
        yield saved
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 193, in setup_                          context
        yield
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 237, in run_se                          tup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 267, in run
        return func()
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 236, in runner
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfi                          le
        exec(code, globals, locals)
      File "/tmp/easy_install-y1hv5eql/cffi-1.9.1/setup.py", line 202, in <module>
        if self.distribution.has_c_libraries():
      File "/usr/local/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1                          056, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 240, in run_se                          tup
        raise
      File "/usr/local/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 193, in setup_                          context
        yield
      File "/usr/local/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 164, in save_m                          odules
        saved_exc.resume()
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 139, in resume
        compat.reraise(type, exc, self._tb)
      File "/usr/local/lib/python3.5/site-packages/setuptools/compat.py", line 65, in reraise
        raise value.with_traceback(tb)
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 152, in save_m                          odules
        yield saved
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 193, in setup_                          context
        yield
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 237, in run_se                          tup
        DirectorySandbox(setup_dir).run(runner)
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 267, in run
        return func()
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 236, in runner
        _execfile(setup_script, ns)
      File "/usr/local/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfi                          le
        exec(code, globals, locals)
      File "/tmp/easy_install-y1hv5eql/cffi-1.9.1/setup.py", line 202, in <module>
        if self.distribution.has_c_libraries():
      File "/usr/local/lib/python3.5/distutils/core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: command 'gcc' failed with exit status 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zfpgivd_/PyNaCl/setup.py", line 259, in <module>
        "Programming Language :: Python :: 3.5",
      File "/usr/local/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 268, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 313, in fetch_bui                          ld_eggs
        replace_conflicting=True,
      File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 836, in re                          solve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1081, in b                          est_match
        return self.obtain(req, installer)
      File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1093, in o                          btain
        return installer(requirement)
      File "/usr/local/lib/python3.5/site-packages/setuptools/dist.py", line 380, in fetch_bui                          ld_egg
        return cmd.easy_install(req)
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 6                          29, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 6                          59, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 8                          42, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1                          070, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 1                          058, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'gcc' failed with                           exit status 1
`

**Comment by SunDwarf** [comment]
https://github.com/Just-Some-Bots/MusicBot

**Comment by SpoopySaitama** [comment]
I'm.. amazed, honestly. That traceback tells you all you need to know.

Just use MusicBot™

**Comment by Rapptz** [comment]
You need to install libffi. `sudo apt-get install libffi-dev`
