### ISSUE TITLE
Mac issue with running the red_start.command.

### ISSUE THREAD

**Issue by haaddaa1** [Rapptz/discord.py#498]
**These are my errors**
And i did everything the red installion of mac told me to do 
   

     [02/03/2017 15:47] ERROR red <module> 622: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/connector.py", line 601, in _create_direct_connection
    local_addr=self._local_addr)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 801, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 827, in _create_connection_transport
    yield from waiter
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/sslproto.py", line 502, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)

**Comment by ccubed** [comment]
Did you try the redbot support server? 

https://discord.gg/red

Also, this is an issue with your SSL certificates.

**Comment by haaddaa1** [comment]
i did

**Comment by haaddaa1** [comment]
And now im getting this after upgrading certificates
Traceback (most recent call last):
  File "red.py", line 603, in <module>
    loop.run_until_complete(main(bot))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "red.py", line 588, in main
    bot=not bot.settings.self_bot)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/client.py", line 416, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/client.py", line 346, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/http.py", line 256, in static_login
    data = yield from self.request(Route('GET', '/users/@me'))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/http.py", line 136, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/connector.py", line 314, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)]]
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at /Users/GarickTejeda/Desktop/G/Red-DiscordBot/cogs/streams.py:460> wait_for=<Future pending cb=[Task._wakeup()]>>

**Comment by haaddaa1** [comment]
an now this Traceback (most recent call last):
  File "red.py", line 603, in <module>
    loop.run_until_complete(main(bot))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "red.py", line 588, in main
    bot=not bot.settings.self_bot)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/client.py", line 416, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/client.py", line 346, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/http.py", line 256, in static_login
    data = yield from self.request(Route('GET', '/users/@me'))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/discord/http.py", line 136, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/aiohttp/connector.py", line 314, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)]]
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at /Users/<user>/Desktop/G/Red-DiscordBot/cogs/streams.py:460> wait_for=<Future pending cb=[Task._wakeup()]>>

**Comment by OrangeChaten** [comment]
Mac is weird with SSL certificates, basically, update your Mac certificates, there are plenty of guides on Google.

**Comment by haaddaa1** [comment]
i just did that and still same thing

**Comment by haaddaa1** [comment]
do u have discord or teamviewer

**Comment by OrangeChaten** [comment]
http://lmgtfy.com/?q=how+to+update+ssl+certificates+on+mac

**Comment by Rapptz** [comment]
Install certifi. e.g. `python3 -m pip install --force-reinstall certifi`

**Comment by haaddaa1** [comment]
Alright i'll try it

**Comment by Phxntxm** [comment]
"do u have discord or teamviewer"
"do u have discord"
>Asking if you have discord on a discord library :thinking:

**Comment by haaddaa1** [comment]
OMFG RAPPTS YOUR THE BEST! IT WORKED

**Comment by haaddaa1** [comment]
thanks

**Comment by Pandentia** [comment]
Just an FYI, next time you forget to add something, you can edit comments. GitHub isn't a chat program, it's a software development platform. Basically what I'm trying to say is, don't double-comment unless a significant amount of time has passed.
