### ISSUE TITLE
Unclosed client session

### ISSUE THREAD

**Issue by Thetexassooner1** [Rapptz/discord.py#502]
```
C:\Python351\python.exe "C:/Users/Jonathan/Desktop/Discord Bots/Dodgers Bot/Version 2/DodgersBotv2.py"
Traceback (most recent call last):
  File "C:/Users/Jonathan/Desktop/Discord Bots/Dodgers Bot/Version 2/DodgersBotv2.py", line 166, in <module>
    client.run('Mjg4MDc3NDYyODU5MTUzNDA4.C54mvQ.uyxuu_QxtHiCdjO8j4FS_C6k_bk')
  File "C:\Python351\lib\site-packages\discord\client.py", line 473, in run
    self.loop.run_until_complete(self.start(*args))
  File "C:\Python351\lib\asyncio\base_events.py", line 337, in run_until_complete
    return future.result()
  File "C:\Python351\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Python351\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Python351\lib\site-packages\discord\client.py", line 445, in start
    yield from self.connect()
  File "C:\Python351\lib\site-packages\discord\client.py", line 399, in connect
    self.ws = yield from DiscordWebSocket.from_client(self)
  File "C:\Python351\lib\site-packages\discord\gateway.py", line 191, in from_client
    ws = yield from websockets.connect(gateway, loop=client.loop, klass=cls)
  File "C:\Python351\lib\site-packages\websockets\py35\client.py", line 19, in __await__
    return (yield from self.client)
  File "C:\Python351\lib\site-packages\websockets\client.py", line 160, in connect
    factory, wsuri.host, wsuri.port, **kwds)
  File "C:\Python351\lib\asyncio\base_events.py", line 663, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "C:\Python351\lib\asyncio\base_events.py", line 675, in _create_connection_transport
    protocol = protocol_factory()
  File "C:\Python351\lib\site-packages\websockets\client.py", line 156, in <lambda>
    loop=loop, legacy_recv=legacy_recv,
  File "C:\Python351\lib\site-packages\discord\gateway.py", line 174, in __init__
    super().__init__(*args, max_size=None, **kwargs)
TypeError: __init__() got multiple values for keyword argument 'max_size'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x030E7290>
```
I can't find a solution that works anywhere. I changed the bot token, made a new python file, made sure there was no errors, and yet it still won't run. Any solutions?

**Comment by Gorialis** [comment]
your token is showing

**Comment by Thetexassooner1** [comment]
> your token is showing

The token already has been changed before this, this was a error before I tried changing it so it doesn't really matter

**Comment by SunDwarf** [comment]
Update your lib and all the dependencies.

**Comment by Rapptz** [comment]
Your library is way out of date. Please update periodically.
