### ISSUE TITLE
Voice seems to have problems with uvloop

### ISSUE THREAD

**Issue by khazhyk** [Rapptz/discord.py#504]
```
[2017-03-07 02:40:48,698][asyncio][ERROR] Task exception was never retrieved
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at /var/lib/spoobeta/venv/lib/python3.5/site-packages/discord/voice_client.py:265> exception=ConnectionClosed('WebSocket connection is closed: code = 1002, no reason.'
,)>
Traceback (most recent call last):
  File "/var/lib/spoobeta/venv/lib/python3.5/site-packages/discord/gateway.py", line 627, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "uvloop/future.pyx", line 146, in uvloop.loop.BaseFuture.result (uvloop/loop.c:108166)
  File "uvloop/future.pyx", line 101, in uvloop.loop.BaseFuture._result_impl (uvloop/loop.c:107674)
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:111405)
  File "/var/lib/spoobeta/venv/lib/python3.5/site-packages/websockets/protocol.py", line 298, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1002, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "uvloop/future.pyx", line 372, in uvloop.loop.BaseTask._fast_step (uvloop/loop.c:111405)
  File "/var/lib/spoobeta/venv/lib/python3.5/site-packages/discord/voice_client.py", line 272, in poll_voice_ws
    yield from self.ws.poll_event()
  File "/var/lib/spoobeta/venv/lib/python3.5/site-packages/discord/gateway.py", line 630, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1002, no reason.
```

websocket 1002 is "protocol error"

**Comment by khazhyk** [comment]
This went away after updating uvloop lol
