### ISSUE TITLE
Owner?

### ISSUE THREAD

**Issue by haaddaa1** [Rapptz/discord.py#509]
Ignoring exception in message
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 252, in _run_extra
yield from coro(*args, **kwargs)
File "/Users/ /Desktop/G/Red-DiscordBot/cogs/selfembed.py", line 33, in on_message
if self.eee["toggle"] and author.id == self.bot.owner.user.id:
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/client.py", line 296, in getattr
raise AttributeError(msg.format(self.class, name))
AttributeError: '<class 'main.Bot'>' object has no attribute 'owner'

**HELP**
And Yes i did put this issue in nerdie cogs

**Comment by Phxntxm** [comment]
Do not post duplicate issues. If you don't understand, read through your issue again, you have been told what to do:

https://github.com/Rapptz/discord.py/issues/506

**Comment by haaddaa1** [comment]
opps
