### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'allow_new'

### ISSUE THREAD

**Issue by artem-6191** [Rapptz/discord.py#5111]
### Summary

Error in `<commands.Bot>.fetch_channel`

### Reproduction Steps

I used `chn = await self.bot.fetch_channel(723126150779633684)` and got this error

### Expected Results

I expected to fetch channel with news

### Actual Results

I got this error
```python
Traceback (most recent call last):

  File "/home/artem/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)

  File "/home/artem/sc/lib/owner.py", line 61, in notify_update
    chn = await self.bot.fetch_channel(723126150779633684)

  File "/home/artem/.local/lib/python3.8/site-packages/discord/client.py", line 1316, in fetch_channel
    channel = factory(guild=guild, state=self._connection, data=data)

  File "/home/artem/.local/lib/python3.8/site-packages/discord/channel.py", line 107, in __init__
    self._update(guild, data)

  File "/home/artem/.local/lib/python3.8/site-packages/discord/channel.py", line 131, in _update
    self._fill_overwrites(data)

  File "/home/artem/.local/lib/python3.8/site-packages/discord/abc.py", line 294, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))

TypeError: __new__() got an unexpected keyword argument 'allow_new'
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have confirmed that the channel ID is correct and channel is exists

### System Information

- Python v3.8.0-final
- discord.py v1.3.3-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 5.3.0-1028-aws #30~18.04.1-Ubuntu SMP Mon Jun 22 15:48:21 UTC 2020

**Comment by oliver-ni** [comment]
#5109
