### ISSUE TITLE
AttributeError: 'function' object has no attribute '__func__'

### ISSUE THREAD

**Issue by artem-6191** [Rapptz/discord.py#5125]
### Summary

Any cog commands failed with error "AttributeError: 'function' object has no attribute '__func__'" 

### Reproduction Steps

I made that bot changes cog_check for every cog when ready:
```py
async def on_ready(self):
  async def check(self, ctx):
    if not ctx.guild:
      return False
    disabled = await self.db('SELECT * FROM disabled_commands WHERE id=$1', ctx.guild.id)
    return str(ctx.command) not in [x['command'] for x in disabled]
  for cog in self.cogs:
    self.cogs[cog].cog_check = check 
```
But if i paste the same check function in all the cogs all will be ok

### Expected Results

Blocking certain commands for certain guilds

### Actual Results

I got this error:
```py
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/artem/.local/lib/python3.8/site-packages/discord/client.py", line 304, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 75, in on_message
    await self.process_commands(msg)
  File "/home/artem/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 934, in process_commands
    await self.invoke(ctx)
  File "/home/artem/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 897, in invoke
    await ctx.command.invoke(ctx)
  File "/home/artem/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 823, in invoke
    await self.prepare(ctx)
  File "/home/artem/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 776, in prepare
    if not await self.can_run(ctx):
  File "/home/artem/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1033, in can_run
    local_check = Cog._get_overridden_method(cog.cog_check)
  File "/home/artem/.local/lib/python3.8/site-packages/discord/ext/commands/cog.py", line 240, in _get_overridden_method    return getattr(method.__func__, '__cog_special_method__', method)
AttributeError: 'function' object has no attribute '__func__'
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have checked that this error not in my bot code

### System Information

- Python v3.8.0-final
- discord.py v1.4.0-alpha
    - discord.py pkg_resources: v1.4.0a2377+g0bc15fa
- aiohttp v3.6.2
- websockets v8.1
- system info: Linux 5.3.0-1028-aws #30~18.04.1-Ubuntu SMP Mon Jun 22 15:48:21 UTC 2020

**Comment by Rapptz** [comment]
This isn't how you override methods, which is why the library didn't expect it to be used like that. Since this is a bit of a Python knowledge issue I won't fix it. However, the proper way to do what you want to do is through a global check instead, not by overriding every cog's cog check.
