### ISSUE TITLE
WebSocket closed with 4011 error code

### ISSUE THREAD

**Issue by Dyleee** [Rapptz/discord.py#5128]
### Summary

So upon launching my bot, there's a websocket closure upon launching Shard 8, might not be the same for testers but the websocket closes with error code 4011 thus shutting down the entire bot.

### Expected Results

Bot should launch normally.

### Actual Results
```
0|MewBot  | Traceback (most recent call last):
0|MewBot  |   File "/usr/local/lib/python3.8/runpy.py", line 193, in _run_module_as_main
0|MewBot  |     return _run_code(code, main_globals, None,
0|MewBot  |   File "/usr/local/lib/python3.8/runpy.py", line 86, in _run_code
0|MewBot  |     exec(code, run_globals)
0|MewBot  |   File "/home/dylee/mewbot/mew/__main__.py", line 83, in <module>
0|MewBot  |     main()
0|MewBot  |   File "/home/dylee/mewbot/mew/__main__.py", line 80, in main
0|MewBot  |     client.run()
0|MewBot  |   File "/home/dylee/mewbot/mew/core/dna.py", line 202, in run
0|MewBot  |     self.loop.run_until_complete(runner())
0|MewBot  |   File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
0|MewBot  |   File "/home/dylee/mewbot/mew/core/dna.py", line 198, in runner
0|MewBot  |     await self.start()
0|MewBot  |   File "/home/dylee/mewbot/mew/core/dna.py", line 192, in start
0|MewBot  |     await super().start(self.token)
0|MewBot  |   File "/home/dylee/.local/lib/python3.8/site-packages/discord/client.py", line 622, in start
0|MewBot  |     await self.connect(reconnect=reconnect)
0|MewBot  |   File "/home/dylee/.local/lib/python3.8/site-packages/discord/shard.py", line 309, in connect
0|MewBot  |     raise item.error
0|MewBot  |   File "/home/dylee/.local/lib/python3.8/site-packages/discord/shard.py", line 134, in worker
0|MewBot  |     await self.ws.poll_event()
0|MewBot  |   File "/home/dylee/.local/lib/python3.8/site-packages/discord/gateway.py", line 529, in poll_event
0|MewBot  |     raise ConnectionClosed(self.socket, shard_id=self.shard_id) from None
0|MewBot  | discord.errors.ConnectionClosed: Shard ID 8 WebSocket closed with 4011
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.

### System Information
- Python v3.8.1-final
- discord.py v1.4.0-alpha
    - discord.py pkg_resources: v1.4.0a2393+g36f3dca
- aiohttp v3.6.2
- system info: Linux 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020

**Comment by Taarek** [comment]
If you read this https://discord.com/developers/docs/topics/opcodes-and-status-codes

It says 4011 is ``Sharding Required`` which essentially means. Shard ID 8 most likely has more than 2500 guilds. You need to increase your total shard count.
