### ISSUE TITLE
Installing 1.3.4 doesn't include code for 1.3.4: _overwrites is still a named tuple

### ISSUE THREAD

**Issue by PaulBags** [Rapptz/discord.py#5148]
### Summary

the command `python3 -m pip install -U discord.py` installs what it calls version 1.3.4 of discord, however the lines of code fixing this bug are missing and _overwrites is still a named tuple.

### Reproduction Steps

Install discord with the suggested method `python3 -m pip install -U discord.py`.

### Expected Results

The code for version 1.3.4 would actually be installed.

### Actual Results

_overwrites is still a named tuple.

### Checklist

- [ X] I have searched the open issues for duplicates.
- [ X] I have shown the entire traceback, if possible.
- [ X] I have removed my token from display, if visible.

### System Information

> Run `python -m discord -v` and paste this information below.
Lol, ok?
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/paul/.local/lib/python3.8/site-packages/discord/__init__.py", line 23, in <module>
    from .client import Client
  File "/home/paul/.local/lib/python3.8/site-packages/discord/client.py", line 34, in <module>
    import aiohttp
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/client.py", line 32, in <module>
    from . import hdrs, http, payload
  File "/usr/local/lib/python3.8/dist-packages/aiohttp/http.py", line 1, in <module>
    import http.server
  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 36, in <module>
    from .errors import HTTPException, Forbidden, NotFound, LoginFailure, GatewayNotFound
ImportError: attempted relative import with no known parent package
```

Python3.8, discord.py 1.3.4, Debian bullseye

**Comment by PaulBags** [comment]
I'm an idiot, pip wasn't installing/uninstalling where I thought it was.
