### ISSUE TITLE
Exception when emoji is in Discord message

### ISSUE THREAD

**Issue by BlaT2512** [Rapptz/discord.py#5158]
### Summary

In the `on_message` function for my discord bot using discord.js, an exception occurs when the discord message received includes an emoji, either a local Windows emoji or a discord emoji.

### Reproduction Steps

Here is the code I am using, it is just a basic example:
```python
# Import the configuration file, config.json
import json
with open('config.json') as file:
    config = json.load(file)
# Import discord.py module
import discord
# Import regular expressions
import re

# Discord bot client class
class MyBot(discord.Client):
    # When the client is ready, run this code
    # This event will only trigger one time after logging in
    async def on_ready(self):
        print('Ready as user', self.user)

   # This code runs every time a message is sent in a server that this bot is in
    async def on_message(self, message): 
        # Log message info to console
        print(message.content) # <---- EXCEPTION OCCURS HERE
        print(message.author.id)

        # Do some stuff with the message
        
# Connect to discord as Bot
client = MyBot()
client.run(config["token"])
```

### Expected Results

The emoji should either be shown in the message as something like `:smile:` or not shown at all in the message because I am not processing the emojis.

### Actual Results

The exception was the following:
```
Traceback (most recent call last):
  File "C:\Users\my_username\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\my_username\Desktop\TestBot\main.py", line 20, in on_message
    print(message.content)
  File "C:\Users\blake\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

`python -m discord -v` results:
```
- Python v3.8.3-final
- discord.py v1.3.4-final
- aiohttp v3.6.2
- websockets v8.1
- system info: Windows 10 10.0.19041
```

**Comment by apple502j** [comment]
This is not a problem with discord.py. The solution is easy; do not `print(message.content)`

**Comment by BlaT2512** [comment]
This isn't the only time that it happens, it happens also other times when I try to interact with `message.content`

**Comment by XuaTheGrate** [comment]
You are trying to print a codepoint that the Windows Command Prompt does not support. It expects a `charmap` encoding but Discord messages are `UTF-8` encoded.

**Comment by BlaT2512** [comment]
Is there anyway to convert this to the correct encoding?

**Comment by XuaTheGrate** [comment]
Iirc you can use ``chcp 65001`` in the command prompt prior to running your bot, this will change the prompt encoding.

**Comment by BlaT2512** [comment]
OK thanks for your help
Sorry if this seems like a dumb question, this is my first time using discord.py as I usually use discord.js and it works correctly with emojis.

**Comment by Rapptz** [comment]
This issue is unrelated to the library but is rather a consequence of your terminal as was mentioned.
