### ISSUE TITLE
Bot crash when joining a new guild

### ISSUE THREAD

**Issue by Katistic** [Rapptz/discord.py#5185]
### Summary

When adding bot account to a new guild while bot is running,
  a TypeError occures in the discord.py library

### Reproduction Steps

Have a simple bot (it can do nothing, it just has to go online). In my case I hadn't overwritten anything to do with joining, leaving, or editing guilds. Add the bot to a new server using an OAuth2 URL

```Python
import discord
import asyncio

class Client(discord.Client):
    async def on_ready(self):
        print("Logged in.")

bot = Client()
bot.run("token")
```

### Expected Results

Nothing to happen

### Actual Results

Received a TypeError
```
Traceback (most recent call last):
  File "main.py", line 254, in <module>
    bot = Client()
  File "main.py", line 195, in __init__
    loop.run_until_complete(self.start(startup_data))
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 612, in run_until_complete
    return future.result()
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 585, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 499, in connect
    await self._connect()
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 463, in _connect
    await self.ws.poll_event()
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\gateway.py", line 471, in poll_event
    await self.received_message(msg)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\gateway.py", line 425, in received_message
    func(data)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\state.py", line 750, in parse_guild_create
    guild = self._get_create_guild(data)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\state.py", line 728, in _get_create_guild
    return self._add_guild_from_data(data)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\state.py", line 274, in _add_guild_from_data
    guild = Guild(data=guild, state=self)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\guild.py", line 177, in __init__
    self._from_data(data)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\guild.py", line 297, in _from_data
    self._sync(guild)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\guild.py", line 324, in _sync    self._add_channel(TextChannel(guild=self, data=c, state=self._state))
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\channel.py", line 107, in __init__
    self._update(guild, data)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\channel.py", line 131, in _update
    self._fill_overwrites(data)
  File "C:\Users\Princess\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\abc.py", line 294, in _fill_overwrites
    self._overwrites.append(_Overwrites(id=overridden_id, **overridden))
TypeError: __new__() got an unexpected keyword argument 'deny_new'
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

Python v3.7.6-final
discord.py v1.3.4-final
aiohttp v3.6.2
websockets v6.0
system info: Windows 10 10.0.19041

**Comment by Gobot1234** [comment]
See #5109

**Comment by Katistic** [comment]
Thanks
