### ISSUE TITLE
"io.UnsupportedOperation: fileno" when using discord.FFmpegPCMAudio

### ISSUE THREAD

**Issue by Armster15** [Rapptz/discord.py#5192]
### Summary

I get a `io.UnsupportedOperation: fileno` when trying to create a `discord.FFmpegPCMAudio` object from a `BytesIO` object

### Reproduction Steps
Below is a TTS command I am attempting to make. I am using the `gTTS` library to do this. Nothing wrong on the library's side - I wrote the output to a mp3 and it works as intended.

```python
@bot.command(name="speak")
@commands.guild_only()
async def speak(ctx, *args):
    msg = "".join(args)

    text = gTTS(text=msg, lang="en", slow=False)
    mp3_fp = BytesIO()
    text.write_to_fp(mp3_fp)
    text.save("audio.mp3")
    mp3_fp.seek(0)

    author = ctx.message.author
    channel = author.voice.channel
    vc = await channel.connect()

    file = discord.FFmpegPCMAudio(mp3_fp, pipe = True)
    if not vc.is_playing():
        await ctx.send(file)
        vc.play(file)
```

I get the error when I specify the `pipe = True` part

### Actual Results

```python
Ignoring exception in command speak:
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:/Users/User/Desktop/Discord Bots/Voice Disguiser/disguiser.py", line 48, in speak
    file = discord.FFmpegPCMAudio(mp3_fp, pipe=True)
  File "C:\Python36\lib\site-packages\discord\player.py", line 220, in __init__
    super().__init__(source, executable=executable, args=args, **subprocess_kwargs)
  File "C:\Python36\lib\site-packages\discord\player.py", line 133, in __init__
    self._process = self._spawn_process(args, **kwargs)
  File "C:\Python36\lib\site-packages\discord\player.py", line 139, in _spawn_process
    process = subprocess.Popen(args, **subprocess_kwargs)
  File "C:\Python36\lib\subprocess.py", line 687, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Python36\lib\subprocess.py", line 924, in _get_handles
    p2cread = msvcrt.get_osfhandle(stdin.fileno())
io.UnsupportedOperation: fileno

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\discord\ext\commands\bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Python36\lib\site-packages\discord\ext\commands\core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Python36\lib\site-packages\discord\ext\commands\core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnsupportedOperation: fileno
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by Armster15** [comment]
If anyone needs a solution, use this modified `FFmpegPCMAudio` class:
```python
import subprocess
import shlex
import io
from discord.opus import Encoder
import discord

class FFmpegPCMAudio(discord.AudioSource):
    def __init__(self, source, *, executable='ffmpeg', pipe=False, stderr=None, before_options=None, options=None):
        stdin = None if not pipe else source
        args = [executable]
        if isinstance(before_options, str):
            args.extend(shlex.split(before_options))
        args.append('-i')
        args.append('-' if pipe else source)
        args.extend(('-f', 's16le', '-ar', '48000', '-ac', '2', '-loglevel', 'warning'))
        if isinstance(options, str):
            args.extend(shlex.split(options))
        args.append('pipe:1')
        self._process = None
        try:
            self._process = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=stderr)
            self._stdout = io.BytesIO(
                self._process.communicate(input=stdin)[0]
            )
        except FileNotFoundError:
            raise discord.ClientException(executable + ' was not found.') from None
        except subprocess.SubprocessError as exc:
            raise discord.ClientException('Popen failed: {0.__class__.__name__}: {0}'.format(exc)) from exc
    def read(self):
        ret = self._stdout.read(Encoder.FRAME_SIZE)
        if len(ret) != Encoder.FRAME_SIZE:
            return b''
        return ret
    def cleanup(self):
        proc = self._process
        if proc is None:
            return
        proc.kill()
        if proc.poll() is None:
            proc.communicate()

        self._process = None
```

<br>

And I replaced
```python
file = discord.FFmpegPCMAudio(mp3_fp, pipe = True)
```

with 
```python
file = FFmpegPCMAudio(mp3_fp.read(), pipe = True)
```
