### ISSUE TITLE
Error after running for approximately 2 hours 36 minutes

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [Rapptz/discord.py#52]
After running smoothly for a very long time, I suddenly got the error:
```
Traceback (most recent call last):
  File "/home/luke/Desktop/discord/discord_main.py", line 16, in <module>
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/discord/client.py", line 542, in run
    self.ws.run()
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 427, in run
    if not self.once():
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 305, in once
    if not self.process(b):
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 362, in process
    self.close(s.closing.code, s.closing.reason)
  File "/usr/local/lib/python2.7/dist-packages/ws4py/client/__init__.py", line 198, in close
    self._write(self.stream.close(code=code, reason=reason).single(mask=True))
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 243, in _write
    self.sock.sendall(b)
  File "/usr/lib/python2.7/ssl.py", line 721, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python2.7/ssl.py", line 687, in send
    v = self._sslobj.write(data)
error: [Errno 14] Bad address
```
Normally i'm pretty good at interpreting python errors, but as I've never used any of the libraries on which discord depends, I'm having trouble. Can someone explain to me why this happens and whether this is a bug?

**Comment by no-paj** [comment]
I think it has to do with your internet connection, DNS or something.

**Comment by The-Penultimate-Defenestrator** [comment]
Maybe, there could have been a momentary lapse in Internet connection. The solution I can think of is a shell script that runs every hour which starts the script if it's not running, but I'm not exactly sure how to do this.

**Comment by no-paj** [comment]
Take a look to PM2 or Forever. It's a nodejs soft that restart your python scripts when they crash.
`pm2 start bot.py`

**Comment by The-Penultimate-Defenestrator** [comment]
Great, I'll take a look. Right now, I just put a try:except that waits a minute after the error and restarts it. I'll look into your solution.
