### ISSUE TITLE
[master] TypeError: string indices must be integers

### ISSUE THREAD

**Issue by ButterCheezii** [Rapptz/discord.py#520]
```
Traceback (most recent call last):
  File "<string>", line 9, in thing
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 2621, in create_invite
    self._fill_invite_data(data)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 2572, in _fill_invite_data
    server = self.connection._get_server(data['guild']['id'])
TypeError: string indices must be integers
```

for this code:

```py

        invite = await bot.create_invite(i)
```

where `i` is a `Server` object.

**Comment by Rapptz** [comment]
This happens on user bots. 

Discord no longer allows user bots to create invites. I'm marking this as wontfix.
