### ISSUE TITLE
bot.close() function does not work

### ISSUE THREAD

**Issue by AlabalikTR** [Rapptz/discord.py#5211]
Before I updated discord.py to 1.4.0 stable version (I was using 1.4.0 development version), my restart command which uses bot.close() function was working 
After I updated it to stable, when I used await bot.close() nothing happened. I updated it back to development version. This time, I get error.

Traceback:
`Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001DC090DBA60>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001DC090DBA60>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001DC090DBA60>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
RuntimeError: Event loop is closed`

**Comment by Gobot1234** [comment]
See https://github.com/Rapptz/discord.py/issues/5209#issuecomment-670161023
