### ISSUE TITLE
ws4py setblocking error

### ISSUE THREAD

**Issue by The-Penultimate-Defenestrator** [Rapptz/discord.py#54]
My script tries to reboot when it crashes. I frequently, on reboot, see the exception:
```
Traceback (most recent call last):
  File "/home/luke/Desktop/discord/discord_main.py", line 48, in run
    client.run()
  File "/usr/local/lib/python2.7/dist-packages/discord/client.py", line 542, in run
    self.ws.run()
  File "/usr/local/lib/python2.7/dist-packages/ws4py/websocket.py", line 420, in run
    self.sock.setblocking(True)
AttributeError: 'NoneType' object has no attribute 'setblocking'
```
Is this a bug or something on my end?

**Comment by no-paj** [comment]
How does it reboot ?

**Comment by The-Penultimate-Defenestrator** [comment]
Basically:
```
try:
    client.run()
except:
    time.sleep(60)
    client.run()
```
Except it happens recursively in a function so it can be called infinitely. I've switched to ps2 now, however.

**Comment by Rapptz** [comment]
Not my issue. Sorry.

**Comment by The-Penultimate-Defenestrator** [comment]
Ok. I've resolved my problem anyway.
