### ISSUE TITLE
Exception on start_private_message()

### ISSUE THREAD

**Issue by lmaohtp** [Rapptz/discord.py#541]
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "main.py", line 136, in on_message
    await client.start_private_message(member)
  File "/usr/lib/python3.6/site-packages/discord/client.py", line 916, in start_private_message
    data = yield from self.http.start_private_message(user.id)
  File "/usr/lib/python3.6/site-packages/discord/http.py", line 198, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400): Cannot send messages to this user

	elif message.content.startswith("$alert"):
			for member in client.get_all_members():
				await client.start_private_message(member)
				await client.send_message(member, MASS_MSG)

**Comment by Phxntxm** [comment]
Some users have the setting off per server, to allow messages to be sent to them. This is what happened here since bot's cannot have friends.

**Comment by Rapptz** [comment]
Don't make something that spam DMs every member your bot sees. It's discouraged.
