### ISSUE TITLE
RuntimeError when exiting with ^C on Rewrite

### ISSUE THREAD

**Issue by Volcyy** [Rapptz/discord.py#545]
Hello,  
I'm using rewrite with the commands extension on OS X with Python version 3.6.1, also occurs on 3.6.0. When stopping the program using `^C`, I get the following traceback:

```py
Exception in callback Client._do_cleanup()
handle: <Handle Client._do_cleanup()>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/Users/Johannes/Documents/Python/Bolt/venv/lib/python3.6/site-packages/discord/client.py", line 456, in _do_cleanup
    self.loop.run_until_complete(self.close())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

Usually it would just exit normally. I am using the decorators instead of subclassing discord.Client, but I can also try it with a subclass if that is wanted. I'm starting the Bot using `client.run('token')` as usual.

**Comment by Volcyy** [comment]
I'm getting the following now:
```py
Exception in callback <bound method Client._do_cleanup of <__main__.Bot object at 0x103b2c9b0>>
handle: <Handle Client._do_cleanup>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 47, in uvloop.loop.Handle._run (uvloop/loop.c:48351)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/client.py", line 460, in _do_cleanup
    self.loop.run_until_complete(self.close())
  File "uvloop/loop.pyx", line 1198, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25480)
  File "uvloop/loop.pyx", line 1191, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25324)
  File "uvloop/loop.pyx", line 1100, in uvloop.loop.Loop.run_forever (uvloop/loop.c:24056)
  File "uvloop/loop.pyx", line 355, in uvloop.loop.Loop._run (uvloop/loop.c:11384)
RuntimeError: this event loop is already running.
Unloaded Stream Cog.
Task exception was never retrieved
future: <Task finished coro=<AutoShardedClient.pending_reads() done, defined at /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/shard.py:184> exception=ConnectionClosed('WebSocket connection is closed: code = 1000, no reason.',)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/gateway.py", line 415, in poll_event
    msg = yield from self.recv()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/websockets/protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/shard.py", line 188, in pending_reads
    yield from shard.poll()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/shard.py", line 56, in poll
    yield from self.ws.poll_event()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/gateway.py", line 423, in poll_event
    raise ConnectionClosed(e, shard_id=self.shard_id) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1000, no reason.
```

**Comment by Volcyy** [comment]
Fixed, thanks.
