### ISSUE TITLE
Rewrite - Connection object missing attributes

### ISSUE THREAD

**Issue by AggressivelyMeows** [Rapptz/discord.py#569]
Traceback:
```py
Traceback (most recent call last):
  File ".\discord\gateway.py", line 415, in poll_event
    msg = yield from self.recv()
  File "C:\python35\lib\site-packages\websockets\protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1001, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\discord\client.py", line 350, in _connect
    yield from self.ws.poll_event()
  File ".\discord\gateway.py", line 420, in poll_event
    raise ResumeWebSocket(self.shard_id) from e
discord.gateway.ResumeWebSocket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\discord\client.py", line 501, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "C:\python35\lib\asyncio\base_events.py", line 387, in run_until_complete
    return future.result()
  File "C:\python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File ".\discord\client.py", line 453, in start
    yield from self.connect(reconnect=reconnect)
  File ".\discord\client.py", line 388, in connect
    yield from self._connect()
  File ".\discord\client.py", line 357, in _connect
    self.ws = yield from asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
  File "C:\python35\lib\asyncio\tasks.py", line 392, in wait_for
    return fut.result()
  File "C:\python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File ".\discord\gateway.py", line 202, in from_client
    ws.shard_count = client.connection.shard_count
AttributeError: 'Connection' object has no attribute 'shard_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\85v3\ABV2\bot.py", line 101, in <module>
    aradiabot.boot()
  File ".\AradiaCore.py", line 231, in boot
    self.run(config['token'])
  File ".\discord\client.py", line 505, in run
    self._do_cleanup()
  File ".\discord\client.py", line 457, in _do_cleanup
    self.loop.run_until_complete(self.close())
  File "C:\python35\lib\asyncio\base_events.py", line 387, in run_until_complete
    return future.result()
  File "C:\python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File ".\discord\client.py", line 429, in close
    for voice in self.voice_clients:
  File ".\discord\client.py", line 195, in voice_clients
    return self.connection.voice_clients
AttributeError: 'Connection' object has no attribute 'voice_clients'
```
It printed this automatically, I presume discord dropped the connection.

**Comment by Rapptz** [comment]
Don't overshadow `Client.connection`.
