### ISSUE TITLE
How to use pins_from()

### ISSUE THREAD

**Issue by shrx** [Rapptz/discord.py#570]
I have this code:
```python
            if channel.id == myChannel:
                pins = self.pins_from(channel)
                for pin in pins:
                    print(pin)
```
The code fails with:

```
<Future pending>
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bin/discordBotClass.py", line 201, in on_message
    for pin in pins:
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 1544, in pins_from
    data = yield from self.http.pins_from(channel.id)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 136, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 304, in connect
    yield from self._create_connection(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 578, in _create_connection
    transport, proto = yield from self._create_direct_connection(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 601, in _create_direct_connection
    local_addr=self._local_addr)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 729, in create_connection
    yield from tasks.wait(fs, loop=self)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 355, in wait
    return (yield from _wait(fs, timeout, return_when, loop))
  File "/usr/lib/python3.5/asyncio/tasks.py", line 438, in _wait
    yield from waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 381, in __iter__
    assert self.done(), "yield from wasn't used with future"
AssertionError: yield from wasn't used with future

```

How do I get a list of pins?

**Comment by Pandentia** [comment]
it's an asynchronous iterator, so use "async for" instead of "for"

**Comment by Rapptz** [comment]
I know this is closed, but @Pandentia answer was incorrect.

You are just missing an `await`.

**Comment by Pandentia** [comment]
Is it? My bad, I assumed due to similar naming to logs_from that it would
also be an async generator.
