### ISSUE TITLE
Event called after session to discord is closed

### ISSUE THREAD

**Issue by alkatar21** [Rapptz/discord.py#5786]
### Summary
A bot should attach a reaction to a command. With a logout command, however, this is apparently done after the session to discord is closed.

### Reproduction Steps
```py
from discord import NotFound, Forbidden
from discord.ext.commands import Bot as BotBase
from discord.ext.commands import Cog, command
import logging

logging.basicConfig(level=logging.DEBUG)
logging.getLogger('discord').setLevel(logging.INFO)
logging.getLogger('discord.gateway').setLevel(logging.WARNING)

class Bot(BotBase):
    async def close(self):
        logging.info('Called bot.close')
        await super().close()
        logging.info('Finished bot.close')

    async def on_error(self, event: str, *args, **kwargs):
        logging.error(f"Called on_error in `{event}`, {args}, {kwargs}", exc_info=True)

class Example(Cog):
    @Cog.listener()
    async def on_ready(self):
        logging.info('Ready...')

    @Cog.listener()
    async def on_command(self, ctx):
        logging.debug('Called on_command.')
        try:
            await ctx.message.add_reaction('👀')
        except (NotFound, Forbidden):
            pass  # deleted, no reactions allowed
        return

    @command()
    async def quit(self, ctx):
        await ctx.bot.logout()

if __name__ == '__main__':
    bot = Bot('!')
    bot.add_cog(Example())
    bot.run(<Token>)
```

### Expected Results

Either that no reaction is added, or that it is added while it is still possible.

### Actual Results
```
INFO:root:Ready...
INFO:root:Called bot.close
DEBUG:root:Called on_command.
ERROR:root:Called on_error in `on_command`, (<discord.ext.commands.context.Context object>,), {}
Traceback (most recent call last):
  File "...\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File ".../test.py", line 34, in on_command
    await ctx.message.add_reaction('👀')  # :eyes:
  File "...\discord\message.py", line 953, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "...\discord\http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "...\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "...\aiohttp\client.py", line 357, in _request
    raise RuntimeError('Session is closed')
RuntimeError: Session is closed
INFO:root:Finished bot.close
INFO:discord.client:Cleaning up tasks.
INFO:discord.client:Closing the event loop.
```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

### System Information

- Python v3.8.3-final
- discord.py v1.4.1-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041

Also tested on a unix system

**Comment by Rapptz** [comment]
Events can be called at any point since they're fire and forget. Realistically speaking what ended up happening here was your on_command event was fired but on hold, it context switched to within the command, logged off, context switched back to the on_command handler and by that point the state had already changed. 

There are no guarantees for this reason.

**Comment by Kaytuu** [comment]
You can actually use `asyncio.run_coroutine_threadsafe` to avoid this:

```py
asyncio.run_coroutine_threadsafe(ctx.bot.logout(), ctx.bot.loop)
```

it uses `loop.call_soon_threadsafe` internally, so `on_command_completion` will fire before the coroutine is executed.
