### ISSUE TITLE
bug beim starting

### ISSUE THREAD

**Issue by Markus1990mg** [Rapptz/discord.py#5792]
### Summary

Traceback (most recent call last):
  File "discord_bot.py", line 1, in <module>
    import discord
  File "/usr/local/lib/python3.5/dist-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 34, in <module>
    import aiohttp
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 12, in <module>
    from typing import (  # noqa
ImportError: cannot import name 'Coroutine'

### Checklist

- [ ] I have searched the open issues for duplicates.
- [ ] I have shown the entire traceback, if possible.
- [ ] I have removed my token from display, if visible.

**Comment by AbstractUmbra** [comment]
You are using a Python version < the current supported version for latest.
You need a minimum of 3.5.3+. The issue you currently see if the lack of support for your version within `aiohttp`, one of Discord.py dependencies.

I'd suggest a later Python version, such as 3.8.
