### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'ack'

### ISSUE THREAD

**Issue by SamSanai** [Rapptz/discord.py#5800]
### Summary

At random times every other day I get this error and it just shuts down one of my clusters having to restart it. Only started happening a week maybe 2 ago.

### Reproduction Steps

Happens while the bot is running no idea how to reproduce it.

### Expected Results

Bot running as usual without an issue.

### Actual Results
Traceback:
```
2020-09-08 09:18:22   -   ready to go...

Traceback (most recent call last):
  File "voicemaster.py", line 264, in <module>
    bot.run(bot_token)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 678, in run
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 658, in runner
    await self.start(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/client.py", line 622, in start
    await self.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.6/dist-packages/discord/shard.py", line 414, in connect
    raise item.error
  File "/usr/local/lib/python3.6/dist-packages/discord/shard.py", line 140, in worker
    await self.ws.poll_event()
  File "/usr/local/lib/python3.6/dist-packages/discord/gateway.py", line 504, in poll_event
    await self.received_message(msg.data)
  File "/usr/local/lib/python3.6/dist-packages/discord/gateway.py", line 401, in received_message
    self._keep_alive.ack()
AttributeError: 'NoneType' object has no attribute 'ack'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f88a6110828>
```
logging.INFO logs:

```
2020-09-08 09:15:16,922:WARNING:discord.client: PyNaCl is not installed, voice will NOT be supported
2020-09-08 09:15:16,978:INFO:discord.client: logging in using static token
2020-09-08 09:15:17,161:INFO:discord.gateway: Shard ID 20 has sent the IDENTIFY payload.
2020-09-08 09:15:19,908:INFO:discord.gateway: Shard ID 20 has connected to Gateway: ["gateway-prd-main-2j63",{"micros":2706904,"calls":["discord-sessions-prd-2-8",{"micros":2698737,"calls":["start_session",{"micros":312750,"calls":["api-prd-main-h0tw",{"micros":309532,"calls":["get_user",{"micros":2331},"add_authorized_ip",{"micros":1428},"get_guilds",{"micros":274016},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":247,"calls":[]},"presence_connect",{"micros":2,"calls":[]}]}]}] (Session ID: f24b951795256219ffd2ff261f316e58).
2020-09-08 09:15:22,497:INFO:discord.gateway: Shard ID 21 has sent the IDENTIFY payload.
2020-09-08 09:15:25,932:INFO:discord.gateway: Shard ID 21 has connected to Gateway: ["gateway-prd-main-1m02",{"micros":3052390,"calls":["discord-sessions-prd-2-37",{"micros":3045827,"calls":["start_session",{"micros":330474,"calls":["api-prd-main-6vkw",{"micros":327521,"calls":["get_user",{"micros":3166},"add_authorized_ip",{"micros":3395},"get_guilds",{"micros":289982},"coros_wait",{"micros":2}]}]},"guilds_connect",{"micros":316,"calls":[]},"presence_connect",{"micros":2,"calls":[]}]}]}] (Session ID: 5c2a13dee95a5e8806c5851fe4304a46).
2020-09-08 09:15:29,782:INFO:discord.gateway: Shard ID 22 has sent the IDENTIFY payload.
2020-09-08 09:15:32,499:INFO:discord.gateway: Shard ID 22 has connected to Gateway: ["gateway-prd-main-s26j",{"micros":2411567,"calls":["discord-sessions-prd-2-14",{"micros":2410148,"calls":["start_session",{"micros":344898,"calls":["api-prd-main-2zjb",{"micros":341073,"calls":["get_user",{"micros":4378},"add_authorized_ip",{"micros":1150},"get_guilds",{"micros":301009},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":327,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 847f17168c4fed7002bfb2ee090ce6d5).
2020-09-08 09:15:38,889:INFO:discord.gateway: Shard ID 23 has sent the IDENTIFY payload.
2020-09-08 09:15:41,996:INFO:discord.gateway: Shard ID 23 has connected to Gateway: ["gateway-prd-main-03dm",{"micros":2696066,"calls":["discord-sessions-prd-2-64",{"micros":2693648,"calls":["start_session",{"micros":364325,"calls":["api-prd-main-p2gv",{"micros":360985,"calls":["get_user",{"micros":2164},"add_authorized_ip",{"micros":1576},"get_guilds",{"micros":302213},"coros_wait",{"micros":2}]}]},"guilds_connect",{"micros":294,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 312d352583211747b4ab9b5f368f6f16).
2020-09-08 09:15:49,855:INFO:discord.gateway: Shard ID 24 has sent the IDENTIFY payload.
2020-09-08 09:15:53,051:INFO:discord.gateway: Shard ID 24 has connected to Gateway: ["gateway-prd-main-tm2c",{"micros":2780324,"calls":["discord-sessions-prd-2-55",{"micros":2778892,"calls":["start_session",{"micros":702783,"calls":["api-prd-main-wt4c",{"micros":362976,"calls":["get_user",{"micros":9065},"add_authorized_ip",{"micros":3078},"get_guilds",{"micros":285071},"coros_wait",{"micros":2}]}]},"guilds_connect",{"micros":334,"calls":[]},"presence_connect",{"micros":2,"calls":[]}]}]}] (Session ID: 9ca5f871f05ff3f3e13a37c03838f3ae).
2020-09-08 09:16:02,620:INFO:discord.gateway: Shard ID 25 has sent the IDENTIFY payload.
2020-09-08 09:16:10,111:INFO:discord.gateway: Shard ID 25 has connected to Gateway: ["gateway-prd-main-z971",{"micros":2477527,"calls":["discord-sessions-prd-2-30",{"micros":2471539,"calls":["start_session",{"micros":389085,"calls":["api-prd-main-pt6w",{"micros":383349,"calls":["get_user",{"micros":7201},"add_authorized_ip",{"micros":1152},"get_guilds",{"micros":323830},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":367,"calls":[]},"presence_connect",{"micros":2,"calls":[]}]}]}] (Session ID: 655f3edcde8af9dd334f89ff94b79290).
2020-09-08 09:16:23,644:INFO:discord.gateway: Shard ID 26 has sent the IDENTIFY payload.
2020-09-08 09:16:27,988:INFO:discord.gateway: Shard ID 26 has connected to Gateway: ["gateway-prd-main-lnn3",{"micros":3144030,"calls":["discord-sessions-prd-2-83",{"micros":3117874,"calls":["start_session",{"micros":363126,"calls":["api-prd-main-cw38",{"micros":358212,"calls":["get_user",{"micros":4005},"add_authorized_ip",{"micros":2811},"get_guilds",{"micros":300032},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":290,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 2bec50d228c730b3be390b4d57d4faa5).
2020-09-08 09:16:30,951:WARNING:discord.gateway: Can't keep up, shard ID 21 websocket is 31.9s behind.
2020-09-08 09:16:35,969:WARNING:discord.gateway: Can't keep up, shard ID 22 websocket is 23.7s behind.
2020-09-08 09:16:47,269:INFO:discord.gateway: Shard ID 27 has sent the IDENTIFY payload.
2020-09-08 09:16:48,628:WARNING:discord.gateway: Can't keep up, shard ID 27 websocket is 11.5s behind.
2020-09-08 09:16:51,405:INFO:discord.gateway: Shard ID 27 has connected to Gateway: ["gateway-prd-main-kb8w",{"micros":2946426,"calls":["discord-sessions-prd-2-90",{"micros":2944703,"calls":["start_session",{"micros":348158,"calls":["api-prd-main-txfb",{"micros":344844,"calls":["get_user",{"micros":2055},"add_authorized_ip",{"micros":1363},"get_guilds",{"micros":306547},"coros_wait",{"micros":2}]}]},"guilds_connect",{"micros":321,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 3a50213defa37b7503ad9b5eed18fe0a).
2020-09-08 09:16:56,861:WARNING:discord.gateway: Shard ID 23 has stopped responding to the gateway. Closing and restarting.
2020-09-08 09:16:58,210:INFO:discord.gateway: Websocket closed with 4000, attempting a reconnect.
2020-09-08 09:17:07,911:WARNING:discord.gateway: Shard ID 24 has stopped responding to the gateway. Closing and restarting.
2020-09-08 09:17:09,297:INFO:discord.gateway: Shard ID 28 has sent the IDENTIFY payload.
2020-09-08 09:17:16,513:INFO:discord.gateway: Websocket closed with 4000, attempting a reconnect.
2020-09-08 09:17:16,797:WARNING:discord.gateway: Can't keep up, shard ID 28 websocket is 15.3s behind.
2020-09-08 09:17:16,798:INFO:discord.gateway: Shard ID 28 has connected to Gateway: ["gateway-prd-main-5xkz",{"micros":2773752,"calls":["discord-sessions-prd-2-2",{"micros":2768516,"calls":["start_session",{"micros":444463,"calls":["api-prd-main-cp73",{"micros":433409,"calls":["get_user",{"micros":4161},"add_authorized_ip",{"micros":8450},"get_guilds",{"micros":334813},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":368,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: 2c8d94c5c250be742700228c907ccd2f).
2020-09-08 09:17:20,630:WARNING:discord.gateway: Shard ID 25 has stopped responding to the gateway. Closing and restarting.
2020-09-08 09:17:21,431:INFO:discord.gateway: Websocket closed with 4000, attempting a reconnect.
2020-09-08 09:17:25,242:WARNING:discord.gateway: Can't keep up, shard ID 20 websocket is 43.4s behind.
2020-09-08 09:17:31,898:INFO:discord.gateway: Shard ID 29 has sent the IDENTIFY payload.
2020-09-08 09:17:32,194:INFO:discord.shard: Got a request to RESUME the websocket at Shard ID 23.
2020-09-08 09:17:41,700:INFO:discord.gateway: Shard ID 29 has connected to Gateway: ["gateway-prd-main-lvh8",{"micros":2956798,"calls":["discord-sessions-prd-1-3",{"micros":2952611,"calls":["start_session",{"micros":401718,"calls":["api-prd-main-t21x",{"micros":398278,"calls":["get_user",{"micros":8808},"add_authorized_ip",{"micros":2558},"get_guilds",{"micros":330566},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":196,"calls":[]},"presence_connect",{"micros":2,"calls":[]}]}]}] (Session ID: a1facf6bf240fa85226ab6b11ca5b415).
2020-09-08 09:17:46,242:WARNING:discord.gateway: Shard ID 26 has stopped responding to the gateway. Closing and restarting.
2020-09-08 09:17:47,589:INFO:discord.gateway: Websocket closed with 4000, attempting a reconnect.
2020-09-08 09:17:53,235:INFO:discord.gateway: Shard ID 23 has sent the RESUME payload.
2020-09-08 09:17:53,737:INFO:discord.shard: Got a request to RESUME the websocket at Shard ID 24.
2020-09-08 09:17:57,557:INFO:discord.gateway: Shard ID 23 session has been invalidated.
2020-09-08 09:17:59,644:INFO:discord.gateway: Shard ID 24 has sent the RESUME payload.
2020-09-08 09:18:00,022:INFO:discord.shard: Got a request to RESUME the websocket at Shard ID 25.
2020-09-08 09:18:02,231:WARNING:discord.gateway: Shard ID 27 has stopped responding to the gateway. Closing and restarting.
2020-09-08 09:18:03,105:INFO:discord.gateway: Websocket closed with 4000, attempting a reconnect.
2020-09-08 09:18:10,635:INFO:discord.gateway: Shard ID 24 session has been invalidated.
2020-09-08 09:18:11,397:INFO:discord.gateway: Shard ID 25 has sent the RESUME payload.
2020-09-08 09:18:11,685:INFO:discord.shard: Got a request to RESUME the websocket at Shard ID 26.
2020-09-08 09:18:15,388:WARNING:discord.gateway: Can't keep up, shard ID 28 websocket is 27.4s behind.
2020-09-08 09:18:16,078:INFO:discord.gateway: Shard ID 26 has sent the RESUME payload.
2020-09-08 09:18:16,274:INFO:discord.gateway: Shard ID 25 session has been invalidated.
2020-09-08 09:18:16,672:INFO:discord.shard: Got a request to RESUME the websocket at Shard ID 27.
2020-09-08 09:18:18,375:INFO:discord.gateway: Shard ID 27 has sent the RESUME payload.
2020-09-08 09:18:18,406:INFO:discord.shard: Got a request to IDENTIFY the websocket at Shard ID 23.
2020-09-08 09:18:20,247:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 732729941413593149. Discarding.
2020-09-08 09:18:20,774:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 707974029482524843. Discarding.
2020-09-08 09:18:21,694:WARNING:discord.gateway: Can't keep up, shard ID 29 websocket is 10.9s behind.
2020-09-08 09:18:22,103:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 613807479318511656. Discarding.
2020-09-08 09:18:22,147:INFO:discord.gateway: Shard ID 26 session has been invalidated.
2020-09-08 09:18:22,464:INFO:discord.gateway: Shard ID 27 session has been invalidated.
2020-09-08 09:18:22,516:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 476282438457360385. Discarding.
2020-09-08 09:18:25,191:INFO:discord.gateway: Shard ID 23 has sent the IDENTIFY payload.
2020-09-08 09:18:25,193:INFO:discord.shard: Got a request to IDENTIFY the websocket at Shard ID 24.
2020-09-08 09:18:27,509:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 720159593443098665. Discarding.
2020-09-08 09:18:28,119:INFO:discord.gateway: Shard ID 23 has connected to Gateway: ["gateway-prd-main-l5rc",{"micros":2867935,"calls":["discord-sessions-prd-2-35",{"micros":2865720,"calls":["start_session",{"micros":288478,"calls":["api-prd-main-2zjb",{"micros":285912,"calls":["get_user",{"micros":2310},"add_authorized_ip",{"micros":1390},"get_guilds",{"micros":260897},"coros_wait",{"micros":2}]}]},"guilds_connect",{"micros":243,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: b2c22c0533f5b4fffa174e24d6cbf73e).
2020-09-08 09:18:37,268:INFO:discord.gateway: Shard ID 24 has sent the IDENTIFY payload.
2020-09-08 09:18:37,579:INFO:discord.shard: Got a request to IDENTIFY the websocket at Shard ID 26.
2020-09-08 09:18:38,317:WARNING:discord.gateway: Can't keep up, shard ID 24 websocket is 13.0s behind.
2020-09-08 09:18:40,930:INFO:discord.gateway: Shard ID 24 has connected to Gateway: ["gateway-prd-main-0qhl",{"micros":2662003,"calls":["discord-sessions-prd-1-15",{"micros":2657197,"calls":["start_session",{"micros":309374,"calls":["api-prd-main-nssz",{"micros":305972,"calls":["get_user",{"micros":2500},"add_authorized_ip",{"micros":1273},"get_guilds",{"micros":282041},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":360,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: cc18d29da330c64934aa86f7122e4d88).
2020-09-08 09:18:48,477:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 142280884219805696. Discarding.
2020-09-08 09:18:56,331:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 690959611716436019. Discarding.
2020-09-08 09:19:01,910:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 402079984807575552. Discarding.
2020-09-08 09:19:02,859:INFO:discord.gateway: Shard ID 26 has sent the IDENTIFY payload.
2020-09-08 09:19:03,209:INFO:discord.shard: Got a request to IDENTIFY the websocket at Shard ID 25.
2020-09-08 09:19:03,803:WARNING:discord.gateway: Can't keep up, shard ID 26 websocket is 10.4s behind.
2020-09-08 09:19:07,360:INFO:discord.gateway: Shard ID 26 has connected to Gateway: ["gateway-prd-main-59ft",{"micros":3516608,"calls":["discord-sessions-prd-1-10",{"micros":3514130,"calls":["start_session",{"micros":754318,"calls":["api-prd-main-nnm0",{"micros":750671,"calls":["get_user",{"micros":3096},"add_authorized_ip",{"micros":2333},"get_guilds",{"micros":697028},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":286,"calls":[]},"presence_connect",{"micros":2,"calls":[]}]}]}] (Session ID: 4af5cdea8c3f10c0328addb89994ee0e).
2020-09-08 09:19:14,764:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 662371003409760298. Discarding.
2020-09-08 09:19:17,656:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 347563165615390732. Discarding.
2020-09-08 09:19:18,095:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 717220354669674556. Discarding.
2020-09-08 09:19:22,804:INFO:discord.gateway: Shard ID 25 has sent the IDENTIFY payload.
2020-09-08 09:19:23,309:INFO:discord.shard: Got a request to IDENTIFY the websocket at Shard ID 27.
2020-09-08 09:19:26,123:INFO:discord.gateway: Shard ID 25 has connected to Gateway: ["gateway-prd-main-ftqk",{"micros":2460180,"calls":["discord-sessions-prd-2-70",{"micros":2458583,"calls":["start_session",{"micros":373347,"calls":["api-prd-main-9s61",{"micros":368662,"calls":["get_user",{"micros":4199},"add_authorized_ip",{"micros":1873},"get_guilds",{"micros":321653},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":319,"calls":[]},"presence_connect",{"micros":2,"calls":[]}]}]}] (Session ID: 71f3a176f23bbb281df009276079bc86).
2020-09-08 09:19:44,557:WARNING:discord.gateway: Shard ID 23 has stopped responding to the gateway. Closing and restarting.
2020-09-08 09:19:46,723:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 535151998199136282. Discarding.
2020-09-08 09:19:47,999:INFO:discord.gateway: Websocket closed with 4000, attempting a reconnect.
2020-09-08 09:19:48,000:INFO:discord.gateway: Shard ID 27 has sent the IDENTIFY payload.
2020-09-08 09:19:48,429:INFO:discord.shard: Got a request to RESUME the websocket at Shard ID 23.
2020-09-08 09:19:49,931:WARNING:discord.gateway: Can't keep up, shard ID 27 websocket is 10.1s behind.
2020-09-08 09:19:52,242:INFO:discord.gateway: Shard ID 27 has connected to Gateway: ["gateway-prd-main-fk5n",{"micros":2813932,"calls":["discord-sessions-prd-2-17",{"micros":2809549,"calls":["start_session",{"micros":282855,"calls":["api-prd-main-4mft",{"micros":279794,"calls":["get_user",{"micros":2090},"add_authorized_ip",{"micros":1841},"get_guilds",{"micros":254247},"coros_wait",{"micros":1}]}]},"guilds_connect",{"micros":227,"calls":[]},"presence_connect",{"micros":1,"calls":[]}]}]}] (Session ID: c681f4c09860e4d9ecac30c61d9524f8).
2020-09-08 09:19:59,392:WARNING:discord.gateway: Shard ID 24 has stopped responding to the gateway. Closing and restarting.
2020-09-08 09:20:01,288:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 165119165286318080. Discarding.
2020-09-08 09:20:01,320:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 709618535789363202. Discarding.
2020-09-08 09:20:01,508:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 665423770273579041. Discarding.
2020-09-08 09:20:04,283:WARNING:discord.state: GUILD_MEMBER_UPDATE referencing an unknown member ID: 442417222317637642. Discarding.
2020-09-08 09:20:09,452:INFO:discord.gateway: Shard ID 23 has sent the RESUME payload.
2020-09-08 09:20:12,752:INFO:discord.client: Cleaning up tasks.
2020-09-08 09:20:12,752:INFO:discord.client: Cleaning up after 6 tasks.
2020-09-08 09:20:12,773:INFO:discord.client: All tasks finished cancelling.
2020-09-08 09:20:12,773:INFO:discord.client: Closing the event loop.
```

### Checklist

- [x ] I have searched the open issues for duplicates.
- [x ] I have shown the entire traceback, if possible.
- [x ] I have removed my token from display, if visible.

### System Information

- Python v3.6.9-final
- discord.py v1.4.1-final
- aiohttp v3.6.2
- system info: Linux 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019

**Comment by Rapptz** [comment]
This should be unlikely to happen but it might be a regression from switching over to aiohttp from websockets. There's no harm in guarding these though.
