### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by CommandaPanda** [Rapptz/discord.py#583]
Hey, 
I'm still rather new to python and pip, but when I try to install discord.py I get this error? 
I'm using `python -m pip install -U discord.py`

`python -m pip install -U discord.py[voice]
Collecting discord.py[voice]
  Using cached discord.py-0.16.8.tar.gz
Collecting aiohttp<1.1.0,>=1.0.0 (from discord.py[voice])
  Using cached aiohttp-1.0.5.tar.gz
Collecting websockets<4.0,>=3.1 (from discord.py[voice])
  Using cached websockets-3.3-py33.py34.py35.py36-none-any.whl
Collecting PyNaCl==1.0.1 (from discord.py[voice])
  Using cached PyNaCl-1.0.1-cp36-cp36m-win_amd64.whl
Collecting chardet (from aiohttp<1.1.0,>=1.0.0->discord.py[voice])
  Using cached chardet-3.0.3-py2.py3-none-any.whl
Collecting multidict>=2.0 (from aiohttp<1.1.0,>=1.0.0->discord.py[voice])
  Using cached multidict-2.1.6-cp36-cp36m-win_amd64.whl
Collecting async_timeout (from aiohttp<1.1.0,>=1.0.0->discord.py[voice])
  Using cached async_timeout-1.2.1-py3-none-any.whl
Collecting six (from PyNaCl==1.0.1->discord.py[voice])
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting cffi>=1.1.0 (from PyNaCl==1.0.1->discord.py[voice])
  Using cached cffi-1.10.0-cp36-cp36m-win_amd64.whl
Collecting pycparser (from cffi>=1.1.0->PyNaCl==1.0.1->discord.py[voice])
  Using cached pycparser-2.17.tar.gz
Installing collected packages: chardet, multidict, async-timeout, aiohttp, websockets, six, pycparser, cffi, PyNaCl, discord.py
Exception:
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Program Files\Python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Program Files\Python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Program Files\Python36\lib\site-packages\pip\req\req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "C:\Program Files\Python36\lib\site-packages\pip\req\req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "C:\Program Files\Python36\lib\site-packages\pip\wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "C:\Program Files\Python36\lib\site-packages\pip\wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "C:\Program Files\Python36\lib\site-packages\pip\utils\__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "C:\Program Files\Python36\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Python36\\Lib\\site-packages\\chardet'`

**Comment by Helehelehele** [comment]
> `PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Python36\\Lib\\site-packages\\chardet'`

Even though your account may have administrator permissions, it's not enough for Windows. You need to run your command prompt as administrator.

**Comment by CommandaPanda** [comment]
Oh I am an idiot. Thanks for the help
