### ISSUE TITLE
ImportError: cannot import name '_Quoter'

### ISSUE THREAD

**Issue by UnknownPlayer78** [Rapptz/discord.py#5859]
## Summary

When I try to run the examaple discord bot from Github its gives me this error.

## Reproduction Steps

1. Copy the code from Github (discord.py/examples/basic_bot.py)
2. Run the bot.

## Expected Results

The bot just runs without any errors.

## Actual Results

`$ python3 bot.py`
```
Traceback (most recent call last):
  File "bot.py", line 2, in <module>
    import discord
  File "/home/user/.local/lib/python3.6/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/home/user/.local/lib/python3.6/site-packages/discord/client.py", line 34, in <module>
    import aiohttp
  File "/home/user/.local/lib/python3.6/site-packages/aiohttp/__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "/home/user/.local/lib/python3.6/site-packages/aiohttp/client.py", line 30, in <module>
    from yarl import URL
  File "/home/user/.local/lib/python3.6/site-packages/yarl/__init__.py", line 1, in <module>
    from ._url import URL, cache_clear, cache_configure, cache_info
  File "/home/user/.local/lib/python3.6/site-packages/yarl/_url.py", line 14, in <module>
    from ._quoting import _Quoter, _Unquoter
ImportError: cannot import name '_Quoter'
```

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

## System Information

OS: `Ubuntu Server 18.04.5 LTS x86_64`
Python version: `Python 3.6.9`
Discord.py version: `1.4.1`

**Comment by Vexs** [comment]
This isn't an issue with discord.py- something's wrong with the `yarl` module in your environment. Try reinstalling `yarl`, but further debugging should be done in one of our support guilds- [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api)

**Comment by UnknownPlayer78** [comment]
Thank you very much thats solved the issue. I tried to reinstall it many times but I never though about removing the cache.
