### ISSUE TITLE
Help creating a command with voice_client

### ISSUE THREAD

**Issue by shotbyapony** [Rapptz/discord.py#595]
Please inform me if this is in the wrong place.

I am trying to create a command that makes a bot join the voice channel of the user that sent the command, play a music file from my computer(or downloaded from youtube, but I prefer the first way), and then leave the voice channel after it is done(like air horn bot does, but it uses discord go and I want to use discord py). I have spliced together the cmd_summon and cmd_disconnect from the bot https://github.com/Just-Some-Bots/MusicBot (I am using this bot as a template). I’ve spent hours upon hours looking through the code of the cmd_play command and I’ve scoured the internet for the code lines that plays the music through the bot, so this really is my last resort.

Please help me, as I’m seriously losing my mind over this. Again, if this is in the wrong place to please tell me and I’ll move it wherever.

Thanks

**Comment by tirel22** [comment]
Hello! You mean something like this? : 
```
async def play_audio_file(audio_file, get_voice_channel_id, audio_duration):
    try:
        voice = await client.join_voice_channel(get_voice_channel_id)
        player = voice.create_ffmpeg_player(audio_file)
        player.start()
        await asyncio.sleep(audio_duration)
        await voice.disconnect()
    except:
        return False
```
- The 'audio file' argument is a string, which is the path to your file.
- voice channel id is the desired voice channel to join(see below how to do it)
-audio_duration is an int that will be manually entered by you for every file.

Now, your next question. How do you get the voice channel id of the user who summoned the bot? I will recommend creating some kind of class with all the info you need , like:

```
class GetInfo:
    def __init__(self, message):
        self.user_voice_ch_id = message.author.voice_channel.id
        self.user_server_id = message.author.server.id
        self.message_content = message.content
        self.message = message
        self.channel = client.get_channel(self.user_voice_ch_id)
```
(Note that 'message' is an argument in the "on_message(message)" function)
Then you can create an instance of that class in the on_message function:

`info = GetInfo(message)`

And now you can call the play_audio_file function:

`await play_audio_file('foo.mp3', info.channel, 5 )`

The OOP is not neccesary, but I think it makes the code much more organized. Also, if you want to inharate from this class you will need to pass the aditional arguments. If you only want to get the voice channel id of the user, just do:

```
async def play_audio_file(audio_file, voice_channel_id, audio_duration):
    channel = client.get_channel(voice_channel_id)
    voice = await client.join_voice_channel(voice_channel_id)
    ...
```
Hope you find this usefull. Also, you need to have the depedencies: Opuslib, ffmpeg. Have a nice day!

**Comment by shotbyapony** [comment]
@tirel22 
> The 'audio file' argument is a string, which is the path to your file.
What do you mean by path? Like the C:\Users\mason\MusicBot\startxp.mp3? I get this as an error when I run it.
`SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape`

**Comment by tirel22** [comment]
@shotbyapony The path is starting from your .py file. If you have a file in a directory in /home/Documents, or, in your case,  C:\Users\mason\MusicBot\ , you need to specify the path from there. If the audio file is in the same directory, just put 'startxp.mp3'

**Comment by shotbyapony** [comment]
@tirel22 
`Connecting...Traceback (most recent call last):
  File "run.py", line 165, in main
    m.run()
  File "C:\Users\mason\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 487, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "C:\Users\mason\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 337, in run_until_complete
    return future.result()
  File "C:\Users\mason\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Users\mason\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\mason\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 458, in start
    yield from self.login(*args, **kwargs)
  File "C:\Users\mason\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 386, in login
    raise TypeError('login() takes 1 or 2 positional arguments but {} were given'.format(n))
TypeError: login() takes 1 or 2 positional arguments but 0 were given
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001E10915F550>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000001E10915F748>`

I get this error when I try to run the bot with the info = GetInfo(message)

**Comment by Hyperclaw79** [comment]
@shotbyapony 
> What do you mean by path? Like the C:\Users\mason\MusicBot\startxp.mp3? I get this as an error when I run it.
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

use \\ instead of \ as '\' is used to denote....let's say, start of an escape character like '\n'. so you have to use \\ to specify that you actually want a \ there.

**Comment by shotbyapony** [comment]
@Hyperclaw79 The problem is in the bot.py, not any other file. The error only occurs when I add the class that @tirel22 told me to add. I've added it right below the class SkipStates, Response, and MusicBot. If you would like the entire bot.py file, I'll upload it to pastebin.

**Comment by Hyperclaw79** [comment]
@shotbyapony Hmm, this is weird. The error and the info instance don't seem to match. Try getting rid of the GetInfo class and just call the other function like he mentioned. But with a few changes:

```py
import discord
import asyncio

#make sure everything below this, are within the bot's class.

async def play_song(self, message):
    try:
        id = message.author.voice_channel.id
        voice = await self.join_voice_channel(id)
        player = voice.create_ffmpeg_player("Insert path to audio file.")
        player.start()
        await asyncio.sleep(audio_duration)
        await voice.disconnect()
    except Exception as e:
        await self.send_message(message.channel,str(e))

async def on_message(self,message):
   if message.content.lowercase().strip() == "play a song":
      await self.play_song(self,message)
```
Try using the modified code and let me know what error you get this time.

**Comment by shotbyapony** [comment]
@Hyperclaw79 No error. What is the command though to make it all happen?

**Comment by Hyperclaw79** [comment]
@shotbyapony since I don't know your command prefix and way you're handling it, I just made the trigger a simple message. The user has to type "Play a song" (only that and nothing else).

**Comment by shotbyapony** [comment]
Saying "play a song" doesn't do anything but when I run a command (like .help) I get this error
`Traceback (most recent call last):
  File "C:\Users\mason\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\mason\MusicBot\musicbot\bot.py", line 2168, in on_message
    if message.content.lowercase().strip() == "play a song":
AttributeError: 'str' object has no attribute 'lowercase'`

Also, I will link you to my bot.py - https://pastebin.com/KR8GDDym use ctrl f to find what you need, async def cmd_(name) is used to define commands and the command prefix is ".". Please try to make it an actual command and not a chat scanner as a scanner is more resource demanding.

**Comment by Hyperclaw79** [comment]
@shotbyapony 

https://pastebin.com/Z9g1WrFR

1. Added the command
2. The very on_message function itself is a chat scanner, for example, it checks if the message author is the bot. 
3. Codeshare.io is way better to share and dynamically alter codes than Pastebin.
4. It was .lower() not lowercase() 😅

**Comment by shotbyapony** [comment]
@Hyperclaw79 https://codeshare.io/2KjmNN Can you make it so that I can just do await play_audio_file('foo.mp3', info.channel, 5 ) inside of a pre-existing command to make it do everything else on its own(plug in the file name, channel, and duration) based on the arguments of play_audio_file or whatever and call it all on its own? Like @tirel22 has, but without the class that crashes it.

**Comment by Rapptz** [comment]
This place is for posting issues regarding the library -- not spoonfeeding or asking for code about how to make a certain component of your bot work. Sorry.
