### ISSUE TITLE
socket.gaierror: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by EdwardChamberlain** [Rapptz/discord.py#5960]
## Summary

DPY (maybe) causes network disconnection. 

## Reproduction Steps

Unsure

## Expected Results

stable operation. 

## Actual Results

Stable operation with dropouts for an hour or so every 12 hours. 

traceback: 
```
2020-10-22 16:49:30,832 --- Got a request to RESUME the websocket.
2020-10-22 16:49:31,155 --- Shard ID None has sent the RESUME payload.
2020-10-22 16:49:31,258 --- Shard ID None has successfully RESUMED session 4af4e7e4a2de7e79f79ac055f8695fa1 under trace ["gateway-prd-main-zh6z",{"micros":1423,"calls":["discord-sessions-prd-2-93",{"micros":17}]}].
```
```
2020-10-22 19:27:36,094 --- Got a request to RESUME the websocket.
2020-10-22 19:27:36,399 --- Shard ID None has sent the RESUME payload.
2020-10-22 19:27:36,516 --- Shard ID None has successfully RESUMED session 4af4e7e4a2de7e79f79ac055f8695fa1 under trace ["gateway-prd-main-rwmc",{"micros":1746,"calls":["discord-sessions-prd-2-93",{"micros":27}]}].
2020-10-22 19:59:29,011 --- Got a request to RESUME the websocket.
2020-10-22 19:59:29,328 --- Shard ID None has sent the RESUME payload.
2020-10-22 19:59:29,438 --- Shard ID None has successfully RESUMED session 4af4e7e4a2de7e79f79ac055f8695fa1 under trace ["gateway-prd-main-pwhw",{"micros":6749,"calls":["discord-sessions-prd-2-93",{"micros":18}]}].
```
```
2020-10-22 22:59:21,353 --- Got a request to RESUME the websocket.
2020-10-22 22:59:21,675 --- Shard ID None has sent the RESUME payload.
2020-10-22 22:59:21,778 --- Shard ID None has successfully RESUMED session 4af4e7e4a2de7e79f79ac055f8695fa1 under trace ["gateway-prd-main-8n3p",{"micros":5711,"calls":["discord-sessions-prd-2-93",{"micros":27}]}].
```
and then this repeating:
```
2020-10-23 11:10:02,144 --- Attempting a reconnect in 1012.42s
Traceback (most recent call last):
  File "/home/pi/Documents/BenchyBot/venv/discord-venv/lib/python3.7/site-packages/aiohttp/connector.py", line 967, in _create_direct_connection
    traces=traces), loop=self._loop)
  File "/home/pi/Documents/BenchyBot/venv/discord-venv/lib/python3.7/site-packages/aiohttp/connector.py", line 830, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/home/pi/Documents/BenchyBot/venv/discord-venv/lib/python3.7/site-packages/aiohttp/resolver.py", line 30, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 789, in getaddrinfo
    None, getaddr_func, host, port, family, type, proto, flags)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/Documents/BenchyBot/venv/discord-venv/lib/python3.7/site-packages/discord/client.py", line 548, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/pi/Documents/BenchyBot/venv/discord-venv/lib/python3.7/site-packages/discord/gateway.py", line 305, in from_client
    gateway = gateway or await client.http.get_gateway()
  File "/home/pi/Documents/BenchyBot/venv/discord-venv/lib/python3.7/site-packages/discord/http.py", line 910, in get_gateway
    data = await self.request(Route('GET', '/gateway'))
  File "/home/pi/Documents/BenchyBot/venv/discord-venv/lib/python3.7/site-packages/discord/http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/home/pi/Documents/BenchyBot/venv/discord-venv/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/pi/Documents/BenchyBot/venv/discord-venv/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/home/pi/Documents/BenchyBot/venv/discord-venv/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/pi/Documents/BenchyBot/venv/discord-venv/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/home/pi/Documents/BenchyBot/venv/discord-venv/lib/python3.7/site-packages/aiohttp/connector.py", line 971, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Temporary failure in name resolution]
```

## Intents

intents = discord.Intents.default()
intents.members = True 
intents.presences = True

## Checklist

- [X ] I have searched the open issues for duplicates.
- [X ] I have shown the entire traceback, if possible.
- [X ] I have removed my token from display, if visible.
- [X ] I have provided the intents that my bot is using.

## System Information

- Python v3.7.3-final
- discord.py v1.5.1-final
- aiohttp v3.6.2
- system info: Linux 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020

**Comment by Rapptz** [comment]
Your server's DNS is unstable. Nothing much I can do on this front. Consider adding a secondary DNS to your server. Googling will help here. Good luck.
