### ISSUE TITLE
[Ubuntu] Unable to get local issuer certificate (_ssl.c:1108)

### ISSUE THREAD

**Issue by MyselfLeo** [Rapptz/discord.py#5968]
## Summary

I've got the `aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]` error, same as #4146, however I'm running WSL Ubuntu 18.04.02 LTS and not MacOS. I've tried every answers to most of the SSL issues I could find but nothing fixed my problem.

It may be a problem with WSL as running the same script on my Ubuntu 18.04 LTS VPS does not cause any errror.

## Reproduction Steps

The error comes from the `run()` command.

## Actual Results

```Traceback (most recent call last):
  File "/home/leo/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1042, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1072, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 609, in <module>
    client.run('TOKEN') # Stable
  File "/home/leo/.local/lib/python3.8/site-packages/discord/client.py", line 678, in run
    return future.result()
  File "/home/leo/.local/lib/python3.8/site-packages/discord/client.py", line 658, in runner
    await self.start(*args, **kwargs)
  File "/home/leo/.local/lib/python3.8/site-packages/discord/client.py", line 621, in start
    await self.login(*args, bot=bot)
  File "/home/leo/.local/lib/python3.8/site-packages/discord/client.py", line 472, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "/home/leo/.local/lib/python3.8/site-packages/discord/http.py", line 288, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/home/leo/.local/lib/python3.8/site-packages/discord/http.py", line 185, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "/home/leo/.local/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/leo/.local/lib/python3.8/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/home/leo/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/leo/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/home/leo/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/home/leo/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/leo/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 938, in _wrap_create_connection
    raise ClientConnectorCertificateError(
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')]
```

## Intents

I'm not using any intents, it's been some time that I didn't program my bot and back then Intents where not a thing (i think ?).

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.8.0-final
- discord.py v1.4.1-final
- aiohttp v3.6.3
- system info: Linux 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020

**Comment by Zomatree** [comment]
```bash
sudo apt install ca-certificates
sudo update-ca-certificates --fresh
export SSL_CERT_DIR=/etc/ssl/certs
```
this works for most people with this issue

**Comment by MyselfLeo** [comment]
OMG thank you very much ! Obviously it had to be so easy. Again thank you !

**Comment by KeparYTbcc** [comment]
MAN, I MEAN, FINALLY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! THANK YOU SO, SO MUCH <3

**Comment by wangqi** [comment]
> ```shell
> sudo apt install ca-certificates
> sudo update-ca-certificates --fresh
> export SSL_CERT_DIR=/etc/ssl/certs
> ```
> 
> this works for most people with this issue

It works on WSL2. Thanks a lot!

**Comment by mariyka314** [comment]
I have the same problem. I tried suggested solution
```
sudo apt install ca-certificates
sudo update-ca-certificates --fresh
export SSL_CERT_DIR=/etc/ssl/certs
```
but it didn't help.
Any ideas what else I can do?

**Comment by jagadish432** [comment]
it didn't work for me,
my error - (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

I'm using "Ubuntu 22.04.3 LTS" through WSL2. Please help me.
