### ISSUE TITLE
PartialTemplateState does not support '_member_cache_flags' | When `fetch_template` is called

### ISSUE THREAD

**Issue by Lost1419** [Rapptz/discord.py#5986]
## Summary

It seems like when I call a `fetch_template` it says that 
`raise AttributeError('PartialTemplateState does not support {0!r}.'.format(attr))
AttributeError: PartialTemplateState does not support '_member_cache_flags'.`

## Reproduction Steps

```py
@commands.command()
@commands.is_owner()
async def guild(self, ctx, code):
        temp = await self.bot.fetch_template(code)
        guild = await temp.create_guild(name="Test Server", region=None, icon=None)
        channel = [channel.id for channel in guild.channels]
        for id in channel:
            invite = await ctx.channel.create_invite()
            await ctx.send(invite)
```

## Expected Results

Should have made a guild and sent an invite for every channel in the server

## Actual Results

```py
Ignoring exception in command guild:
Traceback (most recent call last):
  File "\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\\Desktop\Coding\Python\Lost... Bot\Cogs\staff.py", line 36, in guild
    temp = await self.bot.fetch_template(code)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 1144, in fetch_template
    return Template(data=data, state=self._connection)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\template.py", line 120, in __init__
    self.source_guild = Guild(data=source_serialised, state=state)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\guild.py", line 190, in __init__
    self._from_data(data)
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\guild.py", line 308, in _from_data
    cache_online_members = self._state._member_cache_flags.online
  File "C:\Users\\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\template.py", line 75, in __getattr__
    raise AttributeError('PartialTemplateState does not support {0!r}.'.format(attr))
AttributeError: PartialTemplateState does not support '_member_cache_flags'.
```

## Intents

```py
intents = discord.Intents.all()
```

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.9.0-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.19041

**Comment by FightMan01** [comment]
Same error here.
