### ISSUE TITLE
Error on bot.run

### ISSUE THREAD

**Issue by P3p1d** [Rapptz/discord.py#5996]
## Summary

I run my bot on heroku and it was running fine. Yesterday however the bot crashed on start. I rolled back to previous version of my bot but the error still ocurred the same way. I am using websockets 8.1 and discord.py 1.5.1 on python 3.6.1
The error is somewhere in the discord.py library, that I didn't manipulate at all. Thanks for any help

the error:
`Traceback (most recent call last):
 File "app.py", line 87, in <module>
 bot.run(TOKEN, bot = True)
 File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 708, in run
 return future.result()
File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 687, in runner
 await self.start(*args, **kwargs)
File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 651, in start
 await self.connect(reconnect=reconnect)
 File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 548, in connect
self.ws = await asyncio.wait_for(coro, timeout=60.0)
 File "/app/.heroku/python/lib/python3.6/asyncio/tasks.py", line 352, in wait_for return fut.result()
File "/app/.heroku/python/lib/python3.6/site-packages/discord/gateway.py", line 306, in from_client
 socket = await client.http.ws_connect(gateway)
File "/app/.heroku/python/lib/python3.6/site-packages/discord/http.py", line 132, in ws_connect
return await self.__session.ws_connect(url, **kwargs)
TypeError: ws_connect() got an unexpected keyword argument 'max_msg_size'
Process exited with status 1
State changed from up to crashed`

**Comment by Rapptz** [comment]
The system information is missing which says what versions of the dependencies your system is using.

From the look of this traceback you're using a version of aiohttp that doesn't work with the library. Please ensure you're installing properly with pip and have the right dependency versions.
