### ISSUE TITLE
Shard connection crash "cannot write to closing transport"

### ISSUE THREAD

**Issue by Miolus** [Rapptz/discord.py#6033]
I have 3 shards. The 3rd crashes with the error in the picture. 
If I start the shard, it will run and crash after some time.
![Screenshot_20201111-210936.png](https://user-images.githubusercontent.com/69853686/98859594-b7901480-2462-11eb-9bce-652a96d82385.png)

I don't know how to reproduce it, it happens randomly. Most of the time with this shard. I am using the latest version of d.py, python 3.8.2 on debian 10 and run multiple Bots on my server. I use the AutoShardedBot.
I use the Members intent.

**Comment by Miolus** [comment]
Additional: shard 3 sends messages with a delay of multiple minutes (40seconds - 6 minutes)

**Comment by NCPlayz** [comment]
Is it possible for you to get the traceback log in text form? This image of the traceback seems to be only a fraction of it.

**Comment by Miolus** [comment]
No sorry not possible ☹️. Sometimes the shard just stops and sends "Killed" without and Exception, most of the time this exception occurs.

**Comment by Miolus** [comment]
@NCPlayz here is the complete traceback: 2-sharded bot went offline, but still running on my vps, then this was the log:
ConnectionResetError: Cannot write to closing transport
Task exception was never retrieved
future: <Task finished name='Task-163452' coro=<ConnectionState.chunk_guild() done, defined at /usr/local/lib/python3.8/site-packages/discord/state.py:819> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/state.py", line 824, in chunk_guild
    await self.chunker(guild.id, nonce=request.nonce)
  File "/usr/local/lib/python3.8/site-packages/discord/state.py", line 1121, in chunker
    await ws.request_chunks(guild_id, query=query, limit=limit, nonce=nonce)
  File "/usr/local/lib/python3.8/site-packages/discord/gateway.py", line 658, in request_chunks
    await self.send_as_json(payload)
  File "/usr/local/lib/python3.8/site-packages/discord/gateway.py", line 596, in send_as_json
    await self.send(utils.to_json(data))
  File "/usr/local/lib/python3.8/site-packages/discord/gateway.py", line 592, in send
    await self.socket.send_str(data)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
Task exception was never retrieved
future: <Task finished name='Task-163448' coro=<ConnectionState.chunk_guild() done, defined at /usr/local/lib/python3.8/site-packages/discord/state.py:819> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/discord/state.py", line 824, in chunk_guild
    await self.chunker(guild.id, nonce=request.nonce)
  File "/usr/local/lib/python3.8/site-packages/discord/state.py", line 1121, in chunker
    await ws.request_chunks(guild_id, query=query, limit=limit, nonce=nonce)
  File "/usr/local/lib/python3.8/site-packages/discord/gateway.py", line 658, in request_chunks
    await self.send_as_json(payload)
  File "/usr/local/lib/python3.8/site-packages/discord/gateway.py", line 596, in send_as_json
    await self.send(utils.to_json(data))
  File "/usr/local/lib/python3.8/site-packages/discord/gateway.py", line 592, in send
    await self.socket.send_str(data)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

**Comment by Rapptz** [comment]
A ConnectionResetError is a blip on your network so not much to do here unfortunately.

**Comment by CircuitSacul** [comment]
I get the same error while trying to launch multiple clusters. The first cluster (4 shards) works fine, but when the second cluster tries to set its status, I get this error:

ConnectionResetError: Cannot write to closing transport

Full traceback:
```python
File "/opt/anaconda3/envs/starboard/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)

  File "/Users/lucas/programming/discord/Starboard-2/app/cogs/base/base_events.py", line 152, in on_ready
    await self.bot.change_presence(

  File "/opt/anaconda3/envs/starboard/lib/python3.9/site-packages/discord/shard.py", line 516, in change_presence
    await shard.ws.change_presence(activity=activity, status=status, afk=afk)

  File "/opt/anaconda3/envs/starboard/lib/python3.9/site-packages/discord/gateway.py", line 630, in change_presence
    await self.send(sent)

  File "/opt/anaconda3/envs/starboard/lib/python3.9/site-packages/discord/gateway.py", line 592, in send
    await self.socket.send_str(data)

  File "/opt/anaconda3/envs/starboard/lib/python3.9/site-packages/aiohttp/client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)

  File "/opt/anaconda3/envs/starboard/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)

  File "/opt/anaconda3/envs/starboard/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
```

**Comment by Miolus** [comment]
My final reason was: out of RAM
