### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by appleGun22** [Rapptz/discord.py#6077]
I'm trying to download discord.py libray but i get every time this wierd error

C:\python>pip3 install discord.py
Collecting discord.py
  Using cached discord.py-1.5.1-py3-none-any.whl (701 kB)
Collecting aiohttp<3.7.0,>=3.6.0
  Using cached aiohttp-3.6.3.tar.gz (1.1 MB)
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\base_command.py", line 228, in _main
    status = self.run(options, args)
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\commands\install.py", line 323, in run
    requirement_set = resolver.resolve(
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 183, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 388, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 340, in _get_abstract_dist_for
    abstract_dist = self.preparer.prepare_linked_requirement(req)
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\operations\prepare.py", line 482, in prepare_linked_requirement
    abstract_dist = _get_prepared_distribution(
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\operations\prepare.py", line 91, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\distributions\sdist.py", line 38, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\distributions\sdist.py", line 65, in _setup_isolation
    self.req.build_env = BuildEnvironment()
  File "c:\users\***\appdata\local\programs\python\python39\lib\site-packages\pip\_internal\build_env.py", line 82, in __init__
    fp.write(textwrap.dedent(
  File "c:\users\***\appdata\local\programs\python\python39\lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 148-152: character maps to <undefined>

im guessing its because my user name(c:\users\\***) is not an english text, but i didn't had problems with it before

**Comment by SNvMK** [comment]
try change yo useename or PC name

**Comment by appleGun22** [comment]
> try change yo useename or PC name

yeah as i thought that was the problem, now it works

**Comment by Harmon758** [comment]
This is an issue with pip, not discord.py. See https://github.com/pypa/pip/issues/9054.

For code block usage, see https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks.
