### ISSUE TITLE
Kick Ban doesn't work anymore

### ISSUE THREAD

**Issue by NightZan999** [Rapptz/discord.py#6085]
## Summary
Kick and ban commands are not working atleast inside cogs

## Reproduction Steps
Nothing really just made the commands

## Expected Results
The user to get kicked
## Actual Results
Nothing the traceback is this:

```
Ignoring exception in command kick:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/container/cogs/mod.py", line 299, in kick
    await member.kick(reason=reason)
  File "/home/container/.local/lib/python3.8/site-packages/discord/member.py", line 495, in kick
    await self.guild.kick(self, reason=reason)
  File "/home/container/.local/lib/python3.8/site-packages/discord/guild.py", line 1837, in kick
    await self._state.http.kick(user.id, self.id, reason=reason)
  File "/home/container/.local/lib/python3.8/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 850, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/container/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
```
I have administrator permissions and also 
[file.zip](https://github.com/Rapptz/discord.py/files/5596470/file.zip)

That is my file by the way on the moderation cog. I also made sure the user I was kicking has no perms. So why isnt it working anymore if there is some error in my code please inform me about the same. 

Thanks and Regards,
NightZan999

**Comment by SebbyLaw** [comment]
If you read your traceback, you'll notice something: `discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions`. Your bot does not have the sufficient permissions in that guild to kick or ban.

This is not an issue with discord.py.

GitHub issues for this repository should be used to report issues with this library. They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by Rapptz** [comment]
This is a hierarchy problem. You need permissions and a higher role than the person you're doing a moderator action to.

**Comment by NightZan999** [comment]
So wait your saying my **bot does not have enough permissions to operate the command? **
Is there any error handler for this or what? So I fix this by giving my bot administrator permissions

**Comment by NightZan999** [comment]
Umm sorry guys im really really dumb. Huge apologies.
