### ISSUE TITLE
Runtime error, event loop closed

### ISSUE THREAD

**Issue by IsaacWP121** [Rapptz/discord.py#6105]
```
Traceback (most recent call last):
  File "C:\Users\L0m\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 291, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\L0m\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 245, in request     
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:/Programming/AusSea-Bot/main.py", line 225, in <module>
    client.run(token())
  File "C:\Users\L0m\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 708, in run
    return future.result()
  File "C:\Users\L0m\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 687, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\L0m\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 650, in start
    await self.login(*args, bot=bot)
  File "C:\Users\L0m\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 499, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\L0m\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 295, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001D4CC4B75E0>
Traceback (most recent call last):
  File "C:\Users\L0m\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\L0m\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\L0m\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\L0m\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

I have been experiencing an error out of nowhere on my discord bot, my full code can be found [here](https://github.com/IsaacWP121/AusSea-Bot/blob/master/main.py). I have tried regenerating my token from the dashboard and that worked for a short amount of time however now it won't even start the bot without an error. Any idea what's going wrong here? (side note you may notice I'm using client.run(token()), I have a python script imported as such: `from Token import token` and the function token() returns my token as a string) Any help would be greatly appreciated

**Comment by Vexs** [comment]
It's as straightforward as it gets- 
`discord.errors.LoginFailure: Improper token has been passed.`
Discord, not discord.py, has said you are sending the wrong token, and as they are the ultimate authority, you are.

Discord.py does not futz with the token you send short of removing whitespace from the ends.

**Comment by IsaacWP121** [comment]
Turns out discord changed the token on me after sending it to a co developer over discord. Sorry about my stupidity, I was adamant it hadnt changed

**Comment by Harmon758** [comment]
For future questions like this, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api) for help, as the README also links, or create a [discussion](https://github.com/Rapptz/discord.py/discussions) instead, as you should have been prompted to do when creating this issue.
