### ISSUE TITLE
can't edit message

### ISSUE THREAD

**Issue by Bryan-u-2** [Rapptz/discord.py#6139]
## Summary

I want to replace the image by new one

## Reproduction Steps
@bot22.command(pass_context=True)
async def send(ctx):
	message = await ctx.send(file=discord.File('1.png'))
	await asyncio.sleep(1)
	await message.edit(file=discord.File('2.png'))

## Expected Results

I wanted the image 1.png to be replaced by 2.png 

## Actual Results

Traceback (most recent call last):
  File "/home/.../.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "a.py", line 21, in send
    await message.edit(file=discord.File('2.png'))
  File "/home/.../.local/lib/python3.8/site-packages/discord/message.py", line 884, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, **fields)
  File "/home/.../.local/lib/python3.8/site-packages/discord/http.py", line 156, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "/home/..../.local/lib/python3.8/site-packages/discord/utils.py", line 318, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type File is not JSON serializable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/../.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "/home/.../.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/.../.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Object of type File is not JSON serializable

- [ ] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [ ] I have provided the intents that my bot is using.

## System Information

- Python v3.8.6-final
- discord.py v1.5.1-final
- aiohttp v3.6.3
- system info: Linux 5.4.0-54-generic #60~18.04.1-Ubuntu SMP Fri Nov 6 17:25:16 UTC 2020

**Comment by Rapptz** [comment]
You can't edit attachments.
