### ISSUE TITLE
Error upgrading discord.py to 1.5.1

### ISSUE THREAD

**Issue by NicerNewerCar** [Rapptz/discord.py#6170]
I keep getting the following error whenever I try to update to 1.5.1, I have no outdated packages in my pip (aside from discord): Any help will be appreciated.

>pip install discord.py
Collecting discord.py
  Using cached discord.py-1.5.1-py3-none-any.whl (701 kB)
Collecting aiohttp<3.7.0,>=3.6.0
  Using cached aiohttp-3.6.3.tar.gz (1.1 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\~~~~~\AppData\Local\Temp\pip-build-env-zshjnipi\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "c:\python38\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "c:\python38\lib\site-packages\pip\__main__.py", line 26, in <module>
      sys.exit(_main())
    File "c:\python38\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "c:\python38\lib\site-packages\pip\_internal\commands\__init__.py", line 105, in create_command
      module = importlib.import_module(module_path)
    File "c:\python38\lib\importlib\__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "c:\python38\lib\site-packages\pip\_internal\commands\install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "c:\python38\lib\site-packages\pip\_internal\cli\req_command.py", line 18, in <module>
      from pip._internal.index.collector import LinkCollector
    File "c:\python38\lib\site-packages\pip\_internal\index\collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "c:\python38\lib\site-packages\pip\_vendor\requests\__init__.py", line 125, in <module>
      from . import utils
    File "c:\python38\lib\site-packages\pip\_vendor\requests\utils.py", line 25, in <module>
      from . import certs
    File "c:\python38\lib\site-packages\pip\_vendor\requests\certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "c:\python38\lib\site-packages\pip\_vendor\certifi\__init__.py", line 1, in <module>
      from .core import contents, where
    File "c:\python38\lib\site-packages\pip\_vendor\certifi\core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
    File "c:\python38\lib\importlib\resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "c:\python38\lib\site-packages\typing.py", line 1359, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "c:\python38\lib\site-packages\typing.py", line 1007, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python38\python.exe' 'c:\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\~~~~~\AppData\Local\Temp\pip-build-env-zshjnipi\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

**Comment by Theelgirl** [comment]
This just happened to me today, try doing ``pip uninstall typing`` then update discord.py, you can reinstall typing after.

**Comment by SebbyLaw** [comment]
> you can reinstall typing after

`typing` is a built-in library after version 3.5. No need to install.

**Comment by Theelgirl** [comment]
Oh oops, sorry about that

**Comment by Harmon758** [comment]
This seems to be an issue [with pip](https://github.com/pypa/pip/issues/8272) and/or [the backport for typing](https://github.com/python/typing/issues/573), when the backport is unnecessarily installed for a version of Python (>= 3.5) that already has the typing module in the standard library.
Uninstalling the backport for that version of Python should resolve the issue.

This is not an issue with discord.py itself. GitHub issues for this repository should be used to report issues with this library.
For further help specific to installing and using discord.py, you should join either the [official discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README also links, or create a [discussion](https://github.com/Rapptz/discord.py/discussions) instead, as you should have been prompted to do when creating this issue.

For code block usage, see https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks.
