### ISSUE TITLE
Error while setting webhook avatar

### ISSUE THREAD

**Issue by owoqq** [Rapptz/discord.py#6311]
discord.TextChannel.create_webhook(name="Example", avatar=user.avatar_url)

```py
Ignoring exception in on_message
Traceback (most recent call last):
File "site-packages/discord/client.py", line 343, in _run_event
await coro(*args, **kwargs)
File "/app/cogs/cog.py", line 28, in on_message
created_webhook = await created_channel.create_webhook(name=message.author, avatar=str(message.author.avatar_url))
File "site-packages/discord/channel.py", line 470, in create_webhook
avatar = utils._bytes_to_base64_data(avatar)
File "site-packages/discord/utils.py", line 311, in _bytes_to_base64_data
mime = _get_mime_type_for_image(data)
File "site-packages/discord/utils.py", line 298, in _get_mime_type_for_image
if data.startswith(b'\x89\x50\x4E\x47\x0D\x0A\x1A\x0A'):
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

**Comment by Rapptz** [comment]
[As the documentation states](https://discordpy.readthedocs.io/en/latest/api.html#discord.TextChannel.create_webhook) creating a webhook requires giving the avatar bytes, not a url. You can download an avatar by using the [read() coroutine](https://discordpy.readthedocs.io/en/latest/api.html#discord.Asset.read) on the asset object.
