### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by shahprog** [Rapptz/discord.py#6314]
## Summary

I am trying to get all the commands of bot through `bot.commands`
But I am getting some error

## Reproduction Steps
Anywhere I put `bot.command` I get the error

## Expected Results

It should return a set of commands of the bot. As it was returning in the previous versions of discord.py

## Actual Results

```sh
Traceback (most recent call last):
  File "C:\Users\Shahriyar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jishaku\cog_base.py", line 513, in jsk_python
    async for send, result in AsyncSender(executor):
  File "C:\Users\Shahriyar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jishaku\functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "C:\Users\Shahriyar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jishaku\repl\compilation.py", line 137, in traverse
    async for send, result in AsyncSender(func(*self.args)):
  File "C:\Users\Shahriyar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\jishaku\functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "<repl>", line 1, in _repl_coroutine
  File "C:\Users\Shahriyar\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\ext\commands\core.py", line 1106, in commands
    return set(self.all_commands.values())
TypeError: unhashable type: 'list'
```

## Intents

My bot uses no intent

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information

- Python v3.8.1-final
- discord.py v1.6.0-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.19041

**Comment by Gobot1234** [comment]
What code are you using with bot.command?

**Comment by shahprog** [comment]
> It looks like you've overwritten a documented attribute, [`Bot.all_commands`](https://discordpy.readthedocs.io/en/latest/ext/commands/api.html#discord.ext.commands.GroupMixin.all_commands). Consider naming your list attribute something else to avoid overriding it.
> 
> This is not an issue with discord.py. As far as I can tell, this is a documentation error since `Bot.all_commands` isn't documented in the autoclass even though it inherits from `GroupMixin`.

Thanks. I didnt know that
