### ISSUE TITLE
Error Handler For Discord Objects Isn't Working Completely

### ISSUE THREAD

**Issue by TunayAdaKaracan** [Rapptz/discord.py#6368]
## Summary

Error Handler For Discord Objects Isn't Working Completely. It is sending error message and raising error on cmd

## Reproduction Steps

Use A Object On Any Command
Example Command:
```
@client.command()
async def test(ctx, member:discord.Role=None):
```

Then Make A Error Handler For This Command
Example Error Handler:
```
@test.error
async def test_error(ctx,exc):
    if isinstance(exc, discord.ext.commands.errors.RoleNotFound):
        await ctx.send("Role Not Found")
```

Finally Try Command. Bot Sending Role Not Found Message But It is still printed on cmd

## Expected Results

Sending Error Message Without Any Traceback On cmd

## Actual Results
Bot's Error Message With Traceback:

````
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "C:\Python\Python382\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\tunay\OneDrive\Desktop\Klasörler\Projects\PanVatoz\bot.py", line 122, in on_command_error
    raise error
  File "C:\Python\Python382\lib\site-packages\discord\ext\commands\bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Python\Python382\lib\site-packages\discord\ext\commands\core.py", line 856, in invoke
    await self.prepare(ctx)
  File "C:\Python\Python382\lib\site-packages\discord\ext\commands\core.py", line 790, in prepare
    await self._parse_arguments(ctx)
  File "C:\Python\Python382\lib\site-packages\discord\ext\commands\core.py", line 697, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "C:\Python\Python382\lib\site-packages\discord\ext\commands\core.py", line 552, in transform
    return await self.do_conversion(ctx, converter, argument, param)
  File "C:\Python\Python382\lib\site-packages\discord\ext\commands\core.py", line 505, in do_conversion
    return await self._actual_conversion(ctx, converter, argument, param)
  File "C:\Python\Python382\lib\site-packages\discord\ext\commands\core.py", line 451, in _actual_conversion
    ret = await instance.convert(ctx, argument)
  File "C:\Python\Python382\lib\site-packages\discord\ext\commands\converter.py", line 482, in convert
    raise RoleNotFound(argument)
discord.ext.commands.errors.RoleNotFound: Role "a" not found.
````

## Intents

All intents

## Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.
- [x] I have provided the intents that my bot is using.

## System Information
Python: 3.8.6
Discord.py: 1.6.0-final

**Comment by Rapptz** [comment]
As your traceback shows, you have an `on_command_error` where you're raising an error. This causes it to go to `on_error` which prints the error by default.
