### ISSUE TITLE
Guild.ban() do not work with reason

### ISSUE THREAD

**Issue by Aaronferrari7** [Rapptz/discord.py#6521]
### Summary

I have been trying to do a ban command, but when I give a reason argument to the Guild.ban(), it returns a TypeError. Otherwise I have tried without that argument, and it works fine.

### Reproduction Steps

@commands.command(hidden=True)
    @commands.has_permissions(administrator=True)
    async def ban(self, ctx, User:discord.User=None, *,reason=None):
        if not User or User == ctx.message.author:
            await ctx.send("Can't ban yourself!", delete_after=3)
        elif not reason:
            reason= "Inappropriate behavior"
        embed = discord.Embed(color=0x350000)
        embed.set_author(name=f"You have been banned from {ctx.guild.name}!",icon_url=ctx.guild.icon_url)
        embed.add_field(name="Reason:",value=reason)
        await User.send(embed=embed)
        embed = discord.Embed(color=0x350000)
        embed.set_author(name=f"{User.name} has been banned!",icon_url=ctx.guild.icon_url)
        embed.add_field(name="Reason:",value=reason)
        LogsChannel = await self.client.fetch_channel(channel_id)
        await LogsChannel.send(embed=embed)
        await ctx.guild.ban(User,reason)

### Expected Results

The user get banned with a reason

### Actual Results

Ignoring exception in on_message
Traceback (most recent call last):
  File "\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "DiscordBot\OtherCommands.py", line 734, in ban
    await ctx.guild.ban(User,reason)
TypeError: ban() takes 2 positional arguments but 3 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "\Python\Python37-32\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "\Python\Python37-32\lib\site-packages\discord\ext\commands\bot.py", line 943, in on_message
    await self.process_commands(message)
  File "\Python\Python37-32\lib\site-packages\discord\ext\commands\bot.py", line 940, in process_commands
    await self.invoke(ctx)
  File "\Python\Python37-32\lib\site-packages\discord\ext\commands\bot.py", line 907, in invoke
    await ctx.command.dispatch_error(ctx, exc)
  File "\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 422, in dispatch_error
    await injected(cog, ctx, error)
  File "\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 71, in wrapped
    ret = await coro(*args, **kwargs)
  File "\DiscordBot\OtherCommands.py", line 737, in banerror
    raise error
  File "\Python\Python37-32\lib\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "\Python\Python37-32\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: ban() takes 2 positional arguments but 3 were given

### Intents

guilds, members, reactions, messages

### System Information

- Python v3.7.3-final
- discord.py v1.5.0-final
- aiohttp v3.6.3
- system info: Windows 7 6.1.7601

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by AbstractUmbra** [comment]
It takes a `reason` key-word argument, as stated in the [docs](https://discordpy.readthedocs.io/en/latest/api.html?highlight=guild%20ban#discord.Guild.ban).
