### ISSUE TITLE
Send dm code example fails to send dm

### ISSUE THREAD

**Issue by riodda** [Rapptz/discord.py#6533]
### Summary

send dm example in the docs don't work

### Reproduction Steps

Using the simple sample code for sending dm don't work.
Send a dm to a certain user on ready with the code:

### Expected Results

The expected result is that the user recives the dm.

### Actual Results

Error

Logged in as
JR DSR Messager
819849055366414376

Ignoring exception in on_ready
Traceback (most recent call last):
  File "H:\anaconda3\envs\plaid-ml\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "Z:\Trading\dm_python_bot\dm_python_bot.py", line 74, in on_ready
    dm_user.send('Cazzabubbo')
AttributeError: 'NoneType' object has no attribute 'send'

### Intents

Create a python script that lissen for a webhook and in reaction to re received webhook sends a dm to a certain user.

### System Information

- Python v3.8.8-final
- discord.py v1.6.0-final
- aiohttp v3.7.3
- system info: Windows 10 10.0.17763

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

I've tryed this code:

````

import discord
import nest_asyncio
nest_asyncio.apply()

client = discord.Client()

@client.event
async def on_ready():

    print('Logged in as')    
    print(client.user.name)
    print(client.user.id)
    print()

    dm_user = client.get_user(MEMBERID)
    dm_user.send('This is a test DM')
    print('------')

client.run('MYTOKEN')

````
I have this error popping up on the python console.
````
Logged in as
BOTNAME
BOTUSERID

Ignoring exception in on_ready
Traceback (most recent call last):
  File "H:\anaconda3\envs\plaid-ml\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "Z:\Trading\dm_python_bot\untitled0.py", line 28, in on_ready
    dm_user.send('This is a test DM')
AttributeError: 'NoneType' object has no attribute 'send'
````

**Comment by gogurtenjoyer** [comment]
This is not an issue with discord.py - your get_user method returned None, as it could not find that user.

GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For further help specific to using this library, you should join either the official [discord.py server](https://discord.gg/r3sSKJJ) or the [Discord API server](https://discord.gg/discord-api), as the README recommends.

**Comment by riodda** [comment]
I'm 100% sure that the user id is right.

**Comment by Rapptz** [comment]
If the user is not cached then that function will return `None` as documented.

If you want to resort to using an API call there's `fetch_user` instead which will give you the user regardless of cache at the cost of an API call.

**Comment by riodda** [comment]
> If the user is not cached then that function will return `None` as documented.
> 
> If you want to resort to using an API call there's `fetch_user` instead which will give you the user regardless of cache at the cost of an API call.
````
  File "H:\anaconda3\envs\plaid-ml\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "Z:\Trading\dm_python_bot\untitled0.py", line 28, in on_ready
    dm_user.send('This is a test DM')
TypeError: can't send non-None value to a just-started coroutine
H:\anaconda3\envs\plaid-ml\lib\site-packages\discord\client.py:350: RuntimeWarning: coroutine 'Client.fetch_user' was never awaited
  pass
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

````

Just a different error.

**Comment by helish88** [comment]
await

**Comment by riodda** [comment]
> await
````
Ignoring exception in on_ready
Traceback (most recent call last):
  File "H:\anaconda3\envs\plaid-ml\lib\site-packages\discord\client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "Z:\Trading\dm_python_bot\untitled0.py", line 28, in on_ready
    await dm_user.send('This is a test DM')
TypeError: can't send non-None value to a just-started coroutine
H:\anaconda3\envs\plaid-ml\lib\site-packages\discord\client.py:350: RuntimeWarning: coroutine 'Client.fetch_user' was never awaited
  pass
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
````

**Comment by helish88** [comment]
you should join the official [discord.py server ](https://discord.gg/dpy)

**Comment by riodda** [comment]
> you should join the official [discord.py server ](https://discord.gg/dpy)

I did thanks.
