### ISSUE TITLE
Discord.py 1.6.0 attr Error

### ISSUE THREAD

**Issue by EacyCoding** [Rapptz/discord.py#6548]
### Summary

In the discord.py module is an Attribute Error

### Reproduction Steps

  import discord
  
  class MyClient(discord.Client):
      # Einloggen
      async def on_ready(self): 
  
          # DEBUG 
          print(
              f'{client.user} is connected.'  
              )
  client = MyClient()
  client.run(TOKEN)

### Expected Results

Expected the bot to connect to the server and print out the msg, that he is connected.

### Actual Results

File "c:\Users\Eacy\Documents\Programmieren\Python stuff\DiscordBot\EvoliBot\discord_ basic.py", line 1, in <module>
    import discord
  File "C:\Users\Eacy\AppData\Roaming\Python\Python39\site-packages\discord\__init__.py", line 25, in <module>
    from .client import Client
  File "C:\Users\Eacy\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 33, in <module>
    import aiohttp
  File "C:\Users\Eacy\AppData\Roaming\Python\Python39\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "C:\Users\Eacy\AppData\Roaming\Python\Python39\site-packages\aiohttp\client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "C:\Users\Eacy\AppData\Roaming\Python\Python39\site-packages\aiohttp\http.py", line 7, in <module>
    from .http_parser import (
  File "C:\Users\Eacy\AppData\Roaming\Python\Python39\site-packages\aiohttp\http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "C:\Users\Eacy\AppData\Roaming\Python\Python39\site-packages\aiohttp\helpers.py", line 239, in <module>
    @attr.s(auto_attribs=True, frozen=True, slots=True)
AttributeError: module 'attr' has no attribute 's'

### Intents

just testing the discord.py module

### System Information

Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Program Files\Python39\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Program Files\Python39\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\Eacy\AppData\Roaming\Python\Python39\site-packages\discord\__init__.py", line 25, in <module>
    from .client import Client
  File "C:\Users\Eacy\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 33, in <module>
    import aiohttp
  File "C:\Users\Eacy\AppData\Roaming\Python\Python39\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "C:\Users\Eacy\AppData\Roaming\Python\Python39\site-packages\aiohttp\client.py", line 35, in <module>
    from . import hdrs, http, payload
  File "C:\Users\Eacy\AppData\Roaming\Python\Python39\site-packages\aiohttp\http.py", line 7, in <module>
    from .http_parser import (
  File "C:\Users\Eacy\AppData\Roaming\Python\Python39\site-packages\aiohttp\http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "C:\Users\Eacy\AppData\Roaming\Python\Python39\site-packages\aiohttp\helpers.py", line 239, in <module>
    @attr.s(auto_attribs=True, frozen=True, slots=True)
AttributeError: module 'attr' has no attribute 's'

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

Would really appreciate suggestions what to do, maybe I just made a mistake in my code.

**Comment by kal-byte** [comment]
What version of aiohttp do you have?
