### ISSUE TITLE
Using a " without and ending quote as an argument causes an exception

### ISSUE THREAD

**Issue by Drakomire** [Rapptz/discord.py#6689]
### Summary

Discord.py expects all quotes to be matched with another quote so when that doesn't happen is raises an exception.

### Reproduction Steps

Use the code but replace the string 'token' with your bot token.
Type `-ping ping` in Discord to make sure it works. The bot should respond `ping`.
Type `-ping "`. The bot should crash and print an error to discord.

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands

bot = commands.Bot(command_prefix='-')

@bot.command()
async def ping(ctx,arg):
    await ctx.send(arg)

bot.run('token')
```

### Expected Results

The bot should respond to the message with `"`.

### Actual Results

The bot printed an error to console.
For me it read:
`
Traceback (most recent call last):
  File "C:\Users\Drakomire\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Drakomire\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\ext\commands\core.py", line 855, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Drakomire\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50006): Cannot send an empty message
`

### Intents

I am not using any

### System Information

- Python v3.8.8-final
- discord.py v1.7.1-final
- aiohttp v3.6.2
- system info: Windows 10 10.0.18362

### Checklist

I have searched the open issues for duplicates.
I have shown the entire traceback, if possible.
I have removed my token from display, if visible.

**Comment by Zomatree** [comment]
i cannot repro this. Are you sure you didnt use two single quotes (`'`), if so this is expected behaviour, you passed an empty string to the parameter.

**Comment by Rapptz** [comment]
Generally speaking quotes have to be matched, otherwise there is a parsing ambiguity. If you want quoteless handling then you should use a keyword only parameter instead.
