### ISSUE TITLE
Shard heartbeat blocked from discord.py itsself?

### ISSUE THREAD

**Issue by Miolus** [Rapptz/discord.py#6729]
### Summary

Every shard of my bot got stuck today without any reason.

### Reproduction Steps

Run a discord.py bot with 5 shards. This didn't happen before and not with my 1-shard bot.

### Expected Results

Bot runs

### Actual Results

2021-04-14 20:01:29,465:WARNING:discord.gateway: Shard ID 0 heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/root/invitechecker/shard/./inviconn.py", line 1020, in <module>
    bot.run('token', reconnect=True)
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 53, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 339, in __wakeup
    self.__step()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/discord/shard.py", line 151, in worker
    await self.ws.poll_event()
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 559, in poll_event
    await self.received_message(msg.data)
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 509, in received_message
    func(data)
  File "/usr/local/lib/python3.9/site-packages/discord/state.py", line 910, in parse_guild_delete
    self._remove_guild(guild)
  File "/usr/local/lib/python3.9/site-packages/discord/state.py", line 314, in _remove_guild
    gc.collect()
  File "/usr/local/lib/python3.9/weakref.py", line 106, in remove
    def remove(wr, selfref=ref(self), _atomic_removal=_remove_dead_weakref):

2021-04-14 20:01:29,465:WARNING:discord.gateway: Shard ID 1 heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/root/invitechecker/shard/./inviconn.py", line 1020, in <module>
    bot.run('token', reconnect=True)
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 53, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 339, in __wakeup
    self.__step()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/discord/shard.py", line 151, in worker
    await self.ws.poll_event()
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 559, in poll_event
    await self.received_message(msg.data)
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 509, in received_message
    func(data)
  File "/usr/local/lib/python3.9/site-packages/discord/state.py", line 910, in parse_guild_delete
    self._remove_guild(guild)
  File "/usr/local/lib/python3.9/site-packages/discord/state.py", line 314, in _remove_guild
    gc.collect()
  File "/usr/local/lib/python3.9/weakref.py", line 106, in remove
    def remove(wr, selfref=ref(self), _atomic_removal=_remove_dead_weakref):

2021-04-14 20:01:29,476:WARNING:discord.gateway: Shard ID 2 heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/root/invitechecker/shard/./inviconn.py", line 1020, in <module>
    bot.run('token', reconnect=True)
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 53, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 339, in __wakeup
    self.__step()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/discord/shard.py", line 151, in worker
    await self.ws.poll_event()
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 559, in poll_event
    await self.received_message(msg.data)
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 509, in received_message
    func(data)
  File "/usr/local/lib/python3.9/site-packages/discord/state.py", line 910, in parse_guild_delete
    self._remove_guild(guild)
  File "/usr/local/lib/python3.9/site-packages/discord/state.py", line 314, in _remove_guild
    gc.collect()
  File "/usr/local/lib/python3.9/weakref.py", line 106, in remove
    def remove(wr, selfref=ref(self), _atomic_removal=_remove_dead_weakref):

2021-04-14 20:01:29,602:ERROR:discord: welcomer
Traceback (most recent call last):
  File "/root/invitechecker/shard/./inviconn.py", line 938, in welcomer
    uscount = int(weldata[0][1])
IndexError: tuple index out of range
2021-04-14 20:01:30,678:ERROR:discord: On member join
Traceback (most recent call last):
  File "/root/invitechecker/shard/./inviconn.py", line 938, in welcomer
    uscount = int(weldata[0][1])
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/invitechecker/shard/./inviconn.py", line 233, in on_member_join
    await self.welcomer(inviter=True, invite=invite, member=member, test=False, invitemem=invite.inviter)
  File "/root/invitechecker/shard/./inviconn.py", line 941, in welcomer
    await self.wlc_index(member=member, enmember=enmember, eninviter=eninviter)
RuntimeError: Cannot acquire connection after closing pool
2021-04-14 20:01:30,679:ERROR:discord: On member join
Traceback (most recent call last):
  File "/root/invitechecker/shard/./inviconn.py", line 233, in on_member_join
    await self.welcomer(inviter=True, invite=invite, member=member, test=False, invitemem=invite.inviter)
GeneratorExit
2021-04-14 20:01:56,122:WARNING:discord.gateway: Shard ID 3 heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/root/invitechecker/shard/./inviconn.py", line 1020, in <module>
    bot.run('token', reconnect=True)
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 53, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 339, in __wakeup
    self.__step()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/discord/shard.py", line 151, in worker
    await self.ws.poll_event()
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 559, in poll_event
    await self.received_message(msg.data)
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 423, in received_message
    self._buffer.extend(msg)

2021-04-14 20:02:06,258:WARNING:discord.gateway: Can't keep up, shard ID 4 websocket is 36.0s behind.
2021-04-14 20:02:08,268:WARNING:discord.gateway: Shard ID 3 heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 456, in received_message
    return
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 191, in ack
    log.warning(self.behind_msg, self.shard_id, self.latency)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1446, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    self.manager.emittedNoHandlerWarning = True
  File "/usr/local/lib/python3.9/logging/__init__.py", line 951, in handle
    return rv
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1183, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1087, in emit
    self.handleError(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1065, in flush
    self.release()

2021-04-14 20:02:23,161:WARNING:discord.gateway: Shard ID 2 heartbeat blocked for more than 10 seconds.
Loop thread traceback (most recent call last):
  File "/root/invitechecker/shard/./inviconn.py", line 1020, in <module>
    bot.run('token', reconnect=True)
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 53, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 339, in __wakeup
    self.__step()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/discord/shard.py", line 151, in worker
    await self.ws.poll_event()
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 559, in poll_event
    await self.received_message(msg.data)
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 427, in received_message
    msg = self._zlib.decompress(self._buffer)

2021-04-14 20:02:41,296:WARNING:discord.gateway: Shard ID 3 heartbeat blocked for more than 40 seconds.
Loop thread traceback (most recent call last):
  File "/root/invitechecker/shard/./inviconn.py", line 1020, in <module>
    bot.run('token', reconnect=True)
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 53, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 339, in __wakeup
    self.__step()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/discord/shard.py", line 151, in worker
    await self.ws.poll_event()
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 559, in poll_event
    await self.received_message(msg.data)
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 486, in received_message
    event = msg.get('t')

2021-04-14 20:02:42,228:WARNING:discord.gateway: Shard ID 2 heartbeat blocked for more than 20 seconds.
Loop thread traceback (most recent call last):
  File "/root/invitechecker/shard/./inviconn.py", line 1020, in <module>
    bot.run('token', reconnect=True)
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 713, in run
    loop.run_forever()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 53, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 100, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 339, in __wakeup
    self.__step()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 169, in step
    step_orig(task, exc)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/discord/shard.py", line 151, in worker
    await self.ws.poll_event()
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 559, in poll_event
    await self.received_message(msg.data)
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 433, in received_message
    self._dispatch('socket_response', msg)
  File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 134, in dispatch
    for event in self.extra_events.get(ev, []):

### Intents

Members

### System Information

discord.py 1.7.0, debian 10 64 bit, python3.9

### Checklist

I have searched the open issues for duplicates.
I have shown the entire traceback, if possible.
I have removed my token from display, if visible.

### Additional Context

The bot crashed after a few hours running.

**Comment by Miolus** [comment]
Possible related with the generator exit?

**Comment by Rapptz** [comment]
It appears to me that your CPU is too overloaded to handle this many shards in one core. Consider multiprocessing or getting a strong CPU.
