### ISSUE TITLE
[Interactions, v2.0] Interaction done in DMs causes a ValueError trying to fetch guild

### ISSUE THREAD

**Issue by MGRich** [Rapptz/discord.py#6794]
### Summary

Trying to run an Interaction in DMs will throw a ValueError

### Reproduction Steps

1. Add slash commands to a bot
2. Create a dummy `on_interaction` event
3. Try to run a slash command in DMs

### Minimal Reproducible Code

```python
#bot bot, token t
@bot.event
async def on_interaction(interaction):
    pass

bot.run(t)
```

### Expected Results

Nothing should happen due to the `pass`.

### Actual Results

`object.py:68` throws a ValueError, coming from `interactions.py:120` because `self.guild` and `self.guild_id` are both `None`.

Traceback:
```
Traceback (most recent call last):
  File "bot.py", line 678, in <module>
    bot.run(t, reconnect=True)
  File "...\discord\client.py", line 618, in run
    return future.result()
  File "...\discord\client.py", line 597, in runner
    await self.start(*args, **kwargs)
  File "...discord\client.py", line 561, in start
    await self.connect(reconnect=reconnect)
  File "...\discord\client.py", line 467, in connect
    await self.ws.poll_event()
  File "...\discord\gateway.py", line 553, in poll_event
    await self.received_message(msg.data)
  File "...\discord\gateway.py", line 503, in received_message
    func(data)
  File "...\discord\state.py", line 591, in parse_interaction_create
    interaction = Interaction(data=data, state=self)
  File "...\discord\interactions.py", line 96, in __init__
    self._from_data(data)
  File "...\discord\interactions.py", line 120, in _from_data
    guild = self.guild or Object(id=self.guild_id)
  File "...\discord\object.py", line 68, in __init__
    id = int(id)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

### Intents

Default, members, and presences 

### System Information

- Python v3.8.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3043+g184492af
- aiohttp v3.6.2
- system info: Windows 10 10.0.19041
- I'm also on the `interactions` branch.

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Fixed on newest commit.
