### ISSUE TITLE
Error: discord.errors.HTTPException: 429 Too Many Requests (error code: 0)

### ISSUE THREAD

**Issue by HassHz** [Rapptz/discord.py#6835]
### Summary

Bot has been getting rate-limited frequently lately

### Reproduction Steps

I'm not exactly sure, I have a bot that's used in mainly 1 or 2 servers where people use it to enter a list by typing a command. The servers aren't too over populated at all (~100 members but probably half that interact with the bot) and it's not too spammy when they interact with the bot.

I wonder if it might be due to the purging of the last 50 messages almost every time the bot is interacted with.

### Minimal Reproducible Code

```python
The code the message is being first being thrown on seems like this line (which I usually follow with a `message.channel.send`:
`await message.channel.purge(limit=50, check=draft_message)`
Where the check is

def is_me(m):
  return m.author == client.user

def draft_message(m):
  return is_me(m) and m.content.startswith('**Cap')
```

### Expected Results

Proper rate-limit handling

### Actual Results

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 122, in on_message
    await message.channel.purge(limit=50, check=draft_message)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/channel.py", line 378, in purge
    msg = await iterator.next()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/iterators.py", line 285, in next
    await self.fill_messages()
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/iterators.py", line 331, in fill_messages
    data = await self._retrieve_messages(self.retrieve)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/iterators.py", line 351, in _retrieve_messages_before_strategy
    data = await self.logs_from(self.channel.id, retrieve, before=before)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/http.py", line 209, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 0): You are being blocked from accessing our API temporarily due to exceeding our rate limits frequently. Please read our docs at https://discord.com/developers/docs/topics/rate-limits to prevent this moving forward.
```

```
2021-05-02 03:38:26,087:DEBUG:discord.gateway: For Shard ID None: WebSocket Event: {'t': 'MESSAGE_CREATE', 's': 4960, 'op': 0, 'd': {'type': 0, 'tts': False, 'timestamp': '2021-05-02T03:38:26.030000+00:00', 'referenced_message': None, 'pinned': False, 'nonce': '838258097502814208', 'mentions': [], 'mention_roles': [], 'mention_everyone': False, 'member': {'roles': [], 'premium_since': None, 'pending': False, 'nick': None, 'mute': False, 'joined_at': '2021-02-23T06:20:48.859000+00:00', 'is_pending': False, 'hoisted_role': None, 'deaf': False}, 'id': '<omitted>', 'flags': 0, 'embeds': [], 'edited_timestamp': None, 'content': '$list', 'components': [], 'channel_id': '<omitted>', 'author': {'username': 'Von', 'public_flags': 0, 'id': '<omitted>', 'discriminator': '4500', 'avatar': '7107dc309d0e441f22118b5a03210025'}, 'attachments': [], 'guild_id': '<omitted>'}}
2021-05-02 03:38:26,087:DEBUG:discord.client: Dispatching event socket_response
2021-05-02 03:38:26,088:DEBUG:discord.client: Dispatching event message
2021-05-02 03:38:26,207:DEBUG:discord.http: GET https://discord.com/api/v7/channels/<id>/messages with None has returned 429
```

### Intents

Default

### System Information

Using repl.it to host the bot

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I can provide the full discord.log (about 23k lines but error only really starts appearing near the end).
Please let me know if I can provide any other information

**Comment by pikaninja** [comment]
repl.it shares ips, this means that if someone else on your network gets 429'd, so do you. In any case, this isn't a bug with the library

**Comment by HassHz** [comment]
Thanks for the information!
