### ISSUE TITLE
send messages to channel using discord.py and a simple http server

### ISSUE THREAD

**Issue by thegame4craft** [Rapptz/discord.py#6870]
### Summary

send messages to channel using discord.py and a simple http server

### Reproduction Steps

I started a bot, wich sends message from webserver (http.server) to a discord channel

### Minimal Reproducible Code

```python
import discord, threading, asyncio
from discord.ext import commands
from http.server import HTTPServer, BaseHTTPRequestHandler
import nest_asyncio

intents = discord.Intents.all()

bot = commands.Bot(command_prefix='?', intents=intents)


def asyncio_run(future, as_task=True):
	"""
	A better implementation of `asyncio.run`.

	:param future: A future or task or call of an async method.
	:param as_task: Forces the future to be scheduled as task (needed for e.g. aiohttp).
	"""

	try:
		loop = asyncio.get_running_loop()
	except RuntimeError:  # no event loop running:
		loop = asyncio.new_event_loop()
		t = loop.create_task(future)
		#return loop.run_until_complete(_to_task(future, as_task, loop))
		return loop.run_until_complete(t)
	else:
		nest_asyncio.apply(loop)
		return asyncio.run(_to_task(future, as_task, loop))


def _to_task(future, as_task, loop):
	if not as_task or isinstance(future, asyncio.Task):
		return future
	return loop.create_task(future)

async def sendMessage(client: discord.Member, message):
	await client.send(message)


class Handler(BaseHTTPRequestHandler):
	def do_GET(self):
		global bot
		if self.path.startswith("/message"):
			params = self.path.split("?")[1]
			p = params.split("&")
			args = {}
			
			for param in p:
				d = param.split("=")
				if len(d) != 2:
					d.append("")
				args[d[0]] = d[1]
			
			# print(args)
			self.send_response(200)
			client: discord.Member = bot.get_user(int(args.get("user", 0)))
			if client is None:
				self.wfile.write(b"User not found")
			
			coro = lambda : sendMessage(client, "hello world from bot")
			asyncio_run(coro())
			
			self.wfile.write(b"message send!")
			self.end_headers()


server = HTTPServer(("localhost", 8080), Handler)
ws = threading.Thread(target=server.serve_forever)
ws.start()


@bot.event
async def on_ready():
	print('Logged in as')
	print(bot.user.name)
	print(bot.user.id)
	print('------')


@bot.event
async def on_message(message: discord.Message):
	pass


loop = bot.loop


def close(ws, bot: commands.Bot):
	bot.logout()
	ws.join(1)


try:
	bot.run('***')
	loop.run_until_complete()
except KeyboardInterrupt:
	loop.run_until_complete(close(ws, bot))
# cancel all tasks lingering
finally:
	loop.close()
```

### Expected Results

an exepetion and a error message

### Actual Results

`127.0.0.1 - - [06/May/2021 21:41:52] "GET /message?user=570917654076981248 HTTP/1.1" 200 -----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 64053)
Traceback (most recent call last):
  File "C:/Users/Robin/gamesrapid/GP/api/2fa/main.py", line 20, in asyncio_run
    loop = asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\http\server.py", line 427, in handle
    self.handle_one_request()
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\http\server.py", line 415, in handle_one_request
    method()
  File "C:/Users/Robin/gamesrapid/GP/api/2fa/main.py", line 61, in do_GET
    asyncio_run(coro())
  File "C:/Users/Robin/gamesrapid/GP/api/2fa/main.py", line 25, in asyncio_run
    return loop.run_until_complete(t)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:/Users/Robin/gamesrapid/GP/api/2fa/main.py", line 37, in sendMessage
    await client.send(message)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\abc.py", line 1013, in send
    channel = await self._get_channel()
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\user.py", line 722, in _get_channel
    ch = await self.create_dm()
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\user.py", line 764, in create_dm
    data = await state.http.start_private_message(self.id)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 192, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client.py", line 448, in _request
    with timer:
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\helpers.py", line 635, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
----------------------------------------
`
And this message are multiple in the console because i use firefox and firefox tryes to connect multiple times on failure.

### Intents

All

### System Information

- Python v3.8.2-final
- discord.py v1.7.2-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

full text: i have started created a bot. i uses http.server for the request handler and server. i used discord.py for the bot. when i start the server i getting following error: 

`127.0.0.1 - - [06/May/2021 21:41:52] "GET /message?user=570917654076981248 HTTP/1.1" 200 -----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 64053)
Traceback (most recent call last):
  File "C:/Users/Robin/gamesrapid/GP/api/2fa/main.py", line 20, in asyncio_run
    loop = asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\http\server.py", line 427, in handle
    self.handle_one_request()
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\http\server.py", line 415, in handle_one_request
    method()
  File "C:/Users/Robin/gamesrapid/GP/api/2fa/main.py", line 61, in do_GET
    asyncio_run(coro())
  File "C:/Users/Robin/gamesrapid/GP/api/2fa/main.py", line 25, in asyncio_run
    return loop.run_until_complete(t)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:/Users/Robin/gamesrapid/GP/api/2fa/main.py", line 37, in sendMessage
    await client.send(message)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\abc.py", line 1013, in send
    channel = await self._get_channel()
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\user.py", line 722, in _get_channel
    ch = await self.create_dm()
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\user.py", line 764, in create_dm
    data = await state.http.start_private_message(self.id)
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 192, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client.py", line 448, in _request
    with timer:
  File "C:\Users\Robin\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\helpers.py", line 635, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
----------------------------------------
`
And this message are multiple in the console because i use firefox and firefox tryes to connect multiple times on failure.

I have already tryed and search on the internet, but i didn't found any. my code: 
`import discord, threading, asyncio
from discord.ext import commands
from http.server import HTTPServer, BaseHTTPRequestHandler
import nest_asyncio

intents = discord.Intents.all()

bot = commands.Bot(command_prefix='?', intents=intents)

def asyncio_run(future, as_task=True):
	"""
	A better implementation of `asyncio.run`.

	:param future: A future or task or call of an async method.
	:param as_task: Forces the future to be scheduled as task (needed for e.g. aiohttp).
	"""

	try:
		loop = asyncio.get_running_loop()
	except RuntimeError:  # no event loop running:
		loop = asyncio.new_event_loop()
		t = loop.create_task(future)
		#return loop.run_until_complete(_to_task(future, as_task, loop))
		return loop.run_until_complete(t)
	else:
		nest_asyncio.apply(loop)
		return asyncio.run(_to_task(future, as_task, loop))

def _to_task(future, as_task, loop):
	if not as_task or isinstance(future, asyncio.Task):
		return future
	return loop.create_task(future)

async def sendMessage(client: discord.Member, message):
	await client.send(message)

class Handler(BaseHTTPRequestHandler):
	def do_GET(self):
		global bot
		if self.path.startswith("/message"):
			params = self.path.split("?")[1]
			p = params.split("&")
			args = {}
			
			for param in p:
				d = param.split("=")
				if len(d) != 2:
					d.append("")
				args[d[0]] = d[1]
			
			# print(args)
			self.send_response(200)
			client: discord.Member = bot.get_user(int(args.get("user", 0)))
			if client is None:
				self.wfile.write(b"User not found")
			
			coro = lambda : sendMessage(client, "hello world from bot")
			asyncio_run(coro())
			
			self.wfile.write(b"message send!")
			self.end_headers()

server = HTTPServer(("localhost", 8080), Handler)
ws = threading.Thread(target=server.serve_forever)
ws.start()

@bot.event
async def on_ready():
	print('Logged in as')
	print(bot.user.name)
	print(bot.user.id)
	print('------')

@bot.event
async def on_message(message: discord.Message):
	pass

loop = bot.loop

def close(ws, bot: commands.Bot):
	bot.logout()
	ws.join(1)

try:
	bot.run('**********')
	loop.run_until_complete()
except KeyboardInterrupt:
	loop.run_until_complete(close(ws, bot))
# cancel all tasks lingering
finally:
	loop.close()
`

this is all of these in long form.

**Comment by Rapptz** [comment]
I'm not sure what's going on in here. If you want to use an async web server I recommend using [Quart](https://pgjones.gitlab.io/quart/). As it stands now, this issue seems inactionable.

**Comment by avatar-lavventura** [comment]
@Rapptz How could we entegrage `discord.py` into `Quart`. Is there any recommendation related to it?
