### ISSUE TITLE
Stage channel creation http error

### ISSUE THREAD

**Issue by MCTRACO** [Rapptz/discord.py#6883]
### Summary

http error whe creating a stage channel

### Reproduction Steps

I just have a minimal bot to try and make a "radio" and I need  to create a stage channel so used the code below with that command and it raises an http error, I tried different servers and only works in the first one I was using

### Minimal Reproducible Code

```python
@client.command()
async def stage(ctx):
    await ctx.guild.create_stage_channel("Radio")
```

### Expected Results

Create a stage channel on the server

### Actual Results

This error
`
Traceback (most recent call last):
  File "F:\All_programs\Python3.9\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "f:\PROGRAMMING\Programs\Python\Discord.py\Rock-FM\src\stage.py", line 25, in stage
    channel = await guild.create_stage_channel("Rock Fm Radio")
  File "F:\All_programs\Python3.9\lib\site-packages\discord\guild.py", line 1019, in create_stage_channel
    data = await self._create_channel(name, overwrites, ChannelType.stage_voice, category, reason=reason, position=position, topic=topic)
  File "F:\All_programs\Python3.9\lib\site-packages\discord\http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50024): Cannot execute action on this channel type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\All_programs\Python3.9\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "F:\All_programs\Python3.9\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "F:\All_programs\Python3.9\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50024): Cannot execute action on this channel type
`

### Intents

None

### System Information

- Python v3.9.0-final
- discord.py v1.7.2-final
- aiohttp v3.6.3
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by MCTRACO** [comment]
ok, the thing was the server i was trying it on was not a community one so it cant create the stage channel
