### ISSUE TITLE
Can't use colour in message.edit()'s embed

### ISSUE THREAD

**Issue by Bluscream** [Rapptz/discord.py#696]
The Exception:
```
Ignoring exception in message
Traceback (most recent call last):
  File "D:\Users\sysadmin\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 203, in _run_event
    yield from coro(*args, **kwargs)
  File "D:\Coding\Projekte\Discord-Selfbot-appu1232\cogs\allembeds.py", line 26, in on_message
    await message.edit(content="sad", embed=discord.Embed(description=message.content), color=discord.Colour.red())
  File "D:\Users\sysadmin\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\message.py", line 539, in edit
    data = yield from self._state.http.edit_message(self.id, self.channel.id, **fields)
  File "D:\Users\sysadmin\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\http.py", line 126, in request
    kwargs['data'] = utils.to_json(kwargs.pop('json'))
  File "D:\Users\sysadmin\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\utils.py", line 259, in to_json
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=True)
  File "D:\Users\sysadmin\AppData\Local\Programs\Python\Python36\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "D:\Users\sysadmin\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Users\sysadmin\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Users\sysadmin\AppData\Local\Programs\Python\Python36\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'Colour' is not JSON serializable
```

The code:
```py
                r = randint(0, 255);g=randint(0, 255);b=randint(0, 255)
                print('r {} | g {} | b {}'.format(r,g,b))
                color = discord.Colour.from_rgb(r=r, g=g, b=b)
                print(color)
                await message.edit(content="sad", embed=discord.Embed(description=message.content), color=color)
```

**Comment by NotSoSuper** [comment]
maybe you should put the color keyword in the discord.Embed

**Comment by Bluscream** [comment]
ehhm

**Comment by Rapptz** [comment]
The `color`/`colour` keyword argument belongs to `discord.Embed` not `Message.edit`

**Comment by Bluscream** [comment]
Yeah i was about to close it, how could the three people including me that saw it not realize that. Sorry for the inconvinience
