### ISSUE TITLE
Guild has no attribute icon_url

### ISSUE THREAD

**Issue by AdhTri-001** [Rapptz/discord.py#6976]
### Summary

Guild lost the attribute icon_url in 2.0

### Reproduction Steps

```py
embed= discord.Embed(
            title= 'Server Info!',
            description= f'**{guild.name}** has {guild.member_count}',
            color= ctx.me.color,
            timestamp= datetime.utcnow()
        )
embed.set_thumbnail(url= guild.icon_url)
```

### Minimal Reproducible Code

```python
Use guild.icon_url
```

### Expected Results

should give url of icon of a guild

### Actual Results

Ignoring exception in on_command_error
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\discord\ext\commands\core.py", line 114, in wrapped
    ret = await coro(*args, **kwargs)
  File "f:\VS Code\Python\UFO_bot\cogs\general.py", line 126, in server
    print(guild.icon_url)
AttributeError: 'Guild' object has no attribute 'icon_url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 313, in _run_event
    await coro(*args, **kwargs)
  File "f:\VS Code\Python\UFO_bot\UFO_Bot.py", line 110, in on_command_error
    raise error
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\discord\ext\commands\bot.py", line 960, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\discord\ext\commands\core.py", line 798, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\HP\AppData\Roaming\Python\Python39\site-packages\discord\ext\commands\core.py", line 123, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Guild' object has no attribute 'icon_url'

### Intents

intents.default() && intents.members= True

### System Information

Python version 3.9
Discordpy version 2.0

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Thanks for such an amazing library Danny :)

**Comment by Rapptz** [comment]
This is an explicit design decision in v2.0. If you want the URL you can use `guild.icon.url`. Please don't install the master branch without being aware of the breaking changes in that version since these issues tend to be kind of noisy. Thanks.

**Comment by AdhTri-001** [comment]
Okay sir Thanks 😄
