### ISSUE TITLE
`max_values` in `ui.select` seems to be acting like `min_values`

### ISSUE THREAD

**Issue by muunie** [Rapptz/discord.py#6984]
### Summary

`max_values` in `ui.select` seems to be acting like `min_values`

### Reproduction Steps

You may use this decorator: 
```py
`max_values` in `ui.select` seems to be acting like `min_values`
```

### Minimal Reproducible Code

```python
@ui.select(placeholder="hi", options = [discord.SelectOption(label = "Label", value = "value", description = "hey there")], max_values= 3, min_values=1) 
    async def select_menu(self, _, a):
        pass
```

### Expected Results

I expected my Menu to be sent because I've fulfilled my minimum value count.

### Actual Results

Error Occurred:
```sh
Traceback (most recent call last):
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Discord Bots\fightanimebot\lib\site-packages\discord\ext\commands\core.py", line 114, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Discord Bots\fightanimebot\cogs\fights.py", line 12, in fight
    await ctx.send(embed = fight_view.embed, view = fight_view)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Discord Bots\fightanimebot\lib\site-packages\discord\abc.py", line 1298, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Discord Bots\fightanimebot\lib\site-packages\discord\http.py", line 272, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.1.options: Must be 3 or more in length.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Discord Bots\fightanimebot\lib\site-packages\discord\ext\commands\bot.py", line 960, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Discord Bots\fightanimebot\lib\site-packages\discord\ext\commands\core.py", line 798, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Happy\OneDrive\Documents\Coding Projects\Discord Bots\fightanimebot\lib\site-packages\discord\ext\commands\core.py", line 123, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.1.options: Must be 3 or more in length.
```

### Intents

None

### System Information

```sh
- Python v3.8.7-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3163+gf321efd4
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Zomatree** [comment]
Discord requires you to have greater or equal amount of options as the max_value.

**Comment by muunie** [comment]
Alright. Thanks @Zomatree
