### ISSUE TITLE
TypeError: cannot pickle 'TaskStepMethWrapper' object

### ISSUE THREAD

**Issue by dank-tagg** [Rapptz/discord.py#7036]
### Summary

I tried to subclass help command and overwrite bot.add_cog. But instead I got an error I have never encountered before, and I also asked in discord.py server with vague answers.

### Reproduction Steps

Overwrote `bot.add_cog` and subclassed help command. Must have to do with one of these.

### Minimal Reproducible Code

```python
# Bot subclass
    def add_cog(self, cog: commands.Cog, category: str = "Uncategorized"):
        if not category in self.categories:
            self.categories[category] = set()

        self.categories[category].add(cog.__cog_name__)
        super().add_cog(cog)
  
```
```py
# Help subclass
import discord
from discord.ext import commands
from utils.useful import Embed, Cooldown
import contextlib



class GrootHelp(commands.HelpCommand):

    def __init__(self, bot, **options):
        super().__init__(**options)
        self.categories = bot.categories
    # etc etc
 

class Help(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        help_command = GrootHelp(bot)
        help_command.cog = self
        bot.help_command = help_command
    
def setup(bot):
    bot.add_cog(Help(bot), category="Information")
```

### Expected Results

bot loading the cog and adding it. 

### Actual Results

```py
Traceback (most recent call last):
  File "/home/dank-tagg/env/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 618, in _load_from_module_spec
    setup(self)
TypeError: cannot pickle 'TaskStepMethWrapper' object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dank-tagg/env/lib/python3.9/site-packages/jishaku/cog_base.py", line 218, in jsk_load
    method(extension)
discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.help' raised an error: TypeError: cannot pickle 'TaskStepMethWrapper' object
```

### Intents

All

### System Information

- Python v3.9.4-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3133+g764099ba
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by dank-tagg** [comment]
As @Zomatree pointed out, the error occured when I passed the `bot` param to `help_command = GrootHelp(bot)`.
Closing the issue now. Thanks for the help.
