### ISSUE TITLE
Bot crashes with ValueError (integrations)

### ISSUE THREAD

**Issue by FightMan01** [Rapptz/discord.py#7047]
### Summary

Bot crashes (i don't know the whole context)

### Reproduction Steps

```
Traceback (most recent call last):
  File "bot.py", line 2754, in <module>
    csatlakoz()
  File "bot.py", line 2700, in csatlakoz
    loop.run_until_complete(client.start("token"))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/fightman/.local/lib/python3.8/site-packages/discord/client.py", line 568, in start
    await self.connect(reconnect=reconnect)
  File "/home/fightman/.local/lib/python3.8/site-packages/discord/shard.py", line 412, in connect
    raise item.error
  File "/home/fightman/.local/lib/python3.8/site-packages/discord/shard.py", line 154, in worker
    await self.ws.poll_event()
  File "/home/fightman/.local/lib/python3.8/site-packages/discord/gateway.py", line 553, in poll_event
    await self.received_message(msg.data)
  File "/home/fightman/.local/lib/python3.8/site-packages/discord/gateway.py", line 503, in received_message
    func(data)
  File "/home/fightman/.local/lib/python3.8/site-packages/discord/state.py", line 1106, in parse_integration_update
    integration = cls(data=data, guild=guild)
  File "/home/fightman/.local/lib/python3.8/site-packages/discord/integrations.py", line 115, in __init__
    self._from_data(data)
  File "/home/fightman/.local/lib/python3.8/site-packages/discord/integrations.py", line 194, in _from_data
    super()._from_data(data)
  File "/home/fightman/.local/lib/python3.8/site-packages/discord/integrations.py", line 124, in _from_data
    self.account: IntegrationAccount = IntegrationAccount(data['account'])
  File "/home/fightman/.local/lib/python3.8/site-packages/discord/integrations.py", line 71, in __init__
    self.id: Optional[int] = _get_as_snowflake(data, 'id')
  File "/home/fightman/.local/lib/python3.8/site-packages/discord/utils.py", line 440, in _get_as_snowflake
    return value and int(value)
ValueError: invalid literal for int() with base 10: 'UCIVh3L4yJWs2CLgxnXxciqw'
```

### Expected Results

Error will be handled.

### Actual Results

Bot crashes

### Intents

all

### System Information

- Python v3.8.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3261+g04573c3c
- aiohttp v3.6.2
- system info: Linux 5.4.0-74-generic #83-Ubuntu SMP Sat May 8 02:35:39 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by numbermaniac** [comment]
You need to fill out the "Minimal Reproducible Code" section so that we know what code you used to produce the error.

**Comment by FightMan01** [comment]
I don't know which part is doing this, I just use buttons.
