### ISSUE TITLE
`ctx.message.reference` is invalid for the reference parameter in `send()` even though not None

### ISSUE THREAD

**Issue by Kile** [Rapptz/discord.py#7124]
### Summary

Using `ctx.message.reference` in the reference parameter of abc.Messagable.send() raises the error discord.errors.InvalidArgument: reference parameter must be Message or MessageReference, even though the docs state message.reference returns a MessageReference object. 

### Reproduction Steps

Use the code stated below in a jsk eval or command and reply to a message in the invocation message. If you want to confirm this should be valid, add checks if `ctx.message.reference` is None

### Minimal Reproducible Code

```python
await _ctx.send('uwu', reference=_ctx.message.reference)
```

### Expected Results

The message send by the bot replies to the message the invocation replied to

### Actual Results

An error occurs: 
```
Traceback (most recent call last):
  File "/Users/me/Library/Python/3.8/lib/python/site-packages/jishaku/cog_base.py", line 513, in jsk_python
    async for send, result in AsyncSender(executor):
  File "/Users/me/Library/Python/3.8/lib/python/site-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "/Users/me/Library/Python/3.8/lib/python/site-packages/jishaku/repl/compilation.py", line 137, in traverse
    async for send, result in AsyncSender(func(*self.args)):
  File "/Users/me/Library/Python/3.8/lib/python/site-packages/jishaku/functools.py", line 109, in _internal
    value = await base.asend(self.send_value)
  File "<repl>", line 1, in _repl_coroutine
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/discord/abc.py", line 1034, in send
    raise InvalidArgument('reference parameter must be Message or MessageReference') from None
discord.errors.InvalidArgument: reference parameter must be Message or MessageReference
```
### Intents

`discord.Intents.all()`

### System Information

- Python v3.8.5-final
- discord.py v1.7.1-final
- aiohttp v3.6.2
- system info: Darwin 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by zephyrkul** [comment]
Your discord.py is out of date - 1.7.3 is the current stable version, and includes a fix for this.
