### ISSUE TITLE
TextChannelConverter appears broken for DMs in 2.0a

### ISSUE THREAD

**Issue by mirnovov** [Rapptz/discord.py#7147]
### Summary

When using TextChannelConverter in DMs, it produces an error in 2.0a. 

### Reproduction Steps

I first discovered this apparent issue when working on my own bot, and then reproduced it using the sample code below.

1. Run the sample code
2. In the bot's DMs, use the `test` command with a channel name as an parameter. Of course, this must be a channel otherwise visible to the bot.

### Minimal Reproducible Code

```python
import discord, logging
from discord.ext import commands

token = "token_goes_here"
bot = commands.Bot(command_prefix = "!")

logging.basicConfig(level = logging.INFO)

@bot.command()	
async def test(ctx, channel : discord.TextChannel):
	await ctx.send(f"{channel.name} {channel.id}")
	
if __name__ == "__main__":
	logging.warning(f"discord.py version: {discord.__version__}")
	bot.run(token)
```

### Expected Results

For the example code to produce the channel name and id. This occurs when the same code is run on discord.py version 1.7.2.

I have searched the 2.0 roadmap for changes in this department and failed to find any that would cause such an issue. If there's any that I've missed, apologies. At the very least, it should handle the fact that it's in a DM in a cleaner manner.

### Actual Results

An exception was produced, and the code failed to continue executing:

```
Traceback (most recent call last):
  File "/lib/python3.9/site-packages/discord/ext/commands/converter.py", line 970, in _actual_conversion
    return await converter().convert(ctx, argument)
  File "/lib/python3.9/site-packages/discord/ext/commands/converter.py", line 446, in convert
    return GuildChannelConverter._resolve_channel(ctx, argument, ctx.guild.text_channels, discord.TextChannel)
AttributeError: 'NoneType' object has no attribute 'text_channels'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 960, in invoke
    await ctx.command.invoke(ctx)
  File "/lib/python3.9/site-packages/discord/ext/commands/core.py", line 817, in invoke
    await self.prepare(ctx)
  File "/lib/python3.9/site-packages/discord/ext/commands/core.py", line 751, in prepare
    await self._parse_arguments(ctx)
  File "/lib/python3.9/site-packages/discord/ext/commands/core.py", line 658, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "/lib/python3.9/site-packages/discord/ext/commands/core.py", line 511, in transform
    return await run_converters(ctx, converter, argument, param)
  File "/lib/python3.9/site-packages/discord/ext/commands/converter.py", line 1076, in run_converters
    return await _actual_conversion(ctx, converter, argument, param)
  File "/lib/python3.9/site-packages/discord/ext/commands/converter.py", line 976, in _actual_conversion
    raise ConversionError(converter, exc) from exc
discord.ext.commands.errors.ConversionError: (<class 'discord.ext.commands.converter.TextChannelConverter'>, AttributeError("'NoneType' object has no attribute 'text_channels'"))
```
Note that I have stripped identifying information from the file paths above. Other than that, the traceback is exactly as reported. From it; I suspect that the bot is attempting to grab the current guild regardless of whether it is in a DM.

### Intents

default; see example

### System Information

```
- Python v3.9.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3324+g12e3eba0
- aiohttp v3.7.4.post0
- system info: Darwin 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

If I didn't miss something obvious, this regression appears to have been introduced as part of commit 353737239a61444c0b7ca89144602bbbcf4906b6 (`[commands] Minimise code duplication in channel converters`).

**Comment by mirnovov** [comment]
@Soheab: did you react bc I made a really obvious mistake?
