### ISSUE TITLE
KeyError: 'game_id' -SOLVED

### ISSUE THREAD

**Issue by Canule** [Rapptz/discord.py#72]
I'm trying to run this script with the example

Login goes fine, client.accept_invite goes fine. 
But once the bot is added to a server(manual or with script, serverowner/admin rights or not) I get this error/quit when I run bot.py
```
Traceback (most recent call last):
  File "C:\Users\someone\Desktop\discordbot\bot.py", line 31, in <module>
    client.run()
  File "C:\Python34\lib\site-packages\discord.py-0.9.0-py3.4.egg\discord\client.py", line 542, in run
  File "C:\Python34\lib\site-packages\ws4py-0.3.4-py3.4.egg\ws4py\websocket.py", line 427, in run
  File "C:\Python34\lib\site-packages\ws4py-0.3.4-py3.4.egg\ws4py\websocket.py", line 305, in once
  File "C:\Python34\lib\site-packages\ws4py-0.3.4-py3.4.egg\ws4py\websocket.py", line 377, in process
  File "C:\Python34\lib\site-packages\discord.py-0.9.0-py3.4.egg\discord\client.py", line 128, in received_message
  File "C:\Python34\lib\site-packages\discord.py-0.9.0-py3.4.egg\discord\client.py", line 519, in dispatch
  File "C:\Python34\lib\site-packages\discord.py-0.9.0-py3.4.egg\discord\client.py", line 527, in handle_socket_update
  File "C:\Python34\lib\site-packages\discord.py-0.9.0-py3.4.egg\discord\client.py", line 160, in handle_ready
  File "C:\Python34\lib\site-packages\discord.py-0.9.0-py3.4.egg\discord\client.py", line 150, in _add_server
  File "C:\Python34\lib\site-packages\discord.py-0.9.0-py3.4.egg\discord\server.py", line 77, in __init__
  File "C:\Python34\lib\site-packages\discord.py-0.9.0-py3.4.egg\discord\server.py", line 122, in _from_data
KeyError: 'game_id'
```

**Comment by Canule** [comment]
Didn't received the latest version with: "pip install discord.py"
"pip install --upgrade discord.py" solved it
