### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by kotmw0701** [Rapptz/discord.py#724]
Make sure the get_channel is not None.

I can not execute the code I checked with the API reference.
What kind of code does it work normally?

### Code:
```
    msgiter = client.logs_from(server.get_channel(190495358843879428)).iterate()
    for message in msgiter:
        print(message)
```

### Error Log:
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Kotmw0701\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:\Users\Kotmw0701\Documents\Development\Ecripce_WorkSpace\Discord_bot\Main.py", line 58, in on_message
    print(is_AuthOther(message.server, user))
  File "C:\Users\Kotmw0701\Documents\Development\Ecripce_WorkSpace\Discord_bot\Main.py", line 93, in is_AuthOther
    print(next(msgiter))
  File "C:\Users\Kotmw0701\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\iterators.py", line 115, in iterate
    yield from self.fill_messages()
  File "C:\Users\Kotmw0701\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\iterators.py", line 123, in fill_messages
    data = yield from self._retrieve_messages(retrieve)
  File "C:\Users\Kotmw0701\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\iterators.py", line 141, in _retrieve_messages_before_strategy
    data = yield from self.client._logs_from(self.channel, retrieve, before=self.before)
  File "C:\Users\Kotmw0701\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\client.py", line 1603, in _logs_from
    return self.http.logs_from(channel.id, limit, before=before, after=after, around=around)
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by Rapptz** [comment]
Multiple things wrong here.

1. IDs in v0.16.x are strings, not integers. See [here](http://discordpy.readthedocs.io/en/latest/faq.html#i-m-passing-ids-as-integers-and-things-are-not-working).
2. `client.logs_from` is meant to be used with `async for`, it does not have `iterate()` on it.
3. `for msg in msgiter` is incorrect.

The correct code (after you make sure that `get_channel` isn't `None`, which you said you did in the beginning yet clearly it shows otherwise is:

```py
channel = bot.get_channel('190495358843879428')
async for msg in client.logs_from(channel):
  print(msg)
```
