### ISSUE TITLE
Throw error field.value is required even the field have key and value is have it's content

### ISSUE THREAD

**Issue by dumb-stuff** [Rapptz/discord.py#7255]
### Summary

Throw error field.value is required even the field have key and value is have it's content

### Reproduction Steps

Get yourself a code here https://github.com/dumb-stuff/Pypi-Bot and replace bot.run(token) to be your token and try to run PackageDetail command ``

### Minimal Reproducible Code

```python
from discord.ext import commands
from . import pypiapijson
import discord
import aiohttp
import re
print(pypiapijson)

class placeholder:
	pass


def extractinfo(infos: dict):
	placeholding = placeholder()
	placeholding.classes = ""
	info = infos["info"]
	placeholding.author = info["author"]  # Marked
	placeholding.authoremail = info["author_email"]  # Marked
	placeholding.bugtrack = info["bugtrack_url"]  # Marked
	for classifier in info["classifiers"]:
		placeholding.classes += f"{classifier}\n"  # Marked
	placeholding.description = info["description"]  # Marked
	placeholding.descriptiontype = info["description_content_type"]  # Marked
	placeholding.docsurl = info["docs_url"]  # Marked
	placeholding.downloadurl = info["download_url"]
	placeholding.downloads = info["downloads"] # Marked
	placeholding.homepage = info["home_page"]
	placeholding.keywords = info["keywords"]
	placeholding.license = info["license"]
	placeholding.maintainer = info["maintainer"]
	placeholding.maintaineremail = info["maintainer_email"]
	placeholding.package_url = info["package_url"]
	placeholding.platform = info["platform"]
	placeholding.project_url = info["package_url"]
	placeholding.project_urls = info["project_urls"]
	placeholding.release_url = info["release_url"]
	placeholding.require_dist = info["requires_dist"]
	placeholding.require_python = info["requires_python"]
	placeholding.summary = info["summary"]
	placeholding.yanked = bool(info["yanked"])
	if placeholding.yanked:
		placeholding.yanked_reason = info["yanked_reason"]
	else:
		pass
	return placeholding


class Pypi(commands.Cog):
	def __init__(self, bot):
		self.bot = bot

	@commands.command(case_sensitive=False)
	async def PackageDetail(self, ctx, packagename=None):
		if packagename is None:
			return await ctx.send(
				"I cannot search the package with out it\'s name!")
		async with ctx.typing():
			info = await pypiapijson.asyncs.get(packagename)
			extract = extractinfo(info)
			embed = discord.Embed(title=f"{packagename} info",description=f"Description of {packagename}\n{extract.description}\n\nType of description is {extract.descriptiontype}")
			embed.add_field(name="Author", value=extract.author)
			embed.add_field(name="Author Email", value=extract.authoremail)
			embed.add_field(name=f"Short Description of {packagename}",value=extract.summary)
			embed.add_field(name="Module Home Page", value=extract.homepage)
			embed.add_field(name="Documentation URL", value=extract.docsurl)
			embed.add_field(name="Bug Tracking URL", value=extract.bugtrack)
			links = ""
			for key,val in extract.project_urls.items():
				links += f"{key} : {val}\n"
			print(links)
			print(extract.keywords)
			embed.add_field(name="List of external links", value=f"{links}") #
			
			embed.add_field(name="List of classifiers", value=extract.classes)
			embed.add_field(name=f"Keyword that used in {packagename}",value=extract.keywords)
			
			last_day = extract.downloads["last_day"]
			last_week = extract.downloads["last_week"]
			last_month = extract.downloads["last_month"]
			print(last_day,last_week,last_month)
			embed.add_field(name="Download Statistic",value=f"Yesterday : {last_day}, Last week : {last_week}, Last month : {last_month}") #
			embed.add_field(name="{packagename}\'s download url",value=extract.downloadurl)
			await ctx.send(embed=embed)
def setup(bot):
	bot.add_cog(Pypi(bot=bot))
```

### Expected Results

Give me a nice embed with pypi info with it

### Actual Results

It throw error 
```py
Ignoring exception in command PackageDetail:
Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/runner/Pypi-Bot/stuff/pypi.py", line 82, in PackageDetail
    await ctx.send(embed=embed)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/abc.py", line 1065, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed,
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/http.py", line 254, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.7.value: This field is required
In embed.fields.10.value: This field is required

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embed.fields.7.value: This field is required
In embed.fields.10.value: This field is required
```

### Intents

No

### System Information

- Python v3.8.10-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Linux 5.8.0-1035-gcp #37~20.04.1-Ubuntu SMP Thu Jun 17 16:04:29 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Nothing I guess

**Comment by pikaninja** [comment]
This is not a bug with the lib, most likely one of those values you passed were None, which is empty, you should print out your values to test

**Comment by dumb-stuff** [comment]
I confirm it is not none
[error.txt](https://github.com/Rapptz/discord.py/files/6845772/error.txt)

**Comment by wasi-master** [comment]
The bug tracking url and the keywords fields most likely have empty values

**Comment by ironman9356** [comment]
> The bug tracking url and the keywords fields most likely have empty values

this  its not an error with the lib

**Comment by wasi-master** [comment]
> I confirm it is not none
> [error.txt](https://github.com/Rapptz/discord.py/files/6845772/error.txt)
> 

The error confirms it is none/empty (empty meaning it's "")

**Comment by ironman9356** [comment]
"" is None in python

**Comment by snezhniy** [comment]
> `""` is None in python

No it's not None, it's a string.

**Comment by Robin5605** [comment]
> > `""` is None in python
> 
> No it's not None, it's a string.

It is afaik, the [Programming recommendations](https://www.python.org/dev/peps/pep-0008/#programming-recommendations) section states "For sequences, (strings, lists, tuples), use the fact that empty sequences are false."

**Comment by XuaTheGrate** [comment]
An empty string is not ``None``, it is a false-like value. False-like includes empty lists, tuples, strings, the number 0, None and False.

**Comment by ironman9356** [comment]
i mean it is not getting a value for the field so its giving an error 
i just compared it to None its not None

**Comment by dumb-stuff** [comment]
I fixed it thank you for answering
