### ISSUE TITLE
I set "label" argument. But responce said it is not seted.

### ISSUE THREAD

**Issue by Marusoftware** [Rapptz/discord.py#7305]
### Summary

Button in discord.py 2.0

### Reproduction Steps

When create button 2+ times.

### Minimal Reproducible Code

```python
from discord import Button, ButtonStyle, View
from discord.ext.commands import Bot

bot=Bot()

@bot.command()
async def test(ctx):
    view=View()
    for i in range(10):
        view.add_item(button(label="test"+str(i), custom_id="test"))
    ctx.send("test",view=view)
    view=View()
    view.add_item(button(label="test final", custom_id="test"))
    ctx.send("test",view=view)

class button(Button):
    def __init__(self, label, custom_id):
        super().__init__(label=label, custom_id=custom_id, style=ButtonStyle.primary)
        self.label=label
        self.custom_id=custom_id
    async def callback(self, interaction):
        print(self.custom_id, self.label)

bot.run("token")
```

### Expected Results

```
Ignoring exception in command start_vote:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/core.py", line 125, in wrapped
    ret = await coro(*args, **kwargs)
  (1 line is here. but I can't show you because of privacy)
  File "/usr/local/lib/python3.9/dist-packages/discord/abc.py", line 1413, in send
    data = await state.http.send_message(
  File "/usr/local/lib/python3.9/dist-packages/discord/http.py", line 337, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.1.label: This field is required

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/bot.py", line 960, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/core.py", line 825, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/discord/ext/commands/core.py", line 134, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.1.label: This field is required
```

### Actual Results

2+ times of sending, error is happun.

### Intents

typing=False members=True

### System Information

- Python v3.9.2-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3407+gfc51736b
- aiohttp v3.7.4.post0
- system info: Linux 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Spagetik** [comment]
![image](https://user-images.githubusercontent.com/77984254/127685523-6814b467-c24c-42d4-b7aa-9b4873701ae6.png)
You have to use **discord.ui**
