### ISSUE TITLE
discord.errors.LoginFailure: Improper token has been passed

### ISSUE THREAD

**Issue by Andrea-Miele** [Rapptz/discord.py#7336]
### Summary

When i try to run my code it shows discord.errors.LoginFailure: Improper token has been passed

### Reproduction Steps

1)install discord.py
2)run code

### Minimal Reproducible Code

```python
bot.run("TOKEN")
```

### Expected Results

Run the discord bot normally

### Actual Results

Shows error 
```
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\http.py", line 299, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\http.py", line 253, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\bot.py", line 62, in <module>
    bot_async_start()
  File ".\bot.py", line 49, in bot_async_start
    bot.run("Here there is the token ")
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 755, in run
    return future.result()
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 734, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 697, in start
    await self.login(*args)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 544, in login
    await self.http.static_login(token.strip())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\http.py", line 303, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
```

### Intents

discord.Intents.default

### System Information

- Python v3.8.6-final
- discord.py v1.8.1-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

The token is correctly copied , is the token not the secret, the token is in a string , I also tried to regenerate token and it didn't worked

**Comment by Gobot1234** [comment]
You have to generate your own token on http://discord.com/developers/applications for a bot to run, TOKEN is a placeholder for this.

**Comment by Andrea-Miele** [comment]
i already did

**Comment by Gobot1234** [comment]
You have used the client secret instead of the bot token which you can copy here 
![Screenshot 2021-08-04 at 17 16 19](https://user-images.githubusercontent.com/50501825/128216952-df0838df-5251-4340-94f2-271f4f7386d7.png)

**Comment by Phxntxm** [comment]
Really the only possibilities here, if you're providing the token directly to it are

1) It's the client secret
2) It's an old token
3) It's a token for your *user account* (and this is not supported by the library)

It's kinda hard to narrow this down without seeing the actual token (which is bad for obvious reasons) so for the most part if falls on you to check all these reasons

**Comment by Andrea-Miele** [comment]
As I written before , I'm using the most recent token , The bot token not my account token.

**Comment by Phxntxm** [comment]
You're wrong, discord doesn't randomly go "yeah I'm not feelin it today, I'm gonna lie about this error". You're going to have to double check all of these details, one is wrong. This is not an issue with the library, it is an issue with your code... if you want further help with it then the best place would be in the [discord server](https://discord.gg/r3sSKJJ), not a github issue.

**Comment by Andrea-Miele** [comment]
ok, i will close the issue since it's a discord error

**Comment by GoogleGenius** [comment]
Using self-bots is against ToS and discord.py has removed all methods and any references to them in v2.

**Comment by kms0219kms** [comment]
Hello, I am having the same issue while trying to create **normal** bot.

1. It's the client secret -> No, I am not using client secret. I typed token starts with "MTAzM**********3NTk3OTgxNg.G-"
2. It's an old token -> No, I am generated one seconds ago and paste that token.
3. It's a token for your user account -> No, This token is normal bot.
![image](https://user-images.githubusercontent.com/67222970/209323007-5a964ef4-4482-4c93-9ab4-f4da6ee4e283.png)

**Comment by darmpa123** [comment]
I was having this issue too. I was using the bot token, redeemed a new token, neither worked, no formatting errors. This was the solution and it had nothing to do with the bot token. The answer by Sean Gilbert about halfway down the page is what fixed this for me - https://stackoverflow.com/questions/51602617/improper-token-passed/59558131#59558131?newreg=0f6537799ad64f7ab3c6eccbd918c662

**Comment by ToiLaQuan09** [comment]
I set my TOKEN 3 days ago and write it in .env file. now I reset it, copy a new token and rewrite in .env file but when I run bot again, it error:
discord.errors.LoginFailure: Improper token has been passed.
I sure I rewrite correctly

**Comment by fookashi** [comment]
> I set my TOKEN 3 days ago and write it in .env file. now I reset it, copy a new token and rewrite in .env file but when I run bot again, it error: discord.errors.LoginFailure: Improper token has been passed. I sure I rewrite correctly because when paste it in client.run(token paste), it ran

I suppose it's because you store token in .env, so it's cached. All you have to do is reopen your IDE or update .env file with set_key(i didn't try it, reopening my VSC helped, so i just suppose that it might be helpful too)
