### ISSUE TITLE
Cannot use PythonAnywhere to host my bot due to PythonAnywhere Proxy.

### ISSUE THREAD

**Issue by Rix565** [Rapptz/discord.py#7340]
### Summary

My bot cannot connect to discord due to the Proxy (Discord.py crashes).

### Reproduction Steps

-Upload a bot code to PythonAnywhere
-Launch the bot

### Expected Results

I except that the bot will work normally, without problems like in my development environment (my computer).

### Actual Results

It crashes with this Traceback:
Traceback (most recent call last):
  File "/home/Rixy56/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1017, in create_connection
    raise exceptions[0]
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1002, in create_connection
    sock = await self._connect_sock(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 916, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 485, in sock_connect
    return await fut
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 517, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('162.159.137.232', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 627, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/Rixy56/cogs/rank.py", line 5, in <module>
    from main import thebot
  File "/home/Rixy56/main.py", line 95, in <module>
    thebot.run(token, reconnect=True)
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/client.py", line 659, in run
    return future.result()
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/client.py", line 638, in runner
    await self.start(*args, **kwargs)
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/client.py", line 601, in start
    await self.login(token)
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/client.py", line 470, in login
    await self.http.static_login(token.strip())
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/http.py", line 383, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/http.py", line 276, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/home/Rixy56/.local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/home/Rixy56/.local/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/Rixy56/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/Rixy56/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/Rixy56/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/home/Rixy56/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/Rixy56/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Connect call failed ('162.159.137.232', 443)]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 37, in starter
    thebot.load_extension(f'cogs.{cog}')
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 699, in load_extension
    self._load_from_module_spec(spec, name)
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 629, in _load_from_module_spec
    del sys.modules[key]
KeyError: 'cogs.rank'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 93, in <module>
    starter()
  File "main.py", line 40, in starter
    thebot.unload_extension(f'cogs.{filename[:-3]}')
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 737, in unload_extension
    raise errors.ExtensionNotLoaded(name)
discord.ext.commands.errors.ExtensionNotLoaded: Extension 'cogs.rank' has not been loaded.

### Intents

Hmm... I dunno what is this...

### System Information

- Python v3.8.0-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3453+g58ca9e9
- aiohttp v3.7.4.post0
- system info: Linux 5.4.0-1038-aws # 40 SMP Thu Mar 4 18:32:33 UTC 2021

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Phxntxm** [comment]
Did you provide the proxy information when creating the bot instance?

**Comment by Rix565** [comment]
Proxy info ?

**Comment by Phxntxm** [comment]
Well yeah, if you're using a proxy... then discord.py needs to know the proxy information to use it. Look at the `proxy` and `proxy_auth` kwargs to the client:

https://discordpy.readthedocs.io/en/stable/api.html#discord.Client

**Comment by Rix565** [comment]
how can i implement that on my bot ? on the bot variable ?

**Comment by Rix565** [comment]
Traceback (most recent call last):
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/client.py", line 505, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/gateway.py", line 309, in from_client
    socket = await client.http.ws_connect(gateway)
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/http.py", line 208, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/Rixy56/.local/lib/python3.8/site-packages/aiohttp/client.py", line 754, in _ws_connect
    resp = await self.request(
  File "/home/Rixy56/.local/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/home/Rixy56/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/Rixy56/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 890, in _create_connection
    _, proto = await self._create_proxy_connection(req, traces, timeout)
  File "/home/Rixy56/.local/lib/python3.8/site-packages/aiohttp/connector.py", line 1124, in _create_proxy_connection
    raise ClientHttpProxyError(
aiohttp.client_exceptions.ClientHttpProxyError: 403, message='Forbidden', url=URL('http://proxy.server:3128/')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 627, in _load_from_module_spec
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/Rixy56/cogs/rank.py", line 5, in <module>
    from main import thebot
  File "/home/Rixy56/main.py", line 96, in <module>
    thebot.run(token, reconnect=True)
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/client.py", line 659, in run
    return future.result()
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/client.py", line 638, in runner
    await self.start(*args, **kwargs)
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/client.py", line 602, in start
    await self.connect(reconnect=reconnect)
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/client.py", line 554, in connect
    ws_params.update(sequence=self.ws.sequence, resume=True, session=self.ws.session_id)
AttributeError: 'NoneType' object has no attribute 'sequence'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 38, in starter
    thebot.load_extension(f'cogs.{cog}')
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 699, in load_extension
    self._load_from_module_spec(spec, name)
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 629, in _load_from_module_spec
    del sys.modules[key]
KeyError: 'cogs.rank'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 94, in <module>
    starter()
  File "main.py", line 41, in starter
    thebot.unload_extension(f'cogs.{filename[:-3]}')
  File "/home/Rixy56/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 737, in unload_extension
    raise errors.ExtensionNotLoaded(name)
discord.ext.commands.errors.ExtensionNotLoaded: Extension 'cogs.rank' has not been loaded.
new traceback

**Comment by Astrea49** [comment]
PythonAnywhere has explicitly stated, many times, that they will not support discord.py, sadly. Simply put, it uses websockets for parts of it, and PythonAnywhere doesn't like that.

You can check more about it [here](https://www.pythonanywhere.com/forums/topic/7384/) or just by searching around the fourms.
