### ISSUE TITLE
cant get bot to play youtube video

### ISSUE THREAD

**Issue by chgaming** [Rapptz/discord.py#735]
when i run the command to play music through youtube i get this error

Traceback (most recent call last):
  File "C:\Users\gaming\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\voice_client.py", line 431, in create_ffmpeg_player
    p = subprocess.Popen(args, stdin=stdin, stdout=subprocess.PIPE, stderr=stderr)
  File "C:\Users\gaming\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "C:\Users\gaming\AppData\Local\Programs\Python\Python35\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\gaming\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "C:/Users/gaming/Desktop/DissFm/bot/main.py", line 23, in on_message
    player = await voice.create_ytdl_player("https://www.youtube.com/watch?v=dcLoIj8nXPs")
  File "C:\Users\gaming\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\voice_client.py", line 541, in create_ytdl_player
    player = self.create_ffmpeg_player(download_url, **kwargs)
  File "C:\Users\gaming\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\voice_client.py", line 434, in create_ffmpeg_player
    raise ClientException('ffmpeg/avconv was not found in your PATH environment variable') from e
discord.errors.ClientException: ffmpeg/avconv was not found in your PATH environment variable

**Comment by DiNitride** [comment]
`ffmpeg/avconv was not found in your PATH environment variable`

Install ffmpeg
