### ISSUE TITLE
Tried Starting Bot

### ISSUE THREAD

**Issue by zoaq0** [Rapptz/discord.py#7350]
### Summary

Error when running bot

### Reproduction Steps

i ran the bot

### Minimal Reproducible Code

```python
Traceback (most recent call last):
  File "c:\Users\njmcl\Documents\my code\recognition\bot.py", line 65, in <module>
    bot.run('my token')
  File "C:\Users\njmcl\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 723, in run    
    return future.result()
  File "C:\Users\njmcl\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 702, in runner 
    await self.start(*args, **kwargs)
  File "C:\Users\njmcl\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 666, in start  
    await self.connect(reconnect=reconnect)
  File "C:\Users\njmcl\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 601, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F945EB75E0>
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001F945EB75E0>
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 746, in call_soon
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
RuntimeError: Event loop is closed
PS C:\Users\njmcl\Documents\my code\recognition> & "C:/Program Files/Python39/python.exe" "c:/Users/njmcl/Documents/my code/recognition/bot.py"
Traceback (most recent call last):
  File "c:\Users\njmcl\Documents\my code\recognition\bot.py", line 65, in <module>
    bot.run('my token')
  File "C:\Users\njmcl\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 723, in run
    return future.result()
  File "C:\Users\njmcl\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\njmcl\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 666, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\njmcl\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 601, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000143D5D275E0>
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
PS C:\Users\njmcl\Documents\my code\recognition>
```

### Expected Results

it running

### Actual Results

it didnt run

### Intents

default

### System Information

- Python v3.9.5-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19042

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

it doesnt actually say 'my token'

**Comment by zoaq0** [comment]
im dumb

**Comment by wiseman** [comment]
Wonderful. Love the "I solved it" without the solution.
