### ISSUE TITLE
`TypeError: send() got an unexpected keyword argument 'embeds'`

### ISSUE THREAD

**Issue by schlopp** [Rapptz/discord.py#7351]
### Summary

`discord.abc.Messageable.send` doesn't accept the argument `embeds`, though it's listed in the documentation

### Reproduction Steps

Use [`discord.abc.Messageable.send`](https://discordpy.readthedocs.io/en/latest/api.html?highlight=send#discord.abc.Messageable.send), with the `embeds` argument being a list of embeds

### Minimal Reproducible Code

```python
await ctx.send(embeds=[
  discord.Embed(title='example'), discord.Embed(title='example')
])
```

### Expected Results

I expected to send two embeds in the same message

### Actual Results

````py
Traceback (most recent call last):
  File "C:\my\path\here.py", line 170, in eval
    obj = await local_variables["func"]()
  File "<string>", line 2, in func
TypeError: send() got an unexpected keyword argument 'embeds'


send() got an unexpected keyword argument 'embeds'
```

### Intents

`discord.Intents.default()`

### System Information

```sh
- Python v3.8.10-final
- discord.py v1.7.2-final
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

**Comment by Rapptz** [comment]
This feature is only in v2.
