### ISSUE TITLE
InvalidArgument: 'reason' is not a valid field.

### ISSUE THREAD

**Issue by FeelsBadMan1** [Rapptz/discord.py#7371]
### Summary

The Reasonkeyword dont exist in the libary file but it exist in the doc

### Reproduction Steps

I ran a command that creates roles, delete messages etc. and there is a reason keyword that shows why the bot exaclty deleted a message as example the reason keyword is in the docs and worked the last time i edited the project (about 1 year ago) fine. Now i asked in some discordservers if they understand how to solve it; nobody could solve it => first issuretype they saw so far
I then thought i should look into the libaryfiles and well i found out that the reason keyword does not exist but it should be. 
here the part of the libary that shows what i mean: 
![grafik](https://user-images.githubusercontent.com/40109798/129229735-0f87abd6-296a-4d0f-ad7b-0bb5144a65f0.png)

### Minimal Reproducible Code

```python
Ignoring exception in command serverload:
Traceback (most recent call last):
  File "D:\Downloads\Python\python 3.9.6\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\my_python_projects\testproject\main.py", line 3085, in serverload
    await ctx.guild.create_role(name=role["name"], colour=discord.Colour.from_rgb(*role["colour"]),
  File "D:\Downloads\Python\python 3.9.6\lib\site-packages\discord\guild.py", line 1990, in create_role
    raise InvalidArgument('%r is not a valid field.' % key)
discord.errors.InvalidArgument: 'reason' is not a valid field.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Downloads\Python\python 3.9.6\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "D:\Downloads\Python\python 3.9.6\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Downloads\Python\python 3.9.6\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: InvalidArgument: 'reason' is not a valid field.
```
```


### Expected Results

I expected that there is no error and that the reasonkeyword works fine. Its even listed in the docs.

### Actual Results

The errouroutput above is what happend when i ran the code.

### Intents

No intents are used

### System Information

- Python v3.9.6-final
- discord.py v1.7.3
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000


### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

**Comment by Rapptz** [comment]
`reason` is a hardcoded keyword argument:

https://github.com/Rapptz/discord.py/blob/462ba84809f43349296c44cbe6468f631a00edab/discord/guild.py#L1834

Therefore it should never trigger this exception. I'm not sure what's going on here.
