### ISSUE TITLE
Modals Don't Seem to Work

### ISSUE THREAD

**Issue by Pysics** [Rapptz/discord.py#7576]
### Summary

Modals aren't working with the `master` branch of `discord.py`.

### Reproduction Steps

1. Clone the latest version of `discord.py` from GitHub.
2. Use the code below.

### Minimal Reproducible Code

```python
class test(Modal, title=f"{ctx.author.name}'s Response"):
    response = TextInput(label="Response", placeholder="Enter your response here.")
    async def on_submit(self, interaction):
        await interaction.response.edit_message(content='test')
modal = test()
b1 = Button(label="Respond")
async def b1_callback(interaction):
    if interaction.user != ctx.author:
        await interaction.response.send_message("This is not for you.", ephemeral=True)
    else:
        await interaction.response.send_modal(modal)
view = View()
view.add_item(b1)
await ctx.send(view=view)
```

### Expected Results

A modal response should be sent and after submission the message should be edited to `test`.

### Actual Results

Nothing happens and the following error occurs:
```
Ignoring exception in view <View timeout=180.0 children=1> for item <Button style=<ButtonStyle.secondary: 2> url=None disabled=False label='Respond' emoji=None row=None>:
 Traceback (most recent call last):
   File "/app/.heroku/python/lib/python3.10/site-packages/discord/ui/view.py", line 375, in _scheduled_task
     await interaction.response.defer()
   File "/app/.heroku/python/lib/python3.10/site-packages/discord/interactions.py", line 473, in defer
     await adapter.create_interaction_response(parent.id, parent.token, session=parent._session, params=params)
   File "/app/.heroku/python/lib/python3.10/site-packages/discord/webhook/async_.py", line 192, in request
     raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10062): Unknown interaction
```

### Intents

None

### System Information

Python 3.10
`discord.py` `master` Branch

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by nerdguyahmad** [comment]
You are not assigning `b1_callback` to `b1` button's callback.

**Comment by Pysics** [comment]
Sorry for that. This issue will be closed with this comment.
