### ISSUE TITLE
Random crashing

### ISSUE THREAD

**Issue by Motzumoto** [Rapptz/discord.py#7630]
### Summary

randomly getting crashes

### Reproduction Steps

simply use the latest version (as of writing) of dpy and you'll eventually run into this error

### Minimal Reproducible Code

```python
No response
```

### Expected Results

No response

### Actual Results

No response

### Intents

Members and default. I do not have message content enabled

### System Information

- Python v3.9.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3819+g00db1157
- aiohttp v3.7.4.post0
- system info: Linux 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Heres the error
```py

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 750, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ubuntu/LunarDev/AGB/Cogs/info.py", line 14, in <module>
    from index import (
  File "/home/ubuntu/LunarDev/AGB/index.py", line 225, in <module>
    bot.run(config.token)
  File "/home/ubuntu/LunarDev/AGB/index.py", line 88, in run
    super().run(token)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/client.py", line 704, in run
    return future.result()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/client.py", line 683, in runner
    await self.start(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/client.py", line 647, in start
    await self.connect(reconnect=reconnect)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/shard.py", line 450, in connect
    raise item.error
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/shard.py", line 164, in worker
    await self.ws.poll_event()
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/gateway.py", line 626, in poll_event
    await self.received_message(msg.data)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/gateway.py", line 576, in received_message
    func(data)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/state.py", line 977, in parse_guild_member_add
    guild._member_count += 1
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/LunarDev/AGB/index.py", line 225, in <module>
    bot.run(config.token)
  File "/home/ubuntu/LunarDev/AGB/index.py", line 86, in run
    self.setup()
  File "/home/ubuntu/LunarDev/AGB/index.py", line 94, in setup
    bot.load_extension(f"Cogs.{name}")
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 822, in load_extension
    self._load_from_module_spec(spec, name)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 752, in _load_from_module_spec
    del sys.modules[key]
KeyError: 'Cogs.info'
```

From what I can see, this isn't an issue on my part, but within the package itself.

**Comment by JDJGInc** [comment]
yeah this will be fixed in
https://github.com/Rapptz/discord.py/pull/7617

**Comment by Motzumoto** [comment]
> yeah this will be fixed in

Okie dokie!
