### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by RudeBois** [Rapptz/discord.py#765]
This happens then I attempt to install discord.py with ``python3 -m pip install -U discord.py``:

```(xenial)rudebois@localhost:~$ python3 -m pip install -U discord.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.6/site-packages/pip-1.2.1-py3.6.egg/pip/__init__.py", line 9, in <module>
    from pip.basecommand import command_dict, load_command, load_all_commands, command_names
  File "/usr/local/lib/python3.6/site-packages/pip-1.2.1-py3.6.egg/pip/basecommand.py", line 13, in <module>
    from pip.baseparser import parser, ConfigOptionParser, UpdatingDefaultsHelpFormatter
  File "/usr/local/lib/python3.6/site-packages/pip-1.2.1-py3.6.egg/pip/baseparser.py", line 5, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by Rapptz** [comment]
https://stackoverflow.com/q/7446187/1381108

**Comment by xLingling** [comment]
u dont use python3...... u use python/py instead

**Comment by RudeBois** [comment]
@Rapptz the command it suggests doesn't work for me, even when ran with sudo (because the error message was `error: can't create or remove files in install directory`)

**Comment by Rapptz** [comment]
The gist of it is the same.

Your installation of python is somehow missing setuptools. Find a way to get it and then pip will work.
