### ISSUE TITLE
Unloading Extension fails when manually defining app command group

### ISSUE THREAD

**Issue by Luc1412** [Rapptz/discord.py#7667]
### Summary

Unloading Extension fails when manually defining command group

### Reproduction Steps

1. Use the minimal reproducible code
2. Load a cog
3. Unload the cog

### Minimal Reproducible Code

`test.py`
```python
from discord.ext import commands

bot = commands.Bot(command_prefix='!')
bot.load_extension('test_cog')


@bot.event
async def on_ready():
    bot.unload_extension('test_cog')

if __name__ == '__main__':
    bot.run("token")
```

`test_cog.py`
```python

from discord import app_commands
from discord.ext import commands


class TestCog(commands.Cog, app_commands.Group):

    test_group = app_commands.Group(name='test_group', description='test_group')

    def __init__(self, bot):
        self.bot = bot

    @test_group.command(name='sub', description='Test sub command')
    async def test(self, inter):
        await inter.response.send_message('Test command')


def setup(bot):
    # Add the cog to the bot
    bot.add_cog(TestCog(bot))
```

### Expected Results

The extension will be successfully unloaded

### Actual Results

Following error occurs:
```py
Traceback (most recent call last):
  File "venv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 760, in _load_from_module_spec
    setup(self)
  File "/test_cog.py", line 19, in setup
    bot.add_cog(TestCog(bot))
  File "/venv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 601, in add_cog
    self.__tree.add_command(cog, override=override, guild=guild, guilds=guilds)
  File "/venv/lib/python3.9/site-packages/discord/app_commands/tree.py", line 230, in add_command
    root = command.root_parent or command
  File "/venv/lib/python3.9/site-packages/discord/app_commands/commands.py", line 795, in root_parent
    return self.parent
AttributeError: 'TestCog' object has no attribute 'parent'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/test.py", line 4, in <module>
    bot.load_extension('test_cog')
  File "/venv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 820, in load_extension
    self._load_from_module_spec(spec, name)
  File "/venv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 765, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'test_cog' raised an error: AttributeError: 'TestCog' object has no attribute 'parent'
```

### Intents

Default

### System Information

- Python v3.9.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3849+g6def5c91
- aiohttp v3.7.4.post0
- system info: Darwin 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
You are missing the `super().__init__()` call.
