### ISSUE TITLE
Running AutoShardedBot raises error on startup

### ISSUE THREAD

**Issue by Luc1412** [Rapptz/discord.py#7675]
### Summary

Running AutoShardedBot raises error on startup

### Reproduction Steps

Create a AutoShardedBot and start it.

### Minimal Reproducible Code

```python
from discord.ext import commands

bot = commands.AutoShardedBot(command_prefix='!')

if __name__ == '__main__':
    bot.run("token")
```

### Expected Results

The bot normally starts

### Actual Results

Traceback (most recent call last):
  File "/test.py", line 3, in <module>
    bot = commands.AutoShardedBot(command_prefix='!')
  File "/venv/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 132, in __init__
    super().__init__(**options)
  File "/venv/lib/python3.9/site-packages/discord/ext/commands/core.py", line 1150, in __init__
    super().__init__(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/discord/shard.py", line 323, in __init__
    super().__init__(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/discord/client.py", line 208, in __init__
    self._connection: ConnectionState = self._get_state(**options)
  File "/venv/lib/python3.9/site-packages/discord/shard.py", line 345, in _get_state
    return AutoShardedConnectionState(
  File "venv/lib/python3.9/site-packages/discord/state.py", line 1486, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() missing 1 required keyword-only argument: 'loop'

### Intents

default

### System Information

- Python v3.9.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a3859+g6a43d60a
- aiohttp v3.7.4.post0
- system info: Darwin 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This also applies to AutoShardedClient

**Comment by nmsturcke** [comment]
Pretty sure it has to do with 93af158b0ce72d8b53b13d6aead5be35cff41d28
