### ISSUE TITLE
[Question] - Unknown Exception (Crash)

### ISSUE THREAD

**Issue by jgayfer** [Rapptz/discord.py#769]
Hello,

I might be late to the party here, but just wanted to make sure about a few things. My bot has crashed a couple times with the following exception.

```
Traceback (most recent call last):
  File "spirit.py", line 56, in <module>
    bot.run(token)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 567, in run
    return task.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 475, in start
    yield from self.connect(reconnect=reconnect)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 407, in connect
    yield from self._connect()
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 369, in _connect
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 438, in poll_event
    yield from self.received_message(msg)
  File "/usr/local/lib/python3.5/dist-packages/discord/gateway.py", line 391, in received_message
    func(data)
  File "/usr/local/lib/python3.5/dist-packages/discord/state.py", line 499, in parse_channel_create
    channel = factory(guild=guild, state=self, data=data)
TypeError: 'NoneType' object is not callable
```
I *think* that this commit (1367877d36872ae98e8375d6a9b76ab7dc1c991e) is addressing my issue, but I'm not 100% sure. Is someone able to confirm this? I haven't been able to reproduce this since I updated. However, I just wanted this to be visible in the event that it is a different issue.

Thanks!

**Comment by NotSoSuper** [comment]
yes, that commit fixes it

**Comment by jgayfer** [comment]
Great - thanks @NotSoSuper !
