### ISSUE TITLE
Guild and Global Commands Not Available In Guild

### ISSUE THREAD

**Issue by brarsanmol** [Rapptz/discord.py#7841]
### Summary

I've attempted to get this command named /sentinel working in a Guild that the bot is in it does not work no matter if I leave it as global or put it to a guild.

### Reproduction Steps

```
(sentinel-p2Tj352c-py3.10) brarsanmol@Anmols-MacBook-Pro sentinel % python sentinel/__init__.py
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/Users/brarsanmol/Library/Caches/pypoetry/virtualenvs/sentinel-p2Tj352c-py3.10/lib/python3.10/site-packages/discord/client.py", line 373, in _run_event
    await coro(*args, **kwargs)
  File "/Users/brarsanmol/Developer/sentinel/sentinel/main.py", line 42, in on_ready
    await self.tree.sync(guild=discord.Object(id=932346590767775774))
  File "/Users/brarsanmol/Library/Caches/pypoetry/virtualenvs/sentinel-p2Tj352c-py3.10/lib/python3.10/site-packages/discord/app_commands/tree.py", line 874, in sync
    data = await self._http.bulk_upsert_guild_commands(self.client.application_id, guild.id, payload=payload)
  File "/Users/brarsanmol/Library/Caches/pypoetry/virtualenvs/sentinel-p2Tj352c-py3.10/lib/python3.10/site-packages/discord/http.py", line 491, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
```

### Minimal Reproducible Code

```python
from typing import List
import discord
from discord import Color, Role, app_commands

from sentinel.commands.enter_direct_message_channel import EnterDirectMessageChannel


class Setup(app_commands.Command):
    def __init__(self):
        super().__init__(
            name="sentinel",
            description="Create the Sentinel welcome message, and create the Verified role.",
            callback=self.execute,
            guild_ids=[932346590767775774],
        )

    def get_welcome_message_view() -> discord.ui.View:
        view = discord.ui.View()
        view.add_item(EnterDirectMessageChannel())
        return view

    async def execute(self, interaction: discord.Interaction) -> None:
        if interaction.user.guild_permissions.administrator:
            role: Role = discord.utils.get(interaction.guild.roles, name="Verified")
            if role is None:
                await interaction.user.guild.create_role(
                    name="Verified", color=Color.light_gray, mentionable=False
                )
            interaction.channel.send(
                """
                Verify yourself by clicking the button below!
                """,
                view=self.get_welcome_message(),
            )


```python
        self.tree.add_command(Setup())
        ...
        await self.tree.sync(guild=discord.Object(id=932346590767775774))
        await self.tree.sync()
```

### Expected Results

I expected the command to be registered in the Guild, it is not no matter whether I add or remove the guild options.

### Actual Results

The command is not registered in the Guild, if it is left as Global it is available in direct messages.

### Intents

discord.Intents().all()

### System Information

- Python v3.10.2-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4042+g14582517
- aiohttp v3.8.1
- system info: Darwin 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ChesterWOV-DPY** [comment]
Does the guild have the `applications.commands` scope?

**Comment by brarsanmol** [comment]
> Does the guild have the `applications.commands` scope?

Thank you so much, I didn't have this enabled, but once I enabled it the command's started working!
