### ISSUE TITLE
Webhook.edit_message leads to internal exception

### ISSUE THREAD

**Issue by aldalen** [Rapptz/discord.py#7842]
### Summary

Webhook.edit_message throws "AttributeError: PartialWebhookState does not support 'get_reaction_emoji'"

### Reproduction Steps

My bot updates an embed on a regular cadence, so I store webhook urls in my database, then iterate through them. When posting the new embed, on some servers, I was seeing this in my logs.

I tried with or without "webhook = await webhook.fetch()" to get the "full webhook" and still ran into the same exception. Seems like something on some servers is causing a path to look for reaction emoji.

### Minimal Reproducible Code

```python
async with aiohttp.ClientSession() as session:
            try:
                webhook = discord.Webhook.from_url(hook_url, session=session)
                webhook = await webhook.fetch()
            except discord.InvalidArgument:
                self.logging.error("Error: Webhook invalid.")
                return

            try:
                await webhook.edit_message(config.message_id, content="", embed=append_advert_if_needed(self.bot, config.server.pk, new_embed, lang=config.locale))

            except AttributeError as error:
                # Here is where the PartialWebhookState error is caught
                self.logging.error("CAUGHT AttributeError `{}`".format(str(error)))
                traceback.print_exc(file=sys.stdout)
                pass
```

### Expected Results

No exception

### Actual Results
 ```
AttributeError `PartialWebhookState does not support 'get_reaction_emoji'.`
Traceback (most recent call last):
  File "../countdown/loops.py", line 131, in update_message
    await webhook.edit_message(config.message_id, content="", embed=append_advert_if_needed(self.bot, config.server.pk, new_embed, lang=config.locale))
  File "[path_removed]/lib/python3.9/site-packages/discord/webhook/async_.py", line 1722, in edit_message
    message = self._create_message(data, thread=thread)
  File "[path_removed]/lib/python3.9/site-packages/discord/webhook/async_.py", line 1334, in _create_message
    return WebhookMessage(data=data, state=state, channel=channel)  # type: ignore
  File "[path_removed]/lib/python3.9/site-packages/discord/message.py", line 1383, in __init__
    self.reactions: List[Reaction] = [Reaction(message=self, data=d) for d in data.get('reactions', [])]
  File "[path_removed]/lib/python3.9/site-packages/discord/message.py", line 1383, in <listcomp>
    self.reactions: List[Reaction] = [Reaction(message=self, data=d) for d in data.get('reactions', [])]
  File "[path_removed]/lib/python3.9/site-packages/discord/reaction.py", line 88, in __init__
    self.emoji: Union[PartialEmoji, Emoji, str] = emoji or message._state.get_reaction_emoji(data['emoji'])
  File "[path_removed]/lib/python3.9/site-packages/discord/webhook/async_.py", line 664, in __getattr__
    raise AttributeError(f'PartialWebhookState does not support {attr!r}.')
AttributeError: PartialWebhookState does not support 'get_reaction_emoji'.
```
### Intents

None

### System Information

- Python v3.9.12-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4041+gd5d9a53
- aiohttp v3.8.1
- system info: Linux 5.13.19-6-pve #1 SMP PVE 5.13.19-15 (Tue, 29 Mar 2022 15:59:50 +0200)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This exception is by design, it's meant to tell you unsupported things. However, I also agree that this one is an oversight as the webhook state should be able to handle reactions.

**Comment by aldalen** [comment]
Thanks for getting it resolved!
