### ISSUE TITLE
Possible crash when Discord goes down

### ISSUE THREAD

**Issue by Pandentia** [Rapptz/discord.py#788]
Full traceback as follows:

```py
Traceback (most recent call last):
  File "liara.py", line 406, in run_app
    loop.run_until_complete(run_bot())
  File "uvloop/loop.pyx", line 1203, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25636)
  File "liara.py", line 396, in run_bot
    await liara.connect()
  File "/usr/local/lib/python3.6/site-packages/discord/client.py", line 407, in connect
    yield from self._connect()
  File "/usr/local/lib/python3.6/site-packages/discord/shard.py", line 266, in _connect
    f.result()
  File "/usr/local/lib/python3.6/site-packages/discord/shard.py", line 56, in poll
    yield from self.ws.poll_event()
  File "/usr/local/lib/python3.6/site-packages/discord/gateway.py", line 438, in poll_event
    yield from self.received_message(msg)
  File "/usr/local/lib/python3.6/site-packages/discord/gateway.py", line 391, in received_message
    func(data)
  File "/usr/local/lib/python3.6/site-packages/discord/state.py", line 554, in parse_guild_member_add
    guild._member_count += 1
AttributeError: _member_count
```

I'm guessing this is caused by trying to update an internal count value while the guild is unavailable, but my guess is as good as yours.

**Comment by Rapptz** [comment]
It should be impossible to receive GUILD_MEMBER_ADD after a GUILD_DELETE so not sure how this synchrocity issue happened.

**Comment by Rapptz** [comment]
I believe this was caused by fucked up state on Discord's side from the conversation we had that day.
