### ISSUE TITLE
Error While Using Autocomplete

### ISSUE THREAD

**Issue by Pysics** [Rapptz/discord.py#7880]
### Summary

Autocomplete doesn't seem to work.

### Reproduction Steps

Try an autocomplete command.

### Expected Results

No errors.

### Actual Results

```
 Traceback (most recent call last):
   File "/app/.heroku/python/lib/python3.10/site-packages/discord/app_commands/tree.py", line 898, in wrapper
     await self.call(interaction)
   File "/app/.heroku/python/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1054, in call
     await command._invoke_autocomplete(interaction, focused, namespace)
   File "/app/.heroku/python/lib/python3.10/site-packages/discord/app_commands/commands.py", line 605, in _invoke_autocomplete
     await interaction.response.autocomplete(choices)
   File "/app/.heroku/python/lib/python3.10/site-packages/discord/interactions.py", line 822, in autocomplete
     'choices': [option.to_dict() for option in choices],
   File "/app/.heroku/python/lib/python3.10/site-packages/discord/interactions.py", line 822, in <listcomp>
     'choices': [option.to_dict() for option in choices],
 AttributeError: 'str' object has no attribute 'to_dict'
 ```

### Intents

All

### System Information

Python 3.10
`discord.py` from `master`

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
This has no discernible or actionable info in it. Judging from this traceback chances are instead of returning `app_commands.Choice` objects you're returning strings.
