### ISSUE TITLE
ImportError: cannot import name 'PartialMessageable' from 'discord.channel'

### ISSUE THREAD

**Issue by JustinLiAtSBU** [Rapptz/discord.py#7907]
### Summary

Getting an ImportError on discord.py v1.7.3

### Reproduction Steps

I imported discord with these dependencies in my requirements.txt

> aiohttp==3.7.4.post0
> async-timeout==3.0.1
> attrs==21.4.0
> certifi==2021.10.8
> chardet==4.0.0
> charset-normalizer==2.0.12
> discord-components==2.1.2
> discord-ui==5.1.6
> discord.py==1.7.3
> emoji-country-flag==1.3.0
> ffmpeg-python==0.2.0
> future==0.18.2
> fuzzywuzzy==0.18.0
> idna==3.3
> imageio-ffmpeg==0.4.6
> multidict==6.0.2
> numpy==1.22.3
> py-cord==2.0.0b7
> pycountry==22.3.5
> python-dotenv==0.20.0
> python-Levenshtein==0.12.2
> requests==2.27.1
> typing_extensions==4.1.1
> urllib3==1.26.9
> yarl==1.7.2

### Expected Results

I expected my code to be compiled.

### Actual Results

There is an ImportError in discord.py

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/homebrew/lib/python3.9/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/opt/homebrew/lib/python3.9/site-packages/discord/client.py", line 53, in <module>
    from .webhook import Webhook
  File "/opt/homebrew/lib/python3.9/site-packages/discord/webhook/__init__.py", line 12, in <module>
    from .async_ import *
  File "/opt/homebrew/lib/python3.9/site-packages/discord/webhook/async_.py", line 52, in <module>
    from ..channel import PartialMessageable

### Intents

intents = discord.Intents().default() intents.message_content = True intents.members = True intents.presences = True

### System Information

❯ python3 -m discord -v
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/homebrew/lib/python3.9/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/opt/homebrew/lib/python3.9/site-packages/discord/client.py", line 53, in <module>
    from .webhook import Webhook
  File "/opt/homebrew/lib/python3.9/site-packages/discord/webhook/__init__.py", line 12, in <module>
    from .async_ import *
  File "/opt/homebrew/lib/python3.9/site-packages/discord/webhook/async_.py", line 52, in <module>
    from ..channel import PartialMessageable
ImportError: cannot import name 'PartialMessageable' from 'discord.channel' (/opt/homebrew/lib/python3.9/site-packages/discord/channel.py)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This was working just yesterday. I do see that PartialMessageable is not a class in discord.channel right now, but it was yesterday. This was first an issue on Heroku, but wasn't an issue on my local. I deleted the discord package and reinstalled today and the issue is happening on my local now too. I am not sure what I did to break the dependencies.

**Comment by JDJGInc** [comment]
It's better to use v2 than external libraries

**Comment by JDJGInc** [comment]
I.e. discord.ui and discord-components

**Comment by AbstractUmbra** [comment]
I can see you also have `py-cord` and `discord-ui` installed.
Both of these libraries interfere with `discord.py`'s site-package and as such, cause errors like this.
Please remove the offending libraries and then force a clean reinstall of discord.py:
```sh
pip install -U discord.py --force-reinstall
```

Which should correct the broken installation.

**Comment by SebbyLaw** [comment]
This is not an issue with discord.py. Uninstall third party libraries such as "discord-components", "discord-ui", and "pycord".

**Comment by JustinLiAtSBU** [comment]
Thanks for the quick responses, that worked.
