### ISSUE TITLE
401:Unauthorized with correct token

### ISSUE THREAD

**Issue by nonnymoose** [Rapptz/discord.py#792]
Here is the code I use:
```
#!/usr/bin/env python3

import discord
import asyncio

client = discord.Client()

@client.event
async def on_ready():
    print('Logged in as')
    print(client.user.name)
    print(client.user.id)
    print('------')

@client.event
async def on_message(message):
    if message.content.startswith('!test'):
        counter = 0
        tmp = await client.send_message(message.channel, 'Calculating messages...')
        async for log in client.logs_from(message.channel, limit=100):
            if log.author == message.author:
                counter += 1

        await client.edit_message(tmp, 'You have {} messages.'.format(counter))
    elif message.content.startswith('!sleep'):
        await asyncio.sleep(5)
        await client.send_message(message.channel, 'Done sleeping')

client.run('my_bot_user_token')
```
I always get this:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 258, in static_login
    data = yield from self.request(Route('GET', '/users/@me'))
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./discordbot.py", line 29, in <module>
    client.run('BI-lH53ee1719UaZgfsSrbFNcVAtgJ9j')
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 519, in run
    self.loop.run_until_complete(self.start(*args, **kwargs))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 490, in start
    yield from self.login(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 416, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 346, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 262, in static_login
    raise LoginFailure('Improper token has been passed.') from e
discord.errors.LoginFailure: Improper token has been passed.
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe0c434e278>
```
even though I have tried in excess of twenty times and I am _absolutely sure_ that my token is correct and the bot is authorized on my server.

Is there a problem with my code? If not, what could be the cause for this? Do I need to provide any more information about my configuration?

**Comment by Rapptz** [comment]
If the library says the token is incorrect, then the token is incorrect.

Note that the token is not the secret. You have to click to reveal the token and ensure that there's no trailing whitespace.

**Comment by nonnymoose** [comment]
@Rapptz In all my testing, I neglected to check that I was saving to the right file.

Sorry to waste your time.
