### ISSUE TITLE
WSServerHandshakeError: 503, message='Invalid response status'

### ISSUE THREAD

**Issue by KweezyPlay** [Rapptz/discord.py#7996]
### Summary

WSServerHandshakeError: 503, message='Invalid response status'

### Reproduction Steps

Copy example for repository/net and run

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands
TOKEN = "x"
intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix="!", intents=intents)
@bot.event
async def on_ready():
    print(f'{bot.user} succesfully logged in!')
bot.run(TOKEN)
```

### Expected Results

working bot

### Actual Results

kweezy@rasphost:~/bungee$ python3 example.py
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/kweezy/.local/lib/python3.8/site-packages/discord/client.py", line 579, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 494, in wait_for
    return fut.result()
  File "/home/kweezy/.local/lib/python3.8/site-packages/discord/gateway.py", line 359, in from_client
    socket = await client.http.ws_connect(gateway)
  File "/home/kweezy/.local/lib/python3.8/site-packages/discord/http.py", line 373, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/home/kweezy/.local/lib/python3.8/site-packages/aiohttp/client.py", line 792, in _ws_connect
    raise WSServerHandshakeError(
aiohttp.client_exceptions.WSServerHandshakeError: 503, message='Invalid response status', url=URL('wss://gateway.discord.gg/?encoding=json&v=10&compress=zlib-stream')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 11, in <module>
    bot.run(TOKEN)
  File "/home/kweezy/.local/lib/python3.8/site-packages/discord/client.py", line 711, in run
    asyncio.run(runner())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/kweezy/.local/lib/python3.8/site-packages/discord/client.py", line 708, in runner
    await self.start(*args, **kwargs)
  File "/home/kweezy/.local/lib/python3.8/site-packages/discord/client.py", line 682, in start
    await self.connect(reconnect=reconnect)
  File "/home/kweezy/.local/lib/python3.8/site-packages/discord/client.py", line 630, in connect
    ws_params.update(sequence=self.ws.sequence, resume=True, session=self.ws.session_id)
AttributeError: 'NoneType' object has no attribute 'sequence'
kweezy@rasphost:~/bungee$

### Intents

Default

### System Information

- Python v3.8.10-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a0
- aiohttp v3.8.1
- system info: Linux 5.4.0-1059-raspi #67-Ubuntu SMP PREEMPT Mon Apr 11 14:16:01 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by sidyakinian** [comment]
Same issue

**Comment by lamak** [comment]
same issue

**Comment by KweezyPlay** [comment]
quick fix: change your ip, looks like discord blacklisted it (unconfirmed, but it helped me to solve this)

**Comment by Rapptz** [comment]
I can't really do anything about this, 5xx status codes are Discord issues not mine.
