### ISSUE TITLE
"Deleting emojis return "non existing"

### ISSUE THREAD

**Issue by Eleiber** [Rapptz/discord.py#801]
I have this code

```python
@commands.is_owner()
@bot.command()
async def deleteemojis(ctx):
    for Emoji in ctx.guild.emojis:
        await Emoji.delete()
```

And when I execute the command the traceback give me a `NotFound: NOT FOUND (status code: 404): Unknown Emoji` error, here is my traceback:

```python
Ignoring exception in command deleteemojis:
Traceback (most recent call last):
  File "C:\Users\DigitalGroup21\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\DigitalGroup21\Desktop\Python36\Bot Discord\Bots Discord\Daygger Bot\bot.py", line 373, in troll
    await Emoji.delete()
  File "C:\Users\DigitalGroup21\AppData\Roaming\Python\Python36\site-packages\discord\emoji.py", line 211, in delete
    yield from self._state.http.delete_custom_emoji(self.guild.id, self.id, reason=reason)
  File "C:\Users\DigitalGroup21\AppData\Roaming\Python\Python36\site-packages\discord\http.py", line 210, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): Unknown Emoji

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\DigitalGroup21\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "C:\Users\DigitalGroup21\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 470, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\DigitalGroup21\AppData\Roaming\Python\Python36\site-packages\discord\ext\commands\core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NotFound: NOT FOUND (status code: 404): Unknown Emoji
```

**Note:** when I use `print(emoji.name)` the code shows me the emojis names without problems

**Comment by Rapptz** [comment]
Bots can only delete the emojis they made themselves apparently.
