### ISSUE TITLE
Error - Unable to import name 'handle_message_parameters' from discord.http

### ISSUE THREAD

**Issue by pavelbelov999** [Rapptz/discord.py#8038]
### Summary

Unable to import 'handle_message_parameters' when running main.py with line "import discord"

### Reproduction Steps

1) Installed the new discord.py 2.0 on replit.
2) Organised my python files into the cogs folders
3) Made amendments to the setting up of cogs by changing them to async functions.
4) Initially there were no errors, but after rerunning the bot several times the error began showing up.

### Minimal Reproducible Code

```python
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import discord
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 53, in <module>
    from .webhook import Webhook
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/webhook/__init__.py", line 12, in <module>
    from .async_ import *
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/webhook/async_.py", line 47, in <module>
    from ..http import Route, handle_message_parameters, MultipartParameters, HTTPClient
ImportError: cannot import name 'handle_message_parameters' from 'discord.http' (/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/http.py)
```

### Expected Results

I expected the bot to run as usual without any issues.

### Actual Results

Now I am unable to run my code due to the occurrence of the ImportError.

### Intents

Presence Intent, Server Members Intent and Message Contents Intent(I indicated it as discord.Intents.all())

### System Information

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/client.py", line 53, in <module>
    from .webhook import Webhook
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/webhook/__init__.py", line 12, in <module>
    from .async_ import *
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/webhook/async_.py", line 47, in <module>
    from ..http import Route, handle_message_parameters, MultipartParameters, HTTPClient
ImportError: cannot import name 'handle_message_parameters' from 'discord.http' (/opt/virtualenvs/python3/lib/python3.8/site-packages/discord/http.py)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
I think you've installed the wrong module or your install has been corrupted somehow. I'm not entirely sure how or why exactly, the recommended way to fix this in a CLI is through `pip install --force-install <git url here>`. It's easy to confirm this because the line numbers don't match up with the actual module. Line 53 in client.py is importing Template not Webhook. Regardless, this isn't an issue with the library itself.

**Comment by findmejojo** [comment]
it doesnt work.. please help

**Comment by skrvt** [comment]
Im facing the same issue aswell.

**Comment by just-rich** [comment]
anyone figure out the fix for this?

i've had this bot running for a long while, but recently just changed OS, and the sd card used on the raspberry is bad, may try and mount it to recover python packages but hoping I was going to find a better solution here.

**Comment by lightlybakedman** [comment]
#9169 @skrvt @just-rich

**Comment by just-rich** [comment]
> #9169 @skrvt @just-rich

then I'm back at this error, which iirc installing discord-components or something of the like got me passed it.

`ImportError: cannot import name 'InvalidArgument' from 'discord' (/home/th/.local/lib/python3.10/site-packages/discord/__init__.py)`
