### ISSUE TITLE
OpusError on macOS arm64 platform (only)

### ISSUE THREAD

**Issue by m13253** [Rapptz/discord.py#8046]
### Summary

When creating an opus.Encoder() instance, an exception of discord.opus.OpusError: invalid argument is thrown

### Reproduction Steps

First, install either Python 3.9 or Python 3.10.
```bash
$ brew install python
$ python3 -m pip install -U "discord.py[voice]"
```
Then, execute the code in the section below.

### Minimal Reproducible Code

```python
import discord.opus
opus_encoder = discord.opus.Encoder()
```

### Expected Results

Should load `libopus.dylib` and create an Opus encoder instance.

### Actual Results

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/discord/opus.py", line 290, in __init__
    self.set_bitrate(128)
  File "/opt/homebrew/lib/python3.10/site-packages/discord/opus.py", line 308, in set_bitrate
    _lib.opus_encoder_ctl(self._state, CTL_SET_BITRATE, kbps * 1024)
  File "/opt/homebrew/lib/python3.10/site-packages/discord/opus.py", line 92, in _err_lt
    raise OpusError(result)
discord.opus.OpusError: invalid argument
```

### Intents

Not applicable

### System Information

```
- Python v3.10.4-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

#### [1/4] This bug only happens on arm64 macOS?

Yes, only on arm64 macOS.

Confirmed no issue on x86_64 macOS or Windows or Linux.

#### [2/4] Why can't I use Windows or Linux instead?

It's because my music production software is on this platform.

I'm willing to run test code snippets on my machine if you wish.

#### [3/4] Some more check on libopus

I try to check if libopus is correctly loaded.
**Result:** yes.
```python
>>> import discord.opus
>>> discord.opus._load_default()
True
>>> discord.opus._lib
<CDLL '/opt/homebrew/lib/libopus.dylib', handle 209560680 at 0x104f380a0>
>>> discord.opus._OpusStruct.get_opus_version()
'libopus 1.3.1'
```

I try to check whether there is an architecture mismatch between Python and libopus.
**Result:** Both arm64. None are “fat binary”.
```bash
$ file /opt/homebrew/bin/python3
/opt/homebrew/bin/python3: Mach-O 64-bit executable arm64
$ file /opt/homebrew/lib/libopus.dylib
/opt/homebrew/lib/libopus.dylib: Mach-O 64-bit dynamically linked shared library arm64
```

I try to check if the request numbers are different on arm64.
**Result:** The numbers are same with x86_64.
```c
$ cd /opt/homebrew/include/opus
$ grep -r '#define OPUS_SET_[^ ]*_REQUEST'
./opus_defines.h:#define OPUS_SET_APPLICATION_REQUEST         4000
./opus_defines.h:#define OPUS_SET_BITRATE_REQUEST             4002
./opus_defines.h:#define OPUS_SET_MAX_BANDWIDTH_REQUEST       4004
./opus_defines.h:#define OPUS_SET_VBR_REQUEST                 4006
./opus_defines.h:#define OPUS_SET_BANDWIDTH_REQUEST           4008
./opus_defines.h:#define OPUS_SET_COMPLEXITY_REQUEST          4010
./opus_defines.h:#define OPUS_SET_INBAND_FEC_REQUEST          4012
./opus_defines.h:#define OPUS_SET_PACKET_LOSS_PERC_REQUEST    4014
./opus_defines.h:#define OPUS_SET_DTX_REQUEST                 4016
./opus_defines.h:#define OPUS_SET_VBR_CONSTRAINT_REQUEST      4020
./opus_defines.h:#define OPUS_SET_FORCE_CHANNELS_REQUEST      4022
./opus_defines.h:#define OPUS_SET_SIGNAL_REQUEST              4024
./opus_defines.h:#define OPUS_SET_GAIN_REQUEST                4034
./opus_defines.h:#define OPUS_SET_LSB_DEPTH_REQUEST           4036
./opus_defines.h:#define OPUS_SET_EXPERT_FRAME_DURATION_REQUEST 4040
./opus_defines.h:#define OPUS_SET_PREDICTION_DISABLED_REQUEST 4042
./opus_defines.h:#define OPUS_SET_PHASE_INVERSION_DISABLED_REQUEST 4046
```

#### [4/4] Why am I directly calling `discord.opus.Encoder`? It's supposed to be a private API.

First, the public API will eventually call into this private API and raise exception. There is no difference.

Second, [my bot program](https://github.com/m13253/discord-mic-bot) has to call into this private API in order to perform some WebRTC-level magic.

**Comment by nihaals** [comment]
Full isolated repro steps:
```
$ docker run -it --rm --platform linux/arm64/v8 python:3.10@sha256:85f504ba9cad91a636b58fdec377eb4b69ed4f6ca593a6a7ebf84617f39bad49 bash
root@ec41929e04cd:/# pip install discord.py[voice]
Collecting discord.py[voice]
  Downloading discord.py-1.7.3-py3-none-any.whl (786 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 786.7/786.7 KB 11.9 MB/s eta 0:00:00
Collecting aiohttp<3.8.0,>=3.6.0
  Downloading aiohttp-3.7.4.post0.tar.gz (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 18.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PyNaCl<1.5,>=1.3.0
  Downloading PyNaCl-1.4.0.tar.gz (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 33.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting attrs>=17.3.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 KB 7.5 MB/s eta 0:00:00
Collecting chardet<5.0,>=2.0
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 178.7/178.7 KB 37.9 MB/s eta 0:00:00
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (116 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.6/116.6 KB 25.8 MB/s eta 0:00:00
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.7.2-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (320 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 320.7/320.7 KB 29.6 MB/s eta 0:00:00
Collecting typing-extensions>=3.6.5
  Downloading typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting async-timeout<4.0,>=3.0
  Downloading async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting six
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting cffi>=1.4.1
  Using cached cffi-1.15.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (448 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting idna>=2.0
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 KB 29.1 MB/s eta 0:00:00
Building wheels for collected packages: aiohttp, PyNaCl
  Building wheel for aiohttp (pyproject.toml) ... done
  Created wheel for aiohttp: filename=aiohttp-3.7.4.post0-cp310-cp310-linux_aarch64.whl size=1405565 sha256=26b6ddd3bcd3af21d8d298bf83e4958cf286b016af10b33b1be2110c2963fc32
  Stored in directory: /root/.cache/pip/wheels/fc/84/e0/52113c57eb9b09b6b187a0f369eaad6fc7fc64bb7247c83b89
  Building wheel for PyNaCl (pyproject.toml) ... done
  Created wheel for PyNaCl: filename=PyNaCl-1.4.0-cp310-cp310-linux_aarch64.whl size=674895 sha256=9208be43fadcd838e1dff3d816642b22db5c345381d59d745dbbdcf670c0ae8a
  Stored in directory: /root/.cache/pip/wheels/9a/b9/c4/595227c0f6b2e698fde0463057784cafc0902b1a47fb0866d9
Successfully built aiohttp PyNaCl
Installing collected packages: typing-extensions, six, pycparser, multidict, idna, chardet, attrs, async-timeout, yarl, cffi, PyNaCl, aiohttp, discord.py
Successfully installed PyNaCl-1.4.0 aiohttp-3.7.4.post0 async-timeout-3.0.1 attrs-21.4.0 cffi-1.15.0 chardet-4.0.0 discord.py-1.7.3 idna-3.3 multidict-6.0.2 pycparser-2.21 six-1.16.0 typing-extensions-4.2.0 yarl-1.7.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.0.4; however, version 22.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
root@ec41929e04cd:/# python
Python 3.10.4 (main, May 11 2022, 10:00:39) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import discord.opus
>>> discord.opus.Encoder()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/discord/opus.py", line 286, in __init__
    _OpusStruct.get_opus_version()
  File "/usr/local/lib/python3.10/site-packages/discord/opus.py", line 280, in get_opus_version
    raise OpusNotLoaded()
discord.opus.OpusNotLoaded
```

**Comment by Rapptz** [comment]
Thanks for the detailed bug report. After a lot of debugging, it seems this is an issue with ctypes itself. I've reported an issue upstream if you want to track its progress: https://github.com/python/cpython/issues/92892

**Comment by m13253** [comment]
Cool! Thanks for forwarding to the upstream.
