### ISSUE TITLE
Problem while loading extensions

### ISSUE THREAD

**Issue by Losty17** [Rapptz/discord.py#8058]
### Summary

Problem while loading extensions when running as "python -m "

### Reproduction Steps

This is my file structure:

![image](https://user-images.githubusercontent.com/45098519/169661151-ed65767d-96ad-4432-9bca-b509724e0fb0.png)

where `app.py` was `__main__.py` and I ran the bot as `python -m raphi`.

I had the `load_extensions` method like this:

```python
async def load_modules(self, extensions: List[str]):
        for e in extensions:
            try:
                print(f"Loading: {e}...", end=' ')
                await self.load_extension(f'extensions.{e}')
                print('ok!')
            except Exception as ex:
                print(f"\Could not load: {e}")
                print(ex)
```

And it could not load any Cogs I had, giving me the `ModuleNotFoundError`. When I pass a `package` as second parameter, it seems to ignore it completely.

#### raphi.py:

```python
class Raphi(commands.Bot):
    def __init__(self, command_prefix: str, *, intents: Intents, application_id: int) -> None:
        super().__init__(
            command_prefix,
            intents=intents,
            application_id=application_id
        )

        self.ext = [
            'text',
        ]

        self.glds = {
            "guild": Object(id=id),
        }

    async def setup_hook(self) -> None:
        await self.load_modules(self.ext)

        for g in self.glds:
            self.tree.copy_global_to(guild=self.glds[g])
            await self.tree.sync(guild=self.glds[g])

    async def load_modules(self, extensions: List[str]):
        for e in extensions:
            try:
                print(f"Loading: {e}...", end=' ')
                await self.load_extension(f'extensions.{e}')
                print('ok!')
            except Exception as ex:
                print(f"\nCould not load: {e}")
                traceback.print_exception(ex)
```

#### extensions/text.py:

```python
class Text(commands.Cog):
    def __init__(self, bot: commands.Bot) -> None:
        self.bot = bot

    @app_commands.command()
    async def teste(self, interaction: discord.Interaction):
        ''' /test1 '''
        await interaction.response.send_message("Test1234")


async def setup(bot: commands.Bot):
    await bot.add_cog(Text(bot))
```

#### `__main__.py`:

```python
from .raphi import Raphi

load_dotenv()

APP_ID = bot_id
intents = Intents.default()

bot = Raphi("$", intents=intents, application_id=APP_ID)


@bot.event
async def on_ready():
    print(f'Logged in as {bot.user} (ID: {bot.user.id})')

if __name__ == "__main__":
    bot.run(getenv("BOT_TOKEN"))
```

### Expected Results

I expected my modules to be loaded even when I run my code as `python -m`

### Actual Results

The modules don't load in any way. It seems like an issue with the import lib.

### Intents

discord.Intents.default()

### System Information

- Python v3.10.2-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4286+g7905d63f
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22000

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

#### Traceback with `extensions.text`

```
Loading: text... 
Could not load: text
Traceback (most recent call last):
  File "C:\Users\vinik\Projetos\python\discord-slash\raphi\raphi.py", line 37, in load_modules
    await self.load_extension(f'extensions.{e}')
  File "C:\Users\vinik\.virtualenvs\discord-slash-RtCwlGzd\lib\site-packages\discord\ext\commands\bot.py", line 990, in load_extension
    spec = importlib.util.find_spec(name)
  File "C:\Users\vinik\AppData\Local\Programs\Python\Python310\lib\importlib\util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'extensions'
```

#### Traceback with `.extensions.text`

```
Loading: text... 
Could not load: text
Traceback (most recent call last):
  File "C:\Users\vinik\.virtualenvs\discord-slash-RtCwlGzd\lib\site-packages\discord\ext\commands\bot.py", line 939, in _resolve_name
    return importlib.util.resolve_name(name, package)
  File "C:\Users\vinik\AppData\Local\Programs\Python\Python310\lib\importlib\util.py", line 32, in resolve_name
    raise ImportError(f'no package specified for {repr(name)} '
ImportError: no package specified for '.extensions.text' (required for relative module names)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vinik\Projetos\python\discord-slash\raphi\raphi.py", line 37, in load_modules
    await self.load_extension(f'.extensions.{e}')
  File "C:\Users\vinik\.virtualenvs\discord-slash-RtCwlGzd\lib\site-packages\discord\ext\commands\bot.py", line 986, in load_extension
    name = self._resolve_name(name, package)
  File "C:\Users\vinik\.virtualenvs\discord-slash-RtCwlGzd\lib\site-packages\discord\ext\commands\bot.py", line 941, in _resolve_name
    raise errors.ExtensionNotFound(name)
discord.ext.commands.errors.ExtensionNotFound: Extension '.extensions.text' could not be loaded.
```

#### Traceback with package

```
Loading: text... 
Could not load: text
Traceback (most recent call last):
  File "C:\Users\vinik\Projetos\python\discord-slash\raphi\raphi.py", line 37, in load_modules
    await self.load_extension(f'.extensions.{e}', package=".extensions")
  File "C:\Users\vinik\.virtualenvs\discord-slash-RtCwlGzd\lib\site-packages\discord\ext\commands\bot.py", line 990, in load_extension
    spec = importlib.util.find_spec(name)
  File "C:\Users\vinik\AppData\Local\Programs\Python\Python310\lib\importlib\util.py", line 90, in find_spec
    fullname = resolve_name(name, package) if name.startswith('.') else name
  File "C:\Users\vinik\AppData\Local\Programs\Python\Python310\lib\importlib\util.py", line 32, in resolve_name
    raise ImportError(f'no package specified for {repr(name)} '
ImportError: no package specified for '.extensions.extensions.text' (required for relative module names)
```

**Comment by Losty17** [comment]
Oh, i figured it out. `await self.load_extension(f'.extensions.{e}', package='raphi')`
