### ISSUE TITLE
unable to sync command tree for a single guild

### ISSUE THREAD

**Issue by ArthurKun021** [Rapptz/discord.py#8106]
### Summary

syncing the command tree for a single guild gives error

### Reproduction Steps

1. Have the following permissions
![image](https://user-images.githubusercontent.com/16458204/171978977-73654a3b-88a7-4972-84fb-0daee0298028.png)
2. copied the code from here https://github.com/Rapptz/discord.py/pull/7920/files#diff-bcc352434479dcc79e4f4b23f63b6cc5bca4c36fedcebdf69a553de7a859ad6e
3. tested running the command `.synctree <GUILD_ID>`
4. results in this error
```python
Ignoring exception in command synctree:
Traceback (most recent call last):
  File "venv\lib\site-packages\discord\ext\commands\core.py", line 200, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 62, in synctree
    await bot.tree.sync(guild=discord.Object(id=guild_id))
  File "venv\lib\site-packages\discord\app_commands\tree.py", line 983, in sync
    data = await self._http.bulk_upsert_guild_commands(self.client.application_id, guild.id, payload=payload)
  File "venv\lib\site-packages\discord\http.py", line 500, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "venv\lib\site-packages\discord\ext\commands\bot.py", line 1329, in invoke
    await ctx.command.invoke(ctx)
  File "venv\lib\site-packages\discord\ext\commands\core.py", line 995, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "venv\lib\site-packages\discord\ext\commands\core.py", line 209, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 50001): Missing Access

```

### Minimal Reproducible Code

```python
https://github.com/Rapptz/discord.py/pull/7920/files#diff-bcc352434479dcc79e4f4b23f63b6cc5bca4c36fedcebdf69a553de7a859ad6e

import discord
import asyncio
import random
from discord.ext import commands

description = """Example bot to show the use of hybrid commands.
These can be used as both application (slash) and message (prefix) commands
"""
intents = discord.Intents.default()
intents.message_content = True
intents.members = True

bot = commands.Bot(command_prefix="?", intents=intents, description=description)


@bot.event
async def on_ready():
    print(f"Logged in as {bot.user} (ID: {bot.user.id})")
    print("------")


@bot.hybrid_command()
@commands.is_owner()
async def synctree(ctx: commands.Context, guild_id: int = None):
    """
    Sync the application commands tree
    This must also be done with hybrid commands, to ensure that the application commands also work
    """
    if not guild_id:
        await bot.tree.sync()  # sync global commands
    else:
        await bot.tree.sync(guild=discord.Object(id=guild_id))
    await ctx.send("Synced the application commands tree!")


async def main() -> None:
    async with bot:
        await bot.start(TOKEN)


if __name__ == "__main__":
    asyncio.run(main())
```

### Expected Results

will be able to sync slash commands using single guild

### Actual Results

permission error

### Intents

emojis, reactions, webhooks, integrations, message_content

### System Information

- Python v3.10.4-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4320+g06c1f44d
- aiohttp v3.8.1
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
You say you have those permissions but that first image just means the URL generated has that scope in it. It doesn't mean the guild you're syncing actually has the scope, so it causes a 403. You need to redo the authentication flow to include those scopes. You don't need to kick the bot or anything, just click the URL again with the scope and it'll work.
