### ISSUE TITLE
join_voice_channel doesnt work

### ISSUE THREAD

**Issue by Centurius123** [Rapptz/discord.py#814]
Hey,

I use your playlist.py example.

The bot joins to my channel on discord, but he doesnt come back from the await.
`state.voice = await self.bot.join_voice_channel(summoned_channel)`

I use Debian 9 and Python 3.5

```
Ignoring exception in command summon
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "test.py", line 116, in summon
    state.voice = await self.bot.join_voice_channel(summoned_channel)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 3198, in join_voice_channel
    raise e
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 3195, in join_voice_channel
    data = yield from asyncio.wait_for(voice_data_future, timeout=10.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 404, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TimeoutError: 
Ignoring exception in command summon
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "test.py", line 116, in summon
    state.voice = await self.bot.join_voice_channel(summoned_channel)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 3198, in join_voice_channel
    raise e
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 3195, in join_voice_channel
    data = yield from asyncio.wait_for(voice_data_future, timeout=10.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 404, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TimeoutError: 
```

**Comment by mission** [comment]
try changing
`summoned_channel = ctx.message.author.voice_channel`
to
`summoned_channel = ctx.message.author.voice.voice_channel`

that should fix it

**Comment by Rapptz** [comment]
This issue just means that the bot couldn't connect to the voice channel in time. There could be many reasons for this:

1. You do not have `Connect` permissions in the channel.
2. You did not get the session description payload (this is equivalent to "ICE checking" in the client as far as I'm aware)
3. You just flat out timed out for unknown reasons.

For 2 and 3 you can just retry by catching the exception and re-doing it. Recursion helps a bit here.
