### ISSUE TITLE
View fails to dispatch crashing the bot

### ISSUE THREAD

**Issue by FrequencyX4** [Rapptz/discord.py#8155]
### Summary

Bot crashes a few minutes into running on all the latest commits within the last 2 months

### Reproduction Steps

Install the latest version

### Expected Results

The bot stays online without issue

### Actual Results

The following error crashes the bot 5mins after initializing cache:
```python
Traceback (most recent call last):
  File "/home/luck/Fate/fate.py", line 488, in <module>
    print("Starting Bot")
  File "/home/luck/Fate/fate.py", line 372, in run

  File "/home/luck/.local/lib/python3.10/site-packages/discord/client.py", line 736, in run
    asyncio.run(runner())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/luck/.local/lib/python3.10/site-packages/discord/client.py", line 733, in runner
    await self.start(*args, **kwargs)
  File "/home/luck/.local/lib/python3.10/site-packages/discord/client.py", line 707, in start
    await self.connect(reconnect=reconnect)
  File "/home/luck/.local/lib/python3.10/site-packages/discord/shard.py", line 450, in connect
    raise item.error
  File "/home/luck/.local/lib/python3.10/site-packages/discord/shard.py", line 163, in worker
    await self.ws.poll_event()
  File "/home/luck/.local/lib/python3.10/site-packages/discord/gateway.py", line 622, in poll_event
    await self.received_message(msg.data)
  File "/home/luck/.local/lib/python3.10/site-packages/discord/gateway.py", line 572, in received_message
    func(data)
  File "/home/luck/.local/lib/python3.10/site-packages/discord/state.py", line 728, in parse_interaction_create
    self._view_store.dispatch_view(component_type, custom_id, interaction)
  File "/home/luck/.local/lib/python3.10/site-packages/discord/ui/view.py", line 611, in dispatch_view
    item.view._dispatch_item(item, interaction)  # type: ignore
AttributeError: 'NoneType' object has no attribute '_dispatch_item'
```

### Intents

all

### System Information

I'm currently on a much older version than this shows to run the bot, but this occurs in the latest git version
- Python v3.10.4-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4224+g79d34fbe
- aiohttp v3.7.4.post0
- system info: Linux 5.15.0-37-generic #39-Ubuntu SMP Wed Jun 1 19:16:45 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by FrequencyX4** [comment]
as an update it still crashes on the version shown in system information as well

**Comment by Rapptz** [comment]
How did you add items to the view? There's way too much missing information here

**Comment by FrequencyX4** [comment]
> How did you add items to the view? There's way too much missing information here

I'm not sure which view this is occurring in. when I use the bot all the views seem to work, but then it crashes to this randomly without a proper trace

**Comment by Rapptz** [comment]
I can do a bandaid fix for this but whatever is causing this is a corruption of state that shouldn't have happened in the first place. How many views do you have on your bot? Are you doing something like `view.children.append` instead of using `view.add_item`?

**Comment by FrequencyX4** [comment]
I've got 247 views currently. there's a small chance I'm using children.append, so I'll check soon and comment if I am

**Comment by Rapptz** [comment]
I can't think of a scenario where an item view's is not set while simultaneously being available ready for dispatch. If you have an eval command you can figure out which view it is by trying:

```python
store = bot._connection._view_store
for message_id, dispatch_data in store._views.items():
    for item in dispatch_data.values():
        if item.view is None:
            print(message_id, dispatch_data, item)
            view = store._synced_message_views.get(message_id)
            print('View: ', view)
```

and seeing what it prints

**Comment by FrequencyX4** [comment]
I got things to print. seems it's coming from my help menus View. could using Select.options.append or `select.options = [...]` cause this?

Here's what was printed from that:
```
986940131103612958 {(3, 'bdddaf6323b865c6cc1dc7b88d162da4'): <HelpSelect placeholder='Select an option' min_values=1 max_values=1 options=[<SelectOption label='Mod Cmds' value='Mod Cmds' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Modmail' value='Modmail' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Logger' value='Logger' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='AntiSpam' value='AntiSpam' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='AntiRaid' value='AntiRaid' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Chatfilter' value='Chatfilter' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Verification' value='Verification' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>] disabled=False>, (3, 'a8e870cb2ce080efd8e9bf2631bf9423'): <HelpSelect placeholder='Select an option' min_values=1 max_values=1 options=[<SelectOption label='Mod Cmds' value='Mod Cmds' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Modmail' value='Modmail' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Logger' value='Logger' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='AntiSpam' value='AntiSpam' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='AntiRaid' value='AntiRaid' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Chatfilter' value='Chatfilter' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Verification' value='Verification' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>] disabled=False>} <HelpSelect placeholder='Select an option' min_values=1 max_values=1 options=[<SelectOption label='Mod Cmds' value='Mod Cmds' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Modmail' value='Modmail' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Logger' value='Logger' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='AntiSpam' value='AntiSpam' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='AntiRaid' value='AntiRaid' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Chatfilter' value='Chatfilter' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Verification' value='Verification' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>] disabled=False>
View:  <HelpMenu timeout=300 children=1>
986940131103612958 {(3, 'bdddaf6323b865c6cc1dc7b88d162da4'): <HelpSelect placeholder='Select an option' min_values=1 max_values=1 options=[<SelectOption label='Mod Cmds' value='Mod Cmds' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Modmail' value='Modmail' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Logger' value='Logger' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='AntiSpam' value='AntiSpam' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='AntiRaid' value='AntiRaid' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Chatfilter' value='Chatfilter' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Verification' value='Verification' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>] disabled=False>, (3, 'a8e870cb2ce080efd8e9bf2631bf9423'): <HelpSelect placeholder='Select an option' min_values=1 max_values=1 options=[<SelectOption label='Mod Cmds' value='Mod Cmds' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Modmail' value='Modmail' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Logger' value='Logger' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='AntiSpam' value='AntiSpam' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='AntiRaid' value='AntiRaid' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Chatfilter' value='Chatfilter' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Verification' value='Verification' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>] disabled=False>} <HelpSelect placeholder='Select an option' min_values=1 max_values=1 options=[<SelectOption label='Mod Cmds' value='Mod Cmds' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Modmail' value='Modmail' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Logger' value='Logger' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='AntiSpam' value='AntiSpam' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='AntiRaid' value='AntiRaid' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Chatfilter' value='Chatfilter' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>, <SelectOption label='Verification' value='Verification' description=None emoji=<PartialEmoji animated=False name='📖' id=None> default=False>] disabled=False>
View:  <HelpMenu timeout=300 children=1>```

**Comment by FrequencyX4** [comment]
Here's the code: https://pastebin.com/seqJqhk9

**Comment by Rapptz** [comment]
You are manually calling `self.__init__` which causes the state to corrupt.

**Comment by FrequencyX4** [comment]
that seems to have fixed it. no crashing after I switched to a new function instead of recalling init. thanks for the help
