### ISSUE TITLE
Allow hybrid commands to fail silently

### ISSUE THREAD

**Issue by Dhruvacube** [Rapptz/discord.py#8176]
### Summary

Allow hybrid commands to fail silently, if some of its parameters are suited for the appliation commands

### What is the feature request for?

discord.ext.commands

### The Problem

Some times there are cases where the bot developer wants to apply hybrid commands (definition) to all of the normal command definitions that were created and he/she doesn't care if the all of the normal commands are converted to application commands, also he/she doesn't want any traceback in the logs if the normal command fails to convert to application command due to any reason, he/she just wants to silently fails it.

But you know right now the `hybrid commands` doesn't fails silently instead it gives a traceback if there is a conversion error due to any reason.

### The Ideal Solution

Ideally thee just should be parameter in `self.tree.sync(conversion_fail_silenly=True)` or `self.load_extension('cogs_name',conversion_fail_silenly=True)` to silently fail on any conversion error.

(Yeah here I am ofc subclassing the `commands.Bot`

### The Current Solution

Right now we have to carefully check and apply `hybrid commands` decorator only to those functions which can be converted successfully, which actually takes a lot of time.

### Additional Context

Ig this would be a great feature of the bot developers.

**Comment by Rapptz** [comment]
If you want to change the default error handler then just override it. A non-trivial program should be doing that anyway. See [here](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#error-handling) for more info.

**Comment by Dhruvacube** [comment]
ohh ok thanks!

**Comment by Dhruvacube** [comment]
well still that wont fix, see this 
my error handler cog

```python
import io
import traceback
from typing import TYPE_CHECKING

import discord
from discord.ext import commands
from minato_namikaze.lib import (
    ChannelAndMessageId,
    IncorrectChannelError,
    NoChannelProvided,
    Embed,
    ErrorEmbed,
)
import logging

if TYPE_CHECKING:
    from lib import Context

    from ... import MinatoNamikazeBot

log = logging.getLogger(__name__)


class BotEventsCommands(commands.Cog):
    def __init__(self, bot: "MinatoNamikazeBot"):
        self.bot: "MinatoNamikazeBot" = bot
        self.delete_after_time = 5

    @commands.Cog.listener()
    async def on_command_error(self, ctx: "Context", error):
        if ctx.cog is not None and ctx.cog.qualified_name.lower() == "Music".lower():
            return
        error_channel = await self.bot.fetch_channel(
            ChannelAndMessageId.error_logs_channel.value
        )
        if isinstance(error, TypeError):
            pass
        if isinstance(error, commands.CommandOnCooldown):
            e1 = ErrorEmbed(title="Command Error!", description=f"`{error}`")
            e1.set_footer(text=f"{ctx.author.name}")
            await ctx.channel.send(embed=e1, delete_after=self.delete_after_time)

        elif isinstance(error, commands.BadArgument):
            await ctx.send(
                embed=ErrorEmbed(description=str(error)),
                delete_after=self.delete_after_time,
            )
        elif isinstance(error, commands.TooManyArguments):
            await ctx.send(
                embed=ErrorEmbed(
                    description=f"You called the {ctx.command.name} command with too many arguments."
                ),
                delete_after=self.delete_after_time,
            )

        elif isinstance(error, (NoChannelProvided, IncorrectChannelError)):
            return

        elif isinstance(error, commands.MissingRequiredArgument):
            e4 = ErrorEmbed(title="Command Error!", description=f"`{error}`")
            e4.set_footer(text=f"{ctx.author.name}")
            await ctx.channel.send(embed=e4, delete_after=self.delete_after_time)

        elif isinstance(error, commands.CommandNotFound):
            e2 = ErrorEmbed(title="Command Error!", description=f"`{error}`")
            e2.set_footer(text=f"{ctx.author.name}")
            await ctx.channel.send(embed=e2, delete_after=self.delete_after_time)

        elif isinstance(error, commands.BotMissingPermissions):
            e = ErrorEmbed(description=error)
            await ctx.send(embed=e, delete_after=self.delete_after_time)

        elif isinstance(error, commands.MissingPermissions):
            e = ErrorEmbed(description=error)
            await ctx.send(embed=e, delete_after=self.delete_after_time)

        elif isinstance(error, commands.UserInputError):
            await ctx.send(
                embed=Embed(
                    description=f"There was something **wrong** with your **input**!\n Please type\n ```)help {ctx.command.name}```,\n to know how to use the command"
                ),
                delete_after=self.delete_after_time,
            )

        elif isinstance(error, commands.NotOwner):
            return

        elif isinstance(error, commands.CheckFailure):
            return

        elif isinstance(error, commands.CheckAnyFailure):
            return

        elif isinstance(error, commands.EmojiNotFound):
            await ctx.send(
                embed=ErrorEmbed(
                    description=f"The emoji provided {error.argument} was **not found!**"
                ),
                delete_after=self.delete_after_time,
            )

        elif isinstance(error, commands.PartialEmojiConversionFailure):
            return

        elif isinstance(error, commands.BadInviteArgument):
            return

        elif isinstance(error, commands.PartialEmojiConversionFailure):
            return

        elif isinstance(error, commands.RoleNotFound):
            await ctx.send(
                embed=ErrorEmbed(description=error), delete_after=self.delete_after_time
            )

        elif isinstance(error, commands.NSFWChannelRequired):
            await ctx.send(
                embed=ErrorEmbed(
                    description=f"{error.channel.mention} is an **NSFW Channel**! **{ctx.command.name}** can be run only in **NSFW Channels**! :triumph:"
                ),
                delete_after=self.delete_after_time,
            )

        elif isinstance(error, commands.MissingRole):
            await ctx.send(
                embed=ErrorEmbed(
                    description=f"You **need** the following **role**: **{' '.join(error.missing_role)}**"
                ),
                delete_after=self.delete_after_time,
            )

        elif isinstance(error, commands.MissingAnyRole):
            await ctx.send(
                embed=ErrorEmbed(
                    description=f"You **need** the following **role**: **{' '.join(error.missing_roles)}**"
                ),
                delete_after=self.delete_after_time,
            )

        elif isinstance(error, commands.BotMissingRole):
            await ctx.send(
                embed=ErrorEmbed(
                    description=f"I **need** the following **role**: **{' '.join(error.missing_role)}**"
                ),
                delete_after=self.delete_after_time,
            )

        elif isinstance(error, commands.BotMissingAnyRole):
            await ctx.send(
                embed=ErrorEmbed(
                    description=f"I **need** the following **role**: **{' '.join(error.missing_roles)}**"
                ),
                delete_after=self.delete_after_time,
            )

        elif isinstance(error, commands.BadBoolArgument):
            await ctx.send(
                embed=ErrorEmbed(description=error), delete_after=self.delete_after_time
            )

        elif isinstance(error, commands.BadColourArgument):
            await ctx.send(
                embed=ErrorEmbed(description=error), delete_after=self.delete_after_time
            )

        elif isinstance(error, commands.ChannelNotFound):
            await ctx.send(
                embed=ErrorEmbed(description=error), delete_after=self.delete_after_time
            )

        elif isinstance(error, commands.MessageNotFound):
            await ctx.send(
                embed=ErrorEmbed(description=error), delete_after=self.delete_after_time
            )

        elif isinstance(error, commands.MemberNotFound):
            await ctx.send(
                embed=ErrorEmbed(description=error), delete_after=self.delete_after_time
            )

        elif isinstance(error, commands.GuildNotFound):
            await ctx.send(
                embed=ErrorEmbed(description=error), delete_after=self.delete_after_time
            )

        elif isinstance(error, commands.UserNotFound):
            await ctx.send(
                embed=ErrorEmbed(description=error), delete_after=self.delete_after_time
            )

        elif isinstance(error, commands.ChannelNotReadable):
            await ctx.send(
                embed=ErrorEmbed(
                    description=f"I need the **read message history** permission in that channel! In order to execute **{ctx.command.name}**"
                ),
                delete_after=self.delete_after_time,
            )

        elif isinstance(error, commands.DisabledCommand):
            return

        elif isinstance(error, commands.MaxConcurrencyReached):
            await ctx.send(
                embed=ErrorEmbed(description=error), delete_after=self.delete_after_time
            )

        elif isinstance(error, commands.PrivateMessageOnly):
            await ctx.send(
                embed=ErrorEmbed(
                    description=f"**{ctx.command.name}** works only in **DM's**"
                ),
                delete_after=self.delete_after_time,
            )

        elif isinstance(error, commands.NoPrivateMessage):
            await ctx.send(
                embed=ErrorEmbed(
                    description=f"**{ctx.command.name}** doesn't work in **DM's**"
                ),
                delete_after=self.delete_after_time,
            )

        elif isinstance(error, commands.CommandOnCooldown):
            l = self.bot.get_command(ctx.command.name)
            left = l.get_cooldown_retry_after(ctx)
            e = ErrorEmbed(description=f"Cooldown left - {round(left)}")
            await ctx.send(embed=e, delete_after=self.delete_after_time)

        elif isinstance(error, commands.CommandInvokeError):
            e7 = ErrorEmbed(
                title="Oh no, I guess I have not been given proper access! Or some internal error",
                description=f"`{error}`"[:2000],
            )
            e7.add_field(name="Command Error Caused By:", value=f"{ctx.command}")
            e7.add_field(name="By", value=f"{ctx.author.name}")
            e7.set_footer(text=f"{ctx.author.name}")
            await ctx.channel.send(embed=e7, delete_after=self.delete_after_time)

            e = Embed(
                title=f"In **{ctx.guild.name}**",
                description=f"User affected {ctx.message.author}",
            )
            if ctx.guild.icon:
                e.set_thumbnail(url=ctx.guild.icon.url)
            if ctx.guild.banner:
                e.set_image(url=ctx.guild.banner.with_format("png").url)
            e.add_field(name="**Total Members**", value=ctx.guild.member_count)
            e.add_field(
                name="**Bots**",
                value=sum(1 for member in ctx.guild.members if member.bot),
            )
            e.add_field(name="**Server ID**", value=ctx.guild.id, inline=True)
            await ctx.send(
                "**Error report was successfully sent**",
                delete_after=self.delete_after_time,
            )
            try:
                raise error
            except Exception:

                await error_channel.send(
                    embeds=[e7, e],
                    file=discord.File(
                        io.BytesIO(str(traceback.format_exc()).encode()),
                        filename="traceback.txt",
                    ),
                )

        else:
            haaha = ctx.author.avatar.url
            e9 = ErrorEmbed(
                title="Oh no there was some error", description=f"`{error}`"[:2000]
            )
            e9.add_field(name="**Command Error Caused By**", value=f"{ctx.command}")
            e9.add_field(
                name="**By**",
                value=f"**ID** : {ctx.author.id}, **Name** : {ctx.author.name}",
            )
            e9.set_thumbnail(url=f"{haaha}")
            e9.set_footer(text=f"{ctx.author.name}")
            await ctx.channel.send(embed=e9, delete_after=self.delete_after_time)

            e = Embed(
                title=f"In **{ctx.guild.name}**",
                description=f"User affected {ctx.message.author}",
            )
            if ctx.guild.icon:
                e.set_thumbnail(url=ctx.guild.icon.url)
            if ctx.guild.banner:
                e.set_image(url=ctx.guild.banner.with_format("png").url)
            e.add_field(name="**Total Members**", value=ctx.guild.member_count)
            e.add_field(
                name="**Bots**",
                value=sum(1 for member in ctx.guild.members if member.bot),
            )
            e.add_field(name="**Server ID**", value=ctx.guild.id, inline=True)
            await ctx.send(
                "**Error report was successfully sent**",
                delete_after=self.delete_after_time,
            )
            try:
                raise error
            except Exception:
                await error_channel.send(
                    embed=e,
                    file=discord.File(
                        io.BytesIO(str(traceback.format_exc()).encode()),
                        filename="traceback.txt",
                    ),
                )


async def setup(bot: "MinatoNamikazeBot") -> None:
    await bot.add_cog(BotEventsCommands(bot))
```


and the error

```console
[2022-06-23 12:13:44] [ERROR] discord.client: Ignoring exception in on_ready
Traceback (most recent call last):
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\ext\commands\bot.py", line 917, in _load_from_module_spec
    spec.loader.exec_module(lib)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\projects\Minato Namikaze\yondaime-hokage\minato_namikaze\cogs\polls.py", line 19, in <module>
    class QuickPoll(commands.Cog):
  File "D:\projects\Minato Namikaze\yondaime-hokage\minato_namikaze\cogs\polls.py", line 261, in QuickPoll
    async def quickpoll(self, ctx: "Context", *questions_and_choices: str):
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\ext\commands\hybrid.py", line 844, in decorator
    return HybridCommand(func, name=name, with_app_command=with_app_command, **attrs)  # type: ignore  # ???
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\ext\commands\hybrid.py", line 483, in __init__
    HybridAppCommand(self) if self.with_app_command else None
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\ext\commands\hybrid.py", line 295, in __init__
    super().__init__(
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\app_commands\commands.py", line 523, in __init__
    self._params: Dict[str, CommandParameter] = _extract_parameters_from_callback(callback, callback.__globals__)
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\app_commands\commands.py", line 383, in _extract_parameters_from_callback    
    param = annotation_to_parameter(resolved, parameter)
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\app_commands\transformers.py", line 747, in annotation_to_parameter
    raise TypeError(f'unsupported parameter kind in callback: {parameter.kind!s}')
TypeError: unsupported parameter kind in callback: VAR_POSITIONAL

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\client.py", line 456, in _run_event
    await coro(*args, **kwargs)
  File "D:\projects\Minato Namikaze\yondaime-hokage\minato_namikaze\discordbot.py", line 152, in on_ready
    await self.load_extension(f"minato_namikaze.cogs.{i}")
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\ext\commands\bot.py", line 995, in load_extension
    await self._load_from_module_spec(spec, name)
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\ext\commands\bot.py", line 920, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.ext.commands.errors.ExtensionFailed: Extension 'minato_namikaze.cogs.polls' raised an error: TypeError: unsupported parameter kind in callback: VAR_POSITIONAL
```

**Comment by Dhruvacube** [comment]
so what i am suggesting, could that silenced? if its unsupported then just fail silently

**Comment by Rapptz** [comment]
No.

**Comment by Armaan533** [comment]
> so what i am suggesting, could that silenced? if its unsupported then just fail silently

Bruh you can't just silence all the exceptions 
maybe try using something like put the error in error listener

Note: Sometimes having an error on your console is better than having empty console and commands are not working properly

**Comment by Dhruvacube** [comment]
hmmmmmmmmmmmm.....
