### ISSUE TITLE
PartialWebhookState does not support http methods

### ISSUE THREAD

**Issue by Dhruvacube** [Rapptz/discord.py#8186]
### Summary

After sending the message from webhook, and I retriving that message using `fetch` method, it fails

### Reproduction Steps

Send a message using webhook and try retriving it using the fetch method, it fails

### Minimal Reproducible Code

```python
class Badges(Base):
    __tablename__ = "badges"
    __table_args__ = {"extend_existing": True}

    id = Column(Integer, primary_key=True, autoincrement=True, index=True)
    badge_name = Column(String(250), nullable=False, index=True, unique=True)
    code = Column(String(20), nullable=False, index=True, unique=True)
    file_name = Column(String(500), nullable=False, index=True, unique=True)
    is_inverted = Column(Boolean, default=False, nullable=False, index=True, unique=True)


def check_if_it_is_me(interaction: discord.Interaction) -> bool:
    """Check if the inetractions's users is the bot user

    :return: True or False depending on the result
    :rtype: bool
    """    
    return interaction.user.id == interaction.client.owner_id

def get_badge_code(badge_name: str) -> str:
    """Returns the badge code from its name

    :param badge_name: The name of the badge image
    :type badge_name: str
    :return: Badge Code
    :rtype: str
    """
    return "".join(list(i[0].upper() for i in badge_name.split(" ")))


@app_commands.command()
@app_commands.describe(name='The name of the badge')
@app_commands.describe(file='The raw badge image containing the badge')
@app_commands.check(check_if_it_is_me)
async def add_new_badge(
    interaction: discord.Interaction, 
    name: str,
    file: discord.Attachment,
):
    """Adds a new badge to database"""
    if not file.content_type.startswith('image'):
        await interaction.response.send_message(f'{file.filename} is not a valid image', ephemeral=True)
        return
    embed = StarboardEmbed(title=name.title())
    embed.set_image(url=f'attachment://{name.replace(" ", "").lower()}')
    async with aiohttp.ClientSession() as session:
        wh = discord.Webhook.from_url(Webhooks.badges.value, session=session, bot_token=Tokens.token.value)
        sent_message: discord.WebhookMessage = await wh.send(wait=True,embed=embed, file=await file.to_file(filename=name.replace(" ", "").lower(),use_cached=True, description=f'{file.filename.title()} raw badge data.'))
        sent_message: discord.Message = await sent_message.fetch()
    badge_object = Badges(id=sent_message.id,badge_name=name.title(), file_name=sent_message.embeds[0].url, code=get_badge_code(name))
    async with session_obj() as session:
        async with session.begin():
            session.add(badge_object)
    await interaction.response.send_message(f'Added, {sent_message.jump_url}', ephemeral=True)
```

### Expected Results

It should fetch the message and return it as `discord.Message`

### Actual Results

[2022-06-28 13:40:00] [ERROR] discord.app_commands.tree: Ignoring exception in command 'add_new_badge'
Traceback (most recent call last):
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\app_commands\commands.py", line 650, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "D:\projects\Minato Namikaze\yondaime-hokage\minato_namikaze\cogs\badges.py", line 87, in add_new_badge
    sent_message: discord.Message = await sent_message.fetch()
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\message.py", line 765, in fetch
    data = await self._state.http.get_message(self.channel.id, self.id)
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\webhook\async_.py", line 690, in __getattr__
    raise AttributeError('PartialWebhookState does not support http methods.')
AttributeError: PartialWebhookState does not support http methods.

The above exception was the direct cause of the following exception:

  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\app_commands\tree.py", line 1156, in call
    await command._invoke_with_namespace(interaction, namespace)
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\app_commands\commands.py", line 675, in _invoke_with_namespace                                                                                                                                          ace
    return await self._do_call(interaction, transformed_values)
  File "D:\projects\Minato Namikaze\yondaime-hokage\env\lib\site-packages\discord\app_commands\commands.py", line 668, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'add_new_badge' raised an exception: AttributeError: PartialWebhookState does not support http methods.port http methods.

### Intents

discord.Intents( guilds=True, members=True,bans=True, emojis=True,voice_states=True, messages=True, reactions=True ).all()

### System Information

- Python v3.8.9-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4362+g9648986
- aiohttp v3.8.1
- system info: Windows 10 10.0.19041

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Yes, this is by design (hence why I raise a custom exception...)

There could be a feature request about creating a faux HTTPClient since technically there is enough information to create one more or less. But as a bug report, this is invalid and by design. Note that if I make a faux HTTPClient then this would not allow it to be shared with the bot's rate limit handler since they would be two separate instances -- which is sub-optimal.

**Comment by Dhruvacube** [comment]
ohhh ok

**Comment by Rapptz** [comment]
`fetch` is there because `Message` has it and this does mocking behind the scenes.

For your particular use case, it doesn't make sense to fetch it since you already received it when you called `send` + `wait=True`.

**Comment by Dhruvacube** [comment]
> `fetch` is there because `Message` has it and this does mocking behind the scenes.
> 
> For your particular use case, it doesn't make sense to fetch it since you already received it when you called `send` + `wait=True`.

ohhh ok gotcha1 thanks for the reply
