### ISSUE TITLE
client.start doesn't appear to start the coroutine in Python 3.10

### ISSUE THREAD

**Issue by stridera** [Rapptz/discord.py#8247]
### Summary

client.run works fine.  When I do client.start, on_ready is never called.

### Reproduction Steps

I've created a super minimal bot.  When I call `client.run()` it starts as expected.  When I try to call `client.start()` using any other method (await, asyncio.gather, etc) it just freezes.

### Minimal Reproducible Code

```python
import discord
import asyncio

token = 'token'
client = discord.Client()

@client.event
async def on_ready():
    print(f'{client.user} has connected to Discord!')


async def await_test():
    await client.start(token)

async def gather_test():
    await asyncio.gather(client.start(token))

async def loop_test():
    # From https://discordpy.readthedocs.io/en/stable/api.html#discord.Client.run
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(client.start(token))
    except KeyboardInterrupt:
        loop.run_until_complete(client.close())
    finally:
        loop.close()

# client.run(token) # Runs fine
# asyncio.run(await_test())  # Never calls on_ready
# asyncio.run(gather_test())  # Never calls on_ready
# asyncio.run(loop_test())  # Fails with "RuntimeError: This event loop is already running"
```

### Expected Results

I expect to be able to call client.start as an asyncio task so I can run other tasks concurrently.

### Actual Results

The bot appears to just freeze as soon as I run `client.start()` via any method.  

### Intents

None

### System Information

- Python v3.10.4-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Linux 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
You can't call `run_until_complete` in an async function. 

That aside, I can't reproduce it.

```
> python .\issue8247.py
OAuth2 Sucks#3136 has connected to Discord!
```

**Comment by stridera** [comment]
Not sure if you're running on a different environment, but I just tried 2 machines with Ubuntu 22.10, and I never get the connected message.  I guess I'll keep looking for an answer though.

**Comment by SebbyLaw** [comment]
Your minimal reproducible code is missing the required `intents=` kwarg in the `discord.Client` constructor. I have added `Intents.none()` in my testing.

That aside, no repro on Debian 11 or Windows 10. (with `client.run(token)`, `asyncio.run(await_test())`, and `asyncio.run(gather_test())`)

There is most likely something else in your code that is left out of the minimal reproducible example that is affecting this behavior.

**Comment by stridera** [comment]
I added the intent and it didn't work.  (At least, not in the 15 seconds I waited.  When I do `client.run()` it works pretty instantly.  I created a fresh env for this and everything.

```bash
strider@twilight:~/Code/mud_connector$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
strider@twilight:~/Code/mud_connector$ python3 -mvenv .venv
strider@twilight:~/Code/mud_connector$ source .venv/bin/activate
(.venv) strider@twilight:~/Code/mud_connector$ pip install discord
Collecting discord
  Using cached discord-1.7.3-py3-none-any.whl (1.1 kB)
Collecting discord.py>=1.7.3
  Using cached discord.py-1.7.3-py3-none-any.whl (786 kB)
Collecting aiohttp<3.8.0,>=3.6.0
  Using cached aiohttp-3.7.4.post0-py3-none-any.whl
Collecting typing-extensions>=3.6.5
  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Collecting async-timeout<4.0,>=3.0
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
Collecting chardet<5.0,>=2.0
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting yarl<2.0,>=1.0
  Using cached yarl-1.7.2-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (305 kB)
Collecting attrs>=17.3.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting idna>=2.0
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Installing collected packages: typing-extensions, multidict, idna, chardet, attrs, async-timeout, yarl, aiohttp, discord.py, discord
Successfully installed aiohttp-3.7.4.post0 async-timeout-3.0.1 attrs-21.4.0 chardet-4.0.0 discord-1.7.3 discord.py-1.7.3 idna-3.3 multidict-6.0.2 typing-extensions-4.3.0 yarl-1.7.2
(.venv) strider@twilight:~/Code/mud_connector$ python -m discord -v
- Python v3.10.4-final
- discord.py v1.7.3-final
- aiohttp v3.7.4.post0
- system info: Linux 5.15.0-40-generic #43-Ubuntu SMP Wed Jun 15 12:54:21 UTC 2022
(.venv) strider@twilight:~/Code/mud_connector$ cat test.py | grep -v "token ="
import discord
import asyncio


client = discord.Client(intents=discord.Intents.none())


@client.event
async def on_ready():
    print(f'{client.user} has connected to Discord!')


async def await_test():
    await client.start(token)


async def gather_test():
    await asyncio.gather(
        asyncio.create_task(client.start(token)),
    )


async def loop_test():
    # From https://discordpy.readthedocs.io/en/stable/api.html#discord.Client.run
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(client.start(token))
    except KeyboardInterrupt:
        loop.run_until_complete(client.close())
    finally:
        loop.close()

# client.run(token) # Runs fine
asyncio.run(await_test())  # Never calls on_ready
# asyncio.run(gather_test())  # Never calls on_ready
# asyncio.run(loop_test())  # Failes with "RuntimeError: This event loop is already running"
(.venv) strider@twilight:~/Code/mud_connector$ time python test.py 
^CTraceback (most recent call last):
  File "/home/strider/Code/mud_connector/test.py", line 35, in <module>
    asyncio.run(await_test())  # Never calls on_ready
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1860, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
KeyboardInterrupt

real	0m18.797s
user	0m0.258s
sys	0m0.041s```

**Comment by Rapptz** [comment]
You might want to set up logging to see what's going on (see here: https://discordpy.readthedocs.io/en/v1.7.3/logging.html#logging-setup). This might end up being a networking issue because this code should (and does) work fine for thousands of others.
