### ISSUE TITLE
Embed not working without colors

### ISSUE THREAD

**Issue by nav-github01001** [Rapptz/discord.py#8286]
### Summary

^

### Reproduction Steps

make an hybrid command(the type does not matter anyway) with the which sends an embed.
Full Traceback
```
Traceback (most recent call last):
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\core.py", line 195, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\FalconFiles\EnderBot\cogs\information.py", line 34, in invite
    await ctx.send(embed =Embed(title="Invite Me!", description="Here are the links to invite me"),view=view)
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\context.py", line 841, in send
    return await super().send(
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\abc.py", line 1521, in send
    with handle_message_parameters(
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 178, in handle_message_parameters
    payload['embeds'] = [embed.to_dict()]
  File "C:\Users\navan\AppData\Local\Programs\Python\Python310\lib\site-packages\EpikCord\__init__.py", line 2902, in to_dict
    final_product["color"] = self.color.value
AttributeError: 'NoneType' object has no attribute 'value'
```

### Minimal Reproducible Code

```python
    @commands.hybrid_command()
    async def invite(self, ctx:commands.Context):
        
        AdminLink = Button(style=ButtonStyle.link, label="For administrators", url="https://discord.com/api/oauth2/authorize?client_id=923915598247915540&permissions=8&scope=bot%20applications.commands")
        NonAdminLink = Button(style=ButtonStyle.link, label="Recommended", url="https://discord.com/api/oauth2/authorize?client_id=923915598247915540&permissions=1110216543415&scope=bot%20applications.commands")
        view = View(timeout=600).add_item(AdminLink).add_item(NonAdminLink)
        await ctx.send(embed =Embed(title="Invite Me!", description="Here are the links to invite me"),view=view)
```

### Expected Results

For the bot to respond

### Actual Results

Look up for full tb

### Intents

Intents().all

### System Information

- Python v3.10.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4443+gc26473d0
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.25169

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This can be fixed by self.color.value or {default_color}

**Comment by nerdguyahmad** [comment]
Your error traceback shows you are using another package `Epikcord` and that's probably where your `Embed` class is coming from. The `Embed` you passed to `send()` is not a `discord.Embed` instance.

**Comment by nav-github01001** [comment]
oh shit
