### ISSUE TITLE
HTTPException on bot.tree.sync()

### ISSUE THREAD

**Issue by glass-ships** [Rapptz/discord.py#8326]
### Summary

Unable to sync bot's command tree due to HTTPException. A previous version of my bot still works, but a few commits of unrelated changes later, tree is unable to sync and I can't seem to pin down why... 

### Reproduction Steps

1. Clone my bot:   
    `git clone https://gitlab.com/glass-ships/compass-bot.git`
2. Start the bot:
    ```
    cd compass-bot/ 
    pip install -r requirements.txt # if necessary
    python3 src/main.py
    ```
3. Try to sync the command tree (in guild):  
    `;sync all`

### Minimal Reproducible Code

```python
    @commands.command(name="sync")
    @commands.has_permissions(administrator=True)
    async def _sync(self, ctx: commands.Context, spec: Union[Literal['dev'], Literal["guild"], Literal["all"]]):
        logger.info("Syncing ships...")
        if spec == 'dev':
            g = bot.get_guild(771161933301940224)
            await ctx.send(embed=discord.Embed(description=f"Copying command tree to {g}"), delete_after=5.0)
            bot.tree.copy_global_to(guild=g)
            fmt = await bot.tree.sync(guild=g)
            await ctx.send((f"Synced {len(fmt)} commands to dev guild."))
        elif spec == "guild":
            g = bot.get_guild(ctx.guild.id)
            fmt = await bot.tree.sync(guild=g)
            await ctx.send(embed=discord.Embed(description=f"Synced {len(fmt)} commands to guild."))
            logger.info("Ships synced!")
            return
        elif spec == "all":
            fmt1 = await bot.tree.sync()
            #fmt2 = 0
            guilds = bot.db.get_all_guilds()
            #for guild in guilds:
            #    g = bot.get_guild(guild)
            #    await bot.tree.sync(guild=g)
            #    fmt2 += 1
            await ctx.send(embed=discord.Embed(description=f"Bot tree synced: {len(fmt1)} commands to {len(guilds)} guilds."))
            #await ctx.send(f"Bot tree synced: {len(fmt1)} commands to {fmt2} of {len(guilds)} guilds.")
            logger.info("Ships synced!")
            return
        else:
            await ctx.send(embed=discord.Embed(description=f"Unexpected argument.\nExample usage: `;sync guild`\nType `;help` for more info."))
            logger.warning("Error syncing ships! (Bad argument)")
            return
```

### Expected Results

For the commands in the local tree to be synced globally

### Actual Results

HTTPException:
```
Traceback (most recent call last):
  File "/home/glass/dev/discord-env/lib/python3.10/site-packages/discord/ext/commands/core.py", line 195, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/glass/dev/compass-bot/src/cogs/admin.py", line 48, in _sync
    fmt1 = await bot.tree.sync()
  File "/home/glass/dev/discord-env/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1062, in sync
    data = await self._http.bulk_upsert_global_commands(self.client.application_id, payload=payload)
  File "/home/glass/dev/discord-env/lib/python3.10/site-packages/discord/http.py", line 737, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In 3.description: Must be between 1 and 100 in length.
```

### Intents

discord.Intents.all()

### System Information

```
- Python v3.10.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4483+g4fbafcd7
- aiohttp v3.8.1
- system info: Linux 5.13.0-51-generic #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [x] I have removed my token from display, if visible.

**Comment by AbstractUmbra** [comment]
> In 3.description: Must be between 1 and 100 in length.

This tells me that the description of one of your commands is either too short (0 or less characters), or too long (100 or more characters).
I will assume it's the latter.

**Comment by glass-ships** [comment]
Oh wow, definitely a facepalm moment... 
Thanks so much for catching that, Umbra!! 
Fixed and closing
