### ISSUE TITLE
Syncing application commands defined within a subclass of Bot result in a `CommandSignatureMismatch` when used

### ISSUE THREAD

**Issue by oskiwii** [Rapptz/discord.py#8346]
### Summary

Adding a command to the tree and then syncing results in a `CommandSignatureMismatch` when running said command.

### Reproduction Steps

- Make a subclass of commands.Bot, and define a slash command within
- Within `setup_hook`, add the commands to the tree (`tree.add_command`), and sync to Discord
- Run said application command within Discord, and you should get the exception CommandSignatureMismatch

### Minimal Reproducible Code

```python
class Bot(commands.Bot):
    def __init__(self):
        super().__init__(".", intents = discord.Intents.default())
        
    async def setup_hook(self) -> None:
        self.tree.add_command(self.command_test)
        self.tree.sync()
        
    @discord.app_commands.command()
    async def command_test(self, i: discord.Interaction):
        await i.response.send_message("Works.")
```

### Expected Results

Command should run

### Actual Results

![image](https://user-images.githubusercontent.com/80816818/184997370-8b990052-bb54-4a54-af26-55acb47c4d7f.png)

You get the exception CommandSignatureMismatch

### Intents

discord.Intents.all()

### System Information

- Python v3.9.5-final
- discord.py v2.0.0-alpha
    - discord.py pkg_resources: v2.0.0a4437+gdc8cbc07
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.19043

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

Log is as follows:

```
[2022-08-16 23:47:08] [INFO    ] discord.client: logging in using static token
[2022-08-16 23:47:10] [INFO    ] discord: Syncing global commands...
[2022-08-16 23:47:10] [INFO    ] discord: Syncing commands for guild with ID *************...
[2022-08-16 23:47:10] [INFO    ] discord: Done with syncing commands
[2022-08-16 23:47:15] [INFO    ] discord.gateway: Shard ID None has sent the IDENTIFY payload.
[2022-08-16 23:47:16] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: **********).
[2022-08-16 23:47:18] [INFO    ] discord: Ready! Logged in as ****************
[2022-08-16 23:47:24] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'sync'
Traceback (most recent call last):
  File "C:\****************\lib\site-packages\discord\app_commands\tree.py", line 1175, in call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\****************\lib\site-packages\discord\app_commands\commands.py", line 685, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\****************\lib\site-packages\discord\app_commands\commands.py", line 673, in _do_call
    raise CommandSignatureMismatch(self) from None
discord.app_commands.errors.CommandSignatureMismatch: The signature for command 'sync' is different from the one provided by Discord. This can happen because either your code is out of date or you have not synced the commands with Discord, causing the mismatch in data. It is recommended to sync the command tree to fix this issue.
```

**Comment by Rapptz** [comment]
This isn't supported (it never was, not even with base `ext.commands`). If you want to do this you'll need it to be a free function. 

If you're curious why this is happening, it's because of there's no binding attached to the command object to know what to call.
