### ISSUE TITLE
Opus problem Installed FFmpeg

### ISSUE THREAD

**Issue by jun3453** [Rapptz/discord.py#835]
Hello.
There is my problem
```
Traceback (most recent call last):
  File "examples/playlist.py", line 11, in <module>
    discord.opus.load_opus('opus')
  File "/usr/local/python/lib/python3.5/site-packages/discord/opus.py", line 124, in load_opus
    _lib = libopus_loader(name)
  File "/usr/local/python/lib/python3.5/site-packages/discord/opus.py", line 60, in libopus_loader
    lib = ctypes.cdll.LoadLibrary(name)
  File "/usr/local/python/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/python/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: opus: cannot open shared object file: No such file or directory
```
I try this https://stackoverflow.com/questions/44354130/discord-bot-python-ffmpeg-error
Installed ffmpeg.
```
ffmpeg version N-87739-g1fd8010 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.4.7 (GCC) 20120313 (Red Hat 4.4.7-18)
  configuration: --enable-openssl --disable-yasm
  libavutil      55. 77.101 / 55. 77.101
  libavcodec     57.106.104 / 57.106.104
  libavformat    57. 82.102 / 57. 82.102
  libavdevice    57.  9.101 / 57.  9.101
  libavfilter     6.106.100 /  6.106.100
  libswscale      4.  7.103 /  4.  7.103
  libswresample   2.  8.100 /  2.  8.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```
But It is still out.
Do you know the reason.
Thank's.

**Comment by Zore12345** [comment]
I believe that you have to import opus like so:
```
if not discord.opus.is_loaded():
	discord.opus.load_opus('libopus-0.x64.dll')
```

**Comment by Rapptz** [comment]
You have to actually install the Opus library.

FFmpeg is used to convert audio into PCM and then that PCM has to be converted to Opus frames. The conversion for Opus frames requires libopus, so get that from your favourite package manager. e.g. for debian based systems it's `apt-get install libopus0`.
