### ISSUE TITLE
Modal not working correctly

### ISSUE THREAD

**Issue by NicolasAlmerge** [Rapptz/discord.py#8355]
### Summary

Modal not working correctly

### Reproduction Steps

Upgraded discord.py to version 2.0.0.

### Minimal Reproducible Code

```python
import discord
from discord import app_commands, ui

TOKEN = "TOKEN"
TEST_GUILD = discord.Object(id=0)

intents = discord.Intents.default()
intents.message_content = True

class Client(discord.Client):
    def __init__(self):
        super().__init__(intents=intents)
        self.tree = app_commands.CommandTree(self)

    async def on_ready(self):
        await self.wait_until_ready()
        await self.tree.sync(guild=TEST_GUILD)
        print("Client connected.")

client = Client()

class Questionnaire(ui.Modal, title="Questionnaire"):
    name = ui.TextInput(label="Name", placeholder="Enter your name", min_length=1, max_length=30)
    gender = ui.Select(placeholder="Enter your gender", options=[
        discord.SelectOption(label="Male", description="Boy/Man"),
        discord.SelectOption(label="Female", description="Girl/Woman"),
        discord.SelectOption(label="Rather Not Say", description="Mystery")
    ])
    button = ui.Button(label="Google Page", style=discord.ButtonStyle.link, url="https://www.google.com")

    async def on_submit(self, interaction: discord.Interaction):
        await interaction.response.send_message("Thanks for your response!", ephemeral=True)


@client.tree.command(name="test", description="This is a test", guild=TEST_GUILD)
async def _test(interaction: discord.Interaction):
    await interaction.response.send_modal(Questionnaire())

client.run(TOKEN)
```

### Expected Results

Modal window asking for a name, gender and a link button to [`Google`](https://www.google.com).

### Actual Results

```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/app_commands/commands.py", line 851, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "bot.py", in _test
    await interaction.response.send_modal(Questionnaire())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/interactions.py", line 852, in send_modal
    await adapter.create_interaction_response(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/webhook/async_.py", line 221, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In data.components.1.components.0: Value of field "type" must be one of (4,).
In data.components.2.components.0: Value of field "type" must be one of (4,).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1240, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/app_commands/commands.py", line 876, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/app_commands/commands.py", line 869, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'test' raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In data.components.1.components.0: Value of field "type" must be one of (4,).
In data.components.2.components.0: Value of field "type" must be one of (4,).
```

### Intents

`discord.Intents.default()` + `message_content`

### System Information

- Python v3.10.0-final
- discord.py v2.0.0-final
- aiohttp v3.7.4.post0
- system info: Darwin 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:25 PDT 2022; root:xnu-8020.140.41~1/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by bijij** [comment]
Discord has at this time removed support for Select components in modals, there is no tba on when they will be added back.

**Comment by NicolasAlmerge** [comment]
> Discord has at this time removed support for Select components in modals, there is no tba on when they will be added back.

The problem also seems to occur with the Button component.

**Comment by bijij** [comment]
[Only `TextInput` is currently supported](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-modal).

**Comment by BlackThunder01001** [comment]
> Discord has at this time removed support for Select components in modals, there is no tba on when they will be added back.

The support for these components was never actually intended.
