### ISSUE TITLE
Error on users joining

### ISSUE THREAD

**Issue by EelcovdW** [Rapptz/discord.py#84]
I got an error when new users join a channel:

```
Traceback (most recent call last):
  File "gm_bot.py", line 85, in <module>
    client.run()
  File "C:\Python27\lib\site-packages\discord\client.py", line 550, in run
    self.ws.run()
  File "C:\Python27\lib\site-packages\ws4py\websocket.py", line 427, in run
    if not self.once():
  File "C:\Python27\lib\site-packages\ws4py\websocket.py", line 305, in once
    if not self.process(b):
  File "C:\Python27\lib\site-packages\ws4py\websocket.py", line 377, in process
    self.received_message(s.message)
  File "C:\Python27\lib\site-packages\discord\client.py", line 129, in received_message
    self.dispatch('socket_update', event, data)
  File "C:\Python27\lib\site-packages\discord\client.py", line 527, in dispatch
    getattr(self, handle_method, utils._null_event)(*args, **kwargs)
  File "C:\Python27\lib\site-packages\discord\client.py", line 535, in handle_socket_update
    getattr(self.connection, method)(data)
  File "C:\Python27\lib\site-packages\discord\client.py", line 262, in handle_guild_member_add
    member = Member(server=server, deaf=False, mute=False, **data)
TypeError: type object got multiple values for keyword argument 'mute'
```

Nothing special in my own code (just some setting roles with commands, thats it). This happens every time when a new member joins a channel, tested on multiple channels.

**Comment by khazhyk** [comment]
Update to the latest version, this is fixed in both legacy and async

**Comment by EelcovdW** [comment]
Thanks! upgraded via pip install --upgrade discord.py this earlier, maybe something went wrong there.

**Comment by Rapptz** [comment]
The next minor version isn't pushed to pypi yet so that won't work at the moment.

**Comment by Rapptz** [comment]
It's pushed into pypi so all you legacy using people can just do `pip install --upgrade discord.py`
