### ISSUE TITLE
Help about commands and Args

### ISSUE THREAD

**Issue by KolightFR** [Rapptz/discord.py#874]
Hello i'm starting with multiple arguments commands. Here i wan't to check  if arg1 and arg2 are not null but i don't know how to do ? Thanks in advance

```PYTHON
@client.command(pass_context=True)
async def test(ctx, arg1, arg2):
	if arg1 or arg2 is None:
		client.send_message(ctx.message.channel, "=cw <Carte> <Heure>")
	else:
		desc = 'Bataille sur la carte {0} à {1}'.format(arg1,arg2)
		em = discord.Embed(title='Alerte CW !', description=desc, colour=0x57FE01)
		await client.send_message(client.get_channel("371613656313757699"), embed=em)
```

**Comment by khazhyk** [comment]
Unless you specify default arguments, arg1 and arg2 will never be null - instead a CommandError will be fired before the function is invoked.

You can specify a custom error handler to handle this case. You can either use `@test.error` decorator, or the `on_command_error` event handler.

e.g.

```py
@client.command(pass_context=True)
async def test(ctx, arg1, arg2):
	desc = 'Bataille sur la carte {0} à {1}'.format(arg1,arg2)
	em = discord.Embed(title='Alerte CW !', description=desc, colour=0x57FE01)
	await client.send_message(client.get_channel("371613656313757699"), embed=em)

@test.error
async def test_on_error(ctx, error):
	await client.send_message(ctx.message.channel, "=cw <Carte> <Heure>"
```

**Comment by KolightFR** [comment]
I hate this : 
https://i.gyazo.com/f7981ff94c5fe1a398196fab8487f6dd.gif

  File "bot.py", line 31
    async def on_message(message):

**Comment by NCPlayz** [comment]
Could you post that as a code block or on pastebin?

**Comment by NCPlayz** [comment]
Nevermind, found the issue, there's a missing parenthesis after `"=cw <Carte> <Heure>"`

**Comment by khazhyk** [comment]
copy/pasting example code and expecting it to work with no changes will set
you up for disappointment :)

**Comment by KolightFR** [comment]
Thanks but with his solution nothing is returned in chat when i don't specify arguments : 
```

Task exception was never retrieved
future: <Task finished coro=<test_on_error() done, defined at /usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py:43> exception=CommandInvokeError("Command raised an exception: AttributeError: 'MissingRequiredArgument' object has no attribute 'message'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "bot.py", line 28, in test_on_error
    await client.send_message(ctx.message.channel, "=cw <Carte> <Heure>")
AttributeError: 'MissingRequiredArgument' object has no attribute 'message'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'MissingRequiredArgument' object has no attribute 'message'
```

**Comment by NCPlayz** [comment]
Swap the `error` and `ctx` arguments around.

**Comment by KolightFR** [comment]
Now working, thanks a lot ! :)

**Comment by NCPlayz** [comment]
For further issues, I suggest visiting the guild @khazhyk mentioned earlier.

**Comment by KolightFR** [comment]
I'm in, thanks  :P
