### ISSUE TITLE
[rewrite] Member not found using DM mention to bot

### ISSUE THREAD

**Issue by wiiittttt** [Rapptz/discord.py#878]
It seems like using a "mention" in a DM doesn't get converted to the format "<@id>", but instead remains as "@name#discrim". `guild.get_user_named` only supports "name#discrim" but not "@name#discrim" and thus cannot find the user given. 

Would it be possible to support this case as well? If so, I'm not sure if it is better to change this in `guild.get_user_named` or only in `MemberConverter`.

Error:
```
Ignoring exception in command promote:
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\discord\ext\commands\bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "C:\Python36\lib\site-packages\discord\ext\commands\core.py", line 482, in invoke
    yield from self.prepare(ctx)
  File "C:\Python36\lib\site-packages\discord\ext\commands\core.py", line 446, in prepare
    yield from self._parse_arguments(ctx)
  File "C:\Python36\lib\site-packages\discord\ext\commands\core.py", line 360, in _parse_arguments
    transformed = yield from self.transform(ctx, param)
  File "C:\Python36\lib\site-packages\discord\ext\commands\core.py", line 251, in transform
    raise e
  File "C:\Python36\lib\site-packages\discord\ext\commands\core.py", line 249, in transform
    return (yield from self.do_conversion(ctx, converter, argument))
  File "C:\Python36\lib\site-packages\discord\ext\commands\core.py", line 206, in do_conversion
    ret = yield from instance.convert(ctx, argument)
  File "C:\Python36\lib\asyncio\coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "C:\Python36\lib\site-packages\discord\ext\commands\converter.py", line 123, in convert
    raise BadArgument('Member "{}" not found'.format(argument))
discord.ext.commands.errors.BadArgument: Member "@user#0000" not found
```

Minimal example:
```python
import discord
from discord.ext import commands

bot = commands.Bot(command_prefix='!')

@bot.command(pass_context=True)
async def promote(ctx: commands.Context, member: discord.Member):
    pass

if __name__ == '__main__':
    bot.run('token')
```

**Comment by Rapptz** [comment]
I don't think I want to support this. Sorry.
