### ISSUE TITLE
Client crash: Fatal read error on SSL transport

### ISSUE THREAD

**Issue by shrx** [Rapptz/discord.py#90]
The client crashes if the internet connection is dropped (ethernet cable unplugged in my case):

```
Fatal read error on SSL transport
protocol: <websockets.client.WebSocketClientProtocol object at 0x7fc1ede993c8>
transport: <_SelectorSslTransport fd=7 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 896, in _read_ready
    data = self._sock.recv(self.max_size)
  File "/usr/lib/python3.4/ssl.py", line 733, in recv
    return self.read(buflen)
  File "/usr/lib/python3.4/ssl.py", line 622, in read
    v = self._sslobj.read(len or 1024)
OSError: [Errno 113] No route to host
Task exception was never retrieved
future: <Task finished coro=<run() done, defined at /usr/local/lib/python3.4/dist-packages/websockets/protocol.py:296> exception=OSError(113, 'No route to host')>
Traceback (most recent call last):
  File "/usr/lib/python3.4/asyncio/tasks.py", line 237, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.4/dist-packages/websockets/protocol.py", line 302, in run
    msg = yield from self.read_message()
  File "/usr/local/lib/python3.4/dist-packages/websockets/protocol.py", line 324, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.4/dist-packages/websockets/protocol.py", line 379, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "/usr/local/lib/python3.4/dist-packages/websockets/protocol.py", line 411, in read_frame
    self.reader.readexactly, is_masked, max_size=max_size)
  File "/usr/local/lib/python3.4/dist-packages/websockets/framing.py", line 77, in read_frame
    data = yield from reader(2)
  File "/usr/lib/python3.4/asyncio/streams.py", line 500, in readexactly
    block = yield from self.read(n)
  File "/usr/lib/python3.4/asyncio/streams.py", line 473, in read
    yield from self._wait_for_data('read')
  File "/usr/lib/python3.4/asyncio/streams.py", line 414, in _wait_for_data
    yield from self._waiter
  File "/usr/lib/python3.4/asyncio/futures.py", line 385, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.4/asyncio/tasks.py", line 288, in _wakeup
    value = future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/selector_events.py", line 896, in _read_ready
    data = self._sock.recv(self.max_size)
  File "/usr/lib/python3.4/ssl.py", line 733, in recv
    return self.read(buflen)
  File "/usr/lib/python3.4/ssl.py", line 622, in read
    v = self._sslobj.read(len or 1024)
OSError: [Errno 113] No route to host
```

**Comment by Rapptz** [comment]
What are you expecting here? The internet is used to power the library and you're cutting it off so obviously it's not going to work anymore.

**Comment by shrx** [comment]
I'm expecting the app to keep running, it shouldn't crash if the connection drops when it could be re-estabilished just moments later.

**Comment by Funky7Monkey** [comment]
It appears that Python crashed, not just discord.py, due to the loss of connection. You might have to write another script to restart your client when connection returns. Batch will probably work well for that, it can test to see if it crashes, then wait until it reconnects to restart the client.

**Comment by AraHaan** [comment]
Try Python 3.5.1 maybe they fixed is as I dont see this happening at all.

**Comment by Funky7Monkey** [comment]
It makes no difference what version of Python is being used. When the client looses connection, it throws an exception. Actually, if you catch that exception, you might be able to pass it without the client crashing. I'm not sure if that'll actually work. Alternatively, you can just restart it when it does crash, when @Rapptz updates the client to allow for that. Right now, attempting to restart the bot after a crash throws an exception from asyncio. If the client still crashes when you catch the `OSError` exception, for now you'll just have to use an external program to restart it on said crash.

**Comment by Hornwitser** [comment]
While the `OSError` is a bit of and edge case and could be a called a bug in `websockets`, the realities of the Internet being inherently *unreliable* should be handled in an Internet powered library!

In particular I expect the library to not have me drop everything and start over again in the event of a long term connection being dropped for whatever zillion of reasons that happen.  Not only that, but Discord has outages as well, and in these events I've seen `discord.HTTPException`, subclasses of `aiohttp.ClientError`, `discord.GatewayNotFound`, `websockets.InvalidHandshake` and `websockets.WebSocketProtocolError`, all thrown out of `Client.connect()`!

**Comment by Rapptz** [comment]
Reconnection logic in the rewrite version of the library (v1.0) has improved significantly (see [here](http://discordpy.readthedocs.io/en/rewrite/migrating.html#connection-improvements)). 

Closing this for now.
