### ISSUE TITLE
socket.gaierror / Cannot connect to host ... [getaddrinfo failed]

### ISSUE THREAD

**Issue by Meolsei** [Rapptz/discord.py#9046]
### Summary

Occasionally, the bot needs to reset the connection briefly. When it does so, it will run into an entire set of errors for about a minute or two before going back to a normal state again. This happens constantly when running the bot.

### Expected Results

The bot to continue normally, not run into occasional hiccups while running and return to normal... frequently.

### Actual Results

```
[2022-11-04 18:56:07] [ERROR   ] discord.client: Attempting a reconnect in 2.11s
Traceback (most recent call last):
  File "C:\Users\attic\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "C:\Users\attic\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "C:\Users\attic\AppData\Roaming\Python\Python39\site-packages\aiohttp\resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\asyncio\base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\attic\AppData\Roaming\Python\Python39\site-packages\discord\client.py", line 624, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\asyncio\tasks.py", line 481, in wait_for
    return fut.result()
  File "C:\Users\attic\AppData\Roaming\Python\Python39\site-packages\discord\gateway.py", line 371, in from_client
    socket = await client.http.ws_connect(url)
  File "C:\Users\attic\AppData\Roaming\Python\Python39\site-packages\discord\http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "C:\Users\attic\AppData\Roaming\Python\Python39\site-packages\aiohttp\client.py", line 779, in _ws_connect
    resp = await self.request(
  File "C:\Users\attic\AppData\Roaming\Python\Python39\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\attic\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\attic\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\attic\AppData\Roaming\Python\Python39\site-packages\aiohttp\connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-b.discord.gg:443 ssl:default [getaddrinfo failed]
[2022-11-04 18:56:09] [ERROR   ] discord.client: Attempting a reconnect in 2.20s
```

### Intents

`discord.Intents.all()`

### System Information

```
- Python v3.9.7-final
- discord.py v2.0.1-final
- aiohttp v3.8.3
- system info: Windows 10 10.0.19044
```

**Comment by Rapptz** [comment]
This is a networking error with your DNS. It's not really related to the library, especially since networking can be finicky. The logs say the client will reconnect, which is about the only thing you can feasibly expect me to do here. I suggest setting up a secondary DNS if you keep getting DNS errors.

**Comment by Meolsei** [comment]
I really don't know what to change, unfortunately.
