### ISSUE TITLE
self.bot.send_message() returned 500 Error but message sent anyway

### ISSUE THREAD

**Issue by JayTurnr** [Rapptz/discord.py#910]
Had a few errors in my code yesterday, I'll get around it on my end with try-except clauses for now but the bug is something to do with discord.py or Discord itself.

```
Exception in command 'update xp'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/opt/red/cogs/trainerdex.py", line 314, in xp
    message = await self.bot.say('Processing...')
  File "lib/discord/ext/commands/bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "/opt/red/red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "lib/discord/http.py", line 200, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 634, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "lib/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error
```

Detail over at TrainerDex/TrainerDex-RedCog#27, but for reference, I sent a message with `message = await self.bot.say('Processing...')`, but got back a generally not very helpful `discord.errors.HTTPException: INTERNAL SERVER ERROR (status code: 500): 500: Internal Server Error` however, the message DID post.

![image](https://user-images.githubusercontent.com/11667059/32993893-e8cada14-cd56-11e7-9c97-c6e5ec34f748.png)

I wasn't prepared for false-negatives on errors, my code stopped. Running Discord.py 0.16.12.

**Comment by SunDwarf** [comment]
500 errors are Discord errors. Nothing you can do.

**Comment by Rapptz** [comment]
This isn't a library issue.
