### ISSUE TITLE
Deleting ephemeral messages doesn't work

### ISSUE THREAD

**Issue by RazzerDE** [Rapptz/discord.py#9114]
### Summary

Deleting ephemeral messages doesn't work

### Reproduction Steps

1. Create an select menu from the example page.
2. Try to delete it with `await interaction.message.delete()`

### Minimal Reproducible Code

```python
class GUISnippetSelect(discord.ui.Select):
    def __init__(self, bot, options, creator_id):
        self.bot = bot
        self.creator_id = creator_id

        super().__init__(
            placeholder="placeholder",
            min_values=1,
            max_values=1,
            options=options
        )

    async def callback(self, interaction: discord.Interaction) -> None:
        await interaction.message.delete()
```

### Expected Results

the ephemeral message should be deleted, as discord said of supporting it: https://discord.com/developers/docs/change-log#delete-ephemeral-messages

### Actual Results

The message doesn't gets deleted, i'm getting the error:

```py
Traceback (most recent call last):
  File "/Bots/supporttest-bot/discord/ui/view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "/Bots/supporttest-bot/cogs/support_module.py", line 942, in callback
    await send_snippet(snippet_name, self.creator_id, interaction)
  File "/Bots/supporttest-bot/cogs/support_module.py", line 875, in send_snippet
    await interaction.message.delete()
  File "/Bots/supporttest-bot/discord/message.py", line 805, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/Bots/supporttest-bot/discord/http.py", line 740, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10008): Unknown Message
```

### Intents

None needed

### System Information

- Python v3.9.13-final                                                                                                                 
- discord.py v2.1.0-alpha
    - discord.py metadata: v2.1.0a4616+ga592361f
- aiohttp v3.7.4.post0
- system info: Windows 10 10.0.22621

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by staciax** [comment]
Wait, you haven't sent a message yet.

**Comment by staciax** [comment]
```py
import discord

class GUISnippetSelect(discord.ui.Select['TestView']):
    def __init__(self, bot, options, creator_id):
        self.bot = bot
        self.creator_id = creator_id

        super().__init__(
            placeholder="placeholder",
            min_values=1,
            max_values=1,
            options=options
        )

    async def callback(self, interaction: discord.Interaction) -> None:
        await self.view.interaction.delete_original_response()

class TestView(discord.ui.View):

    def __init__(self, interaction: discord.Interaction):
        self.interaction = interaction
        options = [
            discord.SelectOption(label="label", value="value"),
        ]
        self.add_item(GUISnippetSelect(interaction.client, options, interaction.created_at))
        super().__init__()


# app_commands
view = TestView(interaction)

```

**Comment by RazzerDE** [comment]
That's not working, i get this error:
```
[2022-12-11 22:44:39] [ERROR   ] discord.ui.view: Ignoring exception in view <GUISnippetView timeout=300 children=1> for item <GUISnippetSelect placeholder='📜 › Wähle ein Support-Snippet!' min_values=1 max_values=1 disabled=False options=[<SelectOption label='test100' value='test100_text' description='› Klicke auf dieses Snippet, um es zu nutzen.' emoji=<PartialEmoji animated=False name='📢' id=None> default=False>, <SelectOption label='test500' value='test500_text' description='› Klicke auf dieses Snippet, um es zu nutzen.' emoji=<PartialEmoji animated=False name='📢' id=None> default=False>]>
Traceback (most recent call last):
  File "/Bots/supporttest-bot/discord/ui/view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "/Bots/supporttest-bot/cogs/support_module.py", line 917, in callback
    await send_snippet(snippet_name, self.creator_id, interaction)
  File "/Bots/supporttest-bot/cogs/support_module.py", line 850, in send_snippet
    await interaction.delete_original_response()
  File "/Bots/supporttest-bot/discord/interactions.py", line 499, in delete_original_response
    await adapter.delete_original_interaction_response(
  File "/Bots/supporttest-bot/discord/webhook/async_.py", line 218, in request
    raise NotFound(response, data)
discord.errors.NotFound: 404 Not Found (error code: 10015): Unknown Webhook
```

Maybe my example is not really good, but here my logic:

Button Click -> Ephemeral Embed Message with View -> Click on View should delete the ephemeral message.

**Comment by Rapptz** [comment]
Interaction.message is a Message object which uses regular message delete endpoints. These don't allow you to delete ephemeral messages. If you want to delete ephemeral messages from an interaction you want to use Interaction.delete_original_response though you have to defer the interaction before attempting it.
