### ISSUE TITLE
Issue about Intents 

### ISSUE THREAD

**Issue by AswAstropyYt** [Rapptz/discord.py#9133]
### Summary

when i run the code its making Error i even copied and paste code from here but isn't working  

### Reproduction Steps

*

### Minimal Reproducible Code

```python
import discord
token = open('token.txt', 'r')

class MyClient(discord.Client):
    async def on_ready(self):
        print(self.user, " Is Running!")

    async def on_message(self, message):

        if message.author == self.user:
            return

        if message.content == ':!test':
            await message.channel.send('Hi')

intents = discord.Intents.default()
intents.message_content = True
client = MyClient(intents=intents)
client.run(token)
```

### Expected Results

bot needs run but it making Error

### Actual Results

C:\Users\Arifs\OneDrive\Desktop\DisordBot\Venv\Scripts\python.exe C:\Users\Arifs\OneDrive\Desktop\DisordBot\Main.py 
[2022-12-13 21:04:51] [INFO    ] discord.client: logging in using static token
Traceback (most recent call last):
  File "C:\Users\Arifs\OneDrive\Desktop\DisordBot\Main.py", line 19, in <module>
    client.run(token)
  File "C:\Users\Arifs\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 828, in run
    asyncio.run(runner())
  File "C:\Users\Arifs\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Arifs\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Arifs\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\Arifs\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 745, in start
    await self.login(token)
  File "C:\Users\Arifs\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 577, in login
    raise TypeError(f'expected token to be a str, received {token.__class__!r} instead')
TypeError: expected token to be a str, received <class '_io.TextIOWrapper'> instead

Process finished with exit code 1

### Intents

*

### System Information

Discord.py Version is 2.0.1 Version , Python version is 3.10 and OS is Windows 10 Pro

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by AswAstropyYt** [comment]
So it i changed the code but its makin Error

Code:
import discord
class MyClient(discord.Client):
    async def on_ready(self):
        print(self.user, " Is Running!")

    async def on_message(self, message):

        if message.author == self.user:
            return

        if message.content == ':!test':
            await message.channel.send('Hi')

intents = discord.Intents.default()
intents.message_content = True
client = MyClient(intents=intents)
client.run("my token")

Error:
C:\Users\Arifs\OneDrive\Desktop\DisordBot\Venv\Scripts\python.exe C:\Users\Arifs\OneDrive\Desktop\DisordBot\Main.py 
[2022-12-14 16:22:56] [INFO    ] discord.client: logging in using static token
Traceback (most recent call last):
  File "C:\Users\Arifs\OneDrive\Desktop\DisordBot\Main.py", line 19, in <module>
    client.run("my token")
  File "C:\Users\Arifs\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 828, in run
    asyncio.run(runner())
  File "C:\Users\Arifs\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Arifs\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Arifs\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\Arifs\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 746, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\Arifs\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 672, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

Process finished with exit code 1

**Comment by tailoric** [comment]
Read the error 
> discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.


[You need to add the intents on the developer portal too](https://discordpy.readthedocs.io/en/latest/intents.html?highlight=intents#privileged-intents)

The issues board is not the place for this btw join the [discord server ](https://discord.gg/dpy) to receive help with this or open a post [in discussions](https://github.com/Rapptz/discord.py/discussions)

These problems are with your code / setup not a bug.

**Comment by AswAstropyYt** [comment]
thanks worked

**Comment by bsy-rui** [comment]
# TRY THIS
```py

import discord
import os # default module
from discord.ext import commands

bot = commands.Bot(command_prefix="!",intents=discord.Intents.default()) # prefix is the bot command
@bot.event
async def on_ready():
    print(f"{bot.user} is ready and online!")

@bot.command()
async def hello(ctx):
    await ctx.send("Hello")

bot.run("your token...")
```

**Comment by StevenDevy** [comment]
You need to mention `command_prefix`. Also, I'd not recommend using `on_message` to create commands.

**Comment by StevenDevy** [comment]
You didn't mention a string token. Please try adding `print(type(token))` before running the bot and check if it's a string. Also, I'd not recommend using `on_message` to create commands. I hope this helps
