### ISSUE TITLE
error trying to send embed or button with url

### ISSUE THREAD

**Issue by Subjoel** [Rapptz/discord.py#9138]
### Summary

when  i run my bot and i do .message to send an embed it gives an error with unexpected keyword `url` 

### Reproduction Steps

async def message(ctx):
  embed = discord.Embed(title='', description='__**click**__', color=5763719)
  await ctx.message.channel.send(embed=embed, component=ActionRow[Button(url='myredirecturl.com',label="",style=ButtonStyle.url,emoji='✅')])
  
  then do python bot.py and do the prefix with message.
  
  then you get `
  2022-12-16 13:38:13 ERROR    discord.ext.commands.bot Ignoring exception in command message
Traceback (most recent call last):
  File "/home/runner/disc-bot-test/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/runner/disc-bot-test/main.py", line 21, in message
    await ctx.message.channel.send(embed=embed, component=ActionRow[Button(url='myredirect.com',label="",style=ButtonStyle.url,emoji='✅')])
TypeError: Button.__init__() got an unexpected keyword argument 'url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/disc-bot-test/venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/disc-bot-test/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/disc-bot-test/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Button.__init__() got an unexpected keyword argument 'url'
`

### Minimal Reproducible Code

```python
`
  2022-12-16 13:38:13 ERROR    discord.ext.commands.bot Ignoring exception in command message
Traceback (most recent call last):
  File "/home/runner/disc-bot-test/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/runner/disc-bot-test/main.py", line 21, in message
    await ctx.message.channel.send(embed=embed, component=ActionRow[Button(url='myredirect.com',label="",style=ButtonStyle.url,emoji='✅')])
TypeError: Button.__init__() got an unexpected keyword argument 'url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/disc-bot-test/venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/disc-bot-test/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/disc-bot-test/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Button.__init__() got an unexpected keyword argument 'url'
`
```

### Expected Results

send a button with on click redirect to a link.

### Actual Results

`
  2022-12-16 13:38:13 ERROR    discord.ext.commands.bot Ignoring exception in command message
Traceback (most recent call last):
  File "/home/runner/disc-bot-test/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/runner/disc-bot-test/main.py", line 21, in message
    await ctx.message.channel.send(embed=embed, component=ActionRow[Button(url='myredirect.com',label="",style=ButtonStyle.url,emoji='✅')])
TypeError: Button.__init__() got an unexpected keyword argument 'url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/disc-bot-test/venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/disc-bot-test/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/disc-bot-test/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: Button.__init__() got an unexpected keyword argument 'url'
`

### Intents

intents=discord.Intents().all()

### System Information

~/disc-bot-test$ python -m discord -v
usage: discord [-h] [-v] {newbot,newcog} ...
discord: error: too few arguments

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Subjoel** [comment]
why invalid?

**Comment by Rapptz** [comment]
This doesn't look like discord.py, as it does not have a `components=` keyword argument for `send`. Likewise, there are too many errors here should it even be discord.py.
