### ISSUE TITLE
Error - ImportError: cannot import name 'handle_message_parameters' from 'discord.http' (/usr/local/lib/python3.9/site-packages/discord/http.py)

### ISSUE THREAD

**Issue by Tennixx** [Rapptz/discord.py#9169]
### Summary

Unable to import 'handle_message_parameters' when running main.py with line "import discord"

### Reproduction Steps

Installed Python 3.9 on my Linux Root Server
Installed discord.py
Installed discord.py-message-components

### Minimal Reproducible Code

```python
ImportError: cannot import name 'handle_message_parameters' from 'discord.http' (/usr/local/lib/python3.9/site-packages/discord/http.py)  File "/usr/local/lib/python3.9/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 53, in <module>
    from .webhook import Webhook
  File "/usr/local/lib/python3.9/site-packages/discord/webhook/__init__.py", line 12, in <module>
    from .async_ import *
  File "/usr/local/lib/python3.9/site-packages/discord/webhook/async_.py", line 46, in <module>
    from ..http import Route, handle_message_parameters, MultipartParameters, HTTPClient, json_or_text
ImportError: cannot import name 'handle_message_parameters' from 'discord.http' (/usr/local/lib/python3.9/site-packages/discord/http.py)
Traceback (most recent call last):
  File "/root/***name***-main/sachsenmodding.py", line 1, in <module>
    import dTraceback (most recent call last):
  File "/root/***name***-main/sachsenmodding.py", line 1, in <module>
    import discord
  File "/usr/local/lib/python3.9/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 53, in <module>
    from .webhook import Webhook
  File "/usr/local/lib/python3.9/site-packages/discord/webhook/__init__.py", line 12, in <module>
    from .async_ import *
  File "/usr/local/lib/python3.9/site-packages/discord/webhook/async_.py", line 46, in <module>
    from ..http import Route, handle_message_parameters, MultipartParameters, HTTPClient, json_or_text
ImportError: cannot import name 'handle_message_parameters' from 'discord.http' (/usr/local/lib/python3.9/site-packages/discord/http.py)
Traceback (most recent call last):
```

### Expected Results

I expected the bot to run as usual without any issues.

### Actual Results

Now I am unable to run my code

### Intents

Presence Intent, Server Members Intent and Message Contents Intent(I indicated it as discord.Intents.all())

### System Information

Traceback (most recent call last):
  File "/root/***name***/sachsenmodding.py", line 1, in <module>
    import discord
  File "/usr/local/lib/python3.9/site-packages/discord/__init__.py", line 25, in <module>
    from .client import Client
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 53, in <module>
    from .webhook import Webhook
  File "/usr/local/lib/python3.9/site-packages/discord/webhook/__init__.py", line 12, in <module>
    from .async_ import *
  File "/usr/local/lib/python3.9/site-packages/discord/webhook/async_.py", line 46, in <module>
    from ..http import Route, handle_message_parameters, MultipartParameters, HTTPClient, json_or_text
ImportError: cannot import name 'handle_message_parameters' from 'discord.http' (/usr/local/lib/python3.9/site-packages/discord/http.py)

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ImVaskel** [comment]
Uninstall ``discord.py-message-components``. That is a 3rd party library that is not supported. Components are supported on v2.0+.

**Comment by Tennixx** [comment]
But I had already installed it half a year ago and it worked then. It was just called something else.

**Comment by AbstractUmbra** [comment]
Hello,

This but occurs when you install a 3rd party form/add-on that patches discord.py internals and is subsequently removed.
To fix this you must uninstall these 3rd party items (as they are unsupported here) and then issue the following command from the correct environment:
`python -m pip install -U --force-reinstall discord.py`
