### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'channel'

### ISSUE THREAD

**Issue by Dosentos** [Rapptz/discord.py#921]
My bot throws this error when it's trying to update its own message.

message is the object that bot gets when someone writes comment to bot.
message.channel prints out `<generator object Client.get_message at 0x06FDDDB0>` so I guess get_message function works as it should.

```
old_bot_message = client.get_message(message.channel, "383356260348854283")
await client.edit_message(old_bot_message, new_content="Message updated", embed=None)
```

Here's whole stacktrace in case it's needed:
```
Traceback (most recent call last):
  File "D:\koodia\projektit\discord-bottachable\venv\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "D:\koodia\projektit\discord-bottachable\discord_bottachable\discord_bottachable\management\commands\bot.py", line 41, in on_message_edit
    await handle_messages(after, before)
  File "D:\koodia\projektit\discord-bottachable\discord_bottachable\discord_bottachable\management\commands\bot.py", line 243, in handle_messages
    await client.edit_message(old_bot_message, new_content=string, embed=None)
  File "D:\koodia\projektit\discord-bottachable\venv\lib\site-packages\discord\client.py", line 1437, in edit_message
    channel = message.channel
AttributeError: 'generator' object has no attribute 'channel'
```

I tried to follow docs but I'm not 100% sure if this is my code, misguided docs or actual bug in discord.py. Any ideas?

**Comment by nitros12** [comment]
From the docs: `This function is a coroutine.`
`Client.get_message` is a coroutine, you need to await it.

**Comment by Dosentos** [comment]
I should just be ashamed... -.-'
