### ISSUE TITLE
Expected closing "

### ISSUE THREAD

**Issue by Nocturnal42** [Rapptz/discord.py#9304]
### Summary

ExpectedClosingQuoteError exception on bot.command with *args

### Reproduction Steps

Call test function with a message body containing a single quote, such as

**$test this is also a single quote "**

### Minimal Reproducible Code

```python
from discord.ext import commands

bot = commands.Bot(command_prefix='$')

@bot.command()
async def test(ctx, *args):
    pass

bot.run(TOKEN)
```
```


### Expected Results

I expected *args to be populated with all the words after the command string.

### Actual Results

Ignoring exception in command test:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 856, in invoke
    await self.prepare(ctx)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 790, in prepare
    await self._parse_arguments(ctx)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 713, in _parse_arguments
    transformed = await self.transform(ctx, param)
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/core.py", line 549, in transform
    argument = view.get_quoted_word()
  File "/usr/local/lib/python3.7/dist-packages/discord/ext/commands/view.py", line 148, in get_quoted_word
    raise ExpectedClosingQuoteError(close_quote)
discord.ext.commands.errors.ExpectedClosingQuoteError: Expected closing ".


### Intents

Default

### System Information

- Python v3.7.3-final
- discord.py v1.6.0-final
- aiohttp v3.7.3
- system info: Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11)


### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

**Comment by Rapptz** [comment]
`*args` parses everything as if it was a "word" component and passes it in. A "word" component requires quotes to differentiate between words with spaces so this is working as expected. If you want to get an unfiltered parameter of the remaining string use `*, arg` instead.

Check the [documentation](https://discordpy.readthedocs.io/en/stable/ext/commands/commands.html#parameters) for more info.
