### ISSUE TITLE
Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

### ISSUE THREAD

**Issue by Mqrshe** [Rapptz/discord.py#9365]
### Summary

I try running command and it says i dont have proper missions in the terminal for bot.

### Reproduction Steps

add to server with read messages, manage nicknames permissions. run /sixify. in server you should get "this application didnt respond" and in vsc in terminal i get:

2023-04-17 20:06:03 INFO     discord.client logging in using static token
2023-04-17 20:06:04 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 64d8bee91d32b2f175c708b8a5b2fae5).
Synced 2 command(s)
2023-04-17 20:06:12 ERROR    discord.app_commands.tree Ignoring exception in command 'sixify'
Traceback (most recent call last):
  File "C:\Users\liams\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "c:\Users\liams\OneDrive\Documents\Code\6\6.py", line 23, in sixify_nicks
    await member.edit(nick="six")
  File "C:\Users\liams\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\member.py", line 906, in edit
    data = await http.edit_member(guild_id, self.id, reason=reason, **payload)
  File "C:\Users\liams\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\http.py", line 738, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\liams\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "C:\Users\liams\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 867, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "C:\Users\liams\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\app_commands\commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'sixify' raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions

### Minimal Reproducible Code

```python
import discord
import random
from discord.ext import commands

bot = commands.Bot(command_prefix="!", intents=discord.Intents.all())

@bot.event
async def on_ready():
    try:
        synced = await bot.tree.sync()
        print(f"Synced {len(synced)} command(s)")
    except Exception as e:
        print(e)

@bot.tree.command(name="6", description="Says 6")
async def say_six(interaction: discord.Interaction):
    await interaction.response.send_message("6", ephemeral=False)

@bot.tree.command(name="sixify", description="Changes everyone's nickname to 'six'")
async def sixify_nicks(interaction: discord.Interaction):
    for member in interaction.guild.members:
        if not member.bot:
            await member.edit(nick="six")
    await interaction.response.send_message("All nicknames changed to 'six'", ephemeral=True)

bot.run("Your not getting my token")
```

### Expected Results

To change every user in the discord servers nickname to "six"

### Actual Results

"This application didnt respond on discord"

### Intents

intents=discord.Intents.all())

### System Information

- Python v3.10.10-final
- discord.py v2.2.2-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by LeoCx1000** [comment]
Regarding the actual error, 

- Your bot doesn't have manage nick permissions.
- You're editing members that you can't edit:
- - people who's top role is higher or equal to the bot's top role
- - the owner of the server 

You need to check for those, something along the lines of:

```python3

if member.top_role >= interaction.guild.me.top_role:
    continue

if member.id == interaction.guild.owner_id:
    continue

# rest of the logic of your for loop.
```
