### ISSUE TITLE
Discord.py TypeError: enum.Enum requires at least two values.

### ISSUE THREAD

**Issue by ar-cyber** [Rapptz/discord.py#9373]
### Summary

When trying to add automod rules, I get the error in the title

### Reproduction Steps

You need to add the code in the snippet.

### Minimal Reproducible Code

```python
@client.tree.command(name = "automodrule", description = "Add AutoMod rules")
@has_permissions(administrator = True)
async def automodddddddddddd(ctx: discord.Interaction, name: str, event_type: AutoModRuleEventType, trigger:AutoModTrigger, actions: list[AutoModRuleAction], reason: str):
    guild = ctx.guild()
    await guild.create_automod_rule(name=name, event_type=event_type, trigger=trigger, actions=actions, enabled=True, reason=reason)
    await ctx.response.send_message("AutoMod rule made")
```

### Expected Results

Go to my ASCII showing that it was a success.

### Actual Results

Traceback (most recent call last):
  File "/home/container/app.py", line 476, in <module>
    @client.tree.command(name = "automodrule", description = "Add AutoMod rules")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/app_commands/tree.py", line 889, in decorator
    command = Command(
              ^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 685, in __init__
    self._params: Dict[str, CommandParameter] = _extract_parameters_from_callback(callback, callback.__globals__)
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/app_commands/commands.py", line 393, in _extract_parameters_from_callback
    param = annotation_to_parameter(resolved, parameter)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/app_commands/transformers.py", line 832, in annotation_to_parameter
    (inner, default, validate_default) = get_supported_annotation(annotation)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/app_commands/transformers.py", line 762, in get_supported_annotation
    return (EnumValueTransformer(annotation), MISSING, False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.11/site-packages/discord/app_commands/transformers.py", line 434, in __init__
    raise TypeError('enum.Enum requires at least two values.')
TypeError: enum.Enum requires at least two values.

### Intents

None

### System Information

- Python v3.11.3-final
- discord.py v2.1.1-final
- aiohttp v3.8.4
- system info: Linux 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by ar-cyber** [comment]
How do I fix this

**Comment by Rapptz** [comment]
The `AutoModRuleEventType` only has a single element so it only becomes a single choice, so it's not entirely useful as a parameter.
