### ISSUE TITLE
TimeoutError caused by IPv6

### ISSUE THREAD

**Issue by andyman1222** [Rapptz/discord.py#9442]
### Summary

discord.py attempts to use IPv6 stack when IPv6 isn't supported in Discord's API, causes TimeoutError

### Reproduction Steps

1. Ensure you have a server/PC with proper IPv6 support (check at ipv6-test.com). Set IPv6 to the priority or disable the IPv4 stack.
2. Have DNS64 turned on on your DNS server (such as a locally hosted Unbound DNS or DNSmasq)
3. Attempt to start up a Discord bot
4. After about a minute or so, the bot will attempt to reconnect, but instead crash.

### Minimal Reproducible Code

```python
import discord
intents = discord.Intents()
bot = discord.Client(intents=intents)
bot.run('token')
```

### Expected Results

The bot only attempts to connect to Discord's API via IPv4

### Actual Results

Because of the network configuration, I have IPv6 set to be used by default, so discord.py will attempt to connect to the API over v6, but never establish a connection. I have confirmed that this is caused by IPv6, as on the PC I use to run my bots, I disabled the IPv6 stack on Windows and the bot was able to run.

Output:
```
2023-06-03 19:06:26 INFO     discord.client logging in using static token
2023-06-03 19:09:12 ERROR    discord.client Attempting a reconnect in 1.99s
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\discord\gateway.py", line 372, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\discord\http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\aiohttp\client.py", line 779, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Program Files\Python311\Lib\asyncio\proactor_events.py", line 726, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 656, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\asyncio\tasks.py", line 490, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\discord\gateway.py", line 372, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\discord\http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\aiohttp\client.py", line 779, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Program Files\Python311\Lib\asyncio\proactor_events.py", line 726, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 656, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "C:\Program Files\Python311\Lib\asyncio\tasks.py", line 492, in wait_for
    raise exceptions.TimeoutError() from exc
TimeoutError


Traceback (most recent call last):
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 778, in start
    await self.connect(reconnect=reconnect)
  File "C:\Users\andy\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 716, in connect
    sequence=self.ws.sequence,
             ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sequence'
```

### Intents

Intents are irrelevant in this case

### System Information

- Python v3.11.3-final
- discord.py v2.2.3-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19044

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I'm not entirely sure if discord.py works with sockets, an http lib, or a websocket lib, but I think a safe way to fix this is to resolve the DNS of Discord's API and then only retrieve an IPv4 from the result and connect to that, throwing an exception if an IPv4 cannot be found.

**Comment by andyman1222** [comment]
One additional thing: this bug only shows if DNS64 is enabled, such as in Unbound DNS, which synthesizes AAAA records if none were found. Disabling this, discord.com now only reports with IPv4 addresses (A records). (Side note, that might've been the solution to quite a few issues of my home network...)

I'll keep this open though in case devs want to do something with the API itself to prevent it.
