### ISSUE TITLE
Error 401 discord.py bot.

### ISSUE THREAD

**Issue by Dextication** [Rapptz/discord.py#949]
When I run my discord bot, I receive this error: 

> Traceback (most recent call last):
>   File "C:\Users\info\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\bot.py", line 846, in process_commands
>     yield from command.invoke(ctx)
>   File "C:\Users\info\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 374, in invoke
>     yield from injected(*ctx.args, **ctx.kwargs)
>   File "C:\Users\info\AppData\Local\Programs\Python\Python36\lib\site-packages\discord\ext\commands\core.py", line 54, in wrapped
>     raise CommandInvokeError(e) from e
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: UNAUTHORIZED (status code: 401): 401: Unauthorized

I have changed my bot token already and updated it in my code. I still receive the same error. This is my code at the moment.

bot.py:
```
import discord
from discord.ext import commands
import asyncio
import config

startup_extensions = ['commands']

bot = commands.Bot(command_prefix='!', description='LTT event bot help')

@bot.event
async def on_ready():
    print('Staring bot...')
    print('Logged in as:')
    print(bot.user.name)
    print('Client id')
    print(bot.user.id)
    print('=====================')

@bot.command()
async def load(extension_name : str):
    try:
        bot.load_extension(extension_name)
    except (AttributeError, ImportError) as e:
        await bot.say("```py\n{}: {}\n```".format(type(e).__name__, str(e)))
        return
    await bot.say("{} loaded.".format(extension_name))

@bot.command()
async def unload(extension_name : str):
    bot.unload_extension(extension_name)
    await bot.say("{} unloaded.".format(extension_name))

if __name__ == "__main__":
    for extension in startup_extensions:
        try:
            bot.load_extension(extension)
        except Exception as e:
            exc = '{}: {}'.format(type(e).__name__, e)
            print('Failed to load extension {}\n{}'.format(extension, exc))

bot.run(config.token, bot=True)
````

commands.py:
```
import discord
from discord.ext import commands
import asyncio
import datetime

bot = commands.Bot(command_prefix='!', description='LTT event bot help')

class GeneralCommands():
	def __init__ (self, bot):
		self.bot = bot

	@bot.command(pass_context=True)
	async def ping(self):
		"""Replies with Pong!"""
		await bot.say('Pong! :ping_pong:')
 
	@bot.command()
	async def hello(self):
		"""Replies with 'Hello'"""
		print('A user has issued the command "hello"')
		await bot.say('Heyo! :wave:')

def setup (bot):
	bot.add_cog(GeneralCommands(bot))```

**Comment by SolitudalDeveloper** [comment]
So no issue anymore?
