### ISSUE TITLE
certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Ek2100** [Rapptz/discord.py#9497]
### Summary

My bot is getting some weird errors related to certificates

### Reproduction Steps

- Start the bot using `python3 main.py`

### Expected Results

The bot used to start normally with no errors.

### Actual Results
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/user1/Desktop/test/main.py", line 130, in <module>
    Bot.load_extension(f'cogs.{cog}')
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/cog.py", line 910, in load_extension
    self._load_from_module_spec(spec, name)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/discord/cog.py", line 777, in _load_from_module_spec
    raise errors.ExtensionFailed(key, e) from e
discord.errors.ExtensionFailed: Extension 'cogs.initialise' raised an error: ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]
```
### Intents

`intents = discord.Intents.all()` 

### System Information

MacBook-Pro:discordbot user1$ python3 -m discord -v
- Python v3.11.4-final
- py-cord v2.4.1-final
- aiohttp v3.8.4
- system info: Darwin 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I have checked https://github.com/Rapptz/discord.py/issues/4159 however this relates to windows and its answer does not fix my issue.

**Comment by Ek2100** [comment]
why it work now
