### ISSUE TITLE
DNS Resolution Issue - Handling Temporary Failures and Providing User-Friendly Errors

### ISSUE THREAD

**Issue by TECBURST** [Rapptz/discord.py#9509]
### Summary

DNS Error Handling

### What is the feature request for?

The core library

### The Problem

**Issue:**
I have encountered an issue with the discord.py library related to DNS resolution failures. My bot is hosted on a mobile connection and runs on a Raspberry Pi, which receives a new IP address around 7 a.m. due to the dynamic nature of the connection. This results in a temporary loss of internet connectivity, causing the library to raise a DNS resolution exception with the message "socket.gaierror: [Errno -3] Temporary failure in name resolution."

### The Ideal Solution

**Expected Behavior:**
To handle DNS resolution failures more effectively, I propose the following behavior for the discord.py library:

1. When the library encounters a DNS resolution failure while attempting to connect to a server or perform any network-related operation, it should trigger the following steps:

2. The library should first check for internet connectivity by attempting to ping a reliable server (e.g., 8.8.8.8 or 9.9.9.9).

3. If the ping is successful and internet connectivity is confirmed, the library can then proceed with the DNS resolution of the target domain again.

4. If the second DNS resolution attempt is successful, the library can proceed with the intended operation (e.g., sending a message to Discord) as expected.

5. If the second DNS resolution attempt also fails, it indicates a potential issue beyond a simple DNS resolution failure. In this case, the library should handle the situation gracefully by displaying a user-friendly error message explaining the temporary loss of DNS resolution and suggesting to try again later.

6. During the process of checking internet connectivity and performing DNS resolution attempts, the library should provide informative console messages to keep the user informed about the progress and any potential issues encountered.

By incorporating these steps into the discord.py library's DNS resolution process, users can receive more informative error messages and benefit from automatic retry attempts in case of temporary DNS resolution failures. This approach minimizes manual intervention and provides a smoother user experience when dealing with intermittent internet connectivity or temporary DNS issues.

The proposed behavior is more convenient as it provides a user-friendly error handling approach, which is also better than a Python exception.

### The Current Solution

*DNS resolution exception*

2023-07-22 07:11:54 ERROR discord.client Attempting a reconnect in 0.22s
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 861, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 656, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.9/site-packages/discord/gateway.py", line 372, in from_client
    socket = await client.http.ws_connect(str(url))
  File "/usr/local/lib/python3.9/site-packages/discord/http.py", line 536, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 779, in _ws_connect
    resp = await self.request(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-d.discord.gg:443 ssl:default [Temporary failure in name resolution]
2023-07-22 07:12:04 ERROR discord.client Attempting a reconnect in 2.91s

### Additional Context

**Environment:**
- discord.py version: latest
- Python version: 3.11.4
- Operating System: Raspberry Pi OS on Raspberry Pi

**Thanks**

I appreciate the efforts put into maintaining this fantastic library and would be grateful for any improvements in handling temporary DNS resolution failures. Thank you!

**Comment by Rapptz** [comment]
The operating system is capable of having secondary DNS servers and it should be the venue to add these, not the library level. There is a privacy concern with your solution (some people would not want DNS queries sent to Google) and scope issues (this does not really belong in a library). 

If you want to add a secondary DNS for your raspberry pi, there are a few guides on Google on how to do so, e.g. [here](https://pimylifeup.com/raspberry-pi-dns-settings/).
