### ISSUE TITLE
ClientConnectorCertificateError

### ISSUE THREAD

**Issue by flvffywvffy** [Rapptz/discord.py#9513]
### Summary

I get an ClientConnectorCertificateError when I run my discord bot.

### Reproduction Steps

I installed discord.py, i've run the "Install Certificates.command" file and i've reinstalled python and it doesn't work.

### Minimal Reproducible Code

```python
import discord


class Client(discord.Client):
    async def on_ready(self):
        print('Logged on as', self.user)

    async def on_message(self, message):
        # don't respond to ourselves
        if message.author == self.user:
            return

        if message.content == 'ping':
            await message.channel.send('pong')


intents = discord.Intents.default()
intents.message_content = True
client = Client(intents=intents)
client.run('TOKEN')
```

### Expected Results

The discord bot to run.

### Actual Results

I got this error:
"/Users/---/Desktop/Python Projects/---/venv/bin/python" /Users/---/Desktop/Python Projects/---/main.py 
[2023-07-31 04:24:58] [INFO    ] discord.client: logging in using static token
Traceback (most recent call last):
  File "/Users/---/Desktop/Python Projects/---/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 974, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/---/Desktop/Python Projects/---/main.py", line 20, in <module>
    client.run('MTEzNTQxMDUzMzA0MzAxNTcwMA.GyqYqL.rUftQIhm20v-29t0TnqZJi871R924zNPVAzBPU')
  File "/Users/---/Desktop/Python Projects/---/venv/lib/python3.10/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/---/Desktop/Python Projects/---/venv/lib/python3.10/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/Users/---/Desktop/Python Projects/---/venv/lib/python3.10/site-packages/discord/client.py", line 777, in start
    await self.login(token)
  File "/Users/---/Desktop/Python Projects/---/venv/lib/python3.10/site-packages/discord/client.py", line 612, in login
    data = await self.http.static_login(token)
  File "/Users/---/Desktop/Python Projects/---/venv/lib/python3.10/site-packages/discord/http.py", line 803, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/Users/---/Desktop/Python Projects/---/venv/lib/python3.10/site-packages/discord/http.py", line 625, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/Users/---/Desktop/Python Projects/---/venv/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/---/Desktop/Python Projects/---/venv/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/---/Desktop/Python Projects/---/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/---/Desktop/Python Projects/---/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/---/Desktop/Python Projects/---/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/Users/---/Desktop/Python Projects/---/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/---/Desktop/Python Projects/---/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

Process finished with exit code 1

### Intents

Default

### System Information

- Python v3.10.4-final
- discord.py v2.3.1-final
- aiohttp v3.8.5
- system info: Darwin 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64

### Checklist

- [x] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by JamsRepos** [comment]
Im receiving the same outcome, however I'm not sure what or where the "Install Certificates.command" is so I am unable to test that. I am running on the latest verion of macOS.
