### ISSUE TITLE
AuditLogEntry for channel_id returning nothing for extra variable

### ISSUE THREAD

**Issue by RobertLeeLW** [Rapptz/discord.py#9532]
### Summary

line 647, in _from_data failing channel_id = int(extra['channel_id'])

### Reproduction Steps

client.run(TOKEN)

### Minimal Reproducible Code

```python
client.run(TOKEN)
```

### Expected Results

client.run(TOKEN)

### Actual Results

Traceback (most recent call last):
  File "main.py", line 475, in <module>
    client.run(TOKEN)
  File "/home/runner/venv/lib/python3.10/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/venv/lib/python3.10/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/runner/venv/lib/python3.10/site-packages/discord/client.py", line 778, in start
    await self.connect(reconnect=reconnect)
  File "/home/runner/venv/lib/python3.10/site-packages/discord/client.py", line 659, in connect
    await self.ws.poll_event()
  File "/home/runner/venv/lib/python3.10/site-packages/discord/gateway.py", line 623, in poll_event
    await self.received_message(msg.data)
  File "/home/runner/venv/lib/python3.10/site-packages/discord/gateway.py", line 573, in received_message
    func(data)
  File "/home/runner/venv/lib/python3.10/site-packages/discord/state.py", line 1106, in parse_guild_audit_log_entry_create
    entry = AuditLogEntry(
  File "/home/runner/venv/lib/python3.10/site-packages/discord/audit_logs.py", line 592, in __init__
    self._from_data(data)
  File "/home/runner/venv/lib/python3.10/site-packages/discord/audit_logs.py", line 647, in _from_data
    channel_id = int(extra['channel_id'])
KeyError: 'channel_id'

### Intents

discord.Intents.default()

### System Information

discord
Version 2.3.2
Website
https://github.com/Rapptz/discord.py

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Traceback line numbers do not match newest version. Please update the library instead of opening a bug report, especially one with very little workable information.
