### ISSUE TITLE
playlist.py does not run as it is currently written.

### ISSUE THREAD

**Issue by davidschaeffer2** [Rapptz/discord.py#955]
Running the code as a cog in my bot, so using my token and other information, I receive this traceback:

```Ignoring exception in on_ready
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\discord\client.py", line 223, in _run_event
    yield from coro(*args, **kwargs)
  File "C:/Users/Dave/dev/casper/casper.py", line 28, in on_ready
    casper.load_extension(f'cogs.{sub_dir.name}.'
  File "C:\Python36\lib\site-packages\discord\ext\commands\bot.py", line 698, in load_extension
    lib = importlib.import_module(name)
  File "C:\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\Dave\dev\casper\cogs\music\music.py", line 63, in <module>
    class Music:
  File "C:\Users\Dave\dev\casper\cogs\music\music.py", line 94, in Music
    async def join(self, ctx, *, channel : discord.Channel):
AttributeError: module 'discord' has no attribute 'Channel'
```
And this is most likely because the correct model under discord.py is now TextChannel or VoiceChannel. This change also breaks the 'channel.server' property, since the server property is now the guild property so all instances of server has been changed to guild. 

Once those changes are made, we get an error because Member doesn't have a 'voice_channel' attribute. This is because it's now author.voice.channel to get a Member's voice channel. Making that change leads us to 'Bot' not having the attribute 'join_voice_channel'. 

So it doesn't look like there is a 'join_voice_channel method defined in this file at all, and channel now supplies a connect method to connect to our voice channel, so we call that instead.

Once the above changes are made, the summon command now works. Play breaks though. 'Bot' doesn't have a 'send_message' attribute, because we can now use ctx.send() for our messaging needs. 

Once that is resolved, we run into 'VoiceClient' object has no attribute 'create_ytdl_player'. At this point, I can honestly admit I don't know where the code was trying to go. So I went back to the basic_voice.py example, grabbed the YTDLSource class and yt command, transposed them over to this file (since that's 99.9% of my use cases anyway) and that works as expected.

I was going to make a pull request with the above changes, hence the way they were written but I feel too much would have to be changed at this point and I'm not confident I'm the one to do it. I'd love to hear some feedback about the state of the file though. Here's a gist if you'd like to take a look:

https://gist.github.com/davidschaeffer2/6dc9096c1ab1b0b96f113d095a854ca1

**Comment by SourSpoon** [comment]
Please see issue #952

**Comment by datmellow** [comment]
The playlist.py example was based on the async branch. You are using the rewrite branch. See the basic_voice.py example for an updated one.

**Comment by davidschaeffer2** [comment]
Ah. Well I'll close this, work on some things, and maybe open a pull request down the line.
