### ISSUE TITLE
HTTPException: 401 Unauthorized (error code: 50027): Invalid Webhook Token

### ISSUE THREAD

**Issue by alfred-exe** [Rapptz/discord.py#9578]
### Summary

When using a custom View to edit an interaction, HTTPException 401 crops up.

### Reproduction Steps

Tried pressing a button that would edit an interaction response after a little bit, which threw an error.

### Minimal Reproducible Code

```python
import discord
from discord import app_commands

bot = discord.Client(intents=discord.Intents.default())
tree = app_commands.CommandTree(bot)

class MultipageMessage(discord.ui.View):
    def __init__(self, pages : list[str], title : str = "embed", color = 0x111111, timeout = None):
        super().__init__(timeout=timeout)
        self.pages = pages
        self.title = title
        self.color = color
        self.current_page = 0
        
        self.message = None
        self.left_button = discord.ui.Button(label="←", style=discord.ButtonStyle.gray)
        self.right_button = discord.ui.Button(label="→", style=discord.ButtonStyle.gray)
        self.add_item(self.left_button)
        self.add_item(self.right_button)

    async def left(self, ctx: discord.Interaction):
        if self.current_page - 1 >= 0 and self.message != None:
            self.current_page -= 1
            
            embed = discord.Embed(title=self.title, description=self.pages[self.current_page], color=self.color)
            await self.message.edit(embed=embed, view=self)
        await ctx.response.defer()
        
    async def right(self, ctx: discord.Interaction):
        if self.current_page < len(self.pages) - 1 and self.message != None:
            self.current_page += 1
            
            embed = discord.Embed(title=self.title, description=self.pages[self.current_page], color=self.color)
            await self.message.edit(embed=embed, view=self)
        await ctx.response.defer()

    def init(self, message : discord.Message):
        self.message = message
        self.left_button.callback = self.left
        self.right_button.callback = self.right

@tree.command(name="help", description="Test command")
async def help(ctx : discord.Interaction):
    pages = [
        """
page 1
""",
        """
page 2
"""
    ]
    
    view = MultipageMessage(pages=pages, title="title")
    embed = discord.Embed(title="title", description=pages[0])
    
    await ctx.response.send_message(embed=embed, view=view)
    message = await ctx.original_response()

    view.init(message)

bot.run("token")
```

### Expected Results

For the buttons to work indefinitely until the bot stops running, or the view times out.

### Actual Results

After about 15 minutes, trying to edit an interaction results in this error:
```
[2023-09-23 18:37:17] [ERROR   ] discord.ui.view: Ignoring exception in view <MultipageMessage timeout=None children=2> for item <Button style=<ButtonStyle.secondary: 2> url=None disabled=False label='→' emoji=None row=None>
Traceback (most recent call last):
  File "C:\Users\alfred\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\ui\view.py", line 427, in _scheduled_task
    await item.callback(interaction)
  File "D:\Programs\Python\D&D.py", line 575, in right
    await self.message.edit(embed=embed, view=self)
  File "C:\Users\alfred\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\interactions.py", line 1136, in edit
    res = await self._state._interaction.edit_original_response(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alfred\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\interactions.py", line 487, in edit_original_response
    data = await adapter.edit_original_interaction_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alfred\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\webhook\async_.py", line 221, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 50027): Invalid Webhook Token
```

### Intents

Default

### System Information

- Python v3.11.3-final
- discord.py v2.3.2-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by LeoCx1000** [comment]
This is not a bug, this is how discord interactions work. An interaction has a lifetime of 15 minutes, then it expires. `original_response` returns an `InteractionMessage` object which uses that interaction's token to edit the message. The proper way of editing that message and making it work indefinitely is to use [`InteractionResponse.edit_message()`](https://discordpy.readthedocs.io/en/stable/interactions/api.html#discord.InteractionResponse.edit_message) instead of deferring and editing. Also would be faster since it's only one API call.

**Comment by alfred-exe** [comment]
Thank you, I've fixed my code to use `edit_message()` instead of `edit()` and it works properly now.
