### ISSUE TITLE
Python 3.4.1 required?

### ISSUE THREAD

**Issue by Ghent** [Rapptz/discord.py#96]
Hello,

I was trying to install on my server that has Python 3.3.5 available, which the site lists as compatible, but received this error:

```
selene:~/src
[87] ghent$ pip3.3 install --user git+https://github.com/Rapptz/discord.py@async
Collecting git+https://github.com/Rapptz/discord.py@async
  Cloning https://github.com/Rapptz/discord.py (to async) to /tmp/pip-xn5i7_-build
  Requirement already satisfied (use --upgrade to upgrade): discord.py==0.10.0a0 from git+https://github.com/Rapptz/discord.py@async in /home/ghent/.local/lib/python3.3/site-packages/discord.py-0.10.0a0-py3.3.egg
Collecting aiohttp==0.19.0 (from discord.py==0.10.0a0)
  Downloading aiohttp-0.19.0.tar.gz (2.2MB)
    100% |████████████████████████████████| 2.2MB 323kB/s
    Complete output from command python setup.py egg_info:
    Compiling aiohttp/_websocket.pyx because it changed.
    [1/1] Cythonizing aiohttp/_websocket.pyx
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-eueb7g/aiohttp/setup.py", line 61, in <module>
        raise RuntimeError("aiohttp requires Python 3.4.1+")
    RuntimeError: aiohttp requires Python 3.4.1+

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-eueb7g/aiohttp
```

**Comment by imayhaveborkedit** [comment]
Which "site"?  Because it's not this one. https://github.com/Rapptz/discord.py#requirements

**Comment by Ghent** [comment]
![vers](https://cloud.githubusercontent.com/assets/47145/12596904/65ae03c4-c450-11e5-85fc-3e70ec844bb3.png)

Sorry, I was mislead by this.

**Comment by imayhaveborkedit** [comment]
Oh right, that's probably because the legacy branch is the one on pypi, and the image wasn't changed/removed in the async branch readme.

**Comment by Ghent** [comment]
Sorry about that.  I had been using an earlier version that ran fine in 3.3 so I didn't think to check the requirements.  Thanks again!
