### ISSUE TITLE
Module 'audioop' Missing

### ISSUE THREAD

**Issue by DanialHMD** [Rapptz/discord.py#9742]
### Summary

No module named 'audioop'

### Reproduction Steps

I wrote a code for discord bot(first time using discord py) and I come to this error.

### Expected Results

Expected no errors.

### Actual Results

```
Traceback (most recent call last):
  File "F:\Codes\Python\discordbot\Discord\main.py", line 1, in <module>
    import discord
  File "F:\Codes\Python\discordbot\Lib\site-packages\discord\__init__.py", line 23, in <module>    
    from .client import *
  File "F:\Codes\Python\discordbot\Lib\site-packages\discord\client.py", line 51, in <module>      
    from .user import User, ClientUser
  File "F:\Codes\Python\discordbot\Lib\site-packages\discord\user.py", line 29, in <module>        
    import discord.abc
  File "F:\Codes\Python\discordbot\Lib\site-packages\discord\abc.py", line 59, in <module>
    from .voice_client import VoiceClient, VoiceProtocol
  File "F:\Codes\Python\discordbot\Lib\site-packages\discord\voice_client.py", line 53, in <module>
    from .player import AudioPlayer, AudioSource
  File "F:\Codes\Python\discordbot\Lib\site-packages\discord\player.py", line 28, in <module>
    import audioop
ModuleNotFoundError: No module named 'audioop'
```

### Intents

Presence and Message Content

### System Information

returning error.
os: windows 10
py version: 3.13 64bit

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Rapptz** [comment]
Python 3.13 is not released and this is a known problem already (https://github.com/Rapptz/discord.py/issues/9477). Consider using a stable Python version instead.

**Comment by wilson0x4d** [comment]
@DanialHMD 

https://gist.github.com/wilson0x4d/c434b95939d7920f4a213286733cf1a3

I'm sure Rapptz will eventually find a solution since 3.13 is expected to exit "release candidate" status and go into "release" status within the next few months.

**Comment by linluoran** [comment]
pip install audioop-lts

**Comment by massongit** [comment]
I also encountered this issue.

https://github.com/Rapptz/discord.py/blob/99a7093c340d2b768d8c7c8e216e13988ba64ec0/requirements.txt#L2
Therefore, it would be nice to install a above dependent package when we install `discord.py` on Python 3.13.

**Comment by Rapptz** [comment]
This issue will be fixed when there's a new release, for now just install `audioop-lts` manually if you need it and it'll work regardless of version bump or not.
