### ISSUE TITLE
When editing automod rules, error occuerd

### ISSUE THREAD

**Issue by being24** [Rapptz/discord.py#9797]
### Summary

When editing an automod rule, 400 error occurs if event_type is given as an argument.

### Reproduction Steps

Edit the Automod rules from the bot while they exist.

### Minimal Reproducible Code

```python
await old_rule.edit(
  name=new_rule.name,
  event_type=AutoModRuleEventType.message_send,
  trigger=new_rule.trigger,
  actions=new_rule.actions,
  enabled=new_rule.enabled,
  exempt_roles=[],
  exempt_channels=[],
  reason="AutoModの設定を同期",
)
```

### Expected Results

Editing can be done.

### Actual Results

400 Bad Request (error code: 50035): Invalid Form Body In event_type: Value "['message_send', 1]" is not a valid enum value.

### Intents

    intents = discord.Intents.default()     intents.members = True     intents.typing = False     intents.integrations = True     intents.message_content = True     intents.auto_moderation_execution = True     intents.auto_moderation = True     intents.auto_moderation_configuration = True

### System Information

- Python v3.10.9-final
- discord.py v2.4.0-alpha
    - discord.py metadata: v2.4.0a5005+gd853a3f0
- discord.py v2.3.2 (first i use this version)
- aiohttp v3.9.5
- system info: Linux 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023

### Checklist

- [X] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by being24** [comment]
traceback is here

```
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
  File "/workspaces/yonaga/cogs/automod_sync.py", line 84, in sync_automod
    await old_rule.edit(
  File "/home/vscode/.local/lib/python3.10/site-packages/discord/automod.py", line 537, in edit
    data = await self._state.http.edit_auto_moderation_rule(
  File "/home/vscode/.local/lib/python3.10/site-packages/discord/http.py", line 752, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In event_type: Value "['message_send', 1]" is not a valid enum value.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/home/vscode/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
  File "/home/vscode/.local/lib/python3.10/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'sync_automod' raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In event_type: Value "['message_send', 1]" is not a valid enum value.
```
