### ISSUE TITLE
Can't await for client.logs_from()

### ISSUE THREAD

**Issue by xoxfaby** [Rapptz/discord.py#986]
Maybe I'm doing this wrong but I'm trying to 

`logs = await client.logs_from(message.channel, limit=100)`

and get back 

```
Traceback (most recent call last):
  File "C:\Python3\lib\site-packages\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File ".\bot.py", line 22, in on_message
    logs = await client.logs_from(message.channel, limit=100)
TypeError: object LogsFromIterator can't be used in 'await' expression
```

**Comment by NCPlayz** [comment]
wrap `await` and the coroutine in a pair of brackets - otherwise it would be read as `logs = await` and the rest is unreachable
