### ISSUE TITLE
'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')]

### ISSUE THREAD

**Issue by NethercraftMC5608** [Rapptz/discord.py#9860]
### Summary

I get a SSL error.

### Reproduction Steps

Running client.run('TOKEN') produces this issue.

### Minimal Reproducible Code

```python
import discord
import aiohttp
class MyClient(discord.Client):
    async def on_ready(self):
        print('Logged on as', self.user)

    async def on_message(self, message):
        # don't respond to ourselves
        if message.author == self.user:
            return

        if message.content == 'ping':
            await message.channel.send('pong')

intents = discord.Intents.default()
intents.message_content = True
client = MyClient(intents=intents)
client.run('token')
```

### Expected Results

For it to work normally and connect.

### Actual Results

[2024-06-07 23:03:40] [INFO    ] discord.client: logging in using static token
Traceback (most recent call last):
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\site-packages\aiohttp\connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\asyncio\base_events.py", line 1103, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\asyncio\base_events.py", line 1133, in _create_connection_transport
    await waiter
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\asyncio\sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\asyncio\sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\site-packages\discord\client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\site-packages\discord\client.py", line 777, in start
    await self.login(token)
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\site-packages\discord\client.py", line 612, in login
    data = await self.http.static_login(token)
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\site-packages\discord\http.py", line 803, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\site-packages\discord\http.py", line 625, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\site-packages\aiohttp\client.py", line 1197, in __aenter__
    self._resp = await self._coro
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\site-packages\aiohttp\client.py", line 581, in _request
    conn = await self._connector.connect(
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\site-packages\aiohttp\connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\site-packages\aiohttp\connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\site-packages\aiohttp\connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\bobno\AppData\Local\Programs\Thonny\lib\site-packages\aiohttp\connector.py", line 1027, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')]

### Intents

discord.Intents.default()

### System Information

- Python v3.10.11-final
- discord.py v2.3.2-final
- aiohttp v3.9.5
- system info: Windows 10 10.0.22631

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I tried everything, installing the certificate to my local system. Same error.

**Comment by Gobot1234** [comment]
See https://github.com/Rapptz/discord.py/issues/423#issuecomment-272093801 for the fix. This is not an issue with the library

**Comment by Soheab** [comment]
See [this](https://about.abstractumbra.dev/discord.py/2022/06/15/broken-ssl-on-windows.html>) for Windows.

**Comment by AbstractUmbra** [comment]
For posterity: this is not a library issue and likely should not use this issue tracker, please join the [discord server](https://discord.gg/dpy) and ask there for more assistance.

Fwiw I believe this issue is unrelated to the above post from @Soheab

**Comment by NethercraftMC5608** [comment]
Since its coming from urllib, i tried this script:

import urllib.request
```

url = "https://discord.com"
try:
    response = urllib.request.urlopen(url)
    html_content = response.read()
    print(html_content)
except Exception as e:
    print("Error:", e)
```
I get this output:
`Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)>`

But if i put any other website in, it perfectly reads the content fine? But in my browser i can access the discord website just fine.
