### ISSUE TITLE
Internal error when using `discord.AppInstallationType(guild=True)` on context menus

### ISSUE THREAD

**Issue by Kile** [Rapptz/discord.py#9869]
### Summary

Using `discord.AppInstallationType(guild=True)` on context menus now produces an error when it did not before

### Reproduction Steps

1) Update to the latest release of d.py (2.4.0).
2) Run my provided code
3) Watch in horror as an internal error occurs.

### Minimal Reproducible Code

```python
import discord
from discord.ext import commands
import logging

from asyncio import run

logging.basicConfig(level=logging.INFO, datefmt='%I:%M:%S', format="[%(asctime)s] %(levelname)s: %(message)s", )

class SyncingBot(commands.AutoShardedBot):
    async def setup_hook(self):
        await self.tree.sync()

class TestCog(commands.Cog):
    def __init__(self, bot):
        self.bot = bot
        self.bot.tree.add_command(
            discord.app_commands.ContextMenu(
                name="test",
                callback=self.context_menu_callback,
                allowed_installs=discord.AppInstallationType(guild=True)
            )
        )

    @commands.Cog.listener()
    async def on_ready(self):
        print(f"Logged in as {self.bot.user}")

    async def context_menu_callback(self, interaction: discord.Interaction, message: discord.Message):
        await interaction.response.send_message("Hello!", ephemeral=True)

async def main():
    bot = SyncingBot(command_prefix="!", intents=discord.Intents.default(), chunk_guilds_at_startup=False)
    await bot.add_cog(TestCog(bot))
    await bot.start("TOKEN")

run(main())
```

### Expected Results

No internal error happens

### Actual Results

The following error occurs when I try to start up the bot:

```
Traceback (most recent call last):
  File "/Users/eriklippert/Desktop/Desktop/less important/Local_programming_projects/test/bot.py", line 53, in <module>
    run(main())
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/me/Desktop/Desktop/less important/Local_programming_projects/test/bot.py", line 51, in main
    await bot.start("TOKEN")
  File "/Users/eriklippert/Desktop/Desktop/less important/Local_programming_projects/test/env/lib/python3.12/site-packages/discord/client.py", line 786, in start
    await self.login(token)
  File "/Users/me/Desktop/Desktop/less important/Local_programming_projects/test/env/lib/python3.12/site-packages/discord/client.py", line 629, in login
    await self.setup_hook()
  File "/Users/me/Desktop/Desktop/less important/Local_programming_projects/test/bot.py", line 11, in setup_hook
    synced = await self.tree.sync()
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Desktop/Desktop/less important/Local_programming_projects/test/env/lib/python3.12/site-packages/discord/app_commands/tree.py", line 1125, in sync
    payload = [command.to_dict(self) for command in commands]
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eriklippert/Desktop/Desktop/less important/Local_programming_projects/test/env/lib/python3.12/site-packages/discord/app_commands/commands.py", line 1301, in to_dict
    'integration_types': tree.allowed_installs._merge_to_array(self.allowed_installs),
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/Desktop/Desktop/less important/Local_programming_projects/test/env/lib/python3.12/site-packages/discord/app_commands/installs.py", line 89, in _merge_to_array
    result = self.merge(other) if other is not None else self
             ^^^^^^^^^^^^^^^^^
  File "/Users/me/Desktop/Desktop/less important/Local_programming_projects/test/env/lib/python3.12/site-packages/discord/app_commands/installs.py", line 81, in merge
    guild = self._guild if other._guild is None else other._guild
                           ^^^^^^^^^^^^
AttributeError: 'AppInstallationType' object has no attribute '_guild'. Did you mean: 'guild'?
```

### Intents

default

### System Information

```
- Python v3.12.2-final
- discord.py v2.4.0-final
- aiohttp v3.9.5
- system info: Darwin 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

This code runs if you downgrade to b0024dc86652db19cad16296d6c16c6272b2eaa3. I believe this commit introduced the bug: https://github.com/Rapptz/discord.py/commit/b5ada0a6622438c702881dccbf6502f81ad7b4b9.

This is sad to see and makes me have to downgrade from a stable to an unstable version to be able to use user installed apps while also not getting an error on startup. 

Here it is working fine in the downgraded version:
<img width="290" alt="image" src="https://github.com/Rapptz/discord.py/assets/69253692/fb5c3ebe-9f69-4127-817f-c89277cd8e6b">
<img width="218" alt="image" src="https://github.com/Rapptz/discord.py/assets/69253692/b2c02e4c-e8f5-4596-a98c-c924ad7beac2">

**Comment by DA-344** [comment]
Use ``discord.app_commands.AppInstallationType`` instead.

**Comment by Kile** [comment]
Then why does it work with `discord.AppInstallationType.all()`? Why is it exposed in the first place if it is not meant to be used like that?

**Comment by DA-344** [comment]
Because iirc ``discord.AppInstallationType`` is an array flag that represents the installation types of an application command on APIs side, ``discord.app_commands.AppInstallationType`` is the one that represents the installation types locally and the one utilised when syncing.

**Comment by itswilliboy** [comment]
`discord.AppInstallationType` is __not__ publicly documented and should not be used. Same with eg. `discord.Button` contra `discord.ui.Button`.

**Comment by Kile** [comment]
Fair. And grantedI was using an unstable version so it breaking now makes sense. However I discovered the same thing with `discord.AppCommandContext` and I have used `discord.AppCommandContext.all()` since the feature came out and this now stopped working, even though it was not intended to be used in the first place, the `.all()` was very useful. Maybe mention it as a breaking change?

**Comment by itswilliboy** [comment]
The [version guarantees](https://discordpy.readthedocs.io/en/stable/version_guarantees.html) don't cover it as a breaking change since it isn't documented.

**Comment by Kile** [comment]
I see

Well at least I fixed it now so that has helped me. Thanks.
