### ISSUE TITLE
Unknown sticker type 4 error

### ISSUE THREAD

**Issue by kokofixcomputers** [Rapptz/discord.py#9873]
### Summary

Unknown sticker type 4 error causes the bot to go down.

### Reproduction Steps

i made a giveaway bot and after joining many servers this error happened:
Traceback (most recent call last):
  File "/home/container/main.py", line 800, in <module>
    client.run(".GGu-qb.-")
  File "/home/container/.local/lib/python3.12/site-packages/discord/client.py", line 828, in run
    asyncio.run(runner())
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/discord/client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/container/.local/lib/python3.12/site-packages/discord/client.py", line 746, in start
    await self.connect(reconnect=reconnect)
  File "/home/container/.local/lib/python3.12/site-packages/discord/client.py", line 627, in connect
    await self.ws.poll_event()
  File "/home/container/.local/lib/python3.12/site-packages/discord/gateway.py", line 622, in poll_event
    await self.received_message(msg.data)
  File "/home/container/.local/lib/python3.12/site-packages/discord/gateway.py", line 572, in received_message
    func(data)
  File "/home/container/.local/lib/python3.12/site-packages/discord/state.py", line 611, in parse_message_create
    message = Message(channel=channel, data=data, state=self)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/discord/message.py", line 1470, in __init__
    self.stickers: List[StickerItem] = [StickerItem(data=d, state=state) for d in data.get('sticker_items', [])]
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/discord/sticker.py", line 206, in __init__
    self.url: str = f'{Asset.BASE}/stickers/{self.id}.{self.format.file_extension}'
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/discord/enums.py", line 534, in file_extension
    return lookup[self]
           ~~~~~~^^^^^^
KeyError: <StickerFormatType.unknown_4: 4>

### Minimal Reproducible Code

_No response_

### Expected Results

No error and bot runs smoothly

### Actual Results

Traceback (most recent call last):
  File "/home/container/main.py", line 800, in <module>
    client.run(".GGu-qb.-")
  File "/home/container/.local/lib/python3.12/site-packages/discord/client.py", line 828, in run
    asyncio.run(runner())
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/discord/client.py", line 817, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/container/.local/lib/python3.12/site-packages/discord/client.py", line 746, in start
    await self.connect(reconnect=reconnect)
  File "/home/container/.local/lib/python3.12/site-packages/discord/client.py", line 627, in connect
    await self.ws.poll_event()
  File "/home/container/.local/lib/python3.12/site-packages/discord/gateway.py", line 622, in poll_event
    await self.received_message(msg.data)
  File "/home/container/.local/lib/python3.12/site-packages/discord/gateway.py", line 572, in received_message
    func(data)
  File "/home/container/.local/lib/python3.12/site-packages/discord/state.py", line 611, in parse_message_create
    message = Message(channel=channel, data=data, state=self)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/discord/message.py", line 1470, in __init__
    self.stickers: List[StickerItem] = [StickerItem(data=d, state=state) for d in data.get('sticker_items', [])]
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/discord/sticker.py", line 206, in __init__
    self.url: str = f'{Asset.BASE}/stickers/{self.id}.{self.format.file_extension}'
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/discord/enums.py", line 534, in file_extension
    return lookup[self]
           ~~~~~~^^^^^^
KeyError: <StickerFormatType.unknown_4: 4>

### Intents

intents is set to default with message_content to false

### System Information

- Python v3.12.4-final
- discord.py v2.0.0-final
- aiohttp v3.9.5
- system info: Linux 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

_No response_

**Comment by Rapptz** [comment]
Update the library before making these issues please.

**Comment by kokofixcomputers** [comment]
> Update the library before making these issues please.

Okay thanks
