### ISSUE TITLE
Random crash on parse_guild_soundboard_sounds_update

### ISSUE THREAD

**Issue by Enitoxy** [Rapptz/discord.py#9969]
### Summary

Random crashes on parse_guild_soundboard_sounds_update

### Reproduction Steps

Nothing, the bot randomly crashes (I assume when a GuildSoundBoardSoundsUpdateEvent happens)

### Minimal Reproducible Code

```python
Traceback (most recent call last):
  File "/home/container/main.py", line 250, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/container/main.py", line 246, in main
    await bot.start(TOKEN)
  File "/home/container/.local/lib/python3.11/site-packages/discord/client.py", line 815, in start
    await self.connect(reconnect=reconnect)
  File "/home/container/.local/lib/python3.11/site-packages/discord/shard.py", line 475, in connect
    raise item.error
  File "/home/container/.local/lib/python3.11/site-packages/discord/shard.py", line 164, in worker
    await self.ws.poll_event()
  File "/home/container/.local/lib/python3.11/site-packages/discord/gateway.py", line 624, in poll_event
    await self.received_message(msg.data)
  File "/home/container/.local/lib/python3.11/site-packages/discord/gateway.py", line 574, in received_message
    func(data)
  File "/home/container/.local/lib/python3.11/site-packages/discord/state.py", line 1613, in parse_guild_soundboard_sounds_update
    guild_id = int(raw_sound['guild_id'])  # type: ignore # can't be None here
                   ~~~~~~~~~^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

### Expected Results

I expected the bot to keep running

### Actual Results

The bot randomly crashes and shuts off completely

### Intents

intents = discord.Intents.default()

### System Information

- Python v3.11.9-final
- discord.py v2.5.0-alpha
    - discord.py metadata: v2.5.0a5102+ga5f9350f
- aiohttp v3.8.5
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Enitoxy** [comment]
I am not sure what you mean by "event payload". My bot doesn't listen to soundboard update events, this happens randomly.

**Comment by bsian03** [comment]
discord/discord-api-docs#7207 relevant here
